### ISSUE TITLE
Marvel vs Capcom 2 bugs

### ISSUE THREAD

**Issue by mogwaimon** [libretro/flycast#10]
Not certain if this is the correct place to leave bug reports, or if it's even the right forum for reporting things related to the Reicast core in Retroarch, but I've been playing with it a bit and found some glitches in Marvel vs Capcom 2 (Dreamcast version, not Naomi board).

This was all found using default core settings with an Xinput Dualshock 4 controller in use. No VMU was plugged in either. This was in Retroarch 1.4.0 with the latest core downloaded using the in-emulator GUI, and on a Windows 10 desktop. My PC specs are i7 4790k, 8GB of RAM, Geforce GTX980. If any more detailed information is required, please let me know.

First off, if one enters training mode, uses the pause menu to return to menu, and re-enters training mode, Retroarch crashes to desktop with an error saying that Retroarch requested the runtime to terminate in an unusual way.

Second, the main reason I'm posting (As this is likely a more obscure glitch that I'm fairly sure is not present on real hardware) is an issue with the Hulk's command grab move (HCB+P). When it is done to any opponent, Hulk will shift a few pixels to the other side of the screen. This is barely noticeable in and of itself, but the glitch becomes considerably more apparent when done to Captain America. If you execute the command grab with the High Punch, Hulk will shift not just a few pixels but by almost half the screen's length during the move. Now this I am 90% certain is not present on real hardware.

Please let me know if video or logs are required and I will provide them ASAP

**Comment by inactive123** [comment]
> First off, if one enters training mode, uses the pause menu to return to menu, and re-enters training mode, Retroarch crashes to desktop with an error saying that Retroarch requested the runtime to terminate in an unusual way.

This should no longer happen. At least not on Windows.
