### ISSUE TITLE
System date and time each off by 1

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#100]
If you set the date and time in the system BIOS, then exit RA and check the BIOS again, you'll notice that the date is incremented by 1, and time is decremented by 1.  

For example, if you set the date to "March 1" and time to "3:00", exit and restart RA back to BIOS, you'll see the date set as "March 2" and time as "2:00".

**Comment by PixelCrusader** [comment]
I can corroborate this issue as I am experiencing it as well.

**Comment by flyinghead** [comment]
Date/time is now set automatically and is correct
