### ISSUE TITLE
(NAOMI) Game Settings unable to save.

### ISSUE THREAD

**Issue by kalawangman** [libretro/flycast#101]
Basically, you have to configure them every time you start a game. I notice reicast doesn't generate eeprom or sram files. NullDC Naomi did this and actually saved your settings.

**Comment by toccata10** [comment]
I confirm this on the atomiswave games I tested.

**Comment by barbudreadmon** [comment]
Should be fixed after https://github.com/libretro/reicast-emulator/pull/139 is merged.

**Comment by toccata10** [comment]
Well done. It's working now.

**Comment by kalawangman** [comment]
works now

**Comment by toccata10** [comment]
Strange: on latest revision, it seems to be broken again.

**Comment by barbudreadmon** [comment]
On a specific game ? It is working fine on the games i tried.

**Comment by toccata10** [comment]
MetalSlug6 for example: it always goes back to japanese.
I used to set it once to north-american/english, then all the atomiswave games would be in english.
Now, the setting doesn't seem to stick anymore.
OS is ArchLinux.

**Comment by barbudreadmon** [comment]
> all the atomiswave games would be in english

Ok, i'll clarify a few things : 
- eeprom files are used to store naomi settings (from the service menu you enter when hitting service)
- atomiswave have a secondary service menu you can enter after the naomi boot screen (it replaces the original one), it stores settings in `naomi_nvmem.bin` (alongside bios in the system directory)
- it seems to be working properly for me, perhaps yours is corrupt or something ? Try deleting/renaming it ?
- i wouldn't recommend using North American region, except if you love censorship, the english language is available even if you stay with Japan region.

On a sidenote, i'm wondering if this `naomi_nvmem.bin` shouldn't be per game, storing different game settings in the same file feels like asking for conflict issues imho.
