### ISSUE TITLE
[Windows x64+Vulkan]Closing the core crashes RetroArch

### ISSUE THREAD

**Issue by Immersion95** [libretro/flycast#1010]
There is a problem which appeared a few months ago.

Closing the core is currently also exiting RetroArch.

Launching another game while playing a game doesn't cause any issue though.

Tested with latest RetroArch nightlies x64 + latest Flycast core + Vulkan

**Comment by afjara** [comment]
#974 Same as reported here.

**Comment by barbudreadmon** [comment]
as said in the other issue, a backtrace from a faulty setup is needed, will close this one
