### ISSUE TITLE
House of the Dead 2 (dreamcast) freezes on pressing start

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#102]
With House of the Dead 2, build 130cee6ba26018eaf14fee6f642d2d3218ac5ec7 on a linux x64 system, if you press start after gameplay begins, retroarch freezes.  Note that according to @twinaphex, the game does not lock up on windows x64.

**Comment by aboutafter** [comment]
I can confirm this. It was working with a previous build and now it doesn't.

**Comment by Shoegzer** [comment]
@aboutafter thanks.  Are you using Windows or Linux, and x86 or x64?

**Comment by aboutafter** [comment]
I dual boot KDE Neon and Solus (both 64bit). Oddly enough, it works on Neon bot not on Solus.

**Comment by Shoegzer** [comment]
That IS odd.  What kernel are they running on?  What graphics cards and driver levels are they using?  

Also, don't know much about those distros myself but from [here](https://www.slant.co/versus/2714/17659/~solus_vs_kde-neon) it seems there are some differences such as architecture.  Not sure if that offers any clues for what could be going on here.

**Comment by inactive123** [comment]
What do you have Framerate set to? Fullspeed or Normal? Try fullspeed.

**Comment by Shoegzer** [comment]
@twinaphex ah, yes that fixes it.  Interesting.  It also allows the "empire interactive" screen to appear in [this](https://github.com/libretro/reicast-emulator/issues/116) issue too, though other issues persist there.  Is there a need for "normal" framerate?

**Comment by flyinghead** [comment]
working fine now
