### ISSUE TITLE
Bezel/overlay slowdown

### ISSUE THREAD

**Issue by jhdgghost** [libretro/flycast#1021]
Hello,

Working with flycast in my rpi4 with updated retropie. I detect dreamcast and Atomiswave working fine but if you add bezel/overlays from bezel-project everything start to be very laggy with sound cuts with both systems. No problems in other cores. Is it a rpi4 performance problem? Or maybe can be fixed with lower quality bezels or some configuration changes.

Best

**Comment by barbudreadmon** [comment]
> Is it a rpi4 performance problem?

pi4 barely has the specs to run flycast and several games won't run full speed as a result. It's no surprise that the performance will crumble even more if you add bezel/overlays.
