### ISSUE TITLE
Marvel vs. Capcom 2 (USA) characters glitched

### ISSUE THREAD

**Issue by afjara** [libretro/flycast#1022]
Hi, today I launched the core and noticed the characters are glitched when using the latest build `ea1278e`. Reverting to a previous backup build from november 2020 solved the issue.

![Marvel vs  Capcom 2 (USA)-210120-211027](https://user-images.githubusercontent.com/45073924/105256610-d3035400-5b64-11eb-8412-571c5982d63f.png)

RetroArch 1.9.0 Windows 10 x64
RA video driver set to glcore
flycast at default core settings
GTX950 with latest nvidia drivers

**Comment by barbudreadmon** [comment]
Seems to happen when not using per-pixel alpha sorting, thanks for the report, i'll search for the faulty backport

**Comment by barbudreadmon** [comment]
looks like the mali 400/450 fix is at fault : https://github.com/libretro/flycast/commit/3592cad227a503d2246c3e77c8f1b3c66d65550c

**Comment by afjara** [comment]
> 
> 
> Seems to happen when not using per-pixel alpha sorting, thanks for the report, i'll search for the faulty backport

Thank you too! :)

**Comment by barbudreadmon** [comment]
mali400/450 fix reverted, it should be ok now

**Comment by afjara** [comment]
> 
> 
> mali400/450 fix reverted, it should be ok now

Thanks!

**Comment by afjara** [comment]
Glitched characters in MvC 2 re appeared with build `f3a7d61` !

**Comment by afjara** [comment]
UPDATE:

Problem is present when using a GTX950, but not when trying with an Intel HD Graphics 610 laptop.

Both systems set to glcore video driver.

**Comment by bslenul** [comment]
Yeah, looks like 574d009 reintroduced the guilty Mali fix again, weirdly enough I can't replicate in some games previously affected by this (MvC2 displays fine for example for me), SFA3 is a mess however with GL + per-strip/triangle alpha sorting:

![image](https://user-images.githubusercontent.com/33353403/111238969-81bd9100-85f8-11eb-9f6e-ae0eebe22852.png)

![image](https://user-images.githubusercontent.com/33353403/111238977-86824500-85f8-11eb-9284-cd98cd3215fc.png)

**Comment by afjara** [comment]
With default settings and glcore driver, MvC2 seems affected with my nvidia GPU.

![Marvel vs  Capcom 2 (USA)-210317-211208](https://user-images.githubusercontent.com/45073924/111554825-da5e6c80-8765-11eb-9f45-60df5f7ce276.png)

**Comment by afjara** [comment]
Issue fixed in ddb617a

Thanks @bslenul !
