### ISSUE TITLE
Versioning scheme

### ISSUE THREAD

**Issue by SupervisedThinking** [libretro/flycast#1025]
Well could you start to use versions like `Major.Minor.Patch` for your releases?

**Comment by barbudreadmon** [comment]
Is that some kind of troll or a message generated by a robot ? Not even sure which core you are talking about, but we are following upstream versioning, which is `Major.Minor.Patch`, closing.

**Comment by SupervisedThinking** [comment]
Well I'm obviously not as clever as you and don't understand how you follow the upstream versioning:

https://github.com/libretro/flycast/releases - r7-rc1
https://github.com/reicast/reicast-emulator/releases - Reicast r20.04

Look I'm not a software developer but for me as a layperson `r7-rc1` isn't exactly `Reicast r20.04` but I'm eager to learn.

Also it's interesting to know how you deal with basically "dead" stuff like https://github.com/SourMesen/Mesen where most new PRs where summed up here https://github.com/NovaSquirrel/Mesen/tags while libretro maintains their own fork here https://github.com/libretro/Mesen - so you'll stick at 0.9.9 forever?

Well sorry but I have somewhat the feeling that if there is someone trolling it's not me.

**Comment by barbudreadmon** [comment]
Oops, i thought your 2 issues were on yabause repo, hence why i closed the other one as dupe. My answer above is for the yabause repo actually, not that your issues are anything less than spam anyway, especially since you start speaking about mesen now... so i won't re-open this one. Btw, flycast is not reicast.

**Comment by SupervisedThinking** [comment]
Btw. http://yabause.org/download/ -  Yabause 0.9.15 so maybe I should ask the upstream teams for some version tagging, which you don't use for libretro forks anyway.

So to sum it up: anybody who asks for proper versioning & regulary tags/releases spams or trolls? I see.

**Comment by barbudreadmon** [comment]
What you were asking is versioning, which is following upstream as i said : https://github.com/libretro/yabause/blob/master/yabause/src/libretro/libretro.c#L517

"release tags" (which seems to be what you are asking **now**) and "versioning" are different terms with different means. 

Your fault for being unclear in your request, not that it changes anything considering that : 
- upstream flycast has the same releases => https://github.com/flyinghead/flycast/tags
- yabause core is fresh and has only 1 version => 0.9.15

**Comment by SupervisedThinking** [comment]
You're absolutely right my request was "unclear" since it's not obvious what I was asking for since you consider versioning, tags, releases, whatever as spam or trolling. How could I assume you would recognize what i was asking for, this was really dumb by me. It's way more convenient to use "random" git commit hashs instead of known good versions. 🥇 

Thanks for pointing that out. 👍🏻

**Comment by barbudreadmon** [comment]
Thanks for pointing out that we should use different versioning from upstream, or that we should use release tags when there is only one version, i didn't thought of that.
