### ISSUE TITLE
Street Fighter III - Third Strike [Square glitches around characters]

### ISSUE THREAD

**Issue by Denshadego** [libretro/flycast#1027]
Using the latest core on windows and gl driver, I'm having this squares appear on the characters and fx. Changing alpha sorting to any setting didn't seem to fix it, although the last time I played it worked on normal (I barely touch flycast settings beyond disabling the vibration pack).
![Street Fighter III - 3rd Strike-210205-193532](https://user-images.githubusercontent.com/47835860/107096891-781b5f00-67ea-11eb-9a32-7e07bec18bbc.png)

**Comment by afjara** [comment]
#1022

**Comment by barbudreadmon** [comment]
mali400/450 fix reverted, it should be ok now

**Comment by Denshadego** [comment]
Yes! Can confirm it fixed on my end, thank you!
