### ISSUE TITLE
Lightgun issue

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#1029]
Posted by bslenul:

> Another thing related to gun games, in House of the Dead 2 for example if you're not moving the mouse cursor it says that you're aiming off-screen, which means if you don't move you'll be reloading instead of firing :x
I tried in standalone and it looks like as a workaround the cursor is always moving 1 pixel left/right each frame or something like this to prevent the issue, would be cool to have that in the core

**Comment by bslenul** [comment]
Oh, I thought 0faf9108fb42a9e912e8b8e750d5003da764435c fixed the issue, it seems that I tested this with the only game where it works fine (House of the Dead 2)... Today I messed with Confidential Mission and Death Crimson 1 and 2, and the crosshair "blinks" when you're not moving the mouse cursor, I mean it appears/disappears randomly:

https://user-images.githubusercontent.com/33353403/108057350-cfbf9300-7052-11eb-88cf-6192a24708bf.mp4

Still better than previous behavior (always off-screen when not moving) but I was wrong assuming it was fixed, sorry about that :/

**Comment by bslenul** [comment]
Fixed with 8fa6f79bcb00c72d87a2a75ab9ed017d5cbfd013 :)
