### ISSUE TITLE
"Per-Pixel" is missing in "Alpha Sorting" option on Android

### ISSUE THREAD

**Issue by haojiezhu** [libretro/flycast#1035]
With the latest version from core downloader (0.1 55977d2), "Per-Pixel" is missing from "Alpha Sorting" core option on Android. On Windows, "Per-Pixel" is still available in the same version. "Per-Pixel" is available in the previous version (0.1 0faf910) on Android.

**Comment by inactive123** [comment]
Let us know if this will fix the issue -
https://github.com/libretro/flycast/commit/61ec333f5402fec76cd672835b45bea7d991cbfd

**Comment by flyinghead** [comment]
Per-pixel requires Open GL 4.3 and is not supported on Android

**Comment by haojiezhu** [comment]
> Per-pixel requires Open GL 4.3 and is not supported on Android

But you also mentioned it was supported on Android with Vulkan render in the "Final thoughts" here: https://www.libretro.com/index.php/flycast-is-getting-a-vulkan-renderer-available-later-today-on-retroarch-with-nightly-core/

I tested the only 2 games on my phone (Snapdragon 835) with Vulkan and Per-Pixel alpha sorting. "Code: Veronica" crashes shortly after the "Checking Memory Card" screen. "Marvel vs. Capcom 2" plays fine but I can't see any real difference (probably because it's a 2D game). I'll try to test "Shenmue" on my Shield TV after getting home.

**Comment by haojiezhu** [comment]
> Let us know if this will fix the issue -
> [61ec333](https://github.com/libretro/flycast/commit/61ec333f5402fec76cd672835b45bea7d991cbfd)

Latest update restored "Per-Pixel" option. Thanks. I think this can be closed now.

**Comment by bslenul** [comment]
Hm, just updated to the latest core (689b9d5643d3ae39afb8ac8edf2599a859c2589e) on my phone, which only supports GL, and I can see and select the (non-working) "per-pixel" option. It should probably be hidden when using GL on Android if it's not working!
