### ISSUE TITLE
Looney Tunes Space Race: Crash on boot

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#104]
Looney Tunes Space Race crashes upon booting the game.  Tested on linux x86 against build bbe73d536277a5f170d5c55949a3acc3923a3638

**Comment by inactive123** [comment]
I can confirm this.

**Comment by inactive123** [comment]
This works now as of this commit -

https://github.com/libretro/reicast-emulator/commit/e7181d491d8a431eb2bc23652f9c2c491cb6d7c5
