### ISSUE TITLE
Alice's Mom's Rescue Indie 

### ISSUE THREAD

**Issue by ManiacMunchin** [libretro/flycast#1046]
Installing RetroArch using Flycast & testing a few games, I came across a weird issue with this Indie title. Been using the default setting so far.

The start up bios screens are normal as well as the Select Language screen. But after selecting language it glitches & the lower half of the screen goes black, while the game is visible in the top half, altho severly vertically compressed (its like a game meant to cover 25% of the screen, stretched horizontally to double size). From what I can tell the full play area is visible, as I can't see that anything is cut when comparing to Demul 0.7a were the game plays as expected.
![Alice](https://user-images.githubusercontent.com/79989268/109828932-625c5680-7c3d-11eb-8ea1-ec1db5094a88.jpg)

**Comment by bslenul** [comment]
I remember having a similar issue with a specific game (can't remember which one...), I just had to change `Quick Menu > Options > Cable Type` to anything other than "VGA", then close the core or RetroArch and restart the game. No idea if it'll work with this game tho!

**edit:** Yup, displays fine with the other "cables":

![image](https://user-images.githubusercontent.com/33353403/109883454-bc7c0c80-7c7b-11eb-8789-9337f5a97524.png)

**Comment by ManiacMunchin** [comment]
Awesome, that fixed it. Many thanks
