### ISSUE TITLE
Ooga Booga: No graphics on boot

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#105]
Ooga Booga displays no graphics at all upon booting (just a black screen).  Tested on linux x86 against build bbe73d536277a5f170d5c55949a3acc3923a3638

**Comment by inactive123** [comment]
I think I can get this game to boot now starting as of this commit -

https://github.com/flyinghead/reicast-emulator/commit/cbaaaaf970f7047d8a0bbd7a5648d3f0ec9b504e


![image](https://user-images.githubusercontent.com/1075274/42223695-aaa07ab2-7ed8-11e8-999a-0d7743091bce.png)

The intro/title screen still seems to display a lot of blacked out graphics though - but ingame it seems to be mostly fine.

Try to see how far you can get and if the game suffers from a crash later on.

**Comment by Shoegzer** [comment]
Same observations here.  It goes ingame now, but the menus prior to that are not rendered properly.  I wonder if it's caused by the same issue as with [Wacky Races](https://github.com/libretro/reicast-emulator/issues/107)?

I played for a while and didn't get any crashing though.  Not sure how long I should play though - did you encounter a crash and if so, about when did that happen?

**Comment by flyinghead** [comment]
The game crashed when I started the second tutorial: `Fatal error : ParamType_Object_List_Set`
This type of TA data is not currently supported.
I also had to disable checks on TA data to get to this point so this game is probably using cutting edge features... from a reicast standpoint that is.

**Comment by Shoegzer** [comment]
Interesting.  I wonder if the tutorial crash and the menu issue are somehow related, even though the symptoms are totally different.  @skmp would you happen to know?

**Comment by Shoegzer** [comment]
Menus are now working fine now, probably thanks to https://github.com/libretro/reicast-emulator/commit/ff8e12c61ceb578c3eca9e0d82efb05fec1acd89 (though I haven't confirmed this).  Closing this issue.

Also @flyinghead I played through the second tutorial with no crashes so I won't open a new issue for that one, at least not yet.  Can you retest with a GDI in case your original test was with something else?  Just let me know if you still have issues and I'll try to repro, thanks.

**Comment by inactive123** [comment]
Awesome to hear that these issues are no longer!
