### ISSUE TITLE
GPU Timeout with RDNA Cards on core startup

### ISSUE THREAD

**Issue by doug-clayton** [libretro/flycast#1052]
I'm getting an odd GPU timeout issue with my RX 6800XT card that I was not getting previously with an RX 580. During the BIOS boot animation, the GPU hangs and causes a timeout.
The issue is reproduceable with both _glcore_ and _vulkan_ drivers set in Retroarch.
I am using the latest AMD drivers (21.2.3) and I've been having this issue consistently since I've upgraded my video card. I never had any crashing issues with Flycast beforehand.

This is my log from Crazy Taxi using the BIOS directly.
[retroarch__2021_03_09__18_02_35.log](https://github.com/libretro/flycast/files/6110190/retroarch__2021_03_09__18_02_35.log)

This is my log from Resident Evil 3 using the HLE BIOS, which boots the game, but there is a vertex explosion once anything 3D is rendered and then the GPU hangs.
[retroarch__2021_03_09__18_06_32.log](https://github.com/libretro/flycast/files/6110221/retroarch__2021_03_09__18_06_32.log)

If anyone has any idea what could help, it would be much appreciated.

**Comment by Immersion95** [comment]
It doesn't work with my 6800 non XT neither....
Had no problem with my 3070.

This is the code error that I get : 
DXGI_ERROR_DEVICE_RESET

It happens when 3D is displaying (Scores in CVS2 intro for example).

**Comment by Immersion95** [comment]
@doug-clayton : You can try the standalone version which works well with our card

**Comment by Immersion95** [comment]
It's working now, you can close the issue.
