### ISSUE TITLE
Recording feature on RetroArch does not work on FlyCast

### ISSUE THREAD

**Issue by MiYakuGaming** [libretro/flycast#1069]
I have tried many different settings and resolutions for the core FlyCast for DreamCast and it does not record at all in the RetroArch Menu Screen during game-play.
I tested this on Sonic Adventure Japanese version.
Any option or setting in Options does not record in RetroArch, I have no idea what is going on.
It doesn't crash anymore but it doesn't record at all.
I checked my folder for recordings and nothing is there, RetroArch's Menu even says "Start Recording" even after I clicked it.

The game works, it just seems the recording feature doesn't.

**Comment by aWelshDream** [comment]
I'm having the same issue. Did you find a solution. Thanks

**Comment by barbudreadmon** [comment]
there is a retroarch settings called "gpu recording" or something like that, you need to enable it for hardware-rendered cores.

**Comment by aWelshDream** [comment]
Thanks for your help. It worked Great.
Thanks again
