### ISSUE TITLE
Is it possible to build the core on Windows without JIT?

### ISSUE THREAD

**Issue by bslenul** [libretro/flycast#1072]
Hey!

So devreorder (https://github.com/briankendall/devreorder) is an awesome tool that can be used to force controllers to be re-arranged in a specific order, it is REALLY useful with RetroArch. However, as mentioned in https://github.com/libretro/flycast/issues/974#issuecomment-801392118 it crashes RA on close content :(

Since no crash log is generated I decided to run RA + Flycast through gdb to (hopefully) help devs to see what's going on, but it's interrupted non-stop, apparently because of the JIT. I've read that you can use `handle SIGSEGV noprint nostop` to prevent that, it works but then I don't get the crash on close content anymore...

So is there any way to build the core for Windows without JIT? So I can run gdb without the "noprint nostop" stuff. I remember few months ago trying to build the core with `HAVE_GENERIC_JIT=1` (I'm not a dev but I believe it's the correct option), but I got a bunch of errors at the end of the compilation ("undefined reference to xxx") :/ 

**edit:** that's on Windows 10 btw, using MSYS2 MinGW 64bit, no issue when compiling the core without `HAVE_GENERIC_JIT=1`.

**Comment by ds22x** [comment]
Just tried to compile it for myself with `HAVE_GENERIC_JIT=1`, but I too get a lot (a whole lot infact) of "undefined reference to xxx" errors at the end of compilation.

**Comment by bslenul** [comment]
Yeah, and idk if there's a clean way to cancel it btw, even after a Ctrl+C it keeps going, I have to close MSYS2 and close ld.exe from the Windows task manager :x

**Comment by bslenul** [comment]
If anyone wants to take a look, I let it run for a while, here's the build log (the "multiple definition" and "undefined reference" errors start line 568): https://pastebin.com/dcmh0KA1
