### ISSUE TITLE
Alone in the dark 16bit color textures

### ISSUE THREAD

**Issue by saeedAlshaikh** [libretro/flycast#109]
Like the title says, Alone in the dark textures are is incorrectly rendered in 16bit instead of 32bit check the comparison photos between 
Demul Redream Reicast  at the following link

https://imgur.com/a/kkmBr9i

![demul](https://user-images.githubusercontent.com/40776280/42187614-56e98be0-7e59-11e8-94e0-8e0be1af900f.jpg)
![redream](https://user-images.githubusercontent.com/40776280/42187616-5716215a-7e59-11e8-99f4-441aacae671e.jpg)
![reicast](https://user-images.githubusercontent.com/40776280/42187617-5740b758-7e59-11e8-8aa7-1ae19154b7f6.jpg)

**Comment by flyinghead** [comment]
@twinaphex This commit https://github.com/flyinghead/reicast-emulator/commit/18b2d8273fadcea78e6a8ea1eda1f68137087d9e should fix this issue

**Comment by inactive123** [comment]
Tried backporting this but it looks like this in a lot of sprite-based games -

![image](https://user-images.githubusercontent.com/1075274/42459502-010a1e9a-839c-11e8-8bb1-919bdd1e5a05.png)

Any issues in this diff? Im testing with the OIT renderer -

https://hastebin.com/vidalehefe.diff

**Comment by flyinghead** [comment]
Can you point me to a game in particular? I haven't done extensive tests...

**Comment by flyinghead** [comment]
No need to. I just found one.

**Comment by flyinghead** [comment]
That should fix it: https://github.com/flyinghead/reicast-emulator/commit/889f722e7359db1f3dd0476cffda985b0a4c30e0

**Comment by inactive123** [comment]
Cool, let me try it.

**Comment by inactive123** [comment]
The issues are fixed now, thanks!

**Comment by inactive123** [comment]
Also, not sure if it is because of this commit or the floating point commit before, but Shadow Man now finally works in VGA mode!

**Comment by flyinghead** [comment]
Holy cow! Works for me too. How's that possible?

**Comment by flyinghead** [comment]
Yep, confirmed: another floating point precision victim. Not anymore :)

**Comment by inactive123** [comment]
Hmm, @flyinghead , this is what I get with Alone In The Dark with Reicast OIT -

![image](https://user-images.githubusercontent.com/1075274/42476600-b7ef3a46-83ce-11e8-8042-bd2acbdcb658.png)

**Comment by inactive123** [comment]
Hmm, this seems to affect Soul Calibur greatly too, even with the non-OIT renderer.

![image](https://user-images.githubusercontent.com/1075274/42476866-8d12cb52-83cf-11e8-9880-a6b89aeb7079.png)

**Comment by flyinghead** [comment]
Yes, I see this in the OIT core, not on my branches

**Comment by flyinghead** [comment]
You should probably rebase TexCache.h, and perhaps TexCache.cpp, before applying my commit. I see lots of differences.

**Comment by inactive123** [comment]
OK, rebasing...

**Comment by inactive123** [comment]
Rebased TexCache.cpp. The Soul Calibur regressions are now fixed, unfortunately Alone In The Dark's backgrounds remain blue-ish.

**Comment by flyinghead** [comment]
You're almost there:
```
diff --git a/core/rend/TexCache.h b/core/rend/TexCache.h
index 9c8ef0c..0bd319a 100644
--- a/core/rend/TexCache.h
+++ b/core/rend/TexCache.h
@@ -68,7 +68,7 @@ void palette_update(void);
 
 // Unpack to 32-bit word
 
-#define ARGB8888( word ) ( (((word>>4)&0xF)<<4) | (((word>>12)&0xF)<<8) | (((word>>20)&0xF)<<12) | (((word>>28)&0xF)<<0) )
+#define ARGB8888( word ) ( ((word >> 24) & 0xFF) | (((word >> 16) & 0xFF) << 24) | (((word >> 8) & 0xFF) << 16) | ((word & 0xFF) << 8) )
 
 template<class PixelPacker>
 __forceinline u32 YUV422(s32 Y,s32 Yu,s32 Yv)

```

**Comment by inactive123** [comment]
Ah, thanks for pointing that out. Let me get to that real quick...

**Comment by inactive123** [comment]
yep, that fixed the remaining buggy textures. Thanks a lot!
