### ISSUE TITLE
(Regression) THPS2 special meter not rendered

### ISSUE THREAD

**Issue by Nine-H** [libretro/flycast#110]
The regression appeared just before f3678213292546b3724a8dc1f86e1b11f9a39f61 I'm not sure what commit I was running before then, I've tested it on dynarec and generic and neither of them render it. I'm testing on linux, non-oit.

**Comment by inactive123** [comment]
Try to do a bisect, that commit you point to certainly cannot be it.

**Comment by Nine-H** [comment]
I haven't set up a build environment I can go back through the debian packages I downloaded and give you an over-under if that helps.

**Comment by Nine-H** [comment]
it was working at dc5c3d3e16d444b49924547c13858e4ad3789422
and it broke by 650fddc which doesn't appear in the commit logs but somehow made it out of nightly builds on the 29th of june.

**Comment by inactive123** [comment]
We would really need a proper bisect here. I need to know specifically at which commit this started happening.

**Comment by flyinghead** [comment]
Special meter now renders fine
