### ISSUE TITLE
Twinkle Star Sprites - Unplayably slow

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#112]
Framerate seems to drop to 1/2fps or so, making it essentially unplayable.

**Comment by flyinghead** [comment]
I don't have this framerate drop on my branch but my console is spammed with the following:
`WARN: subv <REG_M>,<REG_N> used, 312B`
I suppose an illegal or unsupported assembler command?

**Comment by flyinghead** [comment]
It is supported :)
```
//Retail game "Twinkle Star Sprites" "uses" this opcode.
```

**Comment by inactive123** [comment]
OK, let me comment this printf and see if it gets us to playable performance.

**Comment by inactive123** [comment]
Yep, that did it. So many similar performance-related issues in this codebase...
