### ISSUE TITLE
Detect region automatically

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/flycast#1146]
I had my Virtua Striker 3 rom display an Error 02, which was fixed by changing the region to "Europe" in the core options.

Can the core simply detect the correct regional settings automatically so you won't have to change them all the time or clutter the config folder with a bunch of per-game core options?

**Comment by barbudreadmon** [comment]
The emulator is already doing that for a lot of romsets, if it doesn't for a specific romset then i suppose this one was simply overlooked.
You should probably make your report upstream at https://github.com/flyinghead/flycast, this forked libretro repo has been adandonned, i'm not sure it's still being looked at by @flyinghead.

**Comment by Tasosgemah** [comment]
Thank you. I'm closing this then.
