### ISSUE TITLE
Flycast no longer working in Retroarch on Steam Deck

### ISSUE THREAD

**Issue by Rohsiph** [libretro/flycast#1155]
Hi, first time reporting an issue so bear with me. 

About two weeks ago I began configuring Retroarch (flatpak install) on my Steam Deck. I tested Flycast early in this process and it worked fine. Last night, I tried again and it immediately crashed to desktop. Spent some time tonight looking through troubleshooting for similar issues, mainly related to BIOS file locations. 
[retroarch__2022_07_02__23_10_11.log](https://github.com/libretro/flycast/files/9034071/retroarch__2022_07_02__23_10_11.log)

Eventually, installed flatpak of Flycast separately. It works with my BIOS files. But no matter where I put the files in RetroArch (same with moving cores, configs, etc. between SD and internal Deck drive) it keeps crashing. Finally turned on RetroArch logging, and it looks like it's making it most of the way, but stops with a fatal error. Log attached: [retroarch__2022_07_02__23_10_11.log](https://github.com/libretro/flycast/files/9034071/retroarch__2022_07_02__23_10_11.log)

**Comment by flyinghead** [comment]
Try resetting all RetroArch and core settings to default. There are many, many options and some combinations can lead to crashes. Also try Open GL instead of Vulkan in case it's a Vulkan issue.

**Comment by Rohsiph** [comment]
Resetting all RetroArch settings to default worked. I deleted the config file and rebuilt my options, and suddenly Flycast works again. Thanks!
