### ISSUE TITLE
Spawn (Naomi) EEprom not saving or being overridden with defaults on a fresh boot

### ISSUE THREAD

**Issue by WarpedPolygon** [libretro/flycast#1159]
When booting this game you need to change Network to OFF in the test menu otherwise it'll just be checking the network constantly and not boot. I save and exit after changing this, booting into the game from the test/service the game and it plays just fine. However on a fresh boot it has reverted back to Network = Slave. So the EEprom is not saving correctly or it is being overridden on a fresh boot.

This causes the user to select Network = Off on every play session

**Comment by barbudreadmon** [comment]
This repo is deprecated, [upstream](https://github.com/flyinghead/flycast) became the official repo for the libretro port.
Maybe [the default spawn eeprom with disabled network](https://github.com/libretro/flycast/commit/1c4cdc5dc50b697ec301cf10b4bd6fa8e66fe7d9) got lost in the process ? I haven't contributed for years so i wouldn't know, i recommend reporting this upstream.

**Comment by WarpedPolygon** [comment]
Cheers. New to github and didn't know where I was. Thanks again
