### ISSUE TITLE
lupinsho offscreen reload button only registers trigger

### ISSUE THREAD

**Issue by WarpedPolygon** [libretro/flycast#1172]
When reloading in this game it is just registering a shot. 

Upon checking in the I/O test screen it appears as if the reload button is doing it's job (removing cursor from screen and firing a shot). The test menu registers the gun pointing offscreen and the trigger button registers as on at the same time.

I think I have figured what is going on. The trigger input is being registered BEFORE it is being registered as offscreen. There needs to be a delay between the cursor being removed from screen and the trigger input turning on.

I couldn't find just an offscreen button that doesn't register a trigger input at the same time. This would be a work around as you can simply hold the offscreen button and press the trigger whenever you need to.

**Comment by flyinghead** [comment]
This repository is no longer used. issues related to the Flycast core should be reported in the upstream repo: https://github.com/flyinghead/flycast/issues
