### ISSUE TITLE
Surf Rocket Racers: Disc read error ingame

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#118]
While testing Surf Rocket Racers, I discovered an interesting issue reading the disc, which usually occurs about 50% of the way through the first race (not lap) in "Championship" mode:

![srr](https://user-images.githubusercontent.com/12475371/42245915-a4caddde-7ee8-11e8-83c4-3e76c6491e50.png)

Testing on linux x64, kernel 4.15, commit 20c509c65d0d92704dbe7d25d9ac714fc056363e, on a gdr dump.

I would especially appreciate confirmation from others on this issue.

**Comment by flyinghead** [comment]
Exact same issue on my branches

**Comment by Shoegzer** [comment]
Ah, thank you.  At least we know this isn't a case of a bad dump, which I was afraid of.  Exactly what this issue is though, I don't even know where to begin.

**Comment by flyinghead** [comment]
Another case of Div Matching problem.
Needs to be disabled for this game.

**Comment by flyinghead** [comment]
This has been fixed and Div Matching can now be used for this game

**Comment by Shoegzer** [comment]
Confirmed working here too.  Excellent, thanks much @flyinghead.
