### ISSUE TITLE
Metal Slug 6 incorrect scrolling framerate (not performance related)

### ISSUE THREAD

**Issue by riggles1** [libretro/flycast#1185]
Can't find an open issue for this but it's been known since before (threads online mentioning it).
Flycast doesn't handle the scrolling of the background smoothly for some reason, as if the framerate is off, it's constantly unevenly stuttering at all times even when not much is going on action wise.

Using the MAME current set dump, and the conversion just as a test.

Emulating other games including other 2D games and Atomiswave games results in perfectly smooth framerates without any scrolling inconsistencies, Dolphin Blue for example is perfect using the exact same configs, both native and upscaled internal resolutions and testing various settings to try rule out specific settings, using vulkan as the driver.

Metal Slug 6 when played on a GDEMU on Dreamcast plays at perfect smoothness, indicating that the game is supposed to scroll smoothly.

**Comment by barbudreadmon** [comment]
The description of this repo mentions that the libretro port was moved upstream at https://github.com/flyinghead/flycast

This is also where you should report issues

**Comment by riggles1** [comment]
Thank you! Just posted there.
