### ISSUE TITLE
World Series Baseball 2K2 - shadows + freezing issue

### ISSUE THREAD

**Issue by tapperp** [libretro/flycast#1200]
Hello. I've tested World Series Baseball 2K2 (USA) using the most recent Flycast Windows build as well as the Retroarch core. I have also tested these issues on Android in both Flycast standalone and Retroarch. I will also note these issues do not appear using the Redream emulator, and I am using Redump verified images compressed to CHD.

Here is what I am seeing:

1) Shadows are incorrect, and no combination of settings fixes them. Note, I do have the shadows setting checked. They appear as solid black without transparency. In other Sega Sports games the shadows do render correctly with transparent shadows, i.e. NFL 2K2 (USA), NBA 2K2 (USA).

2) If I let the game run its demo, it will often freeze at the beginning. Attached is a screenshot where it freezes, and you can also see the solid black shadows issue as well.

Thank you for your attention, and hopefully these issues can be fixed someday.

![Flycast - World Series Baseball 2K2 freeze + shadows issue](https://github.com/user-attachments/assets/0172320b-0aef-498a-9248-b6914f118d78)

**Comment by LibretroAdmin** [comment]
Hi, did you test the core from the buildbot just to make sure?
