### ISSUE TITLE
Soldier of Fortune - Flickering orange clear color when standing still

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#122]
If you stand still in this game and don't move, there will be an orange clear color that will keep flickering. As soon as you start moving it disappears again.

**Comment by flyinghead** [comment]
Dup of #127

**Comment by inactive123** [comment]
Fixed by https://github.com/libretro/reicast-emulator/commit/14c0140201ba9142ac96d30857bee1fcbb0d7da3, thanks to @flyinghead!
