### ISSUE TITLE
(Windows CE) Hello Kitty Magical Block crash

### ISSUE THREAD

**Issue by Alex9534** [libretro/flycast#125]
This game crash after booting bios closing RetroArch. It does not even reach any screen's game. I have tested with .GDI and .CDI formats. I can see in the logs messages as 'Get MemPtr unsupported area: addr=0x5B90' and '[libretro ERROR] Failed to locate bootfile.'

Logs:

[Retroarch_Log_Hello_Kitty_Magical_Block_CDI_Format.log](https://github.com/libretro/reicast-emulator/files/2166983/Retroarch_Log_Hello_Kitty_Magical_Block_CDI_Format.log)
[Retroarch_Log_Hello_Kitty_Magical_Block_GDI_Format.log](https://github.com/libretro/reicast-emulator/files/2166984/Retroarch_Log_Hello_Kitty_Magical_Block_GDI_Format.log)

I have bios files in system/dc and others Dreamcast games run properly.

Thanks to everyone involved in this core and their improvement.

**Comment by flyinghead** [comment]
Alas, Windows CE games are not supported

**Comment by Alex9534** [comment]
Hello Kitty Magical Block now works on Reicast WinCE release! It looks to work very well on i5-6500 (3,2 GHz) with an iGPU Intel HD 530.

35-45 fps playing video (opening-intro) and full speed 60 fps in game.

Thanks flyinghead
