### ISSUE TITLE
(Naomi) Cosmic Smash - Buggy analog stick controls

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#126]
Player character appears to move by itself to the left. Analog stick controls/axes seem to be wrong for this game.

**Comment by barbudreadmon** [comment]
@twinaphex I have serious doubts this is an input issue (analog or not) : 
https://ibb.co/bBwHmd
The 4 analogs are at 0x8000, which is the center value, and all buttons are at 0. 

From looking at http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=csmash&lang=en , this game don't use analogs (in fba, 8-way joystick is always mapped to dpad), see the difference with a game using analogs like monkey ball : http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=monkeyba&lang=en

Also, i noticed there is a ton of error message when starting the game, so an emulation issue is more likely.

**Comment by flyinghead** [comment]
The player moves to the left even in the demo. He's unable to hit the ball.

When starting, the game is trying to load some data into the boot ROM. Might be an address mapping / masking issue.

**Comment by barbudreadmon** [comment]
@twinaphex @flyinghead It seems to be an issue with a specific version of the rom (the "rev A" version ?), i have another one not suffering from this issue.

**Comment by legluondunet** [comment]
This one has correct input:
md5sum: d8358351d9c6c39a544a44eb81fd2022 Cosmic Smash.bin
What is the rom md5sum you meet this issue?

**Comment by flyinghead** [comment]
This is what I have:
549b049b9d8ec6692cddf7ef48da82ac  Cosmic Smash.dat

Thanks for the tip!

**Comment by barbudreadmon** [comment]
The game is working properly with the MAME romset, there is also a version of the dat file which is working, the non-working one might be a bad dump.
Closing !
