### ISSUE TITLE
Soldier of Fortune - Enemy AI appears broken

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#127]
The enemy AI is completely broken in this game, and they just seem to rotate around while not really moving around. This seems to happen to the NPCs in the intro sequence as well.

**Comment by flyinghead** [comment]
I was lucky on this one but still, it was really painful to narrow it down. See https://github.com/flyinghead/reicast-emulator/commit/efa145f50ec55ec04a0e5f56361caf861bfe5d69 for a fix.
Not sure what would be the equivalent compiler flag in MSVC. One option is to set the floating point model to precise for the files `core/hw/sh4/dyna/shil.cpp` and `core/hw/sh4/interpr/sh4_fpu.cpp`. Not sure about the performance hit though.

**Comment by inactive123** [comment]
Awesome, this fixes things indeed!
