### ISSUE TITLE
Crazy Taxi Missing Sound Effects/Very Low Volume [OIT]

### ISSUE THREAD

**Issue by Alaharon** [libretro/flycast#131]
crazy taxi is missing sound effects/very low volume like car engine and menu navigation sounds

**Comment by inactive123** [comment]
Try to see if enabling the DSP fixes this now -

https://github.com/libretro/reicast-emulator/commit/a82c86438d3601701c830fa03119f114e5d18fefv

**Comment by Alaharon** [comment]
Sorry for the late reply, yes enabling the DSP fixes the sound
