### ISSUE TITLE
San Francisco Rush 2049 - Screen cropped at the top.

### ISSUE THREAD

**Issue by PixelCrusader** [libretro/flycast#137]
Windows 7 64 bit, AMD Radeon HD 6450, Intel i5-2320 CPU @ 3.00GHz
RetroArch 1.7.3 - Reicast 0.1 d8a0197

The top of the screen is obscured. The game does not respond to in-game video settings.

![san francisco rush 2049 usa -180708-043628](https://user-images.githubusercontent.com/40935002/42418403-d4ce4646-826d-11e8-82b5-61c59237b690.png)
![san francisco rush 2049 usa -180708-043941](https://user-images.githubusercontent.com/40935002/42418404-d4dd2fd0-826d-11e8-8efd-27ac640a5d19.png)
![san francisco rush 2049 usa -180708-043526](https://user-images.githubusercontent.com/40935002/42418405-d4e9ee64-826d-11e8-9706-a7bd079b10f1.png)
![san francisco rush 2049 usa -180708-043537](https://user-images.githubusercontent.com/40935002/42418406-d4f60d84-826d-11e8-8a62-db31968eb2cc.png)

**Comment by flyinghead** [comment]
@twinaphex This commit https://github.com/flyinghead/reicast-emulator/commit/c0356353411c551c1e65147c84bb18d98d3b0435 should fix it

**Comment by inactive123** [comment]
@flyinghead Backported - https://github.com/libretro/reicast-emulator/commit/02beb052fadcca6943398e73d8795a6922f84163

**Comment by inactive123** [comment]
Seems fixed to me -

![image](https://user-images.githubusercontent.com/1075274/42480456-c9ac5f16-83dd-11e8-92bd-5e6bf94d2fb5.png)

**Comment by PixelCrusader** [comment]
That picture looks accurate, yes. With a +25 vertical center, the bottom of the screen would be filled in too.

Please excuse my inexperience. I'm an end user not really familiar with downloading and compiling from here. Have the changes been made to buildbot nightlies? If not, I'm willing to take your word for it and close the issue. Currently on version fb98f7e.

**Comment by inactive123** [comment]
Download the core again tomorrow and it should be up to date with latest then.

**Comment by PixelCrusader** [comment]
Reicast 0.1 c3712fa

The screen cropping at the top no longer occurs. Thanks! There does seem to be a very slight amount of overscan at the very top of the screen, it's most noticeable on the game's main menu and on the pause menu. I'm only pointing it out for thoroughness' sake, though.

The only big problem that I can still see are with the in-game video settings. The game still doesn't seem to respond to increasing the vertical center.

![san francisco rush 2049 usa -180710-200620](https://user-images.githubusercontent.com/40935002/42544526-6e5efe2c-8480-11e8-91f4-227a7c3d0f4e.png)

![san francisco rush 2049 usa -180710-200713](https://user-images.githubusercontent.com/40935002/42544532-726f958a-8480-11e8-9648-bac039eb1443.png)

Increasing vertical center should normally stretch the game display downward, completely covering the black border at the bottom at around +26 before stretching off of the monitor's screen at higher numbers. Set correctly, it would look like this (edited photos):

![san francisco rush 2049 usa -180710-200620edit](https://user-images.githubusercontent.com/40935002/42545313-26b36d60-8485-11e8-8d33-9572c03773a6.png)

![san francisco rush 2049 usa -180710-200713edit](https://user-images.githubusercontent.com/40935002/42545297-0d1977f0-8485-11e8-984e-52808d9f9e11.png)

**Comment by flyinghead** [comment]
I'm pretty sure these video settings just change the timing of vblank/hblank interrupts in the output video signal of the Dreamcast. They do not change the generated bitmap image and thus have no effect in an emulator.

**Comment by PixelCrusader** [comment]
I see. I only thought otherwise because both Redream and Demul have the same problem with the empty space at the bottom, and the video settings could be used to work around it.

If it's working as intended, I think this issue can be closed.

Edit: Upon looking up gameplay footage, it could be not a matter of the game filling the whole screen, but of the game being oriented towards the top of the screen rather than centered in the middle. 

References: [1](https://www.youtube.com/watch?v=ez61oeRKSOM) [2](https://www.youtube.com/watch?v=X6hD1nStrTw) [3](https://www.youtube.com/watch?v=pvOTTVlAm0Q)

**Comment by PixelCrusader** [comment]
Windows 7 64 bit, AMD Radeon HD 6450, Intel i5-2320 CPU @ 3.00GHz
RetroArch 1.7.5, Git 7c93a0934e, Reicast 0.1 207db67

I hesitated to post this, because I didn't know if this was really a definitive solution or just a band-aid fix that offloaded more work onto end users.

Rush 2049 has been working fine for me now, because I've learned about using custom configurations and custom aspect ratios in RetroArch:

![san francisco rush 2049 usa -181109-194104](https://user-images.githubusercontent.com/40935002/48295446-cdc0ff80-e459-11e8-9057-692223a12639.png)

Before I go further I should point out that doing this will break the games outside of fullscreen mode. If you play in windowed mode, this isn't for you.

What you need is a config file in RetroArch/config/Reicast with a name that matches that of the game you're trying to modify. You can do this by creating a .cfg file with a text editor, but another way is to just save a game override within RetroArch. Launch the game > Open the Quick Menu > Overrides > Save Game Overrides.

My cfg file for this game looks like this:

aspect_ratio_index = "23"
custom_viewport_height = "1181"
custom_viewport_width = "1466"
custom_viewport_x = "227"
custom_viewport_y = "-11"

YMMV. What works for my monitior might not work for another. If you want to do this yourself, change the values in a text editior and save it as videogame.cfg, Otherwise, you can calibrate the screen in RetroArch. Launch the game, open the Quick Menu and back out into the Main Menu without the closing the game. Go to Settings, then go down to Video. Scroll down, change the Aspect Ratio to Custom and then change the Custom Aspect Ratio X Pos, Y Pos, Ratio Width and Ratio Height as needed. You can use a ratio calculator if you have trouble maintaining the correct aspect ratio.

https://www.google.com/search?q=ratio+calculator&ie=utf-8&oe=utf-8&client=firefox-b-1

Once you've resized the image, you can drag it all the way to the left edge of the screen, count the custom_viewport_x number it lands on (hopefully 0), then drag it all the way to the right, noting the number it falls on when the screen hits the edge. Divide by that number (far right value plus the amount of negative numbers you might get on the left) by half and you know what number to center the screen on. Either that, or just move it to the left and right until it looks right to you.

For more information on this and some already made custom cfgs, you can go here:

https://forums.launchbox-app.com/topic/36088-zombeavers-retroarch-psx-and-saturn-overrides/

So with all that out of the way, San Francisco Rush 2049 currently runs great on Reicast Libretro, if you're willing to go through the extra hoops to make it that way.

If there are no objections, I will be closing this.
