### ISSUE TITLE
Redline Racer (Japan) - Graphics issues - Missing UI elements

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#143]
The missing UI elements here are in black.

![image](https://user-images.githubusercontent.com/1075274/42483770-bbd20b7c-83ef-11e8-961d-71b128e81ac9.png)

**Comment by inactive123** [comment]
@flyinghead Looks like these graphics show up now. Maybe as a result of the FPU changes?

**Comment by flyinghead** [comment]
Don't know. I believe I checked and never had this issue on my branch.
