### ISSUE TITLE
(Windows CE) Puzzle Bobble 4 - Crashes after Dreamcast boot screen

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#144]
As description says - crashes after Dreamcat boot screen. Setting cable type (RGB/VGA) doesn't matter.

**Comment by flyinghead** [comment]
Windows CE game:
```
MEM remap 0 : 0x5800 to 0xC1D1800
Get MemPtr unsupported area : addr=0x5B90
Error in core/hw/holly/sb_mem.cpp:WriteBios:69  -> Write to [Boot ROM] is not possible, addr=c,data=636c,size=2
```

**Comment by inactive123** [comment]
Ah, I didn't see it being part of this list -

https://segaretro.org/Windows_CE

**Comment by flyinghead** [comment]
I believe Bust-A-Move 4 and Puzzle Bobble 4 are the same game.

**Comment by inactive123** [comment]
Yeah, you're right. Added the CE label.

**Comment by flyinghead** [comment]
working fine now

**Comment by sergioad** [comment]
Wait, ai am having the exact same issue with both Jojo's bizarre adventure and Bust-A-Move 4, when it reaches the SEGA logo (produced or under license from SEGA Enterprises LTD.) It does not continues

I am using Recalbox, Flycast version 1.9.0 - Flycast (0.1 0059ab3b28)

![IMG_20210105_162546504](https://user-images.githubusercontent.com/5375145/103671363-6b33f300-4f40-11eb-958e-a7e89378c5c1.jpg)

**Comment by barbudreadmon** [comment]
@sergioad you need a 64bit cpu, most likely above 3Ghz, to run those wince games

**Comment by sergioad** [comment]
@barbudreadmon is Jojo's bizarre adventure a Windows CE game? I did not knew that, thanks for the info

**Comment by barbudreadmon** [comment]
it's not, only bust-a-move, not sure what's the deal with jojoba, but you might prefer playing it on arcade (FBNeo most likely on recalbox) anyway, for lesser input lag and way better performance on pi4.
