### ISSUE TITLE
Linux crash after PR #142 (2018-07-10)

### ISSUE THREAD

**Issue by toccata10** [libretro/flycast#145]
I suppose it's the PR #142 which causes problem, as the reicast core from the buildbot dated 2018-07-09 works fine, but the core from 2018-07-10 crashed when loading a rom with:
```
Sh4 Reset
recSh4 Init
Freeing fpcb
nullDC-Naomi rom loader v1.2
File: /home/Arcade2/Roms/atomiswave/MetalSlug6.lst
SIGSEGV @ 0x7f96f104dfa7 (signal_handler + 0x0x14177) ... (nil) -> was not in vram
[libretro INFO] Fatal error : segfault
 in signal_handler -> core/libretro/common.cpp : 392 
DEBUGBREAK!

```

**Comment by barbudreadmon** [comment]
The commit at fault is https://github.com/libretro/reicast-emulator/commit/0265894b590072cab6d531d42d2acb42da0d8fc8, the issue is that you don't have CR/LF end of line (windows type) in your lst file. You can quickly fix this with a good editor. I'll create a PR with a fix later.

**Comment by toccata10** [comment]
Yes, you're right. Thanks

**Comment by toccata10** [comment]
It's working with latest update. Thanks again.
