### ISSUE TITLE
GL2 renderpath regressions (non-OIT renderer) - for OSX

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#148]
@flyinghead For OSX, I need to have a functional GL2 renderpath for the non-OIT renderer. The GL3 renderpath is used for Linux and Windows right now.

The issue I am having right now is that the flat shading support is not available for GL2, which would not be such a big deal if we could just have a codepath for GL2 that does without it. Unfortunately, right now it is leading to a bunch of graphics regressions on OSX, with a lot of polygons being flat shaded.

Is there anything wrong with the ifdefs for the GL2 codepath? I define HAVE_GL3 for Linux/Windows if I want GL3 functionality, so ifndef HAVE_GL3 is the case for OSX.

**Comment by flyinghead** [comment]
I'll have a look but any reason you're not using GL3 for OSX?
Macs support OpenGL 3.3 at a minimum and recent ones support 4.1.

**Comment by inactive123** [comment]
OK never mind, I fixed it. The GL2 codepath works now at least and renders correctly.

As for GL3 support on OSX, that is a separate issue. I'd love to have it but we don't know how to make it work in RetroArch.

You can see our Cocoa GL code here -

https://github.com/libretro/RetroArch/blob/master/gfx/drivers_context/cocoa_gl_ctx.m

We would need to have core context support, and support GL 3.2, GL 3.0, and other core profiles.
