### ISSUE TITLE
Reicast OIT Folder Issue

### ISSUE THREAD

**Issue by Alaharon** [libretro/flycast#149]
The newest version of reicast leaves an empty folder, with the same name, on the directory of the games it loads
 @barbudreadmon

**Comment by barbudreadmon** [comment]
Not sure why you are tagging me. Anyway, be more precise if you want some help, i didn't understand what you are saying and i'm 100% sure no random folder with random name (?) is created in rom directory on my side.

**Comment by Alaharon** [comment]
discord moderator told me to tag you, the reicast oit core when it loads a game, creates an empty folder named "reicast" on the directory of the gdi/cdi file it loaded. Everytime i launch a game an empty folder appears on my game directory

**Comment by inactive123** [comment]
@barbudreadmon I speculated that it could be the case that this directory might be created because of the EEPROM code. Although this is just a guess.

I agree there should probably be more information provided by the OP.

**Comment by barbudreadmon** [comment]
If save directory is set, it will create a reicast subdirectory in it and store eeproms there (i avoid storing saves at the root of the save directory).
If save directory is not set, it won't create a reicast subdirectory, it will store the eeproms alongside the roms.
Basically, it means your save directory is your rom directory, so it is expected behavior. You should either don't set save directory, or set it elsewhere.

**Comment by Alaharon** [comment]
that's strange because this only happened after i updated the core

**Comment by barbudreadmon** [comment]
> that's strange because this only happened after i updated the core

That's not strange, nothing was done about this in reicast before.
Anyway you are right, it seems the `RETRO_ENVIRONMENT_GET_SAVE_DIRECTORY` is always returning something, and is defaulting to rom directory if `savefile_directory` wasn't set in retroarch.cfg (i don't think it was like this when i dealt with eeprom in fba a long time ago, i guess i'll have to modify my code there too). I'll push a fix later today.

**Comment by flyinghead** [comment]
Assuming this is resolved
