### ISSUE TITLE
High Rez Texture Replacement

### ISSUE THREAD

**Issue by shinra358** [libretro/flycast#15]
Would like the ability to have high rez texture packs to clarify and smooth out the 2d elements that are with 3D. As of now, most 2D elements are quite ashy. So whenever the other bugs get smoothed out or performance gets perfected, I'd like to have this.

**Comment by inactive123** [comment]
@flyinghead has implemented xBRZ texture filtering. I have backported it, but currently there is a hang issue that happens when trying to shutdown the core.

**Comment by flyinghead** [comment]
HD texture packs are now supported
