### ISSUE TITLE
Reicast Core Ubuntu Crash

### ISSUE THREAD

**Issue by dragonstory** [libretro/flycast#150]
@flyinghead
Hello
Normal Reicast Core and OIT core has been crashed on Ubuntu 18.
I tested it with 
reicast_oit_libretro.so.zip 2018-07-10 22:54

This is my system OpenGL specs with intel HD GPU

server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.1.3
OpenGL core profile shading language version string: 4.50
OpenGL version string: 3.0 Mesa 18.1.3
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 18.1.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
--------------------------------------------------------------------------------------------------------------------------

And this is the error.

Shader: failed to compile 
0:1(10): error: GLSL 1.40 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, and 3.10 ES

Shader: failed to compile 
0:1(10): error: GLSL 1.40 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, and 3.10 ES

Shader linking: failed to link 
 (102 bytes), - error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader -
[libretro INFO] Fatal error : shader compile fail

 in gl_CompileAndLink -> core/rend/gles/gles.cpp : 391 
DEBUGBREAK!

**Comment by toccata10** [comment]
Reicast_oit is crashing on mesa (known bug). Does reicast (non_oit) crashes too ?

**Comment by dragonstory** [comment]
Yes it has same issue. Crashing too

**Comment by inactive123** [comment]
@flyinghead I believe the issue here is that for some reason on his system, he can't use GL 3.0 profile in conjunction with GLSL 1.40 (talking about the non-OIT renderer here). Could we downgrade the 1.40 requirement to 1.30, and could that maybe fix his issues.

**Comment by flyinghead** [comment]
It looks like OpenGL 3.0 corresponds to GLSL 1.30 so yes, no need for GLSL 1.40.

**Comment by inactive123** [comment]
Pushed a commit setting it to GLSL 1.30. Hopefully this is more compatible.

**Comment by inactive123** [comment]
@dragonstory Can you try it again with the latest Reicast OIT core?

**Comment by dragonstory** [comment]
Hello
i just try it again with lastest Reicast OIT core and it crashes still
please check the link

https://pastebin.com/9bFuSZE7

**Comment by inactive123** [comment]
This is the same issue as this -

https://github.com/libretro/reicast-emulator/issues/167

You can get it to work right now by manually compiling with HAVE_OIT=1 and HAVE_CORE=1, but graphics will be bugged (fogging is bugged right now with core profile).

**Comment by dragonstory** [comment]
when i make it oit:1 and core:1 it is giving Error and not making the core 
https://pastebin.com/GP0tbwmU

**Comment by orbea** [comment]
I want to point out that OIT does not crash with nouveau, instead many textures are missing or broken. Soul calibur is somewhat playable after navigating the missing or empty menus...

**Comment by flyinghead** [comment]
Should now be fixed
