### ISSUE TITLE
error: GLSL 1.40 is not supported

### ISSUE THREAD

**Issue by escalade** [libretro/flycast#151]
The reicast core worked great for me not too long ago, so there must have been a bad commit at some point. This is on the latest c3712fa.

Here's all the relevant logs:

RetroArch log: https://pastebin.com/TzSwZD8e
glxinfo: https://pastebin.com/XBSTXLQt
eglinfo: https://pastebin.com/YTxdT63q

Let me know if you need anything else.

Tested with Mesa 18.1.3 and 18.2 git.

**Comment by inactive123** [comment]
@flyinghead Might there be an issue where the Mesa driver for Intel doesn't support GLSL 1.40 with 3.0 profile context? Is it possible to downgrade to GLSL 1.30 for non-OIT renderer?

**Comment by escalade** [comment]
I got it running using HAVE_GL3=0.

**Comment by inactive123** [comment]
Well, I would still like to find a solution for your problem with GL3. Because ideally, if your GL driver supports 3.0 profile, it should just work from there on out. Not sure if there is any additional functionality in GLSL 1.40 vs. 1.30 that we need for this non-OIT renderer.

**Comment by inactive123** [comment]
Pushed a commit setting it to GLSL 1.30. Hopefully this is more compatible.

**Comment by escalade** [comment]
That did the trick. What about the OIT core? My setup has 4.5 core profile, is a compat profile needed?

**Comment by inactive123** [comment]
Test out the latest core (download it from the buildbot).

**Comment by escalade** [comment]
The same, tried both building it and using the one from the buildbot.

https://pastebin.com/uv8u55Fk

**Comment by inactive123** [comment]
Pushed this commit - hopefully that fixes it -

https://github.com/libretro/reicast-emulator/commit/cd2bdf2e1935823200fe09f5b583f96d0806730e

**Comment by escalade** [comment]
Now I get this:

```
Shader: failed to compile 
0:1(10): error: GLSL 4.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, and 3.10 ES

```

**Comment by inactive123** [comment]
I think Mesa doesn't support GL 4.30 in compatibility context mode. Update and compile the latest version of RetroArch, and then build your reicast oit core with this -

make HAVE_OIT=1 HAVE_CORE=1

See if that works.

**Comment by escalade** [comment]
Fails with RA 1.7.3, but latest git and OIT compiled with HAVE_CORE=1 worked :) Thanks a lot!
