### ISSUE TITLE
Resident Evil Code Veronica with lots of graphics bugs (GL2 non-OIT)

### ISSUE THREAD

**Issue by diegoviola** [libretro/flycast#153]
Hi,

I'm trying to play Resident Evil Code Veronica with the latest reicast core and RetroArch from git.

My hardware is old and can't do OpenGL 3.0, so I had to disable `HAVE_GL3` from the Makefile, the game boots fine with GL2 but it has many graphics glitches, like ones in this screenshot: https://i.imgur.com/HZrqPpL.png

Please note that these glitches also show up when booting the Dreamcast BIOS, so I don't think it's just graphics issues in the game.

My computer is a E5500 CPU with Intel integrated graphics and 2GB of RAM.

    $ lspci | grep VGA
    00:02.0 VGA compatible controller: Intel Corporation 4 Series Chipset Integrated Graphics Controller (rev 03)

I'm on Arch Linux with i3-wm and modesetting drivers.

RetroArch git fd861405143f8dce311fe7e8327199bb15cf1bc2
Reicast core git f556daa98a06818f745e0648db852e070a617138

Thanks in advance.

**Comment by inactive123** [comment]
It could be GL driver issues. @flyinghead Do you know if gl_FragDepth is available on GL 2.x? Maybe the GL driver only supports it through an extension.

**Comment by flyinghead** [comment]
gl_FragDepth is available on all desktop OpenGL versions. On mobile, it requires OpenGL ES 3.

**Comment by diegoviola** [comment]
Looks like a driver issue indeed, and I'm only able to reproduce it on my older G45 machine, I've tried reproducing it on my T450 (broadwell graphics) with the GL2 context and I'm unable to reproduce it there.

I've filed a bug with the Intel upstream developers here: https://bugs.freedesktop.org/show_bug.cgi?id=107212

**Comment by inactive123** [comment]
Try to see if this made any difference - 

https://github.com/libretro/reicast-emulator/commit/fc8eb6db0484def28291466f3d03d305db1098bc

**Comment by diegoviola** [comment]
@twinaphex nope, still the same issue when compiling it without `HAVE_GL3`.

**Comment by diegoviola** [comment]
Wait, I see the commit touches GLES stuff, should I try compiling RA with GLES support?

**Comment by inactive123** [comment]
No. Anyway, looks like it's out of our hands for now then and it's a GL Intel driver problem.

**Comment by diegoviola** [comment]
I've found a workaround for this issue, after applying the workaround graphics look a little better, but still not perfect.
The workaround is:
Remove these two calls to `gl_FragDepth` here: https://github.com/libretro/reicast-emulator/blob/2d411a166d8fa4a4cc5f0cb23c3f60537774333d/core/rend/gles/gles.cpp#L271 and here https://github.com/libretro/reicast-emulator/blob/2d411a166d8fa4a4cc5f0cb23c3f60537774333d/core/rend/gles/gles.cpp#L291.
And replace this line: https://github.com/libretro/reicast-emulator/blob/2d411a166d8fa4a4cc5f0cb23c3f60537774333d/core/rend/gles/gles.cpp#L107 with:

    vpos.z = (1 - 0.002*vpos.w) * vpos.w; \n"

After this graphics should look better, the artifacts are mostly gone but I still get artifacts in other places, like the sky looking black and some artifacts in the walls, etc.

**Comment by diegoviola** [comment]
Nevermind, it doesn't look like #183 is the same issue since it's using a different renderer (OIT), please ignore my last comment.

**Comment by diegoviola** [comment]
@flyinghead do you know if reicast uses `GL_AMD_vertex_shader_layer`? when generating and replaying an apitrace I get the following:

    6405: message: major shader compiler issue 26: 0:1(12): warning: extension `GL_AMD_vertex_shader_layer' unsupported in vertex shader

I wonder if it's the reason behind my problem, I'm using the GL2 context, I have commented `HAVE_GL3`.

**Comment by flyinghead** [comment]
No, the reicast core doesn't use this extension but perhaps the front end does.

**Comment by diegoviola** [comment]
This issue is now fixed with the latest mesa git master.

https://gitlab.freedesktop.org/mesa/mesa/commit/08a5c395abdafd0d7556060596f78c238b4a989f

Closing.
