### ISSUE TITLE
Reicast Naomi save system issues.

### ISSUE THREAD

**Issue by ghost** [libretro/flycast#158]
Reicast needs to revamp it’s save system. The ideal would be a folder called Reicast inside the RA standard saves folder, it should contain only the VMU files and the save files for Naomi (eeprom/sram) and Atomiswave (flash/sram). I don’t know if what was implemented on demul was something standard or entirely created by the author (per game sram) but it works well, I am not using demul anymore, I still have my naomi/atomiswave saves waiting Reicast compatibility.

Right now DC saves are stored with the bios inside the system folder and Naomi eeprom are being saved in a new folder called “savesreicast” located at the main RA directory.

Right SFZ3U has an issue with it's eeprom file. Booting the game without access the test menu works fine. If any change is made like difficulty and game speed the game presents an error like this: 

"ERROR. JAMMA I/O BOARD(S) DON'T HAVE ENOUGH SWITCHES OR FUNCTIONS"

Thanks for the great work, Reicast is a great emulator!

**Comment by barbudreadmon** [comment]
> Reicast needs to revamp it’s save system. The ideal would be a folder called Reicast inside the RA standard saves folder

Already done with my latest commit

> it should contain only the VMU files and the save files for Naomi (eeprom/sram) and Atomiswave (flash/sram)

I used eeprom/nvmem extension for naomi. It is not possible for Atomiswave (reicast doesn't support Atomiswave, it supports "Naomiswave", aka atomiswave games converted to naomi, which is slightly different from a standard atomiswave rom, "Naomiswave" roms will save to eeprom/nvmem)

> Right SFZ3U has an issue with it's eeprom file. Booting the game without access the test menu works fine. If any change is made like difficulty and game speed the game presents an error

Thanks for the information, i'll take a look.

**Comment by ghost** [comment]
Thanks for your reply, now I can use my mvc2 save with all characters unlocked! Do you have any plans to fix the dc bios to make it also save settings/clock preferences ? About SFZ3U it's possible to run the game if no epprom/nvmem is saved in the folder, as soon I quit the game and reopen it the error happens, then it's necessary delete the files to make it work again.

Thanks again for your great passion and work, DC/NAOMI are my favorite platforms and I am having a great time enjoying these games again in such hi quality.

**Comment by barbudreadmon** [comment]
> Do you have any plans to fix the dc bios to make it also save settings/clock preferences ?

To my knowledge, it is supposed to work atm ? Anyway i don't know anything about the dreamcast codebase of this project, so i intend to avoid messing with it if possible. I'm more familiar with arcade systems emulation anyway (spent last ~3 years working on libretro-fbalpha).

The SFZ3U eeprom issue should be fixed after https://github.com/libretro/reicast-emulator/pull/166 is merged. Changing game configuration was actually messing with the bits used to setup the jamma i/o board for this specific game, i'm not sure why, i went back to something closer to reicast original code and the issue disappeared.

**Comment by ghost** [comment]
Thanks for your quick fix for SFZ3U, reicast and fbalpha are my favorite cores, so it looks like i use your  work a lot : D If possible could you take a look on SF Double Impact ? It was working maybe a week ago and now after choose the game the screen goes black but it's still possible to hear the sound and control the menus.

**Comment by barbudreadmon** [comment]
> If possible could you take a look on SF Double Impact ? It was working maybe a week ago and now after choose the game the screen goes black but it's still possible to hear the sound and control the menus.

I guess you are talking about the dreamcast version, i recommend you open an issue about it, with "regression" in the title.

**Comment by ghost** [comment]
Thanks! I'll do it right now.
