### ISSUE TITLE
Tokyo Xtreme Racer - Incorrect colors in vehicle selection

### ISSUE THREAD

**Issue by PixelCrusader** [libretro/flycast#163]
Windows 7 64 bit, AMD Radeon HD 6450, Intel i5-2320 CPU @ 3.00GHz
RetroArch 1.7.3 - Reicast 0.1 19c3a98

During car selection, cars appear with inaccurate colors. Light cars appear as dark and vice versa. Some cars become entirely different colors. Colors will return to normal when pressing up or down on the D-pad to change them. Inverted colors only happen with car selection, they do not carry over into game play,

![tokyo xtreme racer usa -180711-191444](https://user-images.githubusercontent.com/40935002/42604392-7c0a65c8-8540-11e8-800f-ac30236023b5.png)
![tokyo xtreme racer usa -180711-191528](https://user-images.githubusercontent.com/40935002/42604402-8c99fffc-8540-11e8-949d-727175d5a24f.png)

**Comment by inactive123** [comment]
Do you have a video of how it should look like with a real Dreamcast?

**Comment by PixelCrusader** [comment]
Hopefully these clips can suffice:

[1](https://www.youtube.com/watch?v=hpQ052jq1zo#t=1m06s)
[2](https://www.youtube.com/watch?v=6wQhUW20mXo#t=0m58s)
[3](https://www.youtube.com/watch?v=6wQhUW20mXo#t=5m09s)
[4](https://www.youtube.com/watch?v=ROlOHvmATRU)
[5](https://www.youtube.com/watch?v=WlNJYCgcE_s#t=1m20s)

**Comment by inactive123** [comment]
Yeah, I can see the issue clearly with the first car and link 1.

@flyinghead Looks like a valid graphics bug.

**Comment by flyinghead** [comment]
This is caused by the `-ffast-math` gcc option, which turns on the `-ffinite-math-only` option. As the name implies it makes the compiler ignore NaN and Infinity values and leads to incorrect results for operations involving these numbers.
Note that both dynarec and interpreter are affected, although the latter seems to be a bit more accurate.
Working on a fix.

**Comment by inactive123** [comment]
Sure seems to be a recurring pattern where compiler optimizations seems to break many elements of Reicast when it comes to float.

**Comment by flyinghead** [comment]
Absolutely. I wonder if this fast-math option makes sense for desktop platforms. The performance gain is probably negligible compared to the potential for errors.

**Comment by inactive123** [comment]
OK, so I should just remove it from the Makefile?

**Comment by flyinghead** [comment]
It does fix this issue, as well as the previous one with sqrt (Soldiers of Fortune). Not sure of the negative side effects though.
I'd rather work on a fix that works with fast-math so it can be used on low end platforms. But you might want to get rid of this option completely since you don't really target them.

**Comment by inactive123** [comment]
OK, lets see what you come up with then, I am intrigued.

**Comment by flyinghead** [comment]
Here we go: https://github.com/flyinghead/reicast-emulator/commit/ea35eeb72871996121f1b6474ee9c6e3b25dfa63

Yet I still think we'd be better without the fast-math option. I'll do some testing.

**Comment by flyinghead** [comment]
You might want to hold off for now. This commit breaks Fur Fighters (well, it was broken before but now it freezes in game). Potentially other games are affected as well. Looks like more work is needed...

**Comment by inactive123** [comment]
OK, I had backported it just now but I guess I will revert it for now and wait for your better solution.

**Comment by flyinghead** [comment]
Well I stand by my commit so far. Fur Fighters is totally broken anyway, so the problem is elsewhere. I'll do some more investigation in this area anyway.

**Comment by inactive123** [comment]
OK, I will backport your commits now then.

**Comment by inactive123** [comment]
OK, backported them. The OP might want to wait for new updated cores on the buildbot or build his own and test his results.

**Comment by PixelCrusader** [comment]
83c8c07

The cars now appear with their correct colors, consistent with the videos. There is no longer a 'jump' from glitched colors to correct ones when changing them. 

I can't say for certain without a full playthrough on different settings , but at a glance it looks like this game has no more noticeable issues. 

Thanks! Closing the issue.
