### ISSUE TITLE
Demolition Racer crashing

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#164]
Demolition Racer crashes soon after entering a "Demolition" race.

Tested on linux x64, kernel 4.15 against commit 84216d7642484b48fc0e63432a9d6c03c6f960b1

**Comment by flyinghead** [comment]
Another game that needs div32 matching to be disabled. See https://github.com/flyinghead/reicast-emulator/commit/8a9313270f6c43cbe969545177071cceed1ba915

**Comment by inactive123** [comment]
Hopefully this detection works -

https://github.com/libretro/reicast-emulator/commit/03d582c10949110ce5e4f7aa45a31f8dce0b4bf0

**Comment by Shoegzer** [comment]
@twinaphex It works indeed, and the game isn't crashing anymore (though Pro Pinball on that list still crashes).  Thanks, both of you.  I can close this issue now, unless you feel it would be better to keep it open until a proper fix is discovered that avoids per-game settings?  Your call.

**Comment by inactive123** [comment]
I think we can close it for now.
