### ISSUE TITLE
Eldorado Gate 1 broken opening FMV

### ISSUE THREAD

**Issue by anothername99** [libretro/flycast#165]
The music fades out almost immediately for some reason. If you try to watch the whole thing, the emulation will also freeze.

Here's what the opening is supposed to be like, at 0:15: https://www.youtube.com/watch?v=RisCWtOygCo

**Comment by flyinghead** [comment]
This game needs EGHack to be on. See https://github.com/flyinghead/reicast-emulator/commit/df35e95e57ae62989236724c78fd759e9ff61652

**Comment by anothername99** [comment]
Thanks but what is EGHack about? Is it compensating for incomplete AICA emulation?

**Comment by flyinghead** [comment]
It's a hack related to timing of AICA interrupts. This change will be backported to the libretro core soon and you won't have to worry about it.

**Comment by anothername99** [comment]
Ok, I should open a new issue for AICA emulation in general. The only reason I test Reicast and report issues is accuracy.

**Comment by inactive123** [comment]
Hopefully this detection works -

https://github.com/libretro/reicast-emulator/commit/03d582c10949110ce5e4f7aa45a31f8dce0b4bf0
