### ISSUE TITLE
Street Fighter III Double Impact

### ISSUE THREAD

**Issue by ghost** [libretro/flycast#168]
Hello! 
First thanks everyone involved in this project, I am really grateful.

Maybe a week ago or a little more SF3 Double Impact was working normally, now after the screen to choose which game to play, it goes to directly a black screen, it is kinda curious because sound and controls keep working, only the video is not shown.

Thanks again!

**Comment by inactive123** [comment]
I cannot reproduce this - I have tried the PAL CDI version and both Street Fighter III and Street Fighter III: Double Impact work fine.

Perhaps you need to set framerate to fullspeed?

**Comment by aneronds** [comment]
It was working before and stopped, now it's working again, something was changed in the last update yesterday and even the performance seems better. 
I only play fighting games on DC/NAOMI and with this all the games i wanted to play are fully compatible : D

Thanks for your reply!!

**Comment by inactive123** [comment]
OK, so this issue can be closed?

**Comment by aneronds** [comment]
Yes, please close the issue. Thanks for your attention :  )
