### ISSUE TITLE
The King of Fighters Dream Match 1999 - Sprites glitch between rounds

### ISSUE THREAD

**Issue by PixelCrusader** [libretro/flycast#172]
Windows 7 64 bit, AMD Radeon HD 6450, Intel i5-2320 CPU @ 3.00GHz
RetroArch 1.7.3 - Reicast 0.1 db11a17

Character sprites glitch in their animations before, between and the end of rounds.

![king of fighters the - dream match 1999 usa -180711-201230](https://user-images.githubusercontent.com/40935002/42664177-5ba7b2f0-8607-11e8-88c6-b99cf5abc840.png)
![king of fighters the - dream match 1999 usa -180711-202304](https://user-images.githubusercontent.com/40935002/42664191-6df47358-8607-11e8-9f16-39131f9744b0.png)
![king of fighters the - dream match 1999 usa -180711-201720](https://user-images.githubusercontent.com/40935002/42664209-8028e63a-8607-11e8-8045-92e9275419c5.png)
![king of fighters the - dream match 1999 usa -180711-201418](https://user-images.githubusercontent.com/40935002/42664239-a5ff7e14-8607-11e8-9269-550d2d9d8977.png)

Reference Videos: [1](https://www.youtube.com/watch?annotation_id=annotation_2541736385&feature=iv&src_vid=D5R9Zf38MGc&v=o9lssD3hHoA#t=3m53s) [2](https://www.youtube.com/watch?v=suWSzkD-1e0&t=377s#t=3m53s) [3](https://www.youtube.com/watch?v=lxk99ugI5GI&t=59s#t=0m43s)

**Comment by cubatilles** [comment]
Hi,

Just wanted to share that there's a "workaround" for this problem. If you enable Texture upscaling (xBRZ), this does not happen. I have this setting enabled for this game:
reicast_texupscale = "2x"

And all sprites look fine. Of course, sprites now are upscaled and have a xbrz filter, but this is preferable to the glitches described by PixelCrusader.

Greetings.

**Comment by flyinghead** [comment]
These are not glitches but artefacts due to the increased resolution. If you set the resolution to 640x480 these artefacts will disappear.
The workaround proposed by @cubatilles increases the resolution of the textures and thus cancels this effect as well.

**Comment by PixelCrusader** [comment]
Windows 7 64 bit, AMD Radeon HD 6450, Intel i5-2320 CPU @ 3.00GHz
RetroArch 1.7.5, Git 7c93a0934e, Reicast 0.1 207db67

Thanks for helping, @cubatilles . The xBRZ does work on my end. It looks to be useful for running the game at higher resolutions.

@flyinghead , the pictures I posted were from running the game at 640x480 resolution. However, at 320x240 the artifacts disappear.

So either run the game at 320x240 for the accurate experience, or run it at a higher resolution with xBRZ turned on to remove the texture artifacts that will otherwise appear from running the game at a higher resolution than what it was designed for.

That makes this another game that needs custom settings to work, but it does work. If everybody is satisfied, I'm going to close this.

**Comment by mochardi** [comment]
Hi, 
New guy here!
I was wondering about this issue. If the artifacts appear at 640x480 (The native resolution of the Dreamcast) shouldn't this issue be open again?

Running the game at 320x240 fixes the issue, but i don't think that is a permanent solution, just a "workaround" that creates another problem (the 3d backgrounds look like crap in this resolution)

The odd thing is that the sprites glitch only occur in the animations before, between and the end of rounds. Not during the round itself.
