### ISSUE TITLE
Soul Calibur - Pressing R near the side of the camera results in some geometry glitches

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#175]
@flyinghead This issue has become a bit more pronounced now after these commits but it has always been there to a degree so it might be a good time to look into it -

Basically, during a fight, go to the edge of the arena, make sure your character is close to the camera and press R to charge your weapon. The issue I believe is that some of the geometry/lighting happens very close to the near/far plane of the camera, and it results in some geometry/graphics glitches.

Not sure if this happens only on Nvidia but I can easily trigger it.

**Comment by inactive123** [comment]
Here is a screenshot of what it can look like -

![image](https://user-images.githubusercontent.com/1075274/42714260-d53dc654-86f2-11e8-902f-3ff5bb69e467.png)

**Comment by flyinghead** [comment]
Do you have a significant frame rate drop / freeze when this happens?

**Comment by inactive123** [comment]
@flyinghead Nah I think you can ignore that FPS figure, that is just me ALT-TABbing back and forth, and hence FPS being reported inaccurately.

**Comment by flyinghead** [comment]
This is due to my totally bogus fixNaN commit. Please revert it asap.

**Comment by inactive123** [comment]
Fixed entirely by this now -

https://github.com/libretro/reicast-emulator/commit/8f5706bbbae3f79d5525bf6d94753aba70ebef18
