### ISSUE TITLE
Vigilante 8: 2nd Offense (USA version) - crashes after Dreamcast swirl boot screen

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#176]
Vigilante 8: 2nd Offense (USA version) crashes from startup after the Dreamcast swirl boot screen.

The UK version works though, although it has some graphics bugs which I will detail in another issue.

**Comment by flyinghead** [comment]
Could be a bad dump: I tried a USA version (CDI) with the OIT core and no crash. Same issues as the UK version though.

**Comment by ghost** [comment]
Confirmed RA reicast oit crashes to desktop after bios splash.

**Comment by flyinghead** [comment]
Another game that doesn't like Cable = TV (RGB). Use TV (Composite) instead.
