### ISSUE TITLE
Retroarch crashed when activate fullscreen with Reicast core

### ISSUE THREAD

**Issue by legluondunet** [libretro/flycast#179]
Hello,
Retroarch crashed when I activate fullscreen.
I can reproduce this bug each time.

This is my terminal log:
[retroarch.log](https://github.com/libretro/reicast-emulator/files/2194781/retroarch.log)

Config: 
Ubuntu 18.04
Nvidia official Ubuntu drivers 390.48

**Comment by inactive123** [comment]
Known issue, not a priority yet. Context destroyal/recreation is currently buggy with GL.

**Comment by barbudreadmon** [comment]
Fullscreen works for me if i enable it before running a game.

**Comment by flyinghead** [comment]
Works for me. Reopen as needed
