### ISSUE TITLE
Street Fighter Alpha 3 - needs Cable Type set to VGA or else emulator quits

### ISSUE THREAD

**Issue by PixelCrusader** [libretro/flycast#182]
Windows 7 64 bit, AMD Radeon HD 6450, Intel i5-2320 CPU @ 3.00GHz
RetroArch 1.7.3 - Reicast 0.1 83c8c07

Launching Street Fighter Alpha 3 shows the Dreamcast logo and then closes RetroArch. No error message is given.

**Comment by inactive123** [comment]
Which version of the game?

**Comment by PixelCrusader** [comment]
American.

**Comment by inactive123** [comment]
Looks like this only happens with the .gdi version and not the .cdi version. I could get it to work by setting Cable Type to VGA (RGB) though. Try that.

**Comment by PixelCrusader** [comment]
Yes it was the gdi version and it's working now. 

Unless getting it to work on TV (RGB) is a worthy issue, I guess this a false positive. Sorry about that.

**Comment by flyinghead** [comment]
This games doesn't support TV (RGB) which used to be the default
