### ISSUE TITLE
(Regression) Resident Evil Code Veronica - crashes as soon as you press up at the beginning

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#185]
This game worked before without crashes.

It crashes at this screen to be precise -

![image](https://user-images.githubusercontent.com/1075274/43079196-bc548168-8e8c-11e8-88be-c135c9c42249.png)

This is what happens when the crash gets triggered -

[GPF]Unhandled access to : 0x5F36A000
Segmentation fault

I will try doing some more bisects later.

**Comment by inactive123** [comment]
Happens in both OIT and non-OIT renderers.

**Comment by inactive123** [comment]
Went back to this commit from July 10 and here it still works -

https://github.com/libretro/reicast-emulator/commit/e9f0b77c3b676a57f0ddb52cd7b21d582cad597a

Going to bisect a bit more thoroughly now.

**Comment by inactive123** [comment]
@flyinghead

This seems to be the commit that caused the regression -

https://github.com/libretro/reicast-emulator/commit/d0f2502c21133e51ca0f04a2a645459c1a81728b

Any ideas? Does this happen in your fork also or is it only the libretro core? Did I backport something wrong perhaps?

**Comment by flyinghead** [comment]
The same happens on my fork

**Comment by flyinghead** [comment]
Here is a fix: https://github.com/flyinghead/reicast-emulator/commit/04c896d655755712fc9c9038b23a7b344b630cc1

**Comment by inactive123** [comment]
Thanks a lot, going to check this real quick!

**Comment by inactive123** [comment]
Issues are fixed, thanks a lot!
