### ISSUE TITLE
4 Wheel Thunder - Split screen bug?

### ISSUE THREAD

**Issue by cafcmike** [libretro/flycast#186]
I can't seem to get split-screen working on 4 Wheel Thunder. Most of the screen is cut off.

![4 wheel thunder usa -180726-172214](https://user-images.githubusercontent.com/11161083/43275150-f8804dca-90f8-11e8-9044-a65031551a63.png)

**Comment by flyinghead** [comment]
@twinaphex Here is a fix: https://github.com/reicast/reicast-emulator/commit/0e881254ef4899221796301cfc800b1f6dbc95db

**Comment by inactive123** [comment]
thanks @flyinghead!

@cafcmike Backported this -

https://github.com/libretro/reicast-emulator/commit/b7a698654b26efa15ef82b3ea4c2c846fd99bc1b

Let me know if it fixes things.

**Comment by cafcmike** [comment]
Awesome, working great now, thanks!
