### ISSUE TITLE
Aqua GT unplayable

### ISSUE THREAD

**Issue by cafcmike** [libretro/flycast#187]
Aqua GT appears to be unplayable - all I see is this:

![aqua gt europe -180726-210945](https://user-images.githubusercontent.com/11161083/43285917-628353b0-9118-11e8-9bea-de6c865d9bbd.png)

**Comment by inactive123** [comment]
Can you retry this game again after this commit?

https://github.com/libretro/reicast-emulator/commit/ff8e12c61ceb578c3eca9e0d82efb05fec1acd89

The game seems to render mostly fine for me with Reicast OIT and the European version of the game.

**Comment by flyinghead** [comment]
Should work fine now. Reopen as needed
