### ISSUE TITLE
Loading CHD compressed GDI images does not work

### ISSUE THREAD

**Issue by igno2k** [libretro/flycast#19]
When opening a CHD compressed GDI image Reicast fails to play the game. Same image will work with native GDI without compression. Loading the CHD with Redream works.

Tested on Windows (latest build) and Lakka x86_64 (2.1 RC5).

On Windows in Debug mode I can see a lot of this messages:
Sector read miss FAD: <somenumber>

After that Retroarch crashe (can I output the log on Windows somewhere to a file?).

Any help appreciated.

Regards,
Matthias

**Comment by i30817** [comment]
If you try to roundtrip *some* of the gdi images on the TOSEC dump, some roundtrip file, the others get converted to toc+single bin. I don't actually know why, but it might be related.
edit: this is because of the extension of the output parameter of chdman. IF it's `chdman -i a.chd -o out.gdi` it creates a gdi file. If it's  `chdman -i a.chd -o out` it creates a TOC file.

**Comment by crocket** [comment]
I encountered this problem, too.

**Comment by crocket** [comment]
I think this issue is probably a duplicate of https://github.com/reicast/reicast-emulator/issues/676

**Comment by i30817** [comment]
Quite likely.

**Comment by crocket** [comment]
Convert CHD v5 files to CHD v4 files and load them with reicast-libretro if you can.

mednafen-saturn-libretro handles CHD v5 files well.

**Comment by i30817** [comment]
That is not a good idea. Not only the current chdman (the only way to create these files) uses v5 by default, it's the one that has best design of the lot, including a metadata facility, single signature hashsum and lossless compression/decompression roundtrip and multiple decompression formats.

I'll just wait until a v5 library happens and is used by RA. One day, NIH in this format will stop and MAME will finally release a sane library that can be used by other projects (including for VFS). RA doesn't support child/parent clones either.

**Comment by crocket** [comment]
I think it's apt to rename this issue to `Add CHD v5 support`.

**Comment by i30817** [comment]
The MAME core should actually already have code to read them in order to support current cd dumps, but there is probably a reason that MAME doesn't have a library already (ie: code is tightly coupled).

**Comment by Awakened0** [comment]
I wonder if @rtissera 's [libchdr](https://github.com/rtissera/libchdr) that is used in the other cores like beetle PSX and PCE Fast could be used here for CHD V5 support.

**Comment by blisstik** [comment]
@igno2k please verify the latest build and close as necessary.

**Comment by crocket** [comment]
Reicast now supports CHDv5.

**Comment by flyinghead** [comment]
CHD v5 support has been available for a while now.
