### ISSUE TITLE
Resident Evil Code Veronica - wrongly clipped rain fall audio sample

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#191]
At the very beginning of the game, as soon as you get out of the prison and go upstairs, you can hear badly clipped rainfall audio samples. They cut off too soon and then repeat again.

Backporting the generic DSP, enabling it and also backporting this (https://github.com/reicast/reicast-emulator/commit/92c06a72499479a01e96543594ce7fe0bf260dcb) did not help fix this issue I'm afraid.

**Comment by inactive123** [comment]
@flyinghead Might be something worth looking into since it seems some other games exhibit similar issues.

For instance, there is a sound bug reported here that sounds pretty similar in nature -

https://github.com/libretro/reicast-emulator/issues/181

> There is a sound bug during a cutscene in this stage where the sound of running water is cut off prematurely.

**Comment by flyinghead** [comment]
I've been working on audio for the past few days. I found a couple of issues but nothing groundbreaking.
The DSP does help certain games but the sound problems are still there.

**Comment by Shoegzer** [comment]
Confirmed, this is still an issue.  Tested against RetroArch 1.7.5 (Git 75485e7) with pulse audio driver compiled on linux x64 with 4.15 kernel.

**Comment by flyinghead** [comment]
This commit should fix it: https://github.com/libretro/flycast/commit/823624199888ddbb256ed76d81de2f0709a93860

**Comment by inactive123** [comment]
This issue is finally fixed yeah.

**Comment by SkyLinkeira** [comment]
I downloaded a ROM that I am using on the NullDC emulator and I have this same problem, I have no idea how to solve it, could you help me, please?
