### ISSUE TITLE
Reicast/Reicast OIT painfully slow on AMD discrete card.

### ISSUE THREAD

**Issue by ghost** [libretro/flycast#193]
My laptop specs:
Intel Core i5-4200U 1.6 - 2.3 Ghz
Intel HD 4400
AMD Radeon R7M265

With Integrated Intel HD Reicast runs well while Reicast OIT is slow.
With AMD both runs painfully slow.

Latest drivers.

**Comment by schrock** [comment]
I have the same issue. It looks like the Reicast core is not making my AMD card (7970) come up to its regular gaming clock rate (1000 Mhz). Instead, it is just idling at 300 Mhz. Other cores, such as Dolphin work correctly.

**Comment by flyinghead** [comment]
AMD cards should now run at normal speed. Reopen if the issue persists.
