### ISSUE TITLE
Maken X crash-to-desktop during cutscene after mission 1.

### ISSUE THREAD

**Issue by boomercore** [libretro/flycast#196]
First of all, thank you for finally implementing DSP which fixes the sound in this game, but unfortunately after you complete the first level, there's a lengthy cutscene with no opportunity to save that crashes toward the end.  It's the part where brainjacked Russian colonel is about to be approached on the plane, which I believe is supposed to lead into a menu or gameplay.  It dumps right to desktop in the latest nightly retroarch and Reicast OIT build as of 8/9/18.  Game runs incredibly nicely and plays well with widescreen and high resolution rendering otherwise.

Windows 10 x64, i5 4670k, GTX 1060, Nvidia Audio, OpenGL renderer, Xaudio, hard sync.

**Comment by boomercore** [comment]
So I just got past this cutscene by kitchen sink disabling things, sadly.  Wish I had something more scientific.  I turned hard sync off, dialed audio latency from 16ms back up to 64ms, and disabled the softeststep glsl shader I used to smooth out jagged pixels without making them too smooth.  Lord knows what fixed it.  I'll try to recreate in a bit.  I just turned logging on too.

**Comment by boomercore** [comment]
I think it was the GLSL shader.  Have all my options as they were except that and it made it past that part twice now.  I'm not sure why it was that cutscene in particular.  Maybe it put an effect on top that just messed everything up, merely speculating.  Any other reports of shaders crashing the core?

**Comment by inactive123** [comment]
Hi, I heard a similar bug report from another user who said this game crashed for him at the same spot. What would you recommend he do in order to sidestep this?

**Comment by boomercore** [comment]
It actually started happening again in other levels/instances, so I didn't sidestep it.

**Comment by flyinghead** [comment]
A save state or vmu would help here

**Comment by boomercore** [comment]
Turns out I have a VMU with a save right before a point where you can replicate the problem.  If you load this save and select the Oil Palace from the world map it will crash every time in both plain and OIT versions of the Reicast core.  Confirmed this on the last RA nightly and updated versions of the cores in Windows 10 x64.  I had to finish the game in Demul from here.  I can't 100% prove it's the same problem I witnessed in other parts of the game where I'd be able to sometimes progress past the crashing point or not, but it's likely related.

https://files.fm/u/hsmunsa5

**Comment by flyinghead** [comment]
I was able to load the VMU and enter Oil Palace.
At which point is it supposed to crash?

**Comment by flyinghead** [comment]
Correction: the game shows a blackscreen with the non-OIT core.
I also see some texture corruption on the VMU load screen.

**Comment by flyinghead** [comment]
@n1ghttrap Enabling "GD-ROM Fast Loading" seems to make the game work

It it also works on your end, this could be added as a game-specific setting.

**Comment by boomercore** [comment]
Indeed, that fixes the level loading black screen.  Whether or not Fast Loading will fix the other crashes, I can't say.  Thanks for looking at it.

**Comment by inactive123** [comment]
Hmm,that is an odd discovery at least, that the 'GD-ROM Fast Loading' hack actually manages to get us past a crash/freeze.

**Comment by flyinghead** [comment]
Do you know of any game that requires the "GD-ROM Fast Loading" option to be off?

The current interrupt time with Fast Loading off is a bit on the slow side given the theoretical GD-ROM transfer rate but setting it to the right timing doesn't help.

**Comment by flyinghead** [comment]
Skies of Arcadia needs it off apparently

**Comment by blisstik** [comment]
Does fast loading only apply to DC games?

________________________________

**Comment by flyinghead** [comment]
GD-ROM only, yes. I don't think the GD-ROM is emulated for NAOMI games

**Comment by Boviligg** [comment]
Same problem here i'm afraid. It crashes at the exact same cutscene. Enabling fast loading doesn't seem to fix it.

**Comment by flyinghead** [comment]
Closing as resolved
