### ISSUE TITLE
trying to compile for arm generic fails

### ISSUE THREAD

**Issue by Ntemis** [libretro/flycast#20]
core/rec-cpp/rec_cpp.cpp:36:8: warning: type 'struct CC_PS' violates the C++ One Definition Rule [-Wodr]
 struct CC_PS
        ^
core/rec-ARM/rec_arm.cpp:571:8: note: a different type is defined in another translation unit
 struct CC_PS
        ^
core/rec-cpp/rec_cpp.cpp:39:14: note: the first difference of corresponding definitions is field 'prm'
  shil_param* prm;
              ^
core/rec-ARM/rec_arm.cpp:574:14: note: a field with different name is defined in another translation unit
  shil_param* par;
              ^
/tmp/ccqifZeV.s: Assembler messages:
/tmp/ccqifZeV.s:34862: Warning: ignoring changed section attributes for .text
core/rec-ARM/ngen_arm.o(.text+0x34): error: undefined reference to 'ta_vtx_data32(void*)'
core/rec-ARM/ngen_arm.o(.text+0x44): error: undefined reference to 'YUV_data(unsigned int*, unsigned int)'
core/rec-ARM/ngen_arm.o(.text+0xf0): error: undefined reference to 'CompileCode'
collect2: error: ld returned 1 exit status
make: *** [Makefile:554: reicast_libretro.so] Error 1

**Comment by flyinghead** [comment]
No news is good news
