### ISSUE TITLE
Dynamic LST Files

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#202]
Hi,

I'm proposing a way to dynamically create the LST file on the fly.

For example, Toy Fighter.bin file size in bytes is 92274688. Using a calculator to convert decimal to hex will return "5800000". The hex will always be 7 digits and follows the 0x0"5800000"

Toy Fighter
"Toy Fighter.bin", 0x0000000, 0x05800000

So the logic would go something like this:

1. The BIN is used to launch
2. Read the filename of bin without extension
3. Read the filesize of the BIN in bytes
4. Convert that to hex value
5. Generate an LST file based on $filename.bin
6. Generate contents of LST as an example:

$filename
"$filename.bin", 0x0000000, concatenate(0x0, $hexvalue)

7. The LST is generated an used to launch the game

**Comment by barbudreadmon** [comment]
The first line is expected to be a game specific string for lut detection, so your idea wouldn't work.

**Comment by blisstik** [comment]
OK, just throwing it out there. Will close.
