### ISSUE TITLE
Wacky Races - Almost but not quite playable

### ISSUE THREAD

**Issue by SuperL2** [libretro/flycast#214]
So, on the new Android recist build, Wacky Races is the most playable it's ever been. Previously on Android, the game would be nothing but black screen, but on this build, the left half of the screen renders somewhat normally. The controls are also fidgety but I was on one occasion able to get to the character select screen and select a character.

As I understand it, one of the latest builds of the Reicast core for the PC fixed almost all of the issues and made this game and others fully playable. Will those improvements make their way to the Android build?

**Comment by inactive123** [comment]
Hi there -

https://github.com/libretro/reicast-emulator/commit/ff8e12c61ceb578c3eca9e0d82efb05fec1acd89

The menu screen shuld now render properly.

**Comment by SuperL2** [comment]
I just tested it. The menu works just fine and the controls actually work now. However, the opening cutscene is all black (the only part to render properly on standalone reicast), and the right side of the screen is still black. 

I'm using a Shield K1, if it helps.

**Comment by blisstik** [comment]
I also tested this in the Odroid XU4 ARM build. I have the same experience as SuperL2. Opening cutscene is black until you start it and the right side of the screen is all black. I gave up trying to play half blind. LOL

**Comment by inactive123** [comment]
>  However, the opening cutscene is all black (the only part to render properly on standalone reicast),

I think that is down to the general bug on Android/ARM where FMV cut scenes dont' show any graphics.

Any thoughts there @flyinghead ?

**Comment by inactive123** [comment]
> and the right side of the screen is still black.

This might be fixed by the latest commit I just pushed -

https://github.com/libretro/reicast-emulator/commit/5318a366010efb3019fbd6024fd50e2c8f8b44b3

**Comment by SuperL2** [comment]
Tested it. The newest update fixed the black screen problem. However, having the resolution at 640x480 will garble the rightmost part of the screen (but not 320x240).

Without Threaded Video, there are random terrible glitches during the game that make races nigh unplayable.

The controls also don't seem to want to work as well when Threaded Video is turned on, with frequent freezes and lots of input lag. I wasn't able to get far enough to see if the glitches occur with Threaded video as well.

**Comment by inactive123** [comment]
> The controls also don't seem to want to work as well when Threaded Video is turned on, with frequent freezes and lots of input lag. 

I have heard it reported by other people that for the threaded video option in Reicast, you need to set Poll Type Behavior in RetroArch to Early. You can find this setting in Settings -> Input.

**Comment by Deivmsr** [comment]
During game play these graphical glitches occur:
![screenshot_20180817-232232](https://user-images.githubusercontent.com/40547165/44299318-6f084180-a2c1-11e8-893b-dc467f9a63e1.jpg)

**Comment by SuperL2** [comment]
Tested it.

Changing the poll behavior completely fixed the control problem. Thanks, Twinaphex.

On Threaded, the graphical glitches that Deivmsr reported happen much less frequently than they do on non-Thread. For me, it happens at the beginning of the race and whenever the player car collides with the other cars.

Overall, the game is just about playable.

**Comment by SuperL2** [comment]
Oh, and setting the resolution higher than 320x240 will cause the graphics to corrupt. The higher the resolution, the worse the problem is.

And the game will crash Retroarch at random.

**Comment by SuperL2** [comment]
Tested it again. 640x480 now renders properly. However, the in race glitches shown above are still happening and much worse and much more frequently than before. And crashes are still a problem

**Comment by flyinghead** [comment]
`List overrun for list verts`

**Comment by inactive123** [comment]
I merged @flyinghead 's PR. This *might* be fixed now (hopefully).

**Comment by flyinghead** [comment]
Should run fine now
