### ISSUE TITLE
Melty Blood Act Cadenza (Ver B2) Flashing Issue [Naomi XU4 ARM non-OIT]

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#216]
Before the round starts, there's purple/magenta flashing color.

**Comment by flyinghead** [comment]
Should be fixed by https://github.com/reicast/reicast-emulator/commit/395bfd5dbb6c85cffaf50f9349ff5fa95e8cd84f

**Comment by blisstik** [comment]
Fixed!
