### ISSUE TITLE
Soul Calibur, black characters in RetroArch Android core.

### ISSUE THREAD

**Issue by blackman91** [libretro/flycast#218]
Using latest reicast core on Android 7, changing the internal resolution or disabling threaded rendering doesn't fix it:
![screenshot_20180818-203443](https://user-images.githubusercontent.com/6578180/44304675-423b4500-a328-11e8-93af-d230d632c301.png)

Using PAL Soul Calibur .chd

**Comment by inactive123** [comment]
Can you list the hardware you are using?

**Comment by blackman91** [comment]
Motog5 plus. BTW that bug is not present in flyinghead my master reicast builds using the same device.

**Comment by xTMODx** [comment]
I can confirm this also the text is corrupt here 
![screenshot_20180829-031213](https://user-images.githubusercontent.com/19918301/44759301-9a005a00-ab39-11e8-9829-619cfbd25e97.jpg)

**Comment by orbea** [comment]
The corrupted / garbled text is a more wide spread issue. I can reproduce this with both nouveau and the llvmpipe.

**Comment by inactive123** [comment]
I don't get these issues at all with either mainline nvidia drivers (Windows/Linux) and/or Intel HD drivers.

**Comment by inactive123** [comment]
Also @orbea , we need to be careful not to conflate results on Android vs. Windows/Linux here. Completely different GL driver implementations, etc.

Anyway, the only one capable of fixing these issues would be @flyinghead .

**Comment by inactive123** [comment]
What doesn't help is that we don't have devices to help reproduce this.

**Comment by orbea** [comment]
It could be llvmpipe and nouveau are affected the same way as some android drivers for the garbled text issue while intel isn't. The other issue with black textures I can't reproduce on linux either.

**Comment by blackman91** [comment]
This issue and the fmv not showing should be easily reproduceable on any Android phone 32 bit arm with gl 3, 3.1 and above.

**Comment by blisstik** [comment]
Just tested on latest commits, it's still dark characters.

**Comment by inactive123** [comment]
@orbea Could you ask nouveau developers about this? I don't think it happens on the binary nvidia driver.

**Comment by orbea** [comment]
@twinaphex No need, the text issue has already been fixed. https://github.com/libretro/reicast-emulator/pull/239

**Comment by inactive123** [comment]
@orbea what about the black characters glitch? Can that be reproduced on non Android devices?

**Comment by orbea** [comment]
@twinaphex No, that one doesn't happen with nouveau.

**Comment by blisstik** [comment]
Hey guys, I've compiled to the latest and the Odroid XU4 is still having black characters. Why didn't my device get fixed?

**Comment by orbea** [comment]
I suspect your black characters are an android specific driver bug, ideally your phone providers should fix that, but finding a work around might be faster...

Unfortunately android devices are often like this with broken drivers...

**Comment by blackman91** [comment]
But the bug doesn't happen on flying head master from here:
http://builds.reicast.com/

The libretro core is almost the same as fh reicast branch right?

**Comment by flyinghead** [comment]
One major difference is that the reicast core doesn't render directly to screen but to a framebuffer. This can cause issues with depth and shadows. For example shadows are not currently supported on the Raspberry Pi (VideoCore 4) because of this. 
I'll try to reproduce this problem and find a solution.

**Comment by fivefeet8** [comment]
Black characters and title screen happens on my Shield TV as well.

**Comment by blackman91** [comment]
This issue is definitely related to this one:
https://github.com/libretro/reicast-emulator/issues/237

**Comment by blackman91** [comment]
This should be solved on latest core but can't confirm because libretro reicast won't run chd v4, so if anyone else still having this issue please reopen, btw flying head is the man!

**Comment by blisstik** [comment]
Also confirming it's fixed on 32-bit ARM on Odroid XU4
