### ISSUE TITLE
Fullscreen toggle breaks the emulator screen on X11.

### ISSUE THREAD

**Issue by crocket** [libretro/flycast#22]
After fullscreen toggle, the screen becomes black, but the audio is audible.
Resetting reicast-libretro doesn't fix the problem.

OS : Gentoo Linux
CPU : AMD FX-8300
GPU : AMD HD6450
RetroArch-1.7.1
RetroArch Video Driver : gl
reicast-libretro fff2eb2f92251db82cb763d3ab1d19be4a705f95

Does reicast-libretro need to apply https://github.com/reicast/reicast-emulator/pull/774?

**Comment by crocket** [comment]
Does reicast-libretro need to apply https://github.com/reicast/reicast-emulator/pull/774?

**Comment by crocket** [comment]
I just confirmed that the latest commit of reicast-libretro has this issue.

**Comment by marcrobledo** [comment]
I don't know if it would be related but... In Windows switching from FS to window, it just makes RetroArch crash.

**Comment by flyinghead** [comment]
This has been fixed
