### ISSUE TITLE
Reicast core starts always in fullscreen

### ISSUE THREAD

**Issue by marcrobledo** [libretro/flycast#221]
Even if RetroArch is windowed, Reicast core always starts in full screen. And if you try to switch from fullscreen to windowed mode, it crashes.

Tests done in Windows RetroArch.

**Comment by RagingNoob** [comment]
It's appreciated if you could answer the following:

1. Does your Reicast run fine in full screen (runs games) ?
2. Have you saved any custom cfg for Reicast ?
2a. Have you checked inside the 'config' folder for any saved files ?
3. Have you compared your retroarch.cfg with retroarch.default.cfg using a comparison tool, such as diffchecker.com ?
---------------------------
I have a problem where I can only run Reicast in a window (Windows 7 x64 SP1, 1060GTX) . If I switch to full screen it will crash. I will report this issue.

**Comment by orbea** [comment]
The crashes when toggling fullscreen are a known issue. Context reset is broken in reicast. The always starts in fullscreen sounds like a configuration setting in the frontend (RetroArch).

https://github.com/libretro/reicast-emulator/issues/179

**Comment by marcrobledo** [comment]
@RagingNoob 
1. Yes.
2. No. Well, I had some core options in retroarch-core-options.cfg that I removed for testing purposes, without any luck :-(
3. Yes. And I've tried with a clean Retroarch config too.

@orbea no, it happens only with Reicast core. All cores open fine when launched windowed.

**Comment by orbea** [comment]
Well, I'm not sure then. I can't reproduce it on linux, only the crash due to the lack of a working context reset (ppsspp does the same thing currently).

**Comment by flyinghead** [comment]
Should be fixed now. Reopen as needed
