### ISSUE TITLE
BIOS Parameter?

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#224]
Hey guys, is it possible for you guys to add a flag to a path to the bios? It's an if statement, if the flag exist the use the path and filename for the bios. For example

`reicast_libretro.so -b /path/to/bios.bin`

**Comment by orbea** [comment]
You can boot into the bios by going into the core options and selecting the `Boot to bios`.

Instead of an extra flag, I think it would be better (And easier) to make it so that when booted without content reicast would boot into the bios or fail safely if it doesn't exist.
```
retroarch -L reicast_libretro.so
```

**Comment by blisstik** [comment]
We have different use case. For me, I'd like to specify per game, which bios to use. For example, when US bios is used in MvC2, the english localization is loaded.

**Comment by orbea** [comment]
Yes, I did not consider that use case. You can also configure the bios region in the quick menu options.
