### ISSUE TITLE
Threaded Rendering Freezes

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#227]
I couldn't find an open issue about this so I'm opening it here.

On 32bit ARM with threaded rendering turned on - when exiting out of a game, there a chance of it freezing.

**Comment by ghost** [comment]
I just ran into this myself. I had to kill -9 the retroarch process. This was on an Odroid XU4 running f425920.

**Comment by stuken** [comment]
Afraid it's still happening after the c0a06a9 commit.

**Comment by blisstik** [comment]
@flyinghead - I can confirm what @stuken said. It's still happening when trying to exit out via hotkey+button.

**Comment by flyinghead** [comment]
Make sure your version of RetroArch include the following commit: https://github.com/libretro/RetroArch/commit/e52f90926d9dea4b23e47ae05f01c7a5515df140

**Comment by stuken** [comment]
Same behavior using the latest nightly retroarch apk. I've noticed that disabling audio sync allows it to cleanly exit but the side effect is very choppy audio on my device.
