### ISSUE TITLE
Knights of ValournSeven Spirits lst  It works perfectly in Retroarch core Naomi/Reicast not [OIT] 

### ISSUE THREAD

**Issue by Mocorongo** [libretro/flycast#228]
Knights of ValournSeven Spirits
"Knights of ValournSeven Spirits.bin", 0x0000000, 0x07a12000

**Comment by inactive123** [comment]
Added it -

https://github.com/libretro/reicast-emulator/blob/master/lst/Knights%20of%20Valour%20The%20Seven%20Spirits.lst

You might have to edit your .bin file name though.
