### ISSUE TITLE
Soul Calibur Flickering

### ISSUE THREAD

**Issue by Papermanzero** [libretro/flycast#23]
Soul Calibur has a lot of flickering. Font background and some polygons are affected

**Comment by Papermanzero** [comment]
Also Shenmue is affected.

**Comment by NerosTie** [comment]
Wait, you can play Shenmue? It doesn't crash after the intro? 

On my side I have flickering for the shadow under the car at the beginning but I don't know what I have after the intro.

**Comment by Papermanzero** [comment]
No, it is crashing after the intro.

**Comment by inactive123** [comment]
Soul calibur flickering issues should be fixed now. Make Shenmue into a separate issue please.
