### ISSUE TITLE
Threaded rendering freezing with mesa 18 ?

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/flycast#232]
Since upgrading to mesa 18, i get freezes when running this core on my intel gpu : 
- other cores don't seem to be affected
- non threaded rendering doesn't seem to be affected
- mesa 17 doesn't seem to be affected

It's happening early and i have to kill the retroarch process.
For now i went back from mesa 18.1.6 to 17.3.9 (hopefully my OS is Gentoo linux so downgrading is not a big deal).

**Comment by orbea** [comment]
Can you please bisect mesa to see what commit introduced this issue? It could also be worth checking the mesa master to make sure this hasn't already been fixed or is not the result of a bad backport.

Also what gpu are you using? Is this with xorg, wayland or kms?

**Comment by barbudreadmon** [comment]
Intel HD Graphics 405, i'm using xorg with kms driver, no window manager, my gpu conf looks like this : 
> Section "Device"
    Identifier  "Intel Graphics"
    Driver      "modesetting"
    Option      "AccelMethod"    "glamor"
    Option      "DRI"            "3"
    Option      "Backlight"      "intel_backlight"
EndSection

I'll try to bisect, could be a long process though.

**Comment by orbea** [comment]
You could try using xf86-video-intel and / or DRI2 to see if it makes a difference, but I think your best bet is to bisect mesa at this point. Its mostly tedious...

For what its worth, I could not reproduce this with nouveau.

**Comment by barbudreadmon** [comment]
The freezes are disappearing when using intel + dri2 + sna, however those settings seem to be sub-optimal (and the settings i'm using work on other cores).
Using master didn't help, i'll try older version of mesa 18.

**Comment by MastaG** [comment]
I'm running mesa 18.3 git and the threaded renderer does not freeze here.
Fedora 28 with Gnome 3.28 on wayland.

**Comment by barbudreadmon** [comment]
Early mesa 18 seems to have the same issue, also `AccelMethod` doesn't seem to affect it, only DRI 3 and the modesetting driver. As long as i don't use any of those, it is not freezing.
So i guess the factor to reproduce this is mesa18 + xorg + dri3 + modesetting driver, if anyone could confirm ? (@orbea i think you can use those settings even with a nvidia gpu)

**Comment by orbea** [comment]
I'm on mesa commit https://github.com/mesa3d/mesa/commit/275b23ed0e6f7639eb674c3392ec52a0f38274fa (Newer exposes a deal breaking issue in RetroArch's KMS) and tested DRI3 + modesetting and found no new issues with reicast and threaded or non-threaded.

I suppose this issue might be specific to ~~AMD~~ intel or there is something else about your environment that is different than mine.

**Comment by barbudreadmon** [comment]
> AMD

It's intel, and yes it seems to be specific, i'll try to figure out which mesa commit caused this.

**Comment by orbea** [comment]
Sorry, I got mixed up there...

**Comment by barbudreadmon** [comment]
@orbea i don't think i'll be able to find what change caused the issue, all mesa-17 is working, no mesa-18 is working... I'll try messing with the sources of the core to see where it is hanging.

**Comment by orbea** [comment]
@barbudreadmon Build mesa from the git repo and use git bisect to determine what commit caused this.

1. Build mesa master, confirm its still broken.
2. Build arbitrary older commits (Not releases) until you find one that doesn't have the issue.
3. Proceed to a mesa git clone do the following commands.
4. `git bisect start; git bisect bad <bad commit>; git bisect good <good commit>`
5. It will checkout a commit which you will then build.
6. After the build completes configure gentoo to use it (I'm not sure how this is done on gentoo.)
7. Test reicast and see if the issue is present or not.
8. In the git clone you now mark it as a good, bad or skipped commit with `git bisect good`, `git bisect bad` or `git bisect skip`. You can skip any commits that fail in a way that is not related to your issue and make it not possible to test, ideally there should be only a few of these at most.
9. Repeat this until it explicitly tells you the first bad commit.

Since I still can't reproduce this I can't bisect this for you.

**Comment by ccontino84** [comment]
After I solved the issue with the SEGFAULT (see #451) installing the snap package, I also get freezes with the threaded rendering. I'm on Arch linux with mesa 19 and my CPU/GPU is AMD Ryzen 5 2400G.
I managed to fix the freeze setting NO_THREADS=1, but I had to change a few lines because the code didn't compile otherwise. In case it might help someone I created a quick (and dirty maybe? :P ) patch: [patch.zip](https://github.com/libretro/reicast-emulator/files/3025298/patch.zip)

**Comment by Subarasheese** [comment]
I have the same problem.

I use Intel integrated graphics (Intel Corporation Skylake GT2 [HD Graphics 520]), with the latest Mesa drivers (19). I downgraded to Mesa 17, and Reicast worked, but downgrading it also breaks a bunch of stuff I use on Linux, so it's not real solution. 

I tried the following solutions as well, and none of them worked:


- Editing the MakeFile and set “HAVE_GL3” to 1.
- @ckont 's solution, editing the makefile to NO_THREADS=1 and changing a few lines.

But none of the Reicast core builds stopped freezing on bootup, only downgrading Mesa worked.

I would appreciate further solutions.

**Comment by barbudreadmon** [comment]
I would assume `NO_THREADS=1` is basically the same as disabling threaded rendering in core option, it seemed to work in my case but maybe i was just lucky when i tried.
I don't think i ever had a freeze again after setting xorg's gpu like this : 
```
Section "Device"
    Identifier  "Intel Graphics"
    Driver      "intel"
    Option      "DRI"            "2"
EndSection
```
Actually it seems to be a well-known fix for a lot of issues with intel gpu.

**Comment by Subarasheese** [comment]
@barbudreadmon Thank you, that fixed the problem.

**Comment by flyinghead** [comment]
Closing as resolved

**Comment by wyatt8740** [comment]
@flyinghead what?! Resolved how?? It still happens with DRI3 + xf86-video-intel or with modesetting. DRI2 mode makes my already slow machine (ironlake GPU) even slower. Disabling threading is a workaround, not a resolution.

**Comment by barbudreadmon** [comment]
Tbh, i totally forgot about this (long time i didn't boot my udoo x86).
Well, i wouldn't call it a flycast issue in the first place since it's obviously a mesa issue, so anything that could be done about it would be a workaround anyway. Intel drivers are awful, period, pretty much any doc on linux + intel gpu will tell you to set dri to 2 if you encounter issues, this is kinda crazy.
No progress with later mesa and/or vulkan ?

**Comment by MastaG** [comment]
If you use a 3rdparty repository to get the latest Mesa (both Ubuntu and
Fedora have these available). Version 20 rc1 has the new Intel Iris
gallium3d driver for broadwell and newer.
You should try it.

Op vr 31 jan. 2020 11:31 schreef barbudreadmon <notifications@github.com>:

**Comment by flyinghead** [comment]
If there's any workaround that can be implemented in flycast, let me know. I already have a workaround for an Intel Vulkan driver bug so it wouldn't be the first.

**Comment by wyatt8740** [comment]
> No progress with later mesa and/or vulkan ?

My machine is Nehalem era. It doesn't get vulkan (nor any other love from Intel; despite engineers saying that it is technically capable of OpenGL 3 it never got that either).
Mesa is up to date (Debian Sid/unstable).

> For broadwell and newer.

My newest machine is Ivy Bridge unfortunately (Not that that's the fault of anyone here).
