### ISSUE TITLE
Grandia II graphical bugs (Android)

### ISSUE THREAD

**Issue by blackman91** [libretro/flycast#237]
On the reicast Android Retroarch core:
![screenshot_20180830-214937](https://user-images.githubusercontent.com/6578180/44890324-62abbd80-ac9f-11e8-87f3-1d4e68fdd617.png)
![screenshot_20180830-214900](https://user-images.githubusercontent.com/6578180/44890334-70614300-ac9f-11e8-9ecc-f3291554f5c3.png)
![screenshot_20180830-214822](https://user-images.githubusercontent.com/6578180/44890341-7a834180-ac9f-11e8-8ea6-1be972d6458f.png)

**Comment by flyinghead** [comment]
May be fixed by PR #239

**Comment by blackman91** [comment]
Sadly no the same bugs are still present, may be related to this similar issue too:
https://github.com/libretro/reicast-emulator/issues/218

**Comment by blackman91** [comment]
BTW these bugs are not present in your reicast fh branch.

**Comment by MastaG** [comment]
@blackman91 
Could you please retry using the latest build?

**Comment by blackman91** [comment]
Using Reicast 0.1 bb23007 on Android the same bugs are still there.

**Comment by blackman91** [comment]
The same happens on Jojo's Bizarre Adventure on Android:
https://i.redd.it/69wlgf0aqml11.jpg

**Comment by meepingsnesroms** [comment]
Is this a Mali GPU, something similar has happened before with the RetroArch XMB menu flickering black?

**Comment by blackman91** [comment]
Nope my gpu is Adreno 506

**Comment by meepingsnesroms** [comment]
What device and OS version?

**Comment by Siushaga** [comment]
I have same issue on my Samsung Galaxy S8. RetroArch 1.7.5 and reicast build a2d26a5. That build fixed games like PSO not rendering, but still have black boxes in Grandia like the OP. As well as cutscenes showing black and only has audio, but I believe that's is a separate reported issue.

**Comment by blackman91** [comment]
Motog5 plus Android 7

**Comment by flyinghead** [comment]
Hopefully #295 will fix this. Please report.

**Comment by Siushaga** [comment]
@flyinghead what's the easiest way to pull in these code changes? I used core updater in RetroArch, but it still shows 1.7.5 - Reicast 0.1 a2d26a5, which was from when I updated to fix PSO glitches.

**Comment by flyinghead** [comment]
You'll have to be patient as the buildbot has been having some issues lately

**Comment by Siushaga** [comment]
Latest core is much closer to rendering properly... Instead of black boxes, they are now highlighted green while being legible so at least it's playable! Couple sample images linked below. 

https://ibb.co/n0Aste
https://ibb.co/mK2GKK

Issue doesn't seem to be present with latest fh/mymaster standalone, so maybe something specific to the libretro core?

Edit: Seems it may have been related to a save state from before the fix. I loaded from in game save and confirmed its all showing up normally now.

**Comment by blackman91** [comment]
It renders now properly on my device on Android 7 using latest core:
![screenshot_20180930-221530](https://user-images.githubusercontent.com/6578180/46268159-90825d00-c4fe-11e8-82cf-43bf22f3dc73.png)
![screenshot_20180930-221435](https://user-images.githubusercontent.com/6578180/46268168-9c6e1f00-c4fe-11e8-97ec-b606fa11a849.png)

**Comment by blackman91** [comment]
It seems this is fixed now, flyinghead you do great work.
