### ISSUE TITLE
VMU save issue

### ISSUE THREAD

**Issue by orbea** [libretro/flycast#238]
It seems the VMU saves are still somewhat broken, when first starting reicast with only the bios present and no saves it will appear to save the game the first time, but when loading the content a second time it the save will not be present and it will complain that there is not enough room on the VMU to create a save.

To reproduce this.
1. Make sure the system bios directory only contains `dc/dc_boot.bin` and `dc/dc_flash.bin`.
2. Start a game such as Soul Calibur.
3. Configure the time, proceed to the menu and then create a save.
4. Close reicast and then restart it to find the save does not work nor does making new saves.

This can be worked around.
1. Start a game with reicast.
2. Enable `Boot to BIOS (restart)`, then close and restart reicast.
3. In the Dreamcast bios menu select `File` and delete the contents of the VMU memory.
4. Open the core options again and disable `Boot to BIOS (restart)`.
5. Now close reicast and the saves should work normally.

It would be great if this can be solved for good to make it easier for new users.

**Comment by RetroSven** [comment]
@flyinghead I was wondering about this myself.  Does a formatted VMU contain proprietary/copyrighted information?  I was going to make it so that if reicast starts without the vmu file created it will create one based off a pre-formatted image instead of whatever binary blob is currently being used.  Will that break compatibility in some way?

**Comment by flyinghead** [comment]
I think a formatted VMU does contain an icon, so this might be considered copyrighted information. But I guess a blank icon would work too.
And using a pre-formatted VMU image shouldn't be a problem.

**Comment by RetroSven** [comment]
https://github.com/libretro/reicast-emulator/pull/243

**Comment by orbea** [comment]
Thanks! It works now. :)
