### ISSUE TITLE
Reicast Core fails to load (Android - 32bit)

### ISSUE THREAD

**Issue by ChurroBoi** [libretro/flycast#244]
When Reicast core is selected it does not link and 'No Core' remains on the bottom left hand. 
When Content is selected it results in 'Failed to open Libretro core'
Tried Reinstalling Nightly, updating core, core info etc, no luck. Video Driver selected is gl.
Bios is in correct location (retroarch/systems/dc), using GPD XD
See log below.
[gpd_xd_fail-core-reicast.zip](https://github.com/libretro/reicast-emulator/files/2345347/gpd_xd_fail-core-reicast.zip)

**Comment by blackman91** [comment]
Does standalone flying head brach works on your device? what gl version does it have?
This is latest fh apk:
https://www.mediafire.com/file/p9s9ac8ad9z7bfb/reicastfhr7.apk

Also does normal standalone reicast works on your device? Subscribe for latest beta here:
http://builds.reicast.com/

**Comment by ChurroBoi** [comment]
Flying head crashes immediately on launch. Should I make a log for that too?
Latest standalone reicast works fine.
OpenGl is at v3.1

**Comment by blackman91** [comment]
Yes, does normal standalone reicast works?

**Comment by ChurroBoi** [comment]
Yes Standalone nightly build works fine.

**Comment by ChurroBoi** [comment]
Woops! Completely forgot to make a log for flying heads build, sorry. Here we go 
[gpdxd_flyingheadcrash_reicast.txt](https://github.com/libretro/reicast-emulator/files/2355852/gpdxd_flyingheadcrash_reicast.txt)

**Comment by flyinghead** [comment]
This is the error I see in the log:
`java.lang.ClassNotFoundException: Didn't find class "com.applisto.appcloner.classes.DefaultProvider" on path: DexPathList[[zip file "/data/app/com.reicast.emulatot-1.apk"]...`

I have no idea what com.applisto.appcloner is but it's not part of reicast

**Comment by ChurroBoi** [comment]
I looked through the device (and rootbrowser) and can't find anything related to that application class?? Any idea what I could do to resolve that myself or find the source?
Here, I made another log launching the normal libretro core from Arcbrowser instead of fh build, it seems to have a different error, hopefully this helps. Thanks for looking into it.
[retroarch_reicast_arcbrowser.txt](https://github.com/libretro/reicast-emulator/files/2356506/retroarch_reicast_arcbrowser.txt)

**Comment by flyinghead** [comment]
This is helpful, thanks.
Actually I'm having the same issue on my test Android phone but I didn't look further:
`Error(s): dlopen failed: cannot locate symbol "rand" referenced by "reicast_libretro_android.so"...`
Apparently this happens because the core was compiled against a more recent version of Android (`android-24`?) than what your phone is running.
What version of Android do you use?

**Comment by ChurroBoi** [comment]
I'm using custom Rom: Kitkat 4.4.4, the device is spoofed as a Nexus 5 I just realized, I will edit the build prop to it's original state and see if this affects the error perhaps.

(Update: no luck :/ )

**Comment by blackman91** [comment]
Could you take a log of latest fh build but download it from here:
http://builds.reicast.com/

Just scroll down to fh/mymaster and download the most recent apk.

**Comment by ChurroBoi** [comment]
I can't log anything unfortunately, cause it's working perfectly!

**Comment by blackman91** [comment]
Nice! it seems one of the recent changes by fh fixed the issue, great job fh!

**Comment by blackman91** [comment]
Latest fh apk with icon changed from grey to red and you can install it alongside main reicast no problem:
https://www.mediafire.com/file/t670wy64xabfmtu/reicastfhr7.apk

**Comment by ChurroBoi** [comment]
The fh build is working great in terms of being free from graphical anomalies, soulcalibur and Thps2 are totally playable for me now without the huge graphics bugs but now I've taken a huge performance hit, experimenting with both limit fps and synchronous rendering, I can get really high frame rate but too fast gameplay but when limited i get really sluggish or slow mo performance?

**Comment by blackman91** [comment]
With default settings I get similar performance to the main reicast on motog5 plus. How many fps do you get on those games in comparison to the main reicast?

**Comment by ChurroBoi** [comment]
The new build lags frequently and slows down at random points whilst main reicast runs fine. Also new problem has been encountered :/ the standalone fh red icon build crashes on me while the debug version does not. What the hek

**Comment by blackman91** [comment]
Try an older fh/mymaster build and check if performance improves on your device, it might be a driver issue.

**Comment by flyinghead** [comment]
Assuming the issue is resolved. Reopen as needed
