### ISSUE TITLE
Threaded Rendering Appears to be Unthrottled - Running Too Quickly

### ISSUE THREAD

**Issue by ghost** [libretro/flycast#245]
Currently running 1163a2b on Retroarch 1.7.4 on an Odroid XU4 and I'm finding that threaded rendering is helping performance quite a lot however it is making games unplayable. For games that are 2D (Street Fighter Alpha 3 Saikyo Dojo), matches appear to be running at double the speed and are barely playable with Threaded Rendering and Enable DSP enabled. For games that are in 3D (Daytona USA), running with Threaded Rendering enabled and Enable DSP disabled results in a similar problem where the game speeds up far faster than it should and renders itself unplayable due to the speed increase.

This appears to be unaffected by the Framerate option as in both normal and fullspeed, the same thing happens.

**Comment by flyinghead** [comment]
The normal/fullspeed framerate setting is ignored in Threaded Rendering mode so it's normal you don't see any difference.

Normally it's the audio that's supposed to limit the emulator speed. How is the audio when it's running too fast?

**Comment by ghost** [comment]
The audio is rough, dropouts and clicking are frequent.

**Comment by inactive123** [comment]
@RetroSven did this happen as a result of how you reimplemented the sound?

**Comment by RetroSven** [comment]
sounds probable - I wasn't aware the audio thread was also being used as a speed limiter - will think of an alternative

**Comment by blisstik** [comment]
Happens on RA 1.7.3 as well

**Comment by RetroSven** [comment]
@zerojay try https://github.com/libretro/reicast-emulator/pull/247 when it is merged (or pull/compile from my fork)

**Comment by blisstik** [comment]
This is fixed!

**Comment by inactive123** [comment]
Sound is proper now as well?

**Comment by inactive123** [comment]
No more crashes with savestates either with threaded rendering on Android?

**Comment by twinaphex** [comment]
@RetroSven Is it correct that I can no longer fastforward now even with non-threaded rendering? Certainly appears to be the case. That is bad.

**Comment by inactive123** [comment]
The downside of this though is that we can no longer use fastforwarding. There has to be a way to still allow for this.

@Themaister any ideas here? It's obvious the threading is causing a few issues with the way libretro cores expect the runloop to be performed.

**Comment by inactive123** [comment]
This should be finally resolved now, hopefully.

BTW - if you are on Windows, make sure you update RetroArch to the latest version (you can do this with the Desktop UI, go to Updater). Alternatively, if you are on other platforms, download the latest nightly from our buildbot - 

http://buildbot.libretro.com/nightly/

Make sure your Reicast cores are updated too.
