### ISSUE TITLE
Sturmwind stuck on the warning screen - Windows 64 bit

### ISSUE THREAD

**Issue by hostile1975** [libretro/flycast#257]
Sturmwind is crashing Retroarch with both Reicast and Reicast OIT core

**Comment by hostile1975** [comment]
In fact, its not crashing Retroarch but the game get stuck on the warning screen

**Comment by flyinghead** [comment]
Are you using Threaded Rendering? If not, make sure to set Framerate to Full.

I can't get the warning screen to show up on my machine but I might have an issue with retroarch 1.7.4.

The warning screen should be displayed for at least 20 seconds then fade away. That's what happens on my branch at least.

**Comment by hostile1975** [comment]
Hi,
No, I don't use the Threaded Rendering option, and yes the framerate is set to full.
I also tried to launch the game with Threaded Rendering on, but its the same

**Comment by blackman91** [comment]
Try updating the core and RetroArch to latest nightly.

**Comment by hostile1975** [comment]
Thanks, I will try and revert

**Comment by hostile1975** [comment]
I tried to launch the game with the latest nightly build and the updated core.
Its the same : stuck at the warning screen

**Comment by flyinghead** [comment]
Assuming this is resolved. Reopen as needed
