### ISSUE TITLE
No audio with threaded rendering enabled

### ISSUE THREAD

**Issue by stuken** [libretro/flycast#258]
On the current tip, 03360bf02d07220caa144712aa67e3036e436f57 audio output with threaded rendering enabled is not working. 
Behavior noted on both windows and android arm v7.
On exiting the the core in windows also results in a hard crash of retroarch.

**Comment by blackman91** [comment]
Update to RetroArch latest nightly, that fixes it.

**Comment by stuken** [comment]
Confirmed latest retroarch nightly fixes the issue.

**Comment by Liontek1985** [comment]
is it possible to fix the problem manualy without a retroarch update?
