### ISSUE TITLE
[NAOMI] WaveRunner GP: game freezed during intro

### ISSUE THREAD

**Issue by legluondunet** [libretro/flycast#263]
Hello,
I launched WaveRunner GP, the game freezed during intro:

![capture-20180911023815-1920x1053](https://user-images.githubusercontent.com/325405/45331829-392b4580-b56d-11e8-81b9-797ac9c19744.png)

Some sprites missing.

I joined you the retroarch log.

Thank you for your help.
[retroarch_reicast.zip](https://github.com/libretro/reicast-emulator/files/2368938/retroarch_reicast.zip)

**Comment by flyinghead** [comment]
I haven't been able to reproduce. This game works fine on my platform:
commit d62a1a9c49badc0e228b5500555155cff1ac2f44
Linux x64
non-OIT

**Comment by legluondunet** [comment]
@flyinghead   could you give me the md5sum of your WaveRunner GP rom?
mine: 
0443d4b7f30cf1dc8fb9bffdedbb7822  WaveRunnerGP.bin
I use the retroarch default configuration.
I downloaded the Reicast core today from Retroarch interface.

**Comment by flyinghead** [comment]
Yes, I'm running the same rom.

What kind of harwdware/OS are you using?

**Comment by legluondunet** [comment]
I joined the video: the rom launched, then the intro began, as you can see it missed some sprites then the intro freezed, but the audio continued to play.

[Screencast_19-09-2018_22:00:46.zip](https://github.com/libretro/reicast-emulator/files/2398590/Screencast_19-09-2018_22.00.46.zip)

One more thing: if I push "select" on my gamepad before the "freeze point", I can add coins and start a race.
Do you have the "no board drive" message?
I can not drive the jetski, keyboard and gamepad does nothing and you?

**Comment by legluondunet** [comment]
Config: Ubuntu 18.04 Bionic 64 bits - NVIDIA GeForce GTX 770 - Nvidia drivers 396.54 - 1920x1080 - Processor Intel i5-3570 3,4 Ghz - 8 Go RAM

**Comment by flyinghead** [comment]
I now get the same freeze at start up at the very same moment.

I was running with Threaded Rendering disabled previously and it seemed to work OK. I was able to get in-game and play a race. You need to remap the analog controls as axis 0 is for acceleration and axis 1 for direction.

**Comment by inactive123** [comment]
@flyinghead 

Important to note that @RetroSven had to push a couple of commits to the latest RetroArch nightly for the purpose of making the threaded rendering option more stable.

Are you on the latest nightly for RetroArch?

**Comment by legluondunet** [comment]
this game needs the threaded rendering option?

**Comment by flyinghead** [comment]
I wasn't running the latest RA. I am now.
I'm pretty sure it worked at least once with Threaded Rendering disabled. But now it always freezes, regardless of this setting.
It freezes on upstream at the same point as well but works on my branch. Still investigating...

**Comment by flyinghead** [comment]
It is just another dynarec div matching victim. Disabling div matching makes the sprites appear and the freeze go away.

I still get the "no board drive" message, presumably a hardware board that's not emulated.
And the first jetski character in the intro is still black but that doesn't happen in-game.

Note to self: always try all the options in the settings before spending two hours git-bisecting...

**Comment by inactive123** [comment]
Hah, that must have sucked to debug this for over two hours only to find out it's another div matching issue.

BTW, how much does disabling div matching actually hurt in terms of raw performance? How many fps? Wouldn't it be far more compatible if we just disabled it by default and let users manually enable it? I find it hard to justify minusucule performance-oriented hacks like this if they cause so many compatibility issues...

**Comment by flyinghead** [comment]
I don't know the answer but I have the same question. 
I don't feel any change in performance on a desktop machine. But I've heard arm/android users saying that it does make a difference. And I think it's the case on low end hardware.

I'd say that the OIT core clearly should have div matching off by default given the requirements in hardware.
Also, since it is an unsafe optimization, it's probably best to not default to on for the non-OIT core as well, and let the performance-hungry users enable it if they want.

**Comment by ghost** [comment]
I tested the game right now and confirm what I said @flyinghead.

Just disable the div matching option and have the OpenGL bancked.

Nokia 8, Snapdragon 835, Android 8.1

PS: the banner "no board drive" appears but the game has no glitch or freeze, the only drawback is the setting of the buttons of the virtual pad.

**Comment by legluondunet** [comment]
I just tested, the game did not freeze anymore during intro, you did a very nice work :+1: 

> I still get the "no board drive" message, presumably a hardware board that's not emulated.
And the first jetski character in the intro is still black but that doesn't happen in-game.

FYI this two issues are still present.
