### ISSUE TITLE
Graphics Glitches on Multiple Games Without Threaded Rendering.

### ISSUE THREAD

**Issue by PixelCrusader** [libretro/flycast#264]
Windows 7 64 bit, AMD Radeon HD 6450, Intel i5-2320 CPU @ 3.00GHz
RetroArch 1.7.4 1155e11 - Reicast 0.1 03360bf

There are multiple games that display up to two graphical errors when run with threaded rendering turned off. 

1. A line of white displays at the top and right side of the screen.
 
2. When loading, a graphical glitch will appear in the lower left hand corner, in the shape of a square. I am unable to capture this within RetroArch as the UI is unavailable during this. Simply going through the Dreamcast startup screen and/or going through the title screen should reveal the problem most of the time.

Some games that display examples of issue 1 (click to see):

Sonic Adventure:
![sonic adventure usa -180906-012349](https://user-images.githubusercontent.com/40935002/45344082-cc19af00-b570-11e8-9f4e-e649c71a965c.png)

Crazy Taxi:
![crazy taxi usa -180908-174129](https://user-images.githubusercontent.com/40935002/45344090-d045cc80-b570-11e8-9272-d489c8aa79d1.png)

Tokyo Xtreme Racer:
![tokyo xtreme racer usa -180908-033258](https://user-images.githubusercontent.com/40935002/45344095-d471ea00-b570-11e8-8c17-9fc984d33d59.png)

King of Fighters Dream Match 1999:
![king of fighters the - dream match 1999 usa -180911-022916](https://user-images.githubusercontent.com/40935002/45344104-d89e0780-b570-11e8-8534-96c0df3f5d47.png)

Zombie Revenge:
![zombie revenge usa -180911-022736](https://user-images.githubusercontent.com/40935002/45344118-dc318e80-b570-11e8-8144-a76be3e076f0.png)

Some games that have no white lines, but display the square glitch when loading.

Dead or Alive 2
18 Wheeler - American Pro Trucker

None of this seems to occur when threaded rendering is activated. Also, switching from the resolution being used at launch to a much higher one and then switching back seems to mitigate the white line issue in some games, but the problem fullly reappears once another game is launched. Custom cfg aspect ratios are also an imperfect workaround for wide screen monitors.

**Comment by flyinghead** [comment]
Assuming this is fixed. Reopen as needed
