### ISSUE TITLE
Reicast set to 320X240 in internal Resolution core options cause graphic glitches

### ISSUE THREAD

**Issue by hostile1975** [libretro/flycast#269]
If you set internal resolution to 320X240 for both Reicast or Reicast OIT, it will cause graphic glitches, on Windows x24

![samuraishowdownvi-samuraispirits_v4-180914-160405](https://user-images.githubusercontent.com/43080596/45555222-7a0aaf00-b838-11e8-8409-7926deffee4d.png)

**Comment by hostile1975** [comment]
Maybe it will help to know that this problem don't happen on Metal Slug 6 or Capcom Vs SNK 2
Metal Slug 6 and CVS 2 works properly with no graphic bugs when internal resolution set to 320x240

**Comment by inactive123** [comment]
Is it possible this game doesn't actually output at 320x240 natively but rather 640x480? Some of the 2D background layers look way too high resolution for it to be simply 320x240.

**Comment by flyinghead** [comment]
This game's native resolution is 640x480.
These glitches at 320x240 are due to the textures not designed to be used at this resolution.
It's similar to the white lines you see between seamed textures when running at high resolutions.

**Comment by hostile1975** [comment]
I see
Thanks for answer

**Comment by hostile1975** [comment]
So, I close it as the game should not be played at 320x240
Thanks
