### ISSUE TITLE
metal slug 6, marvel vs capcom 2 King, of Fighters New Waveand other games not correct work glsl-shaders

### ISSUE THREAD

**Issue by Eignar17** [libretro/flycast#271]
not work in scalefx xbr or scalehq in native resolution

![captura de pantalla -2018-09-21 00-51-59](https://user-images.githubusercontent.com/8561550/45862772-e0ac3300-bd38-11e8-8b1e-40c41d2f41a9.png)
![captura de pantalla -2018-09-21 00-49-34](https://user-images.githubusercontent.com/8561550/45862773-e144c980-bd38-11e8-8644-e048d5ab29eb.png)
![captura de pantalla -2018-09-21 00-48-18](https://user-images.githubusercontent.com/8561550/45862774-e144c980-bd38-11e8-8aac-7119fdb80345.png)

**Comment by hizzlekizzle** [comment]
That looks like it's working to me. There are elements that are a different resolution and so the pixel detection algorithms miss them (like the character sprites in the first shot), but you can see by the MvC2 HUD and Metal Slug text that the shaders are indeed working.

**Comment by Eignar17** [comment]
Could you make it work in sprites?

**Comment by Eignar17** [comment]
in to 320x240 work 
![captura de pantalla -2018-09-21 21-24-37](https://user-images.githubusercontent.com/8561550/45912326-1ad30e80-bde5-11e8-8459-adce033074f8.png)
Could you make it work in sprites in to native resolution?

**Comment by Eignar17** [comment]
@hizzlekizzle not works is problem fix to https://forums.libretro.com/t/request-add-320x240-resolution-to-dreamcast-cores/15707/3

create new shader to fix problem?
