### ISSUE TITLE
(Android) Reicast makes RetroArch crash when pressing the home or recent apps button

### ISSUE THREAD

**Issue by blackman91** [libretro/flycast#272]
Using the reicast core during gameplay If you press the home or recent apps button on Android and you go back to RetroArch, RetroArch crashes unlike all other cores that work on Android and standalone reicast.

**Comment by flyinghead** [comment]
Is this still happening? If not, please close this issue.

**Comment by blackman91** [comment]
It doesn't crash anymore but when you go back to RetroArch after pressing the home button or recent apps button the graphics get messed up also if you open the quickmenu first and then press home button and go back you get a blackscreen and if you close content RetroArch freezes.
