### ISSUE TITLE
Graphical Issues Android

### ISSUE THREAD

**Issue by Siushaga** [libretro/flycast#277]
Can't seem to find settings that will render gameplay in Reicast Libretro core properly. Menus will work fine, but then actual gameplay won't render properly. Video is below. 

https://youtu.be/u6-83V9-Ib0

Here's my core options. Have tried many different settings, this is just the latest one. 

https://pastebin.com/hA3Y9BKV

Running on a Galaxy S8. Have tried loading latest nightly build and updated core. Any ideas?

**Comment by blackman91** [comment]
It seems to be an Android specific bug:
https://github.com/libretro/reicast-emulator/issues/279

Others game should work fine.

**Comment by inactive123** [comment]
Any ideas here @flyinghead ?

Seems to be depth-related.

**Comment by Siushaga** [comment]
Strange. Besides Libretro, I tried the latest play store beta build and it worked fine, but like you said the flyinghead for standalone reicast also won't display. Not sure that it's just PSO, though, Sonic Adventure 2 is another with the same behavior.

**Comment by flyinghead** [comment]
I tested PSO with my branch on Android and I have no issue.
Android 4.4
Samsung J1 (Mali-400 GPU)

**Comment by flyinghead** [comment]
My phone only supports GLES 2 so it could be a problem specific to GLES 3. Unfortunately my new test phone hasn't arrived yet.

**Comment by Siushaga** [comment]
Same issue using Vulkan too, so not sure if GLES 3 would be the culprit, but I don't know enough about the inner workings. :)
