### ISSUE TITLE
CHDs v4 no longer work.

### ISSUE THREAD

**Issue by blackman91** [libretro/flycast#278]
I converted most of my gdis to chd v4 using the gdi to chd tool but after updating the Retroarch reicast core on Android 7 to test the new online features most of my chds now boot directly to the bios, I know the files are fine because they boot correctly on standalone reicast and on flying head reicast branch, tried a clean installation of RetroArch but the issue still remains, also I made sure the core option boot directly to bios is disabled, any ideas on what might have broken them? .gdi and .cdi appear to work fine, please fix it, the format saves a ton of space:
https://forum.xda-developers.com/nvidia-shield/shield-qa/reicast-gdi-to-chd-t2823608

**Comment by blackman91** [comment]
Here is a log:

![screenshot_20180925-201059](https://user-images.githubusercontent.com/6578180/46052207-e9b74e80-c102-11e8-9640-06797ce276b6.png)

**Comment by blackman91** [comment]
Same is happening on windows 7 after updating the reicast core to 0.1 bb51449, can anyone else that uses GDI to CHD tool to save space confirm this is happening too?

**Comment by baka0815** [comment]
It would be nice to know if Linux builds are also affected.

**Comment by blackman91** [comment]
So far affected chd:
Cannon Spike
Marvel vs Capcom 2
Alone in the dark new nightmare
Capcom vs SNK 2
Elemental Gimmick Gear
Ikaruga
Soul reaver
Outtrigger
Power Stone 2
Prince of Persia Arabian Nights
Rayman 2
Record of Lodoss War
Shenmue
Skies of Arcadia (US)
Soul Calibur
Soul fighter
Underdefeat
Zombie Revenge

chd that still work:
Spiderman 2000
Crazy Taxi
Jet grind radio
Dino crisis
Dynamite Cop 

This should be easy to reproduce please just download this and try to play it using latest reicast libretro core:
https://www.mediafire.com/file/sgwl1a3x0o9ivf1/Cannon_Spike_%2528USA%2529.chd/file

**Comment by baka0815** [comment]
And those work with my branch of main reicast or don't they?
Did all of them work before the mentioned commit?

**Comment by blackman91** [comment]
Yes all of them worked fine before that change, they still all work on main reicast and on fh branch, what is your branch called?

**Comment by baka0815** [comment]
Ok, so they can't be in v5 format, because that's not supported in fhs branch and main reicast.
My branch of main reicast would be ``baka/chdv5_2``.

Could you retest your files with that and provide the ``chdman info`` feedback I asked about in the other issue, please.

**Comment by blackman91** [comment]
Tested all the same chd on Android using the latest apk of your baka/chdv5_2 branch 6a8eafb	and surely the same ones I posted above just boot directly to bios and the same ones run.

**Comment by blackman91** [comment]
They appear to be chd v4:
16:21:59.688: Info: starting process
16:21:59.723: Info: process started: PID = 7336
16:21:59.756: Info: stdout: chdman - MAME Compressed Hunks of Data (CHD) manager 0.200 (mame0200)
16:21:59.757: Info: stdout: Input file: Cannon Spike (USA).chd
16:21:59.757: Info: stdout: File Version: 4
16:21:59.757: Info: stdout: Logical size: 1,344,333,888 bytes
16:21:59.757: Info: stdout: Hunk Size:    9,792 bytes
16:21:59.758: Info: stdout: Total Hunks:  137,289
16:21:59.758: Info: stdout: Unit Size:    2,448 bytes
16:21:59.758: Info: stdout: Total Units:  549,156
16:21:59.758: Info: stdout: Compression:  zlib (Deflate)
16:21:59.758: Info: stdout: CHD size:     187,177,359 bytes
16:21:59.758: Info: stdout: Ratio:        13.9%
16:21:59.758: Info: stdout: SHA1:         6647f6d16e770e09c355b86d9a90bd865a01821f
16:21:59.759: Info: stdout: Data SHA1:    b411085c63da5c35fc25fae335d8f8e57c665f38
16:21:59.759: Info: stdout: Metadata:     Tag='CHT2'  Index=0  Length=88 bytes
16:21:59.759: Info: stdout:               TRACK:1 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:674 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0.
16:21:59.760: Info: stdout: Metadata:     Tag='CHT2'  Index=1  Length=86 bytes
16:21:59.760: Info: stdout:               TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:44326 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0.
16:21:59.760: Info: stdout: Metadata:     Tag='CHT2'  Index=2  Length=91 bytes
16:21:59.760: Info: stdout:               TRACK:3 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:504150 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0.
16:21:59.761: Info: stdout:      Hunks  Percent  Name
16:21:59.761: Info: stdout: ----------  -------  ------------------------------------
16:21:59.761: Info: stdout:     11,048     8.0%  Legacy 8-byte mini
16:21:59.762: Info: stdout:    126,241    92.0%  Deflate
16:21:59.762: Info: process finished: exitCode = 0, exitStatus = normal, execTime = 00:00:00.039

**Comment by blackman91** [comment]
Changed title, I am sure now most chd v4 don't run in latest reicast RetroArch core but all run on standalone reicast.
