### ISSUE TITLE
Games Crash on both AMD/Intel GPU's using Arch Linux

### ISSUE THREAD

**Issue by ghost** [libretro/flycast#280]
GPU : AMD Radeon 530 and Intel UHD 630
OS : Antergos LInux.
Thats the log: retroarch.log : 
[retroarch.log](https://github.com/libretro/reicast-emulator/files/2418836/retroarch.log)

I am using the mesa-git driver but it didnt work with mesa stable either.
I used OpenGL threading and then tried without threading.

**Comment by flyinghead** [comment]
You need to install the Dreamcast bios

**Comment by ghost** [comment]
But I have the bios.
In DC folder.

**Comment by flyinghead** [comment]
From your log: `[libretro INFO] Unable to find bios in /run/media/nir777/8E666F1E666F05F5/system/dc/`

**Comment by flyinghead** [comment]
assuming this is resolved
