### ISSUE TITLE
Virtual Joystick Issue on Reicast Core.

### ISSUE THREAD

**Issue by blackman91** [libretro/flycast#289]
Using any touchscreen controller overlay that has a virtual joystick moving the left virtual joystick also presses the Dreamcast LT button continuously for some reason  making games that use the joystick to move the character unplayable on touchscreen, not sure if this happens only on Android I don't have a windows device with touchscreen.

**Comment by blackman91** [comment]
A good game to reproduce this is jet set radio and moving the character using the virtual touchscreen joystick. 
@flyinghead can you reproduce this bug? Or is it just me?

**Comment by flyinghead** [comment]
I can reproduce it

**Comment by flyinghead** [comment]
Please reopen if this is still an issue
