### ISSUE TITLE
Clear up some Makefile flags

### ISSUE THREAD

**Issue by MastaG** [libretro/flycast#290]
Since this project lacks some docs about this, I'm going to open an issue for it.
I'd like to know which graphic renders are supported with and without OIT.
This is the Makefile:

```
DEBUG         := 0
NO_REND       := 0
HAVE_GL       := 1
HAVE_GL2      := 0
HAVE_OIT      := 0
HAVE_CORE     := 0
NO_THREADS    := 0
NO_EXCEPTIONS := 0
NO_NVMEM      := 0
NO_VERIFY     := 1
HAVE_LTCG     := 1
HAVE_GENERIC_JIT   := 1
HAVE_GL3      := 0
FORCE_GLES    := 0
STATIC_LINKING:= 0
HAVE_TEXUPSCALE := 1
HAVE_OPENMP   := 1
HAVE_CHD := 1
```

So if I'd like to build for OpenGL ES 3.0. I should enable FORCE_GLES and disable HAVE_GL ?
Also should I enable HAVE_GL3 ? and HAVE_OIT?
Because there's no HAVE_GLES3 option..

**Comment by flyinghead** [comment]
HAVE_GL should always be set
HAVE_OIT selects the OIT renderer (implies HAVE_GL3, not available for GLES)
FORCE_GLES should be set to build for GLES (supports both GLES 2 and GLES 3)

In many cases the options are set automatically based on the target platform. For example, building for Android will select FORCE_GLES. And building for Windows or Linux will select HAVE_GL3 (unless HAVE_GL2 is set for OpenGL 2 only platforms)

**Comment by MastaG** [comment]
Thanks for clearing it up.
So the OIT renderer is only meant to be used for OpenGL 3.
But how does the source determines whether to build for GLES 2 or 3 then?

Like for example, for Odroid we force GLES 2, but what if I'd like to build for a platform that supports GLES 3?

**Comment by flyinghead** [comment]
There's no difference at compile time between GLES 2 and 3.

The renderer gets the GLES version at runtime and selects which GLES features can be used accordingly.

**Comment by MastaG** [comment]
Thank you, thanks for clearing that up.
