### ISSUE TITLE
Keyboard cursor keys not working in Typing of the Dead

### ISSUE THREAD

**Issue by stuken** [libretro/flycast#291]
As per title. Cursor keys are not registering on the title screen for selecting modes and options. Verified with game focus on and both US and Japanese versions. However they do function correctly in Quake 3 when setting modem config options.

**Comment by flyinghead** [comment]
I'm not able to reproduce this. Cursor keys work for me even with a non-US keyboard layout, both for game mode and options.
I have a gamepad on port 1 and the keyboard on port 2.

Are you sure you don't have any hotkey or gamepad binding on your keyboard?

**Comment by stuken** [comment]
Tried this again with a clean install of the latest nightly retroarch and the reicast oit core with all default settings.
Tested with keyboard in port 1, gamepad port 2 and gamepad in port 1 and keyboard in port 2 and the manual recommended keyboard port one, gamepad port 3.

All cases still result in no cursor input. I'm running windows 10 UK English with the default UK qwerty keyboard layout.
