### ISSUE TITLE
Online communication issue in Alien Front Online

### ISSUE THREAD

**Issue by ONLYUSEmeFEET** [libretro/flycast#292]
I've been doing extensive testing with the new Reicast online features, but came up against a frustrating  connection issue when playing Alien Front Online. A quick note before I go into my issue: you need a 7-digit phone number to connect to AFO. Libretro's 666 example will not allow you to connect at all, so use something like 111-1111 instead. On the technical side, my computer and connection are way above recommended specs, and I have no issues playing Quake III and PSO V2 online through Reicast OIT.

After I successfully connect to Alien Front Online, the game tells me I'm connected at 75 baud. I am then able to create my own game, but get get a connection problem as soon as I load in. Finally, I get disconnected from the server and subsequently, kicked back to the Main Menu. I'll post screenshots below to provide a visual for this flow.

![afo_dca](https://user-images.githubusercontent.com/8323849/46228590-7eeb5a80-c330-11e8-8cd1-ddfd8113bbc2.png)
![afo_dcb](https://user-images.githubusercontent.com/8323849/46228591-7eeb5a80-c330-11e8-9ce9-87251c4d29dc.png)
![afo_dcc](https://user-images.githubusercontent.com/8323849/46228592-7f83f100-c330-11e8-9f26-5a38053be497.png)

From looking at Alien Front Online multiplayer YouTube videos, I should be connecting at 336000 baud. I have tried configuring my connection through Quake III and Planetweb 3.0, but still cannot connect. I am also having a related issue where I can't load any websites through Planetweb 3.0 or Sonic Adventure after saving my Internet Options.

I've been testing most online games through Reicast OIT and while I'd like to keep this Issue to Alien Front Online, I was wondering if there's anywhere to post my successes and failures on connecting to various games/programs? I can also provide additional screenshots in this issue. Thank you.

**Comment by flyinghead** [comment]
Alien Front Online requires UDP port 7980 to be forwarded to your computer. This needs to be configured on your router.

You can find the port forwarding requirements for all supported games at the bottom of this page: https://www.dreamcastlive.net/connection-guide

If you get the "Experiencing comunications problems..." message as soon as you enter a game, then it's probably a port forwarding issue on your router.

**Comment by flyinghead** [comment]
Regarding the message that the modem is connecting at 75/1200, you can safely ignore it. For technical reasons we emulate a V23 modem connection but the actual bit rate is around 33.6 Kbps.

I haven't tested PlanetWeb but I was able to browse web sites with DreamKey and XDP so there might be something else on your end. Web browsing doesn't require anything special configuration.

**Comment by ONLYUSEmeFEET** [comment]
Thanks for the Port Forwarding link! Sadly, I'm still having the same issue. I port forwarded AFO and set the DMZ to my Dreamcast's IP address. Out of desperation, I've also tried every combination of setting addresses to my PC, emulated Dreamcast, and the suggested address on the port forwarding page.

A few things about my setup seem strange. Quake III states my Dreamcast's IP address is 192.168.167.2 which isn't close to the IP address in the documentation (192.168.1.*). Also, I cannot get XDP 4 LE to run in Reicast. It freezes on the Sega copyright screen (white screen with XDP's logo below). I'm running the latest build of Reicast OIT and Retroarch 1.7.4 on Windows 10. I also have tried the latest Reicast build in all of my testing to no avail.

**Comment by flyinghead** [comment]
The IP address reported by Quake III is only used internally. The actual IP address of the emulated Dreamcast is the same as your PC. Make sure you've allowed retroarch to open listening network connections.
I think XDP needs to run in VGA mode otherwise it freezes on the Sega copyright screen.

**Comment by ONLYUSEmeFEET** [comment]
> The IP address reported by Quake III is only used internally. The actual IP address of the emulated Dreamcast is the same as your PC. Make sure you've allowed retroarch to open listening network connections.
> I think XDP needs to run in VGA mode otherwise it freezes on the Sega copyright screen.

The VGA mode fixed XDP. I was able to connect online through XDP and download game files in Chu Chu Rocket! But Alien Front Online still refuses to sync and I'm getting the same behavior. I opened the required ports (AFO and Retroarch), checked my settings to ensure everything was open (and the rest were default), but the above issue persists. I am also getting a Password Error in Chu Chu Rocket instantly; right after connecting. My router settings are set to what's listed on the Port Forwarding page, with my computer's static IP address used as the Local IP. Is there something special I need to do for these particular games to work? Not sure what to do given the Web, Quake III, and PSO V2 work great. Thanks.

**Comment by flyinghead** [comment]
I'm having a password error with Chuchu Rocket as well. I haven't been able to figure out why yet.

I did a test with Alien Front Online today and I was able to start an online game and play (against bots).

Would you be able to capture a packet log using Wireshark of your connection attempt to AFO?

**Comment by ONLYUSEmeFEET** [comment]
Sure, here is my AFO packet capture. I didn't filter it as I'm not 100% sure what needs to be looked at. Thank you.
[afo packet capture.zip](https://github.com/libretro/reicast-emulator/files/2430951/afo.packet.capture.zip)

**Comment by flyinghead** [comment]
Fantastic!
What I'm seeing is that UDP packets from the AFO server are not received. This seems to indicate a port forwarding problem.
Could you check your router/firewall?

You should have a NAT/port forwarding rule to forward all UDP packets on port 7980 to your PC's IP address: 192.168.1.51

You can load your packet capture and use the following display filter: `ip.addr ==  146.185.135.179` to see all traffic to and from the AFO server. You'll see that there is some initial TCP communication that works just fine, but when you start the game no UDP packet is received from the server.

**Comment by ONLYUSEmeFEET** [comment]
Port 7980 appears to be forwarded on my router. I saw your game and tried to join several times, but am having the same issue as above. Here are my WAN settings in my router. I did try disabling my router and computer firewalls, but it made no difference.
[WAN Settings.zip](https://github.com/libretro/reicast-emulator/files/2430969/WAN.Settings.zip)

**Comment by flyinghead** [comment]
I don't see anything wrong in your router settings.
Yeah I started a game in case it would help. I saw your name on the score board at some point.

You should see this in the RA stdout when connecting:
```
My IP is X.X.X.X
AFO server IP is 146.185.135.179
```
The "My IP" should be your public IP address. It's not used at the moment but that might give us a clue.

**Comment by flyinghead** [comment]
Again, nothing suspicious in the log. I get pretty much the same thing.

I don't think it's caused by your PC's firewall (if any) because the Wireshark packet log would show the incoming UDP packets, even if they're discarded by the firewall.

So the main suspect would be the router. I took the liberty of scanning the ports of your public IP address (sorry if your firewall freaked out) and specifically UDP port 7980 and everything seems to be blocked right now. We can retest later today if you're available. You can ping me on the libretro Discord server.

**Comment by ONLYUSEmeFEET** [comment]
Turns out I had a Double Nat issue that affected way more than Alien Front. Retroarch/Reicast were fine; issues were on my end. Closing this issue and editing out my info from previous.

**Comment by Minepika55** [comment]
Hi sorry for bringing this up again but I've tried with 3 different computers and two phones and I get the same error (tried on 3 routers with Upnp enabled) I'm able to start a game on the lobby and then get immediately disconnected with the same error as the screenshots or sometimes last long enough to try to connect a second player which then disconnects me automatically.

![Image](https://github.com/user-attachments/assets/a7a8e115-834a-4c35-9443-2009727ab30b)

![Image](https://github.com/user-attachments/assets/0adba8a4-ea92-46f6-93ed-2209924341ba)

![Image](https://github.com/user-attachments/assets/150cff55-2e35-42b1-a570-705e9d284e43)
