### ISSUE TITLE
Reicast Core not Loading on Android

### ISSUE THREAD

**Issue by Smoker1** [libretro/flycast#294]
Load Core, Select Reicast, goes back to Main Screen showing "No Core"

Using CatLog, I was able to find these 2 Error Logs:

Failed to open libretro core: “/data/data/com.retroarch/cores/reicast_libretro_android.so”

Error(s): dlopen failed: cannote locate symbol “rand” referenced by “reicast_libretro_android.so”…

**Comment by flyinghead** [comment]
Which Android version are you using?

**Comment by blackman91** [comment]
It seems the core is not building for Android, it is not available on the online updater right now.

**Comment by flyinghead** [comment]
There's been a problem with the buildbot. It's slowly getting back to normal.

**Comment by Smoker1** [comment]
Just Updated. Still Not Loading. A couple Days ago it Loaded, but when you tried to run a Game, the whole App Crashed.
Device is my GPD XD.
Also, for the Windows Build (x64), latest Nightly I guess, the Core will Load, but when you run a Game, it will just take you to the BIOS Menu. When you hit Play, it says to insert a Game Disc

**Comment by flyinghead** [comment]
The reicast core currently requires Android 7.0 or later.

The windows x64 build problem is certainly a different issue. A log would help.

**Comment by Smoker1** [comment]
So that's why. Yeah, the GPD XD is running only 4.x.x . If only the XD+ had more Storage :( . That runs the latest Android.
Is there a List of all the Naomi Button Listings?

**Comment by Smoker1** [comment]
Core works great on my Note Pro 12.2 with Android 5.1.1
Core not Loading on my LG G6 with Android 8

**Comment by flyinghead** [comment]
The reicast core should now load on Android 4.4 as of 773634c2a980ac4ee7a02ab4e2c76ee2335f2282

**Comment by Smoker1** [comment]
Working PERFECTLY!!!!!!!!!
In fact, it seems to be working better than my Note Pro (Enter Initials would not show the Text in the 3 Boxes), and faster than my LG G Pad X 8.0 . Still has the Trigger Issue (Unable to do things like the Boost Jump on Hydro Thunder).
Not sure if I can inquire to this here, but since it is involving Reicast, I will take a shot....
Which Device has better Hardware for Emulation - GPD XD or the Vita? Been asking around, and so far, there are more saying the Vita could work with Reicast if Developed Properly. I am hoping that there can be Test Builds so Users can test the Limits of the Device. Also, thanks to the Cheat Search/Creation added, Users will not have to deal with the GS/CB/AR .cdi Images, which dont want to work in either the Official Reicast, or the RA Core. 
Here are the Specs for both:
GPD XD Specs:
Rockchip RK3288 / ARM Cortex-A17 / 2GB DDR3-SDRAM / ARM Mali-T764 / 1280x720p

Vita Specs:
Quad-core ARM Cortex-A9 MPCore / 512 MB RAM, 128 MB VRAM / Quad-core PowerVR SGX543MP4+ / 960x544 qHD

**Comment by blackman91** [comment]
This should be closed now that it works on Android 4.4
