### ISSUE TITLE
System Clock not saved

### ISSUE THREAD

**Issue by prataczak** [libretro/flycast#300]
The 'set date and time' screen comes up on every load.

**Comment by mac1202** [comment]
I confirm this issue is back since several week.

**Comment by Tatsuya79** [comment]
Same here on win7 x64.

**Comment by ghost** [comment]
Try setting the date/time to the same as what's on your computer. If that doesn't work, try formatting your VMU first and then doing that again.

**Comment by Tatsuya79** [comment]
It worked this time, I set it at the exact PC clock...

**Comment by zanac** [comment]
I run in an embedded board that dont start date at boot at 1970, this bug is a problem

**Comment by ghost** [comment]
Having the same issue, also doesn't seem to save my network connection settings or language option. Failing to write the bios memory perhaps?

**Comment by 7oxicshadow** [comment]
I believe this issue also exists in the main Reicast branch for a long time.

You have to set the time and date reasonably accurately (with respect to PC time) otherwise it does not get saved. I never delved deep enough into the code to find out why.

**Comment by Metalwario64** [comment]
I tried setting it down to the minute of my PC time, and it still won't save.

It was working for me for the past few months (after initially not working), but I recently reinstalled RA from scratch including my cores, and now it's back to happening again.

**Comment by flyinghead** [comment]
As of https://github.com/libretro/reicast-emulator/commit/3dd45d27159278e88a73352a318d0b23bc241a1a, you should never have to set the date and time anymore.

**Comment by prataczak** [comment]
Cool, thanks!
