### ISSUE TITLE
Sega Worldwide Soccer 2000 - Euro Edition [Dreamcast]

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#303]
The game launches but only half of the screen is rendered. The bottom half gets stuck on the SEGA screen.

**Comment by flyinghead** [comment]
Are you running in VGA mode?
If that's the case, retry in TV mode.

**Comment by blisstik** [comment]
I got it work on TV mode with VGA but there is a new issue. While playing the game, the CPU soccer player will freeze with the ball and can't get it out. He's literally frozen with the ball. This happens right after opponents goalie kicks it midfield.

**Comment by flyinghead** [comment]
Interesting. I'll have a look.

**Comment by flyinghead** [comment]
Actually it's the contrary: it works in VGA mode, not in TV.

I've reproduced it on Android but not on Linux. What platform are you on?

**Comment by blisstik** [comment]
That's odd. I got it to work full screen on TV and setting it to PAL with
Europe as region.

I'm on an Odroid XU4.

**Comment by flyinghead** [comment]
Ok, this game needs broadcast set to PAL and works fine with VGA or TV. If broadcast is set to NTSC, only VGA will work full screen.

Back to the freeze issue, it could be an arm-only problem but it doesn't seem to happen on my branch.

**Comment by flyinghead** [comment]
I finally was able to reproduce it on linux x64 and on my branch.

Could be a math precision problem. Tried with -O0 and no -ffast-math but problem remains. Tried to limit the precision of sh4 FTRV op as per the documentation to no avail.

**Comment by blisstik** [comment]
Its a pretty funny issue. Might be detecting it's not real hardware and dummies out.

________________________________
