### ISSUE TITLE
NBA and NFL 2K Games

### ISSUE THREAD

**Issue by Nardokrazy2x** [libretro/flycast#304]
They work and Go online but you wont receive the invite it always says player didnt responded or something simlair to it

**Comment by flyinghead** [comment]
First make sure that you forward the following ports on your router to your PC/device:
UDP 5502 | UDP 5503 | UDP 5656
TCP 5011 | TCP 6666

Then, yes, there's an issue with these games. I think I know what to do but I need another player. Ping me on Discord if you volunteer.

**Comment by Nardokrazy2x** [comment]
I willing help what your discord

**Comment by flyinghead** [comment]
This commit https://github.com/libretro/reicast-emulator/commit/dfe8d3cf5185aa345d529d66783ef606e680c9cb should fix it.
Please let me know if it works

**Comment by flyinghead** [comment]
I tested NFL 2K2 online for more than 20 minutes without problem. If there is an issue receiving challenges, or communication errors early into the game, it's likely that you or your opponent don't have the required UDP and TCP ports forwarded, or they are blocked by a firewall.

Refer to this page for more information: https://www.dreamcastlive.net/connection-guide

For the same network reasons, this game cannot be played on cellular networks.
