### ISSUE TITLE
Reicast Core Performance Regression in Retroarch.

### ISSUE THREAD

**Issue by ghost** [libretro/flycast#307]
Good morning.

I wanted to communicate, that the Core Reicast, starting from the version after build 0.1-bb23007, has performance problems with all the games, crackling sound problems and downgrade of the scene.

This, with all the builds tested until the last one.

Thank you.

**Comment by blackman91** [comment]
Enable the option threaded rendering for better performance, it can even run on Android phones with that option enabled.

**Comment by ghost** [comment]
Hi blackman91 and thank you for reply.

With active rendering thread, from Retroarch's options, I do not get extra performance.

With the rendering thread, in the Core Reicast options, I get either the scene freeze, or the pads overlay does not work. (no effect at the touch of any key and direction)

With the Core set by default, all builds, after version 0.1-bb23007, have low performance.

Nokia 8, Snapdragon 835, Android 8.1

Thank you.

**Comment by blackman91** [comment]
After you run a game with threaded rendering on open RetroArch quick menu and in the option latency set poll type behaviour to early that fixes the screen freezing and overlay not working on Android.

**Comment by ghost** [comment]
blackman91, Thank you for your kind availability reply, but the general problem of performance, does not hit anything with Retroarch.

the problem is right in the Core Reicast.

It's very simple; performance downgrade, after the build -bb23007.

And this, for all the versions of Core Reicast, up to the last build.

Thank you.

**Comment by blackman91** [comment]
Did you even try doing what I said? That should fix the performance issue you are having with the reicast threaded rendering option on. Try it before you reply.

**Comment by flyinghead** [comment]
@blackman91 stizzo1 is reporting a performance regression that started at a specific build/commit.

While it is nice of you to try to help him work around this performance problem, it is even more important to know why this performance regression happened and if it can be avoided.

I believe this is @stizzo1 's point here.

**Comment by ghost** [comment]
Thanks to friend @flyinghead and thanks also for your help @blackman91.

I can give more information: the performance downgrade, becomes evident with scalefx.glslp shader filter

For example, when playing both the Dreamcast (Limited Edition) version and the Naomi (Millennium Edition) version of a Dead Or Alive 2, you can see the difference. (in particular, playing with Kasumi, in the scene with her clone, you notice a terrible downgrade, rendering of the polygonal scene)

Thank you.

**Comment by ghost** [comment]
Report that with the latest build 0.1-127f845, the performance is back to normal.

Thank you very much, guys.
