### ISSUE TITLE
crash on linux: shader compile fail

### ISSUE THREAD

**Issue by toccata10** [libretro/flycast#31]
ArchLinux, i7 4770k, r9 fury (mesa 18.0), retroarch 17.3. After updating the reicast core, I can't launch it: it crashes with (driver: Opengl):
```
Using Recompiler
Sh4 Reset
recSh4 Init
@@      ngen_ResetBlocks()
Freeing fpcb
Shader: failed to compile 
0:6(17): error: could not implicitly convert operands to arithmetic operator

Shader linking: failed to link 
 (51 bytes), - error: linking with uncompiled/unspecialized shader -
[libretro INFO] Fatal error : shader compile fail

 in gl_CompileAndLink -> core/rend/gles/gles.cpp : 330 
DEBUGBREAK!

```

**Comment by inactive123** [comment]
Should be fixed now. Please recompile and try again.

**Comment by toccata10** [comment]
I updated the core via the retroarch updater tool. It's fixed now. Power Stone 1 is very much improved: no more flickering in the HUD, in the selection,... ! Thanks so much for your work. It's great to see Dreamcast emulation receiving some love and becoming very enjoyable on linux.
