### ISSUE TITLE
External Drive Issue

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#311]
Hi there @flyinghead - I was hoping you  can help me with this.

I have an XU4 running retropie. I'm using an external USB drive for the roms and bios files. The paths have not changed since it mirrors the same paths without the USB drive. When loading a game, it takes a while and not even getting to the Naomi logo.

I'm wondering if its not able to load retroarch which is on the SD card and not the USB.

https://pastebin.com/raw/4GbkgXDE

**Comment by flyinghead** [comment]
Do you have write access to the current directory? 
If not, please change the permissions and retry.

**Comment by blisstik** [comment]
I can confirm the roms and BIOS/dc and BIOS/dc/data directory have write permissions. When I tried lr-fbalpha, I was able to run a game and save states. Confirmed the file exists. With the BIOS folder, I SSH and transferred some files without issue.

The mount command used is `mount -o bind`, which mounts a subtree. Mount has read/write flags by default without specifying the -rw flag for it.

**Comment by blisstik** [comment]
OK I figured it out. The mount had noexec flag so I had to change it to exec flag.

**Comment by blisstik** [comment]
@flyinghead - Do you know if the emulator is copying a file either in the BIOS/dc folder or roms/naomi folder, then execute it to create the eeprom and nvrom files? I'm trying to understand why changing the mount flag to `exec` solved our issue. It must be executing a file somewhere right?

**Comment by flyinghead** [comment]
The emulator creates a file in the current directory to contain the dynarec code cache and maps it to memory, then deletes the file immediately. So it needs to have the exec flag because this memory area contains code.

**Comment by ghost** [comment]
Is there anything stopping us from, say, deciding we want the dynarec code cache to be written elsewhere instead to avoid this requirement? Why wouldn't it be created in, for instance, the Retroarch System directory instead?

**Comment by blisstik** [comment]
@flyinghead - just want to ensure when you say current directory, you mean the roms directory? If so, would it be possible to move the execution where `reicast_libretro.so` exists then copy the files over to the roms folder?

**Comment by flyinghead** [comment]
Actually I was wrong: the reicast core is different from upstream for this.
It creates the file I mentioned earlier in the game directory, hence the need to have the exec flag I suppose.
Now I'm pretty sure this file could be created elsewhere, like in /tmp.

**Comment by blisstik** [comment]
Hi flyinghead... any traction on moving the creation of files outside the game directory?

**Comment by flyinghead** [comment]
It's on my (quite long) To-Do list...

**Comment by ghost** [comment]
For what it's worth, it doesn't appear to be an issue on the Nvidia Shield
which seems far more restrictive for permissions.

**Comment by flyinghead** [comment]
Check the following setting in your retroarch.cfg:
`savefile_directory = "~/.config/retroarch/save"`
Is it a writable directory? If not, it will fallback to using the game directory

**Comment by blisstik** [comment]
I just tested this using an external FAT32 USB with noexec and exec mount options. With noexec, the game did not load but with exec it did create the eeprom and nvmem files in `~/.config/retroarch/save`

So it looks like it still needs the exec rights in the game directory.

**Comment by flyinghead** [comment]
Not able to reproduce this anymore. Can you check this option?
```
system_directory = "~/.config/retroarch/system"
```
This should be a writable, exec directory.

In the first log you posted, here is the problem:
```
81500000-81d00000 r--s 03000000 08:01 130        /home/pigaming/RetroPie/BIOS/dc/dcnzorz_mem (deleted)
```
This file needs the executable permission.

**Comment by blisstik** [comment]
OK that was it. That path was pointing to a folder in the mounted drive, which if moved outside the mounted drive resolves the issue. Thank you!
