### ISSUE TITLE
[OIT] wrong default ‘Alpha sorting' settings

### ISSUE THREAD

**Issue by 5schatten** [libretro/flycast#316]
According to https://www.libretro.com/index.php/reicast-libretro-and-reicast-oit-libretro-merged-into-one-what-you-need-to-know/

"By default, Reicast Libretro will boot in non-OIT mode." -> it won't

If you compile with HAVE_OIT=1 & try to start on a non-oit compatible system (i3-6100 IGP) it fails to run if you havent started the non-oit core before so if for example retroarch-core-options.cfg isn't existing.

https://pastebin.com/tEZ2q2az

If you add reicast_alpha_sorting = "per-triangle (normal)"  to retroarch-core-options.cfg the oit build starts on my "non-oit system"

So I guess you have to test if the core can run with enabled OIT or you have to make sure the first run sets always alpha sorting to per-triangle.

**Comment by flyinghead** [comment]
dupe of #309

**Comment by blackman91** [comment]
Try RetroArch latest nightly, it is fixed now.

**Comment by 5schatten** [comment]
Isn't the patch reverted?
https://github.com/libretro/RetroArch/commit/508e5efdd772fce232affc884f2bc759eb00fab8

**Comment by blackman91** [comment]
Yeah it is now crashing again on latest nightly on windows, any official word?

**Comment by inactive123** [comment]
Hopefully this makes things work now again -

https://github.com/libretro/reicast-emulator/commit/ac53abda116c75ddcbc3b706174f494d1b8b85bf

Update both RetroArch and the core.

**Comment by blackman91** [comment]
Yep it is working now on RetroArch latest nightly after updating the core. Awesome job as always.
