### ISSUE TITLE
Reicast Core Crashing RetroArch.

### ISSUE THREAD

**Issue by blackman91** [libretro/flycast#318]
Got a pc with opengl 4.6 but RetroArch still crashes after loading any game with the reicast core on windows 10:

[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 44055.95 Hz.
[INFO] [Video]: Video @ 1920x1440
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [GL]: Found GL context: wgl
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [WGL] extensions: WGL_ARB_buffer_region WGL_ARB_create_context WGL_ARB_create_context_no_error WGL_ARB_create_context_profile WGL_ARB_create_context_robustness WGL_ARB_context_flush_control WGL_ARB_extensions_string WGL_ARB_make_current_read WGL_ARB_multisample WGL_ARB_pbuffer WGL_ARB_pixel_format WGL_ARB_pixel_format_float WGL_ARB_render_texture WGL_ATI_pixel_format_float WGL_EXT_colorspace WGL_EXT_create_context_es_profile WGL_EXT_create_context_es2_profile WGL_EXT_extensions_string WGL_EXT_framebuffer_sRGB WGL_EXT_pixel_format_packed_float WGL_EXT_swap_control WGL_EXT_swap_control_tear WGL_NVX_DX_interop WGL_NV_DX_interop WGL_NV_DX_interop2 WGL_NV_copy_image WGL_NV_delay_before_swap WGL_NV_float_buffer WGL_NV_multisample_coverage WGL_NV_render_depth_texture WGL_NV_render_texture_rectangle 
[INFO] [WGL]: Adaptive VSync supported.
[INFO] [WGL]: wglSwapInterval(1)
[INFO] [GL]: Vendor: NVIDIA Corporation, Renderer: GeForce GTX 1050/PCIe/SSE2.
[INFO] [GL]: Version: 4.3.0 NVIDIA 416.16.
[INFO] [GL]: Using Core GL context, setting up VAO...
[ERROR] [GL]: Failed to initialize VAOs.
[ERROR] [Video]: Cannot open video driver ... Exiting ...
[ERROR] Fatal error received in: "init_video()"
[ERROR] failed_to_start_audio_driver
[libretro INFO] Using Recompiler

**Comment by inactive123** [comment]
Can you test if it works now with the latest RetroArch (either built from source or nightlies, preferably built from source) and the latest core?

**Comment by blackman91** [comment]
Yep that did it, now the default setting is per triangle.
