### ISSUE TITLE
Replace soft/fierce trigger binds with an analog axis.

### ISSUE THREAD

**Issue by Nine-H** [libretro/flycast#32]
Ideally this will make xbox 360 triggers work.

**Comment by Papermanzero** [comment]
Alternatively using a setting called L analog and R analog beside soft/fierce trigger, whichenqbles the analog input.

**Comment by hiddenasbestos** [comment]
I've fixed this in pull request #42 - replaced weak/fierce with actual triggers

**Comment by Nine-H** [comment]
I tested it, and it seems good, should I close it or is there anything left on it?

**Comment by hiddenasbestos** [comment]
Great I'm glad you managed to get a good result from testing it. So, yeah, I'd feel free to close this issue now.
