### ISSUE TITLE
JVS Issues from #320

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#321]
When I load Capcom vs SNK 1 or 2, it loads the service menu automatically. I'm able to use R3 (right stick thumb) to cycle thru menu items but I'm not able to use the other button to select or exit out of it.

This is on an Odroid XU4

**Comment by flyinghead** [comment]
The Naomi button mappings have completely changed with this PR so make sure to check your bindings

**Comment by flyinghead** [comment]
I confirm there is an issue with the Test button.

**Comment by blisstik** [comment]
@flyinghead - I think there is still an issue with the new supported games. For example, Virtual On will not load and will crash. I'm using the LST provided here.

https://pastebin.com/raw/LKuP1Fku

**Comment by flyinghead** [comment]
Yes, I can reproduce it, on my branch as well. It works with a previous revision so it's a regression.

**Comment by blisstik** [comment]
The good news is that these gun games now work using analog sticks:
- Confidential Mission
- Death Crimson OX
- The Maze of the Kings

While these two can't load:
- Gun Survivor 2 - Biohazard CODE Veronica (stuck on image with two heads and a monster)
- Lupin The Third - The Shooting (stays on black screen)

Can load with issues:
- Sports Shooting USA (loads, can start a game but can't use analog stick for aiming)
- Sega Clay Challenge (loads, only select button works for multiple coins and R3 for single coins)

**Comment by 6alileo** [comment]
- Sports Shooting USA loads, can start a game but can't use analog stick for aiming

**Comment by 6alileo** [comment]
- Sega Clay Challenge, loads, only select button works for multiple coins and R3 for single coins

**Comment by flyinghead** [comment]
Sports Shooting uses a dreamcast-like light gun apparently

**Comment by flyinghead** [comment]
With the latest commits, the following games should support a Light Gun controller:
Confidential Mission
Death Crimson OX

**Comment by blisstik** [comment]
I've noticed a new issue - with games like Sega Strike Fighter and Chaos Field, after setting the game assignments to player 1, the nvmem is created but on the next boot, it does not save the game assignments. Previously, saving the nvmem or eeprom file would save these settings. I also noticed that eeprom files are no longer generated.

**Comment by flyinghead** [comment]
Thanks for the heads up. I noticed the same thing and I just spotted the problem.

**Comment by flyinghead** [comment]
This should help: https://github.com/libretro/reicast-emulator/pull/325

**Comment by flyinghead** [comment]
Regarding Gun Survivor 2 - Biohazard CODE Veronica, is the game frozen or not accepting input?
Can you insert coins?
This game doesn't use the start button. You start a game with button 1 or 2.

**Comment by blisstik** [comment]
After all the logos shuffle like Capcom and others, it gets stuck on an image with two heads of characters on the right and a monster on the left. I can't start the game with any button. When I press select, I hear coins

________________________________

**Comment by blisstik** [comment]
Wave Runner GP now has controls using the left analog stick for gas and brake. Still has that "NO DRIVE BOARD" on the bottom right.

**Comment by flyinghead** [comment]
Then it's probably an input mapping problem in RA. Check that Button 1 and 2 are properly mapped.

Regarding Wave runner, the NO DRIVE BOARD message is "normal"
You need to map the analog axes properly. I think axis 1 is direction, axis 2 is gas and axis 3 is brake(?) like many Naomi driving games.

**Comment by blisstik** [comment]
- Gun Survivor 2 - Biohazard CODE Veronica
I'm stuck on this image, can't press any button: https://ibb.co/dpUBTp

- Virtua Golf
Get's stuck on this image: https://ibb.co/kkOug9

**Comment by blisstik** [comment]
- Sega Strike Fighter - black screen after Naomi boot logo
https://pastebin.com/raw/2jcccfHv

**Comment by flyinghead** [comment]
Virtua Golf requires a specific set up of two I/O boards that's not currently emulated so it doesn't work yet.
However Gun Survivor 2 and Sega Strike Fighter should boot. 
This is what you should see:
![gun survivor 2-181013-104959](https://user-images.githubusercontent.com/16261910/46903478-d44d6d00-ced5-11e8-8660-02ec13c003c9.png)

**Comment by roisiano** [comment]
Hello:

Any news about compatibility with Virtua golf?

I've been testing it today and the controls don't work.

Kind regards

**Comment by flyinghead** [comment]
Virtua Golf works fine. It uses a trackball, which is emulated by a mouse. No need to set the controller as mouse though.
