### ISSUE TITLE
[NAOMI] WWF Royal Rumble crashes retroarch

### ISSUE THREAD

**Issue by legluondunet** [libretro/flycast#326]
Hello,
if I launch WWF Royal Rumble, it crashes Retroarch.
I joined you the log file.
[retroarch.log](https://github.com/libretro/reicast-emulator/files/2475036/retroarch.log)

md5sum: 71a19b7d9ef4f04c2ead7fbd1708cf16  WWF_Royal_Rumble.bin

Thank you for your help.

Config:
Ubuntu 18.04

**Comment by flyinghead** [comment]
That's weird: it works fine for me on ubuntu 16/nvidia 1080.
commit https://github.com/libretro/reicast-emulator/commit/bc92da858da3853f186be01e6e2a25febcb17420
Using your lst file and the same .bin file.
I tried enabling Div Matching but still working fine.

Is the Naomi BIOS booting? Do you see any screen from WWF?

**Comment by legluondunet** [comment]
there is no Naomi logo, just a black screen then Retroarch crashes.

**Comment by legluondunet** [comment]
I just deleted my retroarch-core-options.cfg file to start Reicast with default option and that changed nothing, You didn't see anything interesting in my log?
I verified, the others Naomi games launched normally.

**Comment by flyinghead** [comment]
The log clearly indicates a crash but doesn't say where.
Would you be able to run with with gdb and give me a stack trace?
Not sure how technical you are but here are the commands:
```
gdb --args retroarch /home/legluondunet/Autres_applications/Jeux/Emulateurs/Consoles/SEGA\ Dreamcast/Naomi/WWF_Royal_Rumble.lst -s /home/legluondunet/.config/retroarch/savefiles -S
 /home/legluondunet/.config/retroarch/savestates -c /home/legluondunet/.config/retroarch/retroarch.cfg -L /home/legluondunet/.config/retroarch/cores/reicast_libretro.so
handle SIGSEGV noprint nostop
run
# wait for the crash then:
bt
```

**Comment by legluondunet** [comment]
I did it another way, I hope this is correct too:
`$ gdb --args ./retroarch`
I joined you the terminal log
[retroarch_gdb_WWF.log](https://github.com/libretro/reicast-emulator/files/2475290/retroarch_gdb_WWF.log)

**Comment by flyinghead** [comment]
That's exactly what I wanted but unfortunately there are no symbols or function names so it doesn't help much.
Not your fault of course.

**Comment by legluondunet** [comment]
Could it be a bios bug?

![capture d ecran de 2018-10-13 12-15-15](https://user-images.githubusercontent.com/325405/46904252-ad953380-cee1-11e8-9886-ed228e2ad541.png)

or with my graphics drivers:
Distro: Ubuntu 18.04.1 LTS - Kernel: 4.15.0-33-generic - GPU: Nivida  GeForce GTX 770 drivers 396.54 - CPU: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz - RAM: 7922 Mo

**Comment by flyinghead** [comment]
I'm using the same bios.
Ubuntu 16.04.2 LTS
NVidia driver 390.77.

Check your .lst file for bad characters or typo. When the Naomi bios doesn't boot that's usually the problem.

**Comment by legluondunet** [comment]
This is my lst file:
[WWF_Royal_Rumble.zip](https://github.com/libretro/reicast-emulator/files/2475430/WWF_Royal_Rumble.zip)
I already had issues with the typo or text file properties with others games.
Could you try to launch the game with my lst file? Thanks.

**Comment by flyinghead** [comment]
I get pretty much the exact same crash as you... if I don't set the name of the .bin correctly. Otherwise it's fine...

Your bin file is named **`SWWF_Royal_Rumble.bin`** ? sure about the S?
Mine is **`WWF_Royal_Rumble.BIN`**

**Comment by legluondunet** [comment]
Sorry to waste your time for such a ridiculous issue: a bad copy/paste of the rom name file.
I am ashamed and I think I need rest, thank you.
