### ISSUE TITLE
Gun Survivor 2 - Biohazard CODE Veronica [non-OIT] [XU4]

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#328]
This game has the same issue prior to JVS enhancements where it would boot past all the logos and once I press a button, it gets stuck on the main screen background. The foreground game logos do not get rendered. Screenshot: https://ibb.co/dpUBTp

I'm able to press Select for coins but can't start the game.

The XU4 uses a Mali-T628 MP6 GPU with OpenGL ES3.1 support.

MD5: 58536E653B866F0945AA10DFA5DB1BFD

LST
```
Gun Survivor 2 - Biohazard CODE Veronica
"Gun Survivor 2 - Biohazard CODE Veronica.bin", 0x0000000, 0x10000000
```

**Comment by flyinghead** [comment]
Did a test on Android with the latest nightly and I get heavy graphic corruption that quickly lead to a crash.
```
2018-10-13 18:11:39.611 9876-9906/? I/RetroArch: Verify Failed  : !IsModVolList(ta_fsm_cl)
     in ta_handle_cmd -> /home/buildbot/buildbot/android/libretro-reicast/jni/../core/hw/pvr/ta.cpp : 246 
2018-10-13 18:11:39.611 9876-9906/? I/RetroArch: Fatal error : segfault
     in signal_handler -> /home/buildbot/buildbot/android/libretro-reicast/jni/../core/libretro/common.cpp : 394 
```
Apparently it's sending corrupted TA data. 
Could be an arm-specific memory issue.

**Comment by flyinghead** [comment]
Should be fixed by https://github.com/libretro/reicast-emulator/pull/341

**Comment by blisstik** [comment]
No longer boots to black screen. However, the LEFT ANALOG STICK needs to be rotated as left makes the character move forward; right makes them move backward; down makes them move left; up makes them move right.

The RIGHT ANALOG STICK seems to work properly in moving the camera angles.
