### ISSUE TITLE
Lupin The Third - The Shooting / Sega Strike Fighter [non-OIT] [XU4]

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#329]
Both of these games has the same issue prior to JVS enhancements where it would boot past the Naomi logo and just eventually lead to black screen **without any audio**. I'm able to launch RetroArch RGUI and exit out of the game but not able to do anything else.

The XU4 uses a Mali-T628 MP6 GPU with OpenGL ES3.1 support.

Lupin The Third - The Shooting MD5: C2EA18573C5E3EE07BC27DE78C435B67
Sega Strike Fighter MD5: C80E4AC1CE7621CCD3DE86454FDD09FA

LSTs
```
Lupin The Third - The Shooting
"Lupin The Third - The Shooting.bin", 0x0000000, 0x0D77B800

Sega Strike Fighter
"Sega Strike Fighter.bin", 0x0000000, 0x0B000000
```

**Comment by flyinghead** [comment]
Should be fixed by https://github.com/libretro/reicast-emulator/pull/341

**Comment by blisstik** [comment]
No longer boots to black screen. Lupin The Third does NOT have any audio.
