### ISSUE TITLE
Soul Calibur is broken (white screen) with VGA RGB

### ISSUE THREAD

**Issue by Papermanzero** [libretro/flycast#33]
If you start Soul Calibur the game freezes after the time setting screen.
The whole emulator with retroarch freezes.

**Comment by inactive123** [comment]
Must be a problem on your end, it works completely fine here.

Post more information for starters on your system/GPU/driver/a log of some kind, this tells us basically nothing.

**Comment by Papermanzero** [comment]
I tried now to trace the issue. With the debug exe (retroarch_debug.exe) the game is running without issue.
With the normal exe (retroarch.exe) the game goes to the white screen and retroarch crashes. 
Do you know how to log the normal exe?

Edit: Ok, the issue seems different. Even with the debug exe the game crashes. So it seems the PAL version of Soul Calibur boots sometimes but not every time. Most of the time the game crashes.

**Comment by Papermanzero** [comment]
Here the log

...
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[INFO] [GL debug (Low, API, Other)]: Rasterization quality warning: A non-fullscreen clear caused a fallback from CSAA to MSAA.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[INFO] [GL debug (Low, API, Other)]: Texture state usage warning: The texture object (0) bound to texture image unit 0 does not have a defined base level and cannot be used for texture mapping.
[INFO] [GL debug (Low, API, Other)]: Rasterization quality warning: A non-fullscreen clear caused a fallback from CSAA to MSAA.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
[ERROR] [GL debug (High, API, Error)]: GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.
Sh4: i-cache invalidation AC09EC6E
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at AC09EC6E
HASH: 8C09ED16 reloc >:1:05:BD3BE51F:1E886EE6:6BDB3F70:7FB25EA3:DE0083A8
Sh4: i-cache invalidation AC00043A
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at AC00043A
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at AC0082FE
Sh4: i-cache invalidation AC0082FE
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at AC0082FE
Sh4: i-cache invalidation AC00E0DA
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at AC00E0DA
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at AC00FFFE
Sh4: i-cache invalidation AC00FFFE
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at AC00FFFE
G2-EXT1 DMA : SB_E1DIR==0:DMA Write to 0x9F0000 from 0xCFF0000 32 bytes
Sh4: i-cache invalidation 8C29D9D2
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at 8C29D9D2
Sh4: i-cache invalidation AC2A259A
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at AC2A259A
SPI : unknown ? [0x70]
SPI : unknown ? [0x71]

**Comment by inactive123** [comment]
Have you tried setting the region and cable type to something different? I don't use the PAL version (I use the NTSC version of Soul Calibur), but maybe setting it to VGA RGB would fix it?

**Comment by Papermanzero** [comment]
VGA is enabled. But I can try to reset all settings mayb it works

**Comment by Papermanzero** [comment]
The root cause is VGA RGB. If you change to TV RGB it is working without issue.

**Comment by flyinghead** [comment]
Can't reproduce anymore. Reopen as needed
