### ISSUE TITLE
[Naomi] Zombie Revenge, Crazy Taxi and Power Stone controls not working

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#330]
This game boots fine and the demo looks to be running fast. However, none of the buttons on the controller works.

MD5: 746314359647DDEEC7E3927DEDF28A80

LST
```
Zombie Revenge
"Zombie Revenge.bin", 0x0000000, 0x0A000000
```

**Comment by flyinghead** [comment]
This is a known issue that affect these three games. Chances are they have the same problem and will be fixed by the same change. I renamed the issue to reflect this.

**Comment by 6alileo** [comment]
I have Crazy Taxi and Power Stone in the same bucket of booting into black
screen without audio. Along with these: Alient Front, Melty Blood Actress
Again, Outtrigger, Virtua NBS, Virtua Tennis, Virtua Tennis 2, World Series
Baseball.

**Comment by twinaphex** [comment]
@6alileo your roms are probably bad then. Virtua Tennis 1/2 boot up at least, same with Crazy Taxi and Power Stone.

What device is this that you are running it on?

**Comment by 6alileo** [comment]
On an XU4 but they do load on my Windows desktop with Nvidia GPU so I think it's specific to arm.

I'll post md5s in a bit

________________________________

**Comment by flyinghead** [comment]
I'd rather keep this issue to track a known problem, affecting all platforms, for the games mentioned in the title.

All these problems with other games (but may be affecting these games as well) seem to point to an arm-specific issue. 
They should be tracked by a separate issue.

**Comment by inactive123** [comment]
OK, @6alileo, can you please post these issues somewhere else in another issue dedicated to ARM/XU4? This is about a different bug altogether.

EDIT: opened this for you already -

https://github.com/libretro/reicast-emulator/issues/333

Moved the contents to there and cleaned up this issue for you @flyinghead

**Comment by flyinghead** [comment]
Should be fixed by https://github.com/libretro/reicast-emulator/pull/335

**Comment by blisstik** [comment]
These no longer have boot to black screen issues. However, their controls are wonky.

Examples:

- Jambo Safari and Crazy Taxi have the brakes always on. To remove the brake pedal, I would have to press the RIGHT analog stick to the LEFT.

- Zombie Revenge I think needs the LEFT stick to be rotated for it to be oriented properly.

- Power Stone is fine.

**Comment by flyinghead** [comment]
You need to map the controls properly. This is not done by the core. The best way is to use the game test mode in the service menu and then select the input test.
When done you can save your mappings for each game.

**Comment by blisstik** [comment]
Got it! Thanks for supporting the ARM versions!

**Comment by grendyzer** [comment]
> You need to map the controls properly. This is not done by the core. The best way is to use the game test mode in the service menu and then select the input test. When done you can save your mappings for each game.

thanks, it's good, change control numéric to analog.
