### ISSUE TITLE
Jambo Safari [non-OIT] [XU4]

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#331]
This game has the same issue prior to JVS enhancements where it would boot past the Naomi logo and just eventually lead to black screen **with audio**. I'm able to hear the game demo thru the black screen. I'm able to launch RetroArch RGUI and exit out of the game but not able to do anything else.

The XU4 uses a Mali-T628 MP6 GPU with OpenGL ES3.1 support.

MD5: 4EFD869B0D688A80A8AB8C51F4897D24

LST
```
Jambo Safari
"Jambo Safari.bin", 0x0000000, 0x04800000
```

Other games that have a similar issue (boots into black screen with audio)
- Street Fighter Zero 3 Upper
- Virtua Striker 2

**Comment by flyinghead** [comment]
Should be fixed by https://github.com/libretro/reicast-emulator/pull/341

**Comment by blisstik** [comment]
No longer boots to black screen. Although has a control issue where brakes are always on.
