### ISSUE TITLE
18 Wheeler STD and DX [XU4] [non-OIT]

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#332]
This also boots into a black screen but I'm able to get past that and select a truck and play the game. Although I think there are some issues with cutscenes.

**Comment by flyinghead** [comment]
This is a depth precision issue. The console version of this game has the same problem. Most of the menus and overlays are invisible.
The only way around this is to use GLES3 or GL2+.

**Comment by MastaG** [comment]
But the XU4 supports GLES 3.1.. Mali-T628 MP6(OpenGL ES 3.1/2.0/1.1 and OpenCL 1.2 Full profile)

**Comment by flyinghead** [comment]
A verbose log would help verifying what is the GLES version actually used by the core

**Comment by blisstik** [comment]
What's the command to figure out the GLES version?

**Comment by flyinghead** [comment]
`retroarch --verbose`

**Comment by blisstik** [comment]
Here's the log for 18 Wheeler
https://pastebin.com/raw/Dhc4kGGc

Just for comparison, I logged one of the games without issues, Cannon Spike:
https://pastebin.com/raw/J71FcxuB

What I'm seeing on both is its requesting OpenGLES2 on line 169

`[INFO] Requesting OpenGLES2 context.`

**Comment by flyinghead** [comment]
Right, it's requesting an Open GLES 2 context because that's the minimum it needs. On Android you get a GLES 3 context if it's supported. Not sure in this case.
Can you run the console version of this game or Cannon Spike or Dynamite Cop without issue?

**Comment by blisstik** [comment]
The Dreamcast versions of Cannon Spike and Dynamic Cop don't have issues but 18 Wheeler has the same issues on Naomi

________________________________

**Comment by flyinghead** [comment]
Not reproducible on Android 8.1 / OpenGL ES 3.2

**Comment by MastaG** [comment]
@flyinghead 
Yes so it seems:
[INFO] Environ SET_HW_RENDER.
[INFO] Requesting OpenGLES2 context.
[libretro INFO] Setting save dir to /home/pigaming/RetroPie/roms/naomi/
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 44055.95 Hz.
[INFO] [Video]: Video @ 640x480
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [EGL] Falling back to eglGetDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [GL]: Found GL context: mali-fbdev
[INFO] [GL]: Detecting screen resolution 0x0.
[INFO] [EGL]: Created shared context: 0x613f00.
[INFO] [EGL]: Current context: 0x5c78f0.
[INFO] [GL]: Vendor: ARM, Renderer: Mali-T628.
[INFO] [GL]: Version: OpenGL ES 3.1 v1.r12p0-04rel0.03af15950392f3702b248717f4938b82.
[INFO] [GL]: Using resolution 1920x1200
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.

The driver reports OpenGL ES 3.1 but the OpenGLES3 context isn't requested in the first place?

**Comment by blisstik** [comment]
Is there a way to force to request OpenGLES3 context? I wonder if its a configuration issue on Ubuntu?
