### ISSUE TITLE
ARM / XU4 Naomi bugs

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#333]
These games all boot up to a black screen in one form or another (with non-OIT renderer) -

* 18 Wheeler STD and DX
* Power Stone
* Zombie Revenge
* Alient Front
* Melty Blood Actress Again
* Outtrigger
* Virtua NBA
* Virtua Tennis
* Virtua Tennis 2
* World Series Baseball

Originally posted by @6alileo

```
53FBA9AD492F96F0BFB709532582D51C  Virtua Tennis 2.bin
89B214A71A7FF0721FBA674DFB678C3C  Virtua Tennis.bin
6AF9021B6E6D881F55F01C5229E3EA8E  Power Stone.bin
8669B1236399E81B3F9549A13B2A24C8  Crazy Taxi.bin
```

**Comment by flyinghead** [comment]
Outtrigger, Melty Blood Actress Again, Virtua Tennis and World Series Baseball are not currently supported. See the Naomi compatibility list: #136 

18 Wheeler DX has depth precision problems. See #332 

Zombie Revenge should now be playable. It works fine on a Raspberry Pi.

Alien Front, Jambo Safari, Virtua NBA and Virtua Tennis 2 boot to a black screen on RPi.

**Comment by flyinghead** [comment]
Should be fixed by https://github.com/libretro/reicast-emulator/pull/341

**Comment by blisstik** [comment]
Please close this @twinaphex
