### ISSUE TITLE
Reicast core doesn't start under Vulkan driver

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#339]
Setting the video driver to "Vulkan" causes the reicast core to not load any games.  

Tested on RetroArch 1.7.5 (Git 75485e7) compiled on Linux x64, kernel 4.15, under X11.  Using Nvidia driver 390.77.

**Comment by inactive123** [comment]
It doesn't have a Vulkan renderer at all, only OpenGL.

**Comment by Shoegzer** [comment]
Ah, didn't realize that.  I assume it's well-known that it needs a Vulkan renderer so rather than revising the issue as a feature request I'll just close it.  Thanks.
