### ISSUE TITLE
Sports Shooting USA [XU4] [non-OIT]

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#346]
Boots but does not have analog controls like in Confidential Mission. The buttons for guns do work.

**Comment by flyinghead** [comment]
The AtomisWave version should work with light gun support. There might be polishing needed as triggers sometimes don't register if you don't move the mouse (?). Let me know if it works for you.

Also you must calibrate to the light guns once (the results are saved to the flash RAM so you don't have to do it again).

**Comment by blisstik** [comment]
I went into service menu and did the I/O test. Using my Hori PS4-100U controller, I was NOT able to activate the trigger button (to start the test) and LEFT analog stick did not register any coordinates.

On a Naomi game like Death Crimson OX, I'm able to use the same controller and use the LEFT analog stick to aim and press buttons to shoot and reload.

**Comment by flyinghead** [comment]
Most Naomi games use analog controls for light guns so they work with a regular joystick/gamepad (although it's not ideal.)
AW games use maple light guns so you need to bind a light gun in RetroArch rather than a Gamepad for the current user.

**Comment by blisstik** [comment]
I tried binding my gamepad using Light Gun in RA but it doesn't work. So I guess I need to get a USB light gun. Which one do you use?

**Comment by flyinghead** [comment]
RA will use the mouse if you bind a Light Gun for a player without an actual light gun attached. I don't have a light gun myself.

**Comment by blisstik** [comment]
I plugged in a mouse then went into RA and selected `mouse`. Not sure what I need to do next but nothing worked except Start and Select on the gamepad (attached separately).

**Comment by flyinghead** [comment]
This PR should help once merged: https://github.com/libretro/reicast-emulator/pull/400

For this to work you need to specify Light Gun as the RA controller. Without an actual light gun connected you can use the mouse. Bind the light gun trigger to mouse button 1 and other stuff to other buttons: Start, Button 1, Reload...
