### ISSUE TITLE
Sega Clay Challenge [XU4] [non-OIT]

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#347]
Boots but does not have any controls. The analog stick and buttons do not work.

**Comment by flyinghead** [comment]
The AtomisWave version should work with light gun support. There might be polishing needed as triggers sometimes don't register if you don't move the mouse (?). Let me know if it works for you.

Also you must calibrate to the light guns once (the results are saved to the flash RAM so you don't have to do it again).
