### ISSUE TITLE
Grandia II freezing before reaching memory card menu

### ISSUE THREAD

**Issue by anothername99** [libretro/flycast#35]
From the title menu I select Continue. Then I get a black screen and the game freezes. There is no way to load my save.

**Comment by inactive123** [comment]
DId you try generic_recompiler?

**Comment by anothername99** [comment]
@twinaphex Yes, the issue happens with generic_recompiler.

**Comment by flyinghead** [comment]
Can't reproduce anymore. Reopen if the problem persists
