### ISSUE TITLE
Extra Depth Scale Problem on Sega Marine Fishing

### ISSUE THREAD

**Issue by TradeDraft** [libretro/flycast#355]
Normally the Title Screen Missing the Sega Marine Fishing Logo. So I turn on the Extra Depth Scale I then get just the Logo and Menu and nothing else and can't go back Fishing and Playing Game until I turn it back off.

Is this Fixable?

**Comment by flyinghead** [comment]
Interesting. This means it's very likely a depth fighting issue.

What platform are using? What Open GL/GLES version?

**Comment by TradeDraft** [comment]
What is the Difference between Open GL/GLES Version.

I just use the Windows 64 1.7.5 Stable Version with latest Reicast Core I can download from Buildbot.

Video Showing What Happens:

https://youtu.be/lD_IOkGX6Gc

**Comment by flyinghead** [comment]
What graphic card do you have?

**Comment by flyinghead** [comment]
Looks issue #37 is the same as this one so let's keep only one.
