### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by RossComputerGuy** [libretro/flycast#356]
I got this outputted in stdout:
```
Unimplemented opcode: 00000800 next_pc: A0000016 pr: 00000000 msg: Unknown opcode
DEBUGBREAK!
SIGSEGV @ 0x7f8a48b8b6f5 (signal_handler + 0x0x68be5) ... 0x7f8a48b8b6f5 -> was not in vram
DEBUGBREAK!
Illegal instruction (core dumped)
```

**Comment by orbea** [comment]
How can this be reproduced?

**Comment by RossComputerGuy** [comment]
Run Gundam Side Story UC 0079

**Comment by flyinghead** [comment]
I don't get Unknown opcode with this game but it freezes at boot on the Sega copyright screen. This only happens on x64 platforms (linux and presumably windows although I didn't test it).

This fixed it for me: https://github.com/libretro/reicast-emulator/pull/423

**Comment by flyinghead** [comment]
Please retest with latest core build and update.
Thanks

**Comment by RossComputerGuy** [comment]
Still has the problem and I figured out the game that actually has this issue is Half-Life.26.11.2018, 10:32, "flyinghead" <notifications@github.com>:Please retest with latest core build and update.
Thanks

**Comment by inactive123** [comment]
Isn't Half-LIfe a Windows CE game?

**Comment by RossComputerGuy** [comment]
I don't know but it might be.26.11.2018, 11:09, "Twinaphex" <notifications@github.com>:Isn't Half-LIfe a Windows CE game?

**Comment by flyinghead** [comment]
Half-Life is a Windows CE game. Not currently supported.

**Comment by flyinghead** [comment]
Please re-open this issue with appropriate information. Thank you.
