### ISSUE TITLE
Dead or Alive 2 LE causing RetroArch to crash

### ISSUE THREAD

**Issue by anothername99** [libretro/flycast#36]
I select Survival Mode and select Kasumi. The game is then supposed to load a level but instead RetroArch crashes.

**Comment by inactive123** [comment]
Is this the Japanese Shokai Genteiban version? I believe that game has issues yeah with Reicast. However, the other Dead or Alive 2 versions (in particular the US version) should work fine. Unfortunately, they don't have a bunch of the features that this more recent version has.

I will try to see if there is some dynarec setting that causes this.

**Comment by anothername99** [comment]
It's Shokai Genteiban yes.

It seems like the dynarec breaks a lot of games. It might be interesting to try the interpreter, but I don't see an option for it. Do you know what the state of the interpreter is, if there is any?

**Comment by inactive123** [comment]
I made an issue for this on the reicast upstream repo and added a $30 bounty to it -

https://github.com/reicast/reicast-emulator/issues/1168

Would be nice if you could chip in as well. Any little bit helps.

I tried the game with the generic recompiler but that crashes as well. Tried disabling idle loop skips, didn't help. Tried disabling NVMEM, didn't help either.

**Comment by inactive123** [comment]
Should be fixed as of this commit -

https://github.com/libretro/reicast-emulator/commit/130cee6ba26018eaf14fee6f642d2d3218ac5ec7
