### ISSUE TITLE
[Android 9.0] Multiple issues with Sonic Adventure 2, all potentially related

### ISSUE THREAD

**Issue by ubergeek77** [libretro/flycast#361]
## Device Information

OS: Android 9.0 Pie
Device: [Google Pixel 3 XL](https://www.gsmarena.com/google_pixel_3_xl-9257.php)
CPU: Qualcomm SDM845 Snapdragon 845 
GPU: Adreno 630
Graphics Driver: gl (OpenGL)
OpenGL Info: OpenGL ES 3.2 V@313.0

## Breakdown of issues
(Summary of issues at the bottom)
This all started with me trying to figure out why the Reicast core wasn't rendering shadows properly in Sonic Adventure 2 (see [Screenshot A](https://i.imgur.com/ZBl2ZAj.jpg)). If you look closely under Omochao and Sonic, there are no shadows. This is with the default settings provided by both Retroarch and the Reicast core. A Reddit user who was helping me figure this out [showed that shadows were working fine on his end](https://www.reddit.com/r/EmulationOnAndroid/comments/9rgyze/reicast_on_retroarch_no_shadows/e8h9nyk/) (see [Screenshot B](https://i.imgur.com/QTwZnB2.png), from his device, not mine).

For reference, Alpha Sorting is set to "per-triangle" by default, and I have left this setting untouched throughout all of my testing for this issue.

In addition to the lack of shadows, any time the game would load something or transition screens, a strange tiling effect would occur (see [Screenshot C](https://i.imgur.com/K08zR3j.png), which is what the emulator looks like immediately after pressing "start" to skip the intro sequence). As you can see, a portion of the screen is "tiled," and it will even do this with the on-screen controls provided by Retroarch, not just the Dreamcast video output, so it seems like something at a higher level than just the Reicast core is causing this.

The same Reddit user pointed out to me that the latest fh/mymaster build of the standalone Reicast APK does not have these issues, and he was right. According to him, since the Reicast RetroArch core and the fh/mymaster build of Reicast are nearly identical, shadows should also render properly on RetroArch. I tested that build on my phone, and it works pretty much perfectly fine, shadows included, apart from some other miscellaneous issues that RetroArch does not have, such as:

- You have to press "back" to open the on-screen menu at least once before playing, otherwise the screen stays blank
- Joystick inputs are very sensitive and jumpy due to no deadzone controls
- The right analog stick and the triggers of my external controller do not work
- There are no resolution options

But I digress. It's possible the lack of shadows in the Reicast core has something to do with threaded rendering on my hardware. From completely default settings, if I enable "Threaded Rendering" under the Reicast core settings (which is disabled by default), the "tiling" issue I mentioned before does not happen. However, after about 10-15 seconds, the controller loses all responsiveness, and a "RetroArch isn't responding" popup appears (see [Screenshot D](https://i.imgur.com/KZXBhEK.png)). If I select "Wait" instead of "Close App," emulation will continue at normal speed, but I lose all controller functionality. Both external controllers and the on-screen controls stop functioning when Threaded Rendering is enabled.

Interestingly, if I play with threaded rendering disabled, save a state somewhere I can clearly see where a shadow should be, then re-load the state with threaded rendering enabled, the shadows will actually render correctly on the Reicast core. But I will still lose controller input just like before.

## Summary:
- Sonic Adventure 2 does not render shadows on the Reicast core with the default settings (threaded rendering disabled).
- Under the default settings, there is a strange GPU "tiling" effect whenever things are being loaded
- If threaded rendering is enabled, the shadows render correctly, and the "tiling" effect no longer occurs.
- If threaded rendering is enabled, all controller input, from both external controllers and on-screen controls, will stop working completely after a short period of time.
- All instances of "threaded rendering" in this issue is referring to the option listed in the Reicast core settings, not to be confused with the "Threaded Video" option under RetroArch's Video settings, which has remained untouched.
- This may affect other games, but I have only tested Sonic Adventure 2 

I wanted to compare these findings with the Windows version of RetroArch and Reicast, but unfortunately, I can't seem to get RetroArch to load any cores at the moment, and I'm not sure how to fix it.

If there is any additional information I can gather to solve this issue, please let me know. I would be happy to assist.

## Screenshots
**Screenshot A:** https://i.imgur.com/ZBl2ZAj.jpg
**Screenshot B:** https://i.imgur.com/QTwZnB2.png
**Screenshot C:** https://i.imgur.com/K08zR3j.png
**Screenshot D:** https://i.imgur.com/KZXBhEK.png

**Comment by flyinghead** [comment]
Thank you for this very detailed report.
Regarding the lost of input responsiveness in threaded rendering mode, setting the input poll type to Early seems to fix the problem (Settings -> Input -> Poll Type Behavior = Early). This is a known issue but the underlying cause is still unknown.
Other than that, I did a test on a Snapdragon 845 device and I confirm that shadows do not appear in non-threaded rendering mode. I still have no idea why this happens.

**Comment by ubergeek77** [comment]
Thanks! I can confirm changing the poll type to Early fixed the crashing, games run like a dream now and everything is rendered correctly. I never would have thought to change something *input* related to fix a graphics issue. Very strange, but I'm glad it worked!
