### ISSUE TITLE
Crashing on any game [non-OIT] [ARM]

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#365]
Updated to the latest lr-reicast 500393a and retroarch master branch. When loading a game, it just crashes. I don't get the mapped controller notification on bottom left and does not get to the Naomi boot.

Previous compiled version 127f845 works fine with the same setup.

```
Parameters: 
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-reicast/reicast_libretro.so --config /opt/retropie/configs/naomi/retroarch.cfg "/home/pigaming/RetroPie/roms/naomi/Shikigami No Shiro II.bin" --appendconfig /dev/shm/retroarch.cfg
[reicast]: Got size: 640 x 480.
Creating dir: /home/pigaming/RetroPie/BIOS/dc/data
ARM VFP-Run Fast (NFP) enabled !
Linux paging: 00001000 00001000 00000FFF
MAP 00800000 w/ 50331648
MAP 20000000 w/ 50331648
MAP 04000000 w/ 33554432
MAP 06000000 w/ 33554432
MAP 0C000000 w/ 0
A8
vmem reserve: base: 90CB0000, aram: b0cb0000, vram: 94CB0000, ram: 9CCB0000
Resetting mem
Mem alloc successful!Loaded /home/pigaming/RetroPie/BIOS/dc/naomi_boot.bin as bootrom

flash/nvmem is missing, will create new file...Sh4 Reset
recSh4 Init
Freeing fpcb
readm helpers: up to B1782250
nullDC-Naomi rom loader v1.2
File: /home/pigaming/RetroPie/roms/naomi/Shikigami No Shiro II.bin
+1 romfiles, 112.30 MB set size, 112.30 MB set address space
NAOMI GAME ID [SHIKIGAMI NO SHIRO 2]

Mapped ROM Successfully !

EEPROM file : /home/pigaming/RetroPie/roms/naomi/Shikigami No Shiro II.bin.eeprom

	 ARM7_TCB addr: 0xb2a82000 | from: 0xb2a81178 | addr here: 0xb2a497c8
Sh4 Reset
reios: IP.bin is ''
reios: Hardware ID is: 
reios: Maker ID is:    
reios: Device info is: 
reios: Area symbols is: 
reios: Peripherals is: 
reios: Product number is: 
reios: Product version is: 
reios: Release date is: 
reios: Boot filename is: 
reios: Software company is: 
reios: Software name is: 
reios: loading ip.bin from FAD: 0
reios: bootfile is ''
context_reset.
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1008:  9917 Segmentation fault      /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-reicast/reicast_libretro.so --config /opt/retropie/configs/naomi/retroarch.cfg "/home/pigaming/RetroPie/roms/naomi/Shikigami No Shiro II.bin" --appendconfig /dev/shm/retroarch.cfg
```

**Comment by flyinghead** [comment]
Does it happen also with dreamcast games?

**Comment by flyinghead** [comment]
Another idea: do you have more than 4 (virtual) controllers connected? Try to use only 4 to see if it makes a difference.

**Comment by flyinghead** [comment]
I have tested Android, Linux x64 and Linux arm (RPi) without issue. I will need a verbose log or a stack trace to figure it out.

**Comment by blisstik** [comment]
It happens on Dreamcast as well. I only have 1 controller connected via Bluetooth during the logs below:

Naomi: https://pastebin.com/raw/yUqTLt63
Dreamcast: https://pastebin.com/raw/k9GsKcH9

**Comment by blisstik** [comment]
Here's another comparison of verbose working vs non-working of the same game (Daytona USA for DC).

127f845: https://pastebin.com/raw/eaRMW30e
500393a: https://pastebin.com/raw/HfxAMPN5

Doing a text compare, I notice that the block below gets created before `[INFO] Skipping SRAM load..` on the latest version while almost the same block gets created after `[INFO] [PulseAudio]: Unpausing.` on the previous version.

```
Creating dir: /home/pigaming/RetroPie/BIOS/dc/data
ARM VFP-Run Fast (NFP) enabled !
Linux paging: 00001000 00001000 00000FFF
MAP 00800000 w/ 25165824
MAP 20000000 w/ 25165824
MAP 04000000 w/ 16777216
MAP 06000000 w/ 16777216
MAP 0C000000 w/ 0
A8
vmem reserve: base: 911D0000, aram: b11d0000, vram: 951D0000, ram: 9D1D0000
Resetting mem
Mem alloc successful!Loaded /home/pigaming/RetroPie/BIOS/dc/dc_boot.bin as bootrom

Loaded /home/pigaming/RetroPie/BIOS/dc/dc_nvmem.bin as nvram

[libretro INFO] Using Recompiler
Sh4 Reset
recSh4 Init
Freeing fpcb
readm helpers: up to B16D0250

Session 1 has 1 track(s)
Saving  Track:  1  Type: Mode2/2336  Pregap: 150  Size: 57857   LBA: 0       
Track position: 350400

Session 2 has 1 track(s)
Saving  Track:  2  Type: Mode2/2336  Pregap: 150  Size: 289537  LBA: 69257   
Track position: 135854752
gdrom: Opened image "/home/pigaming/RetroPie/roms/dreamcast/Daytona USA (USA).cdi"

	 ARM7_TCB addr: 0xb29d0000 | from: 0xb29cf178 | addr here: 0xb29977c8
Initializing VMU data...
Initializing VMU data...
Initializing VMU data...
Initializing VMU data...
Sh4 Reset
reios: IP.bin is 'SEGA SEGAKATANA SEGA ENTERPRISES2BD2 GD-ROM1/1  JUE     2799A10 MK-51037  V1.00420010214        1ST_READ.BIN    themacN         DAYTONAUSA                                                                                                                      /home/pigaming/RetroPie/BIOS/dc/'
reios: Hardware ID is: SEGA SEGAKATANA 
reios: Maker ID is:    SEGA ENTERPRISES
reios: Device info is: 2BD2 GD-ROM1/1  
reios: Area symbols is: JUE     
reios: Peripherals is: 2799A10 
reios: Product number is: MK-51037  
reios: Product version is: V1.004
reios: Release date is: 20010214        
reios: Boot filename is: 1ST_READ.BIN    
reios: Software company is: themacN         
reios: Software name is: DAYTONAUSA                                                                                                                      
reios: loading ip.bin from FAD: 69407
reios: bootfile is '1ST_READ.BIN    '
reios: iso9660 PVD found
reios: iso9660 root_directory, FAD: 69430, len: 28672
Found 1ST_READ.BIN at 000065
filename len: 14
file LBA: 357660
file LEN: 2010720
[libretro INFO] [LUT]: Product number: MK-51037  .
```

**Comment by flyinghead** [comment]
Yes, there has been changes regarding when the core initialization is done. Previously it was done lazily, when the game was starting up. It is now done when the game is being loaded.
I'm thinking this issue could be a consequence of these changes but no luck in reproducing it and so far no other user reported it.
Any way you could get a stacktrace with gdb? Not sure if -g is enabled by default to get symbols.

**Comment by blisstik** [comment]
If I run this manually, it runs on top of EmulationStation very slow with glitches but it does crash when running using runcommand on RetroPie

`/opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-reicast/reicast_libretro.so --config /opt/retropie/configs/naomi/retroarch.cfg "/home/pigaming/RetroPie/roms/naomi/Shikigami No Shiro II.bin" --appendconfig /dev/shm/retroarch.cfg`

**Comment by blisstik** [comment]
Retropie uses runcommand to execute `$COMMAND` which is the command above this comment.

Question - how can I run gdb on this line?

`eval $COMMAND </dev/tty &>>"$LOG"`

**Comment by blisstik** [comment]
I've noticed something in the logs. On the working one, the order is as follows

```
[INFO] Written to playlist file: /opt/retropie/configs/dreamcast/content_history.lpl
Creating dir: /home/pigaming/RetroPie/BIOS/dc/data
context_reset.
ARM VFP-Run Fast (NFP) enabled !
```

The non-working one changes the order of `context_reset.`

Can you maybe put it back in between

`Creating dir: /home/pigaming/RetroPie/BIOS/dc/data`

and

`ARM VFP-Run Fast (NFP) enabled !`?

Also just to throw this out there, the working one gets to creating the content_history prior to creating the dir

`[INFO] Written to playlist file: /opt/retropie/configs/dreamcast/content_history.lpl`

Below is the non-working. Notice the order of where `context_reset.` is

```
Creating dir: /home/pigaming/RetroPie/BIOS/dc/data
ARM VFP-Run Fast (NFP) enabled !
Linux paging: 00001000 00001000 00000FFF
MAP 00800000 w/ 25165824
MAP 20000000 w/ 25165824
MAP 04000000 w/ 16777216
MAP 06000000 w/ 16777216
MAP 0C000000 w/ 0
A8
vmem reserve: base: 911D0000, aram: b11d0000, vram: 951D0000, ram: 9D1D0000
Resetting mem
Mem alloc successful!Loaded /home/pigaming/RetroPie/BIOS/dc/dc_boot.bin as bootrom

Loaded /home/pigaming/RetroPie/BIOS/dc/dc_nvmem.bin as nvram

[libretro INFO] Using Recompiler
Sh4 Reset
recSh4 Init
Freeing fpcb
readm helpers: up to B16D0250

Session 1 has 1 track(s)
Saving  Track:  1  Type: Mode2/2336  Pregap: 150  Size: 57857   LBA: 0       
Track position: 350400

Session 2 has 1 track(s)
Saving  Track:  2  Type: Mode2/2336  Pregap: 150  Size: 289537  LBA: 69257   
Track position: 135854752
gdrom: Opened image "/home/pigaming/RetroPie/roms/dreamcast/Daytona USA (USA).cdi"

	 ARM7_TCB addr: 0xb29d0000 | from: 0xb29cf178 | addr here: 0xb29977c8
Initializing VMU data...
Initializing VMU data...
Initializing VMU data...
Initializing VMU data...
Sh4 Reset
reios: IP.bin is 'SEGA SEGAKATANA SEGA ENTERPRISES2BD2 GD-ROM1/1  JUE     2799A10 MK-51037  V1.00420010214        1ST_READ.BIN    themacN         DAYTONAUSA                                                                                                                      /home/pigaming/RetroPie/BIOS/dc/'
reios: Hardware ID is: SEGA SEGAKATANA 
reios: Maker ID is:    SEGA ENTERPRISES
reios: Device info is: 2BD2 GD-ROM1/1  
reios: Area symbols is: JUE     
reios: Peripherals is: 2799A10 
reios: Product number is: MK-51037  
reios: Product version is: V1.004
reios: Release date is: 20010214        
reios: Boot filename is: 1ST_READ.BIN    
reios: Software company is: themacN         
reios: Software name is: DAYTONAUSA                                                                                                                      
reios: loading ip.bin from FAD: 69407
reios: bootfile is '1ST_READ.BIN    '
reios: iso9660 PVD found
reios: iso9660 root_directory, FAD: 69430, len: 28672
Found 1ST_READ.BIN at 000065
filename len: 14
file LBA: 357660
file LEN: 2010720
[libretro INFO] [LUT]: Product number: MK-51037  .
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 44055.94 Hz.
[INFO] [Video]: Video @ 640x480
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [EGL] Falling back to eglGetDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [GL]: Found GL context: mali-fbdev
[INFO] [GL]: Detecting screen resolution 0x0.
[INFO] [EGL]: Created shared context: 0x6422d0.
[INFO] [EGL]: Current context: 0x5f5b60.
[INFO] [GL]: Vendor: ARM, Renderer: Mali-T628.
[INFO] [GL]: Version: OpenGL ES 3.1 v1.r12p0-04rel0.03af15950392f3702b248717f4938b82.
[INFO] [GL]: Using resolution 1920x1200
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Resetting shader to defaults ... 
[INFO] [GL]: Using 1 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Initializing HW render (1024 x 1024).
[INFO] [GL]: Max texture size: 8192 px, renderbuffer size: 8192 px.
[INFO] [GL]: Supports FBO (render-to-texture).
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[WARN] [udev]: Couldn't open any keyboard, mouse or touchpad. Are permissions set correctly for /dev/input/event*?
[INFO] [udev]: Plugged pad: HORI CO.,LTD. HORIPAD mini4 (3853:238) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event1) supports 0 force feedback effects.
[INFO] [Autoconf]: 2 profiles found.
[INFO] [autoconf]: selected configuration: /home/pigaming/.config/retroarch/autoconfig/HORI CO.,LTD. HORIPAD mini4.cfg
[INFO] [Joypad]: Found joypad driver: "udev".
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [Video]: Found display server: null
[INFO] Found shader "/home/pigaming/.config/retroarch/shaders/bilinear.glslp"
[INFO] Found shader "/home/pigaming/.config/retroarch/shaders/nearest.glslp"
[INFO] Found shader "/home/pigaming/.config/retroarch/shaders/slang-conversion-template.glsl"
[INFO] Found shader "/home/pigaming/.config/retroarch/shaders/stock.glsl"
context_reset.
```

**Comment by flyinghead** [comment]
Run it directly. Something like:
```
gdb --args /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-reicast/reicast_libretro.so "/home/pigaming/RetroPie/roms/dreamcast/Daytona USA (USA).cdi"
```

**Comment by blisstik** [comment]
Ran it and here's the output

`
Reading symbols from /opt/retropie/emulators/retroarch/bin/retroarch...(no debugging symbols found)...done.`

If I ran it via terminal, the game will load on top of emulationstation but very slow, like its fighting for which video is on top.

If I kill emulationstation, then run it via terminal, the game will load and run normally but I lose the functionality of exiting out and running a diff game or system.

If I run it via emulationstation, RetroPie uses [runcommand.sh](https://github.com/Retro-Arena/RetroPie-Setup/blob/master/scriptmodules/supplementary/runcommand/runcommand.sh) on line 1008 as `eval $COMMAND </dev/tty &>>"$LOG"` where the logs show it segfaults.

What I'd like to do is modify runcommand.sh with `gdb` so it outputs it to a log but `gdb --args` didn't even work via terminal.

**Comment by flyinghead** [comment]
You would probably have to recompile the core with symbols (-g) to get a meaningful stack trace from gdb.

The fact that it's working fine if you run it manually probably means that emulationstation is passing arguments / config files that make it crash. I would try to find out what it is. There have been recent changes in the controllers/input code so it could be in that area.

**Comment by blisstik** [comment]
If I fork for testing, where would I change the `context_reset.` so it is run after creating the directory?

```
Creating dir: /home/pigaming/RetroPie/BIOS/dc/data
context_reset.
ARM VFP-Run Fast (NFP) enabled !
```

**Comment by flyinghead** [comment]
Not sure I understand. context_reset is called to initialize the Open GL context so it doesn't care about the BIOS directory.
You shouldn't have to change anything in the code.

**Comment by blisstik** [comment]
I compiled a2214fc (save states v3) and this is where the issue began. If I replace the libretro.cpp from 127f845 (linked below), it resolves the issue. There were a ton of changes on this file so not sure what from old file fixed it.

https://github.com/libretro/reicast-emulator/blob/127f8458bf8cb7817bf1e90349f16664f11240db/core/libretro/libretro.cpp

**Comment by flyinghead** [comment]
So the crash is due to the change of when dc_init() is called.
It would really help to have a gdb stack trace with symbols. Also compiling without #defining RELEASE or NDEBUG could increase the level of logging.

**Comment by blisstik** [comment]
I've been compiling to see which will work with the least amount of code changes. Here's what worked for the XU4. I did not test any other games.

Works fast (fps) for Shikigami No Shiro II
https://github.com/6alileo/reicast-emulator/commit/c317b82197d3ae078643eeb734b016fdf734df6a

Works slow (fps) for Shikigami No Shiro II
https://github.com/6alileo/reicast-emulator/commit/26324122ec0edca4382546a42b63673639072cef

**Comment by flyinghead** [comment]
All this points to a problem due to the dc_init() change but we need to understand why it's failing on this platform.

**Comment by blisstik** [comment]
Yeah I need help on compiling so I can get you a debug log. Is it a flag I add on the make command?

________________________________

**Comment by blisstik** [comment]
So do I modify the makefile like?

CFLAGS += -g -mcpu=cortex-a15 -mtune=cortex-a15.cortex-a7 -mfpu=neon-vfpv4 -mvectorize-with-neon-quad

________________________________

**Comment by flyinghead** [comment]
Build with `make DEBUG=1`
That should be enough.

**Comment by blisstik** [comment]
OK, I've compiled with `make DEBUG=1 platform=odroid BOARD="ODROID-XU3" ARCH=arm` and ran the gdb command above. [See this photo](https://ibb.co/b4qw7f)

**Comment by flyinghead** [comment]
Then type the following commands in gdb:
```
handle SIGSEGV nostop noprint
run
```
Wait for the crash, then:
```
bt
```
and report.
Thanks

**Comment by blisstik** [comment]
I launched a diff game and removed any spaces to avoid using quotes. I was able to run it on terminal via 

`/opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-reicast/reicast_libretro.so --config /opt/retropie/configs/atomiswave/retroarch.cfg /home/pigaming/RetroPie/roms/atomiswave/JamboSafari.bin`

Then do `gdb --args ...` then `handle ...` then `run` and it just stops. See below.

```
pigaming@odroid:~$ gdb --args /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-reicast/reicast_libretro.so --config /opt/retropie/configs/atomiswave/retroarch.cfg /home/pigaming/RetroPie/roms/atomiswave/JamboSafari.bin
GNU gdb (Ubuntu 8.2-0ubuntu1~16.04.1) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/retropie/emulators/retroarch/bin/retroarch...(no debugging symbols found)...done.
(gdb) handle SIGSEGV nostop noprint
Signal        Stop      Print   Pass to program Description
SIGSEGV       No        No      Yes             Segmentation fault
(gdb) run
Starting program: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-reicast/reicast_libretro.so --config /opt/retropie/configs/atomiswave/retroarch.cfg /home/pigaming/RetroPie/roms/atomiswave/JamboSafari.bin

[11]+  Stopped                 gdb --args /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-reicast/reicast_libretro.so --config /opt/retropie/configs/atomiswave/retroarch.cfg /home/pigaming/RetroPie/roms/atomiswave/JamboSafari.bin
```

**Comment by blisstik** [comment]
Just to add to this - I even compiled retroarch using `make DEBUG=1 GL_DEBUG=1` and it outputted `(no debugging symbols found)`

**Comment by flyinghead** [comment]
I don't get it. Why would it stop?
Are you pressing ctrl+Z? Running in the background with `&` ??

**Comment by blisstik** [comment]
Yeah that's puzzling for me too. I didn't press anything on keyboard or have it running in the background. It also happens instantly as soon as I enter the run command, it stops right away.

**Comment by flyinghead** [comment]
Are you sure /opt/retropie/emulators/retroarch/bin/retroarch is not a shell script? Now that you mention it I remember there is that runcommand script on Retropie that redirect inputs. It must be getting in the way.

**Comment by blisstik** [comment]
Yes I'm sure it's not a shell script. Runcommand is a shell script that gathers different paths and puts into a single long command to launch the game. The configs from emulationstation are not passed along. RA has its own config files.

The only thing I've noticed is when `context_reset.` is called earlier rather than later, it works.

Could you maybe explain why there's only 1 dc_init after dc_prepare_system()? What is working for this platform is the two diff dc_init codes earlier in the code.

https://github.com/6alileo/reicast-emulator/commit/c317b82197d3ae078643eeb734b016fdf734df6a

**Comment by flyinghead** [comment]
My guess is retroarch is trying to open the console tty input or something like that and it's stopped because there's already a shell on this tty.
The dc_init function was previously called when the emulator was starting (either in retro_run or in the emulator thread depending on whether threaded rendering is on)
This causes problems when save state are loaded very early (auto save state) because dc_init does some unconventional things with memory at startup.
It is now called in retro_load_game, before the game starts.

**Comment by blisstik** [comment]
Hi @flyinghead - would it help if I sent you an XU4 board and power supply? If you could, please DM me on Discord using the same name here `@6alileo`

**Comment by flyinghead** [comment]
I can't find you either in the retroarch or reicast Discord servers. Can you @mention me there?

**Comment by blisstik** [comment]
Hi there - I have an idea. Would it be possible to create a flag called `LAZYLOAD` or something to that nature where if it set to `LAZYLOAD=1` it would compile `libretro.cpp` as below?

https://github.com/6alileo/reicast-emulator/commit/c317b82197d3ae078643eeb734b016fdf734df6a

I have tested it, even with the mame m2 updates and it works

**Comment by blisstik** [comment]
Something in emulationstation caused this crap.

**Comment by ficoos** [comment]
I'm hitting the same problem, what was it you had to change in emulationstation?
