### ISSUE TITLE
Start Button Opens Service Menu

### ISSUE THREAD

**Issue by newoski** [libretro/flycast#369]
Currently, there doesn't seem to be a way to disable the Start button -- both via Keyboard and Gamepad -- from pulling up the Service Menu, while the BIOS image is on screen. This creates a real problem with button-happy users

Any way to decouple the Service Menu trigger from the Start button?

**Comment by flyinghead** [comment]
I don't know why this happens. Reicast doesn't mix the Start and Service buttons, yet pushing the (P1) Start button opens the service menu at boot.
I don't know how a real Naomi arcade cabinet works and I couldn't find any information on that particular point.

**Comment by newoski** [comment]
In my testing, Demul seems to have a built-in function where it ignores user inputs during the boot/bios screen. Not sure if this could be implemented to core/core options?

**Comment by blisstik** [comment]
@newoski  - Does this happen on DC games only?

**Comment by newoski** [comment]
@6alileo I've only seen it on arcade games (atomiswave2naomi)

**Comment by newoski** [comment]
I believe this can be closed. Looks like the Service button has been remapped to L3 now, instead of Start?

**Comment by flyinghead** [comment]
This is still happening.
Start was never mapped to Service but for some reason BIOS version g and h open the test menu when pressing Start during boot.
This doesn't seem to appear with earlier BIOS versions.
