### ISSUE TITLE
Sega Marine Fishing Logo not there on StartScreen

### ISSUE THREAD

**Issue by TradeDraft** [libretro/flycast#37]
Comes up like this:

https://s5.postimg.cc/5vpyjfymf/Sega_Marine_Fishing_v1.001_2000_Sega_NTSC_US_-180610-0514.png

as I made Screenshot from Demul:

https://s5.postimg.cc/jpeb8jonr/Sega_Marine_Fishing_Logo_Working.jpg

Just letting you know about this

**Comment by inactive123** [comment]
Weird - both Reicast and Reicast OIT render this properly for me -

![image](https://user-images.githubusercontent.com/1075274/41201929-7804b1be-6cc1-11e8-98a1-b780980ee1d8.png)


![image](https://user-images.githubusercontent.com/1075274/41201911-16b0d974-6cc1-11e8-8947-c4c2b0630f56.png)

What is your GPU, what OS are you running, etc?

**Comment by TradeDraft** [comment]
Using Windows 10 and It's either GeForce 1080 or 1080ti(Can't Think Top of my Head which One)

**Comment by TradeDraft** [comment]
Still have the Problem

**Comment by TradeDraft** [comment]
Hopefully this New Extra Depth Scale Report makes it easier for you guys to fix this Problem

**Comment by flyinghead** [comment]
This should be fixed. Reopen as needed.
