### ISSUE TITLE
Player 3 & 4 Controls Don't Work

### ISSUE THREAD

**Issue by newoski** [libretro/flycast#372]
I just tested Guilty Gear Isuka. Can't get the P3 and P4 controls working via RetroPad or Keyboard

**Comment by blisstik** [comment]
Isn't this a 2P game only?

**Comment by newoski** [comment]
![ggisuka-181102-153952](https://user-images.githubusercontent.com/13788074/47936919-99779d00-deb5-11e8-99cc-9a5f9ac02f10.png)

This is what I'm seeing

( :

**Comment by flyinghead** [comment]
By default there's only a 2-player I/O board connected to Naomi games. Power Stone 2 has a special setting to use a 4-player I/O board.
So we need a new core option to add a second 2-player I/O board as an option.

**Comment by newoski** [comment]
Was this fixed? Latest blog post seems to imply second I/O board has been added?

**Comment by flyinghead** [comment]
There was a fix for Ring Out 4x4. Not for this game yet.

**Comment by flyinghead** [comment]
The AW version of Guilty Gear Isuka now supports 4 players by default with the latest core

**Comment by newoski** [comment]
Can this be applied to the lst/bin format, as well? Doesn't seem to work, currently

**Comment by blisstik** [comment]
I don't think it'll work on the bin as that is naomi converted. Please test using the mame version.

**Comment by newoski** [comment]
Ok, MAME ROM is already tested and working. Closing issue
