### ISSUE TITLE
Service Menu Doesn't Respond to Inputs

### ISSUE THREAD

**Issue by newoski** [libretro/flycast#373]
The only thing I'm able to do, using both RetroPad and Keyboard, is to essentially exit back to the game. Attempts to navigate the menu are completely unresponsive

**Comment by flyinghead** [comment]
Make sure you enable the "Allow Naomi service buttons" core option. To navigate the service menu you need the Service and the Test buttons.

**Comment by blisstik** [comment]
@newoski - please test and close if resolved. I think you just forgot to enable the ALlow Naomi service buttons in RetroArch RGUI
