### ISSUE TITLE
Audio Stutters on Capcom vs. SNK 2 [non-OIT] [naomi]

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#375]
Using the XU4, I compiled using the latest 01ab59e and ran it by killing emulationstation and running the command manually so it would launch.

With threaded emulation ON, the game has stuttering audio during character selection screen.

If someone can verify if this happening on Android as well.

**Comment by ghost** [comment]
Core at the same revision number as yours, 01ab59e, and I hear no audio stuttering on the character select screen of CvS2 on an Nvidia Shield 2017 running Android.

**Comment by blisstik** [comment]
No longer happening after increasing audio buffer to 2048
