### ISSUE TITLE
Blocking simutaneous opposite directions keys?

### ISSUE THREAD

**Issue by raidenii** [libretro/flycast#376]
Is it possible to implement the feature that inputs of simultaneous opposite directions (e.g., left+right, up+down) get filtered? Specifically, Metal Slug 6 suffers from the bug that pressing left+right+fire leads to game crash, and seems that no DC emulators has input processing regarding this.

MAME does have this implemented ([https://github.com/mamedev/mame/blob/master/src/emu/ioport.cpp](url)), as follows:

```
// lock out opposing directions (left + right or up + down)
if ((m_current & (UP_BIT | DOWN_BIT)) == (UP_BIT | DOWN_BIT))
	m_current &= ~(UP_BIT | DOWN_BIT);
if ((m_current & (LEFT_BIT | RIGHT_BIT)) == (LEFT_BIT | RIGHT_BIT))
	m_current &= ~(LEFT_BIT | RIGHT_BIT);
```

Thanks!

**Comment by blisstik** [comment]
@raidenii - can you please test and close if its working?

**Comment by raidenii** [comment]
My bad - GitHub didn't send me a notification regarding this issue and I forgot to check about this. Tested 1119a9e and it's working! Thanks so much!
