### ISSUE TITLE
Reicast Naomi

### ISSUE THREAD

**Issue by telanus** [libretro/flycast#379]
tried running crazi taxi (naomi) on reicast using retroarch' gui, did a build this morning and getting this error, not sure what I'm doing wrong

```
This track seems truncated. Skipping...
Unsupported format: Could not find the track start markUnsupported format: Could not find the track start markUnsupported sector sizeUnsupported format: Track mode not supportedSaving  Track: 27874  Type: Mode2/2048  Pregap: 3726364429  Size: 300359168  LBA: 179467027
```

if I load it from terminal like: retroarch -L /Games/retroarch/cores/reicast_libretro.so "/Games/Romz/naomi/crzytaxi.zip"
it gives:
```
Linux paging: 00001000 00001000 00000FFF
MAP 00800000 w/ 50331648
MAP 20000000 w/ 50331648
MAP 04000000 w/ 33554432
MAP 06000000 w/ 33554432
MAP 0C000000 w/ 0
A8
vmem reserve: base: AD720000, aram: cd720000, vram: B1720000, ram: B9720000
Resetting mem
SIGSEGV @ 0x7fbeec38d105 (signal_handler + 0x0x1e3c91c5) ... 0x7fbecd71e408 -> was not in vram
[libretro INFO] Fatal error : segfault
 in signal_handler -> core/libretro/common.cpp : 394 
DEBUGBREAK!
SIGSEGV @ 0x7fbecdfc34b7 (signal_handler + 0x0xfffffffffffff577) ... 0x7fbecdfc34b7 -> was not in vram
[libretro INFO] Fatal error : segfault
 in signal_handler -> core/libretro/common.cpp : 394 
DEBUGBREAK!
```

**Comment by flyinghead** [comment]
Are you sure you are running the latest code? It seems zip files are not recognized as such here.

**Comment by telanus** [comment]
Yes I'm certain: 

```
~/src/libretro/reicast-emulator$ git pull
Already up to date.
```

![screenshot_20181105_173105](https://user-images.githubusercontent.com/19357986/48007597-a9df8000-e120-11e8-95f1-8b04143f6fd7.png)

**Comment by flyinghead** [comment]
Commit 31c1caf dates from Aug 2nd but it shows ZIP as a supported extension...
Did you do a make clean first?

**Comment by telanus** [comment]
> Did you do a make clean first?

Yes, downloaded the source now three times, and each time it compiles to that commit.. Really don't get this, also the buildbot seems to build to that commit
