### ISSUE TITLE
Problem in the Wacky Races Menu

### ISSUE THREAD

**Issue by Deivmsr** [libretro/flycast#381]
The menu view of the game Wacky Races in gdi format is buggy.
Reicast libretro commit 8334be9
![screenshot_20181106-124911](https://user-images.githubusercontent.com/40547165/48073210-0f814a00-e1bd-11e8-9752-9c94e85ca2e9.jpg)
![screenshot_20181106-124929](https://user-images.githubusercontent.com/40547165/48073211-0f814a00-e1bd-11e8-9113-486f1c8753e0.jpg)

**Comment by flyinghead** [comment]
Should be fixed by https://github.com/libretro/reicast-emulator/commit/c619a7f5c8991ce5d52a63965ef4db1aa047345e

**Comment by Deivmsr** [comment]
Ok. The problem is fixed really. Thanks.
