### ISSUE TITLE
Reicast Android (NVIDIA SHIELD TV, non-OIT) performance regression

### ISSUE THREAD

**Issue by kikeminchas** [libretro/flycast#385]
I had briefly tried Reicast with RA 1.7.4 end of August. All games I tried were running full speed AFAIR at default Internal Resolution (640x480) on a Nvidia Shield TV. Latest RA and Reicast Core doesn’t seem to run almost any game full speed… Not sure if my memory is betraying me but i was pretty sure Crazy Taxi was full speed. Now , start an arcade game, gets me around 40-50 fps, depending on scene, music skipping like crazy. Threaded rendering increases speed and fixes music but seems to introduce lots of frameskipping so game is not smooth at all.

Just for my peace of mind, I tried Reicast standalone r8.1 with the same game. Fullspeed with room to spare and smooth (synchronous rendering activated), disabling frame limit, makes the game fly at 2 times the normal speed or more … Not sure what is wrong with Reicast Core in RA. Updated core again and deleted all settings to make sure everything is default, still too slow…

I realize that the latest improvements in Reicast core could introduce a performance penalty. The difference though is in the dozens of frames. Is this really expected?

**Comment by MastaG** [comment]
Thats exactly what I'm facing as well on my XU4 running linux.
I've compiled RetroArch and reicast rom the latest git rev and I'm using the gbm drivers (running retroarch from shell).
Without reicast' threaded renderer its indeed 40-50FPS and with the threaded renderer enabled its fullspeed with massive frameskipping and not fluent at all (sometimes too fast).

**Comment by inactive123** [comment]
Reicast standalone doesn't have a bunch of GPU features emulated that libretro does, unless you're talking about the flyinghead branch (which I don't think it is).

@flyinghead any thoughts here?

**Comment by flyinghead** [comment]
I'd be nice if you could test my branch with the same setup/game. You can get the latest APK here: http://builds.reicast.com/#fh/mymaster
This would help figuring out where the performance regression is (my branch or the libretro core, possibly both to various degrees).

**Comment by kikeminchas** [comment]
@flyinghead , I have tried the latest build from your branch:

https://github.com/reicast/reicast-emulator/commit/fb92d8d

I have used Crazy Taxy (in gdi format) for the test, the same as I was using before, just select arcade and measure performance in the first scenario. All options in Reicast are as default, apart from Synchronous Rendering which I set to ON (this I believe is the same as setting Threaded Rendering OFF in the libretro core).

Your branch is full speed and smooth with this settings in this game (in libretro, it hovers around 40-50 fps) so I disabled FPS limit and tried to compare the max frames it would reach in both reicast master and your master. Problem is that the FPS counter is broken, at least in the SHIELD I only see 'XX'' so it is difficult to compare. I used a stopwatch to check how long it takes in real time for the game seconds counter to go over 10 seconds. In both branches it takes in between 6-7 seconds, which means the game is running 30-40% faster than expected without FPS limit. It is possible that your branch is slightly slower but it's difficult to say because of the inacurate nature of manually using a stopwatch...

So with your build, reicast standalone is still much faster than the libretro core and not significantly slower than reicast master, at least with the game and the scenario I tried in both retroarch and reicast. Does your branch contain all additions to the GPU features that are present in libretro?

If you see something on my testing that doesn't make sense to you or you want me to test something else let me know...

**Comment by flyinghead** [comment]
Thanks a lot for this information. This is very helpful.

The upstream FPS counter is updated at a very low rate, but it normally displays a value if you wait long enough. It may be broken though.

To answer your question, my branch has all the GPU additions that the libretro core has. However, the libretro core has an inherent overhead compared with the standalone emulator. This happens with all cores, not only reicast.
It also has a number of additional features such as support for Naomi and AtomisWave arcade games in the same core, and dynamic switching between native and generic dynarec. These features may have an impact on performance, and could perhaps be optimized.

**Comment by kikeminchas** [comment]
The tests I performed lasted for a minute or so but the FPS counter always showed 'XX'.
I also realized that in the standalone Reicast, there is no way to change the Internal Resolution (latest beta master has an option to set 640x480 but doesn't work on the Shield). As far as I can see, it seems to be outputting to Android's native resolution (in my case 1080p), could you confirm this?. All tests I have performed with the libretro core were at 640x480. Bumping the resolution to 1080p like reicast standalone supposedly uses, gives a 5-10 fps drop in the same testing scenario I'm using. The difference in performance in this case is even bigger than I thought.

Thanks for the confirmation regarding the GPU additions, it is nice that even with those Reicast standalone performs well on the Shield, pity about the libretro core though, I like the idea and convenience of having all emus under a common framework... 

Something probably stupid but you mentioned that libretro switches in between native and generic dynarec, is it possible that it could choose the wrong one? In core options I just see 'dynamic recompiler'.

**Comment by flyinghead** [comment]
Upstream reicast outputs at the native resolution of the device and writes directly to the screen.
The reicast core lets you choose the resolution at which the game is rendered (640x480 by default), and this output is then upscaled (and optionally filtered), overlays/OSD are drawn and the result is displayed on the screen. All these operations have a cost even though the game is rendered at a lower resolution.

The options of the CPU Mode setting are a bit misleading. A more accurate description would be "native recompiler" (instead of dynamic) and "generic recompiler". I doubt the core would pick the wrong one but you're welcome to try the generic recompiler to check that performance decreases as it should.

We've been adding many many features to the reicast core lately and performance hasn't been the top priority so it's not surprising that it dropped on some platforms. There's certainly room for optimization here and there to improve it.

**Comment by kikeminchas** [comment]
OK, thanks flyinghead. I cannot select any option in CPU mode, just 'dynamic recompiler'. 

I guess I will stay with upstream Reicast and keep an eye on the libretro core :) then.

**Comment by srk15372** [comment]
Hi, I note the same behaviour. I was able to play fullspeed atomiswave games on august 2018.
I have just update the core and now it's really slow on shield tv android.
Hope you could apply some optimisation as before to your marvelous work and core.  thanks

**Comment by flyinghead** [comment]
After some investigation it appears that upstream's "Synchronous Rendering" option is not the same as running the libretro core with Threaded Rendering off. 

I have backported this option from upstream so that a fairer comparison can be made. See this commit 01ffff9facb9b970ac2a7c5336fd1bf301e386f7.

I have noted much less frame skipping with this option on, depending on the game and host platform. 

**Important**: both Threaded Rendering and Synchronous Rendering must be enabled.

**Comment by kikeminchas** [comment]
Thanks flyinghead, I will try as soon as a new build for Android is ready. So if I understand correctly Threaded rendering is always active in upstream and this 'Synchronous rendering' is a separate option that was not present in libretro?

**Comment by flyinghead** [comment]
Exactly

**Comment by kikeminchas** [comment]
so I have tried again the same game (Crazy Taxi [USA]) and I can confirm that with both options active, Threaded Rendering + Synchronous Rendering the game is still not full speed in most areas (you can see the FPS counter almost never reaches 60 fps) but the frame skipping has been reduced quite a bit indeed so game is much less choppy, good news!

I have tried then some other options that didn't seem to make a noticeable change (at least not bring the game to full speed) before and if I set the Alpha Sorting to 'per strip' + the 2 options mentioned above, the game is 60 fps, totally smooth! This is a very similar experience to upstream so I wonder if upstream is using 'per strip' by default?

Thanks a lot again for looking into this! I know you have been busy adding lots of features and game support lately, hope you will still have some time in the future to get into further optimizations to help us, users of lesser systems ;-) 

@srk15372 , maybe you want to try again your Atomiswave games with the 2 options above on and confirm you also see an improvement?

**Comment by srk15372** [comment]
hi thanks for the update unfortunaly after activated the 2 options, games doesn't load anymore.
will wait for some revisions  thanks

**Comment by kikeminchas** [comment]
That's weird, i am going through my (admitedly small) collection and all are booting fine for the moment. Do you have input polling set as 'early'? This is needed when threaded rendering is activated. I don't have any Atomiswave game yo try at this moment. Which one are you trying in particular?

**Comment by flyinghead** [comment]
Closing as inactive
