### ISSUE TITLE
[Request] Crosshair for lightgun input

### ISSUE THREAD

**Issue by cubatilles** [libretro/flycast#386]
Hi,

Now that Reicast supports lightgun emulation for both Dreamcast and Naomi games, it would be great to add a crosshair option on the core (just like others cores like beetle-psx, bettle-saturn...).

Right now you can aim and shoot with mouse, but you never know where are you aiming at, unless you use your system mouse pointer for reference. I think a crosshair should be drawn on the screen.

Greetings.

**Comment by blisstik** [comment]
What's your setup? So does mouse aiming work for you?

**Comment by cubatilles** [comment]
Yes, mouse aiming works for me as expected. I'm not complaining about a bug or problem on my setup, this is a request. I think the core should have a crosshair (just like other cores for systems supporting lightgun games) for lightgun games like confidential mission or house the dead. The way it is now you have to depend on your mouse cursor as there is no crosshair drawn on the screen. Maybe some people don't care, but I think the mouse pointer on Windows is too small on high resolutions to use it as a crosshair.

**Comment by blisstik** [comment]
I get that. I was wondering what your environment is because I can't get mouse to work on mine so I was curious about that.
________________________________

**Comment by cubatilles** [comment]
Oh well, I'm using the reicast core on RetroArch 1.7.5 for windows. Windows10 Pro as OS. Nvidia GTX970 with latest stable drivers.  For getting mouse to work as lightgun, I've just setup Lightgun as the controller device on RA's core controller option. I'm not using the latest core, though, it's a core build from about a month ago. Mouse' left button is the gun trigger.

**Comment by hiddenasbestos** [comment]
Hey @cubatilles , I've implemented your request in #531

**Comment by cubatilles** [comment]
Wow, thank you so much @hiddenasbestos. I'll test when I get home. Thanks so much!!

**Comment by cubatilles** [comment]
Hi @hiddenasbestos , I've updated reicast core on RA to try your crosshair implementation, but I'm unable to find any option to enable it. Seeing #531 seems like it hasn't been merged yet?

**Comment by hiddenasbestos** [comment]
Yes, that's right @cubatilles - I'm not able to merge, only submit patches. I think it's still being reviewed.
All you can do at this stage is grab the patched source and build it yourself, it won't be on the build server.
