### ISSUE TITLE
nvmem2 Issues

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#391]
I noticed that nvmem and nvmem2 files are created AFTER exiting RetroArch. Certain games with nvmem2 files will not boot and will get stuck on gray "notice" screen. 

If the nvmem2 file is deleted prior to launch, the game will work, but then the nvmem2 file gets recreated at each exit.

- demofist
- fotns
- kofxi
- kov7sprt
- waidrive

**Comment by flyinghead** [comment]
I can't reproduce this on linux x64 with any of the specified games (I haven't tried kov7sprt).
Could it be specific to odroid?

**Comment by blisstik** [comment]
I've dug a little deeper on this. Here's what I found. It may or may not be specific to the Odroid XU4.

I've found 3 unique conditions if NVMEM2 file exists:

**Case 1**
If nvmem2 file exists, roms below **loads**; I'm able to go into the SERVICE menu, change some settings (i.e., Coin Assignments to Free Play) and Exit successfully. The game will reload with the updated configuration. But, upon reloading the game a second time, the updated configuration goes back to default settings. Does AW normally delete backup data file on boot as stated by the gray "notice" screen?

- dolphin 
- maxspeed
- rumblef 
- rumblef2

**Case 2**
If nvmem2 file exists, roms below **loads**; I'm able to go into the SERVICE menu, change some settings (i.e., Coin Assignments to Free Play) and will freeze upon Exit

- basschal
- claychal
- ftspeed 
- ggisuka 
- ggx15   
- sprtshot
- xtrmhunt

**Case 3**
If nvmem2 file exists, roms below will **not load** and freeze on "Notice - All Backup Data Has Been Cleared" message

- demofist
- dirtypig
- fotns   
- kofxi   
- kov7sprt
- mslug6  
- ngbc    
- rangrmsn
- samsptk

**Comment by Tatsuya79** [comment]
WIn7 x64 here, I tried launching again fotns and samsptk and they worked fine despite nvmem2 already there.
They even remembered the number of credits previously inserted.

**Comment by blisstik** [comment]
Thanks. I figured out the issue and it was something in emulationstation.
