### ISSUE TITLE
AW Screen Orientation

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#392]
By default, the following games boot vertically. If these are set in Options -> Screen Orientation -> Vertical, then the game config is saved, upon reboot, the game will freeze or gets stuck in the "Notice" screen.

I've compiled RetroArch to the latest master branch.

- anmlbskt
- blokpong
- waidrive

**Comment by flyinghead** [comment]
I suppose this is the same issue as #391. The screen orientation setting is saved in the nvmem2 file.

**Comment by blisstik** [comment]
Are all of the TEST menu items saved on `nvmem2` file?

**Comment by flyinghead** [comment]
I believe so

**Comment by blisstik** [comment]
I also noticed when going into TEST menu then saving the settings, it will freeze for other games. I'm closing this one as it looks like its related to nvmem2 issue that is already opened.
