### ISSUE TITLE
orangepi problems to run

### ISSUE THREAD

**Issue by Liontek1985** [libretro/flycast#394]
Hello Guys

I have problems to run reicast with accelaration in libretro
All the other emulators have 3d accelaration in retroarch

I have make the emulator with "platform= classic_armv7_a7"
I can run the emulator with retroarch, the performance is very slow and the image looks like software rendering

i know the classic_armv7_a7 is for nes,snes classic mini the consoles have the same cpu architecture and gpu like orangepi 

Have anyone a idea who is the problem?

best regards fredy

Distribution: armbian jessie
Board: Orange PI PC
CPU: Allwinner H3 (Cortex A7 Quad-Core) 
GPU: MALI400MP2
RAM: 1GB DDR3
Drivers: GL / SDL2 (GL set in retroarch)

**Comment by flyinghead** [comment]
The reicast core doesn't have a software renderer, so it's using Open GL ES and hardware 3D rendering.
I'm not familiar with the Orange Pi PC but it seems its performance is below what most dc games require.

**Comment by Liontek1985** [comment]
thx for your answer
when iam use reicast(non libretro) looks the image smooth and run like 25fps
with lr-reicast looks the image like zoomed pixels and run like 5fps...

i can make a picture or a video if you want

**Comment by flyinghead** [comment]
Make sure to enable Threaded Rendering in the core options.
By default the reicast core outputs at 640x480, the native dreamcast resolution. You can change it in the core options.
Upstream reicast outputs at the native resolution of your screen (or its window).

**Comment by Liontek1985** [comment]
Threaded Rendering its enabled!
i have tested more resolutions and video settings included 320x240 
no big change

need iam a special setting for sunxi-mali ?
the mali gpu supports OpenGL ES 2.0, need iam here a extra setting for make?

**Comment by flyinghead** [comment]
Again I'm not familiar with this particular platform. I don't think there's any compile option missing regarding GL ES 2 (or it wouldn't compile).

**Comment by kikeminchas** [comment]
@Liontek1985 , I don't know about the compiling options but regarding performance differences in between upstream and libretro you can have a read at the exchange in between flyinghead and myself at https://github.com/libretro/reicast-emulator/issues/385 . Unfortunately, it seems that libretro reicast is orders of magnitude slower than upstream at the moment, even if upstream renders at higher resolution. I cannot confirm if your compiled version is correct but you shouldn't expect similar performance in any case to upstream unfortunately...

**Comment by Liontek1985** [comment]
thx for the information
i have see a video who run the emulation on a snes classic on retroarch with a lot better performance

thanks for trying to help

**Comment by flyinghead** [comment]
You should get performance very similar to the SNES classic as it is basically the same AllWinner SoC.
I remember the driver / linux distrib being a mess with these chips. You should use one that uses the Mali proprietary closed-source drivers.

**Comment by Liontek1985** [comment]
the problem from the software rendering i have solved... its a retroarch setting

when iam set in retroarch "bilinear filtering" looks the picture smooth

the performance is now  better with threaded rendering! a littlebit slower than normal reicast not much


now i have the other problems
1.) drops, all minutes i have a drop like a video buffering

2.) no audio in emulator, all other retroarch ermulators have audio
**with threaded rendering enabled i have no sound! https://github.com/libretro/reicast-emulator/issues/258**

3.) Installation, when iam install reicast over the install script i become only a black picture and the game breaks me down to the menu without an error
when i am copy the core in retroarch core folder and iam load the core manualy i can play the games
the same error like here: https://github.com/libretro/reicast-emulator/issues/451
**solved -> retroarch setting, with default run the emulator**

4.)graphic glitches, many games have flickering textures

**Comment by flyinghead** [comment]
Assuming this is resolved. Reopen as needed
