### ISSUE TITLE
[Naomi] Cosmic Smash crashes when entering game test mode

### ISSUE THREAD

**Issue by flyinghead** [libretro/flycast#398]
MAPLE ERROR : DESTINATION NOT ON SH4 RAM 0x1A2040

**Comment by blisstik** [comment]
Also happens for `alpilot` and `alpilotj`

**Comment by blisstik** [comment]
- Verified 90512ba fixed Cosmic Smash
- Airline Pilots still crashes RA when entering test mode on Windows and XU4 (uses airlbios.zip)

**Comment by flyinghead** [comment]
Fixed by https://github.com/libretro/reicast-emulator/pull/409
