### ISSUE TITLE
(Naomi) Support for Namco roms

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#399]
There is regression on Gun Survivor 2 – Biohazard – Code: Veronica. It boots past the naomi logo then gets stuck on a black screen. This happens for both Windows 10 x64 and Odroid XU4.

Workaround: use the BIN version of Gun Survivor 2 – Biohazard – Code: Veronica with MD5 below:
58536E653B866F0945AA10DFA5DB1BFD

Also, it would be great to have support for Mazan, Ninja Assault and World Kicks.

```
Namco
--------------------------------------------------------------------------------------------------------------
gunsur2     M2    pass bios epr-21577h.ic27 (US),      working!
mazan       M2    pass bios epr-21577h.ic27 (US),      working! (use lightgun/mouse for controls)
ninjaslt    M2    pass bios epr-21577h.ic27 (US),      working!
toukon4     M2    pass bios epr-21576h.ic27 (JP),      working!
wldkicks    M2    pass bios epr-21577h.ic27 (US),      working! (control issues, may crash during gameplay)
```

**Comment by flyinghead** [comment]
I don't recall being able to run gunsur2.zip. To my knowledge only the decrypted .bin works.

**Comment by flyinghead** [comment]
I got Ninja Assault to boot after fixing the rom layout (the one in mame is incomplete).
This game checks for a particular Namco JVS I/O board at startup. After faking it, the game seems to work (coin, start, test menu) but no gun trigger so far.

**Comment by blisstik** [comment]
I see, I didn't know Gun Survivor bin was decrypted and the mame one isn't. Regarding Ninja Assault, maybe the controls issue is similar to House of the Dead 2. Awesome work as usual.

**Comment by flyinghead** [comment]
M2 carts needed a bit more work. This should fix it: https://github.com/libretro/reicast-emulator/pull/400
mazan, ninjaaslt and wldkicksj now boot.
mazan and ninjaaslt both use very specific I/O input boards so more work is needed in this area.
I haven't checked wldkicksj controls yet.

**Comment by blisstik** [comment]
I updated my findings in the first post. Summary below.

- Ninja Assault is working!
- Mazan is passing bios then going into an "I/O PCB" error
- Gun Survivor 2 is passing bios then black screen
- World Kicks is passing bios then black screen

**Comment by blisstik** [comment]
Updates:
- Resident Evil now boots using WinCE and master branch
- World Kicks now boots with controls and crash issues

**Comment by barbudreadmon** [comment]
With the "basic" emulation of naomi comm board, i think "Gun Survivor 2" is also working properly with the mame rom now (that stuff might only be on the wince branch atm though).

**Comment by flyinghead** [comment]
Reopen issues for mazan or wldkicks as needed
