### ISSUE TITLE
(Request) Fix saves and add save states support

### ISSUE THREAD

**Issue by orbea** [libretro/flycast#4]
Can someone with the proper skill set hook up the save and save state features for the reicast core? Needless it would make this core far more attractive as well as improve bug testing and enjoyment.

Thanks!

**Comment by ghost** [comment]
Whut.
I thought it fucking worked.

**Comment by inactive123** [comment]
Nope, no savestates, lulz. Usually the first thing you'd add in an emulator. Hell, it might have been actually debuggable then instead of having to sit through Shenmue 1's 5/10 minute intro all the time only for it to crash later :(

But yeah, it'd require quite a bit of work. Hopefully we can pull it off.

**Comment by ghost** [comment]
No fucking saves at all? Must nulldc be rewrote again?

**Comment by inactive123** [comment]
true story - even nulldc didnt have it.

**Comment by ghost** [comment]
Wow...just wow....

**Comment by orbea** [comment]
Apparently saves do work and I just did not know the work around to fix the emulated memory card.

This can be done with:
1. Start a game with Reicast.
2. Open the core options, they can be found in the RetroArch quick menu.
3. Enable `Boot to BIOS (restart)`, then close and restart the emulator.
4. In the Dreamcast bios menu select 'File' and reformat the memory card.
5. Open the core options again and disable `Boot to BIOS (restart)`.
6. Now close and restart Reicast to enjoy a working memory card.

Thanks to @bparker for letting me know how to do this.

**Comment by RetroSven** [comment]
@twinaphex another dupe that can probably be closed now

**Comment by orbea** [comment]
Save states still don't work here, it just says "This core does not support save states." Is there something I am missing?

**Comment by RetroSven** [comment]
you need to pull from a nightly build or compile yourself

**Comment by orbea** [comment]
Yes, I built the git master last night and am currently on commit f425920.

**Comment by orbea** [comment]
@RetroSven Apologies, it must of picked an old core without me realizing. I updated the buildbot again and then explicitly loaded my own build from the command line and found creating and loading states works now!

Thanks a lot!
