### ISSUE TITLE
NAOMI: P1+P2 Control Mapping Issues

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#411]
Using Mame rom for 18 Wheeler (18wheelr.zip)

Going into TEST menu, I/O test, the following buttons can NOT be mapped. Shift H is available in RetroArch Controls but is not responsive.

- Shift L
- Shift H
- Shift R

Workaround: use Dreamcast version

**Comment by flyinghead** [comment]
This game mixes digital inputs from player 1 and 2 so it needs some more work on the core side.

**Comment by flyinghead** [comment]
Jambo Safari: unable to map the Lever Up and Lever Down buttons.
Virtual On: unable to map right lever (P2 dpad)

**Comment by blisstik** [comment]
Thank you for fixing this!
