### ISSUE TITLE
jambo Control Mapping Issue

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#412]
Using Mame rom for Jambo Safari (jambo.zip)

Going into TEST menu, I/O test, I'm unable to map the Lever Up and Lever Down buttons. These are the buttons used to try to capture the animals.

**Comment by flyinghead** [comment]
This game mixes digital inputs from player 1 and 2 so it needs some more work on the core side.

**Comment by flyinghead** [comment]
closing in favor of #411
