### ISSUE TITLE
alienfnt Always Rotating

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#413]
Using Mame rom for Alien Front (alienfnt.zip)

The game boots and runs but once the gameplay starts, it is always rotating to the right automatically without pressing any buttons on the controller.

Workaround: use Dreamcast version

**Comment by flyinghead** [comment]
This is due to your analog axes not being properly mapped or calibrated.
Alien Front uses 3 digital axes:
WHEEL (full axis)
RIGHT PEDAL (half axis)
LEFT PEDAL (half axis)
You should map the pedals on the L/R triggers and make the calibration in the game test menu.
