### ISSUE TITLE
(Naomi) vtennis and vtennisg Gameplay Crashes

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#416]
Using Mame rom for Virtua Tennis: M2 version (vtennis.zip) and GD version (vtennisg.zip)

Both versions of Virtua Tennis crash RetroArch during gameplay.

Workaround:
- use Dreamcast version of Virtua Tennis
- use Dreamcast version of Virtua Tennis 2
- use Naomi version of Virtua Tennis 2 (vtenis2c.zip) or (vtennis2.zip)

**Comment by flyinghead** [comment]
Confirmed. mame has the same issue.

**Comment by aminta** [comment]
This should be marked as milestone...

**Comment by blisstik** [comment]
`vtenis2c` seems to work on the Nvidia Shield

**Comment by r3tro80** [comment]
This has been fixed 19 days ago on standalone... could be backported to libretro core?

https://github.com/flyinghead/flycast/commit/e94e757743d9f0dc1678e6b814508b47a591dba8

**Comment by barbudreadmon** [comment]
thanks for the heads-up, i'll look into this soon

**Comment by barbudreadmon** [comment]
looks like i'll have to backport https://github.com/flyinghead/flycast/commit/a41a81f5dde460c711e4e2874bd20df16ae1ac01 first

**Comment by barbudreadmon** [comment]
done, seems to work, i'll close
