### ISSUE TITLE
Info file needs more detail

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#419]
The reicast core info file should list the files and hashes contained within the zips, rather than the zips themselves.  For example with naomi.zip, [MAME documentation](https://github.com/mamedev/mame/blob/master/src/mame/drivers/naomi.cpp) (search on page for #define NAOMI_BIOS), lists each file and hash in naomi.zip. This would make the file more comparable in size to other libretro info files e.g. bsnes/higan, but would help e.g. to avoid issues in troubleshooting due to corrupt or missing files.

Note that there is a separate but related [issue](https://github.com/libretro/reicast-emulator/issues/99) with the info file pertaining to the dreamcast flash as the current hash represents a known bad dump.

**Comment by blisstik** [comment]
The comparable file is `roms.h` file. It should go there right?

**Comment by Shoegzer** [comment]
Not sure what you mean.  The files and hashes should be listed in reicast_libretro.info.

**Comment by barbudreadmon** [comment]
The info file was updated months ago, the list should be complete, the md5 is the one from the torrentzipped file, storing hash from every file in every zip is unrealistic.
Closing this issue.

**Comment by Shoegzer** [comment]
@barbudreadmon 

Well, even if it's considered "unrealistic" in the info file, either RA or the core should at least have some way to integrity-check each support file against e.g. an internal db to insure they are valid/good and don't lead to users reporting false issues with the core itself.  This is consistent with MAME's high standards and practices - see "$ mame -verifyroms naomi"

Also, relying on a torrentzipped MD5 doesn't work for many circumstances, such as those people who import their bios zip from a MAME collection which gets rebuilt through ClrMAME whenever the file changes (which I assume is most people, but even if not there are many other similar circumstances).

Request that we reopen this one or I can at least open a new issue as a feature request that might help to address the above concerns.

**Comment by barbudreadmon** [comment]
@Shoegzer You might be right, however that's unrelated to reicast itself, all arcade related cores do the same thing, and the md5 checksum isn't even mandatory or checked at all in those info files. Maybe try opening an issue in the retroarch repo instead ?

**Comment by Shoegzer** [comment]
@barbudreadmon Good point.  Thanks for your thoughts, I'll open an issue there.
