### ISSUE TITLE
Grandia 2 - Not Working on latest Android build (01ffff9)

### ISSUE THREAD

**Issue by kikeminchas** [libretro/flycast#431]
Grandia 2 freezes just after the title screen. It shows 'Now Loading...' and then screen stays black. I need to force quit Retroarch. Tried GDI and CHD versions, Same files were working fine on previous releases

System: NVIDIA SHIELD TV (Android TV 8.0)
Options: Deleted all options from cfg file to start fresh. All default. 
Threaded rendering:off
Synchronous Rendering:off
Per triangle alpha transparency
Resolution: 640x480
DIV hack:off

Core version: 01ffff9

**Comment by flyinghead** [comment]
It looks like this is a consequence of the fix for Shikigami No Shiro II (previously this game was very slow). However I don't think this fix introduced a regression but rather exposes a bug in the arm dynarec, possibly related to self-modifying code.
Still investigating...

**Comment by flyinghead** [comment]
Should be fixed as of https://github.com/libretro/reicast-emulator/commit/108c7acb665d29bbfeecd1c300419bc93c53d6fa

**Comment by kikeminchas** [comment]
Indeed, this is now fixed. Thanks!
