### ISSUE TITLE
Soul Calibur - No character Shadows [SHIELD - Android TV] 

### ISSUE THREAD

**Issue by kikeminchas** [libretro/flycast#438]
Hi,

I had understood that since the implementation of Volume Modifier Shadow support shadows should now be visible in Soul Calibur. [https://www.libretro.com/index.php/introducing-reicast-oit-libretro-core-updated-reicast-regular-core/]. This is not the case for me. Using a SHIELD TV with version a45420f of the core (non OIT, obviously). Relevant Options:

Alpha sorting: per-triangle
Extra depth: Auto
Mipmapping: On
Volume Modifier: On
DIV matching: OFF
RTT: ON
RTT buffer: Tried ON and OFF, no difference
Threaded rendering: OFF
Sync Rendering: OFF

Is this a regression or a specific problem with the ARM version of the core? Thanks!

**Comment by blackman91** [comment]
Are shadows visible if you enable threaded rendering?

**Comment by kikeminchas** [comment]
They do, ok feel stupid now. I always try to test as close as possible to default settings and didn't think on activating this one. Closing. Thanks!
