### ISSUE TITLE
Context reset causes red squares

### ISSUE THREAD

**Issue by orbea** [libretro/flycast#440]
OS: `Slackware64-current`
reicast: https://github.com/libretro/reicast-emulator/commit/57b76774c6f5a9c5830b911f701a3cc99ae2c16a
GPU: `AMD RX Vega 56`

When toggling full screen (Context reset) it will cause various graphical issues, for example these red squares in the Dreamast bios or Soul Calibur Title screen. I have experienced this with both the regular reicast core and the oit core.

![1](https://i.imgur.com/Yg2yZtr.png)
![2](https://i.imgur.com/gAM52Ux.png)

Also, thanks a lot for fixing the context reset!

**Comment by requeijaum** [comment]
I can confirm a similar issue where I toggle fullscreen and then all the textures and also the VMU overlays screens get corrupted. No red squares, though.

**Comment by flyinghead** [comment]
I believe this is now fixed. Reopen as needed
