### ISSUE TITLE
Atomiswave games don't play 

### ISSUE THREAD

**Issue by Tiganjos** [libretro/flycast#441]
I trying to play atomiswave games not converted for naomi I have aw bios in system dc but I tryed to run fotns zip file and nothing can someone help me i am using android phone

**Comment by kikeminchas** [comment]
Fist of the North Star, mame version, works. Check the version of your game and the awbios.zip file, try to get one with the suggested md5. (Make sure in fact that the bios is detected by checking the core information inside retroarch's menu)

**Comment by Tiganjos** [comment]
What core to use to run fist of the north star mame core or reicast core please help

**Comment by barbudreadmon** [comment]
I wouldn't recommend mame to play naomi games, the cpu requirements are a lot higher and the support is still preliminary.
Don't know what's your issue, this game works for me. Make sure your roms are up-to-date (= from a mame 0.204 romset).

**Comment by blisstik** [comment]
Use lr-reicast core which has support for naomi and atomiswave Mame roms. The recent mame rom set is recommended.

Please close this issue as this type of issue should be posted in Libretro forums.
