### ISSUE TITLE
Reset Button Doesn't Work 

### ISSUE THREAD

**Issue by newoski** [libretro/flycast#445]
From testing, the Reset button for RetroArch doesn't seem to have any impact. So far, I've only tested it on Atomiswave games. No response

**Comment by requeijaum** [comment]
The same is happening on Dreamcast mode, using Reicast v0.1 37da602 from RetroArch v1.7.5. I need to use "Close Content" button in order to unload the core and start it again.

**Comment by flyinghead** [comment]
As of https://github.com/libretro/reicast-emulator/commit/80a92857b1db53cea9926de5016720abb24919f7 Restart should work as expected.
