### ISSUE TITLE
salmankt MAME rom for Atomiswave 

### ISSUE THREAD

**Issue by newoski** [libretro/flycast#446]
Not sure quite what the issue is, but the P2 buttons seem to open an in game debug menu. 

Coin Button works, but Start doesn't seem to, which makes game unplayable

**Comment by flyinghead** [comment]
I can't get the original Atomiswave mame rom to boot at all. It hangs on a grey screen right after the Sammy logo.
The NAOMI conversion (.bin) does boot but the inputs are not working, which is very common in these conversions.

**Comment by barbudreadmon** [comment]
The game appears to be playable with the MAME romset now, i'll close
