### ISSUE TITLE
[solved] Controller drifting upwards

### ISSUE THREAD

**Issue by BanditTech** [libretro/flycast#458]
Finally got myself transitioned from the standalone Reicast emulator to the Libretro version because it plays my favorite game Rez without graphical corruption. But now that I have, I am having issues with controller drift. I need to increase the deadzone to 25% just so that my character will not move up on its own. Pushing the stick up will make it instantly start moving up the screen very fast. Pushing down respects the 25% deadzone and will move down on the screen at half the speed. Basically the Y axis is off centered by a large amount and I cannot figure out how to calibrate it. I read in some of the other posts a game test mode being mentioned, but I cannot find any reference to how to access it. Service Menu is not a button I can map in the core options, can you give me more information how to make this calibration.

**Comment by flyinghead** [comment]
The game Test Mode and Service Menu are only for arcade games (Naomi/Atomiswave) not for regular Dreamcast games.
There's probably an issue in the libretro controller mappings. I'd suggest you start from a default/clean libretro config.

**Comment by BanditTech** [comment]
I reset to default to try fixing the issue, but it was a hardware failure. I tested other controllers and they do not show any drift. I had to have a talk with the gf about dropping the controllers :P
