### ISSUE TITLE
Threads support

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/flycast#46]
It seems this core lacks the thread support present upstream, so it won't run well on hardware with a cpu around 2.6Ghz, even with the dynarec enabled.
I tried forcing it by adding `settings.pvr.MaxThreads = 3` into libretro.cpp and adding `NO_THREADS=0` to the make command, of course the core wouldn't work (i expected this ^^), and i got the following output before it stopped : 

> Sh4 Reset
recSh4 Init
@@	ngen_ResetBlocks()
Freeing fpcb
DEBUGBREAK!
chd: parsing file ChuChu Rocket! (USA).gdi.chd
TRACK:1 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:7334 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0
TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:37666 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0
TRACK:3 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:309752 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0

Is there any plan to fix threads support ?

**Comment by inactive123** [comment]
I have rebased the code to be like upstream, including the threading code, but yeah, unfortunately this still crashes. 

We will need a GL expert who is also adept at debugging multithreaded code.

**Comment by barbudreadmon** [comment]
Thanks for trying :). I hope someone will be able to help with this, GL and MT are far beyond my skills.

**Comment by barbudreadmon** [comment]
@twinaphex @flyinghead I tried to look into this again and got the following message with gdb : 
>Thread 4 "retroarch" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff92f15700 (LWP 13712)]
0x00007ffff4c63dc9 in glGetIntegerv () from /usr/lib64/opengl/nvidia/lib/libGL.so.1

I think the issue could be related to this : 
> In order for any OpenGL commands to work, a context must be current; all OpenGL commands affect the state of whichever context is current. The current context is a thread-local variable, so a single process can have several threads, each of which has its own current context. However, a single context cannot be current in multiple threads at the same time.

Source : https://www.khronos.org/opengl/wiki/OpenGL_Context

Edit : actually, isn't that kinda related to the "shared hardware context" feature in retroarch ?

**Comment by flyinghead** [comment]
OpenGL calls can only be done on one thread: the renderer thread. This also includes TA parsing because textures are created/updated during this phase.
In upstream, when using multi-threading, semaphores are used to start parsing/rendering and notifying back the emulator with interrupts. But all the OpenGL calls are done on the renderer thread.

**Comment by barbudreadmon** [comment]
So what's the current status on this ? I noticed some commits about it, however the emulator still seems to run everything on the same thread / cpu core.

**Comment by inactive123** [comment]
@barbudreadmon A threaded rendering option was implemented by @flyinghead. It should offload audio and video to a secondary thread.

Does it not work according to expectations?

**Comment by barbudreadmon** [comment]
@twinaphex i didn't realize it was a core option disabled by default. Once it is enabled, the core performs a lot better on my mini computer. Is there any reason for disabling it by default ? Is that different from how the standalone version handles MT ?

**Comment by inactive123** [comment]
There are still some issues with it on Android, where you have to set Poll Type Behavior to Early in order for it to work properly. Also, frame pacing IMHO is still a tiny, tiny bit worse than non-threaded mode.

In any case, the option is there and can be enabled at any one time. Maybe when the poll type behavior issues are fixed by @flyinghead we could make it enabled by default on platforms like Android at least.

**Comment by barbudreadmon** [comment]
@twinaphex ok, at the very least this issue is solved, so i'll close. Thanks !
