### ISSUE TITLE
core stopped working after x64 dynarec optimization on windows 10 64 opengl nvidia gtx 1060

### ISSUE THREAD

**Issue by rubenjavier** [libretro/flycast#464]
Hello,
after upgrading to the new core 1.7.5-Reicast 0.1275cf48 no game on either GDI or CHD format is working, not even the bios dreamcast screen is shown

This was tested with a previously working retroarch folder and also with the latest nightly with just the dc_boot.bin dc_flash.bin and naomi_boot.bin

vmu_save_XX.bin are created but dc_nvmem.bin is not being created.

No core options are shown on the retroarch xmb entry
 and no core options are being written on the cfg file (also tested on a clean install)

The loading goes as far as read the product number LUT from the CHD/GDI file and then restart/shutdown all
[libretro INFO] [LUT]: Product number: T1401N    .
[INFO] Environ SET_DISK_CONTROL_INTERFACE.
[INFO] Skipping SRAM load...

here is the complete log in pastebin:
https://pastebin.com/59RvNa4t

thanks in advance

**Comment by barbudreadmon** [comment]
It sets input descriptors for the 4 users 4 times in a row, that's wrong behavior, and i remember having some weird failures in fba in the past for something similar (it was segfaulting on windows after a certain number of "set input descriptors" iteration in a row).

**Comment by rubenjavier** [comment]
I went into Input menu and set a max of 2 users, still crashed
I think the input number you see is taked from the retroarch.cfg file that comes with all those possible users even when you set a max number on the menu

**Comment by M0KUJINKEN** [comment]
Hey you too!? I notice my Naomi ROMs stopped working today, how can we get old cores back?

Gtx 750ti

**Comment by RicardoZagada** [comment]
Hi. Never used the reicast until yesterday and it never booted, always crashing in a few seconds after selecting the game. God knows how much time i spent trying to change bios, filenames, filepaths, redownloading cores thinking it was a dumb problem on my end. Glad to know it's being looked into, wish you luck ;)

EDIT: Windows 10 x64
Intel Core i5 -7300HQ CPU 2.50GHz
Nvidia GeForce GTX 1050 4Gb

**Comment by flyinghead** [comment]
The problem has been identified and a fix will be released shortly

**Comment by flyinghead** [comment]
Core version 701c55c is available and should fix the issue. Please update and report back. Thanks

**Comment by rubenjavier** [comment]
fixed with the latest update, just downloaded the latest build and the games are working again, in my case I needed to load a gema before recovering the core options menu... its really fast now, thank you @flyinghead
