### ISSUE TITLE
Skies of Arcadia - glitches (dark menus and corrupt texture in cutscene)

### ISSUE THREAD

**Issue by bryc** [libretro/flycast#467]
Testing with build 701c55c. Win7/i7-3770/GTX 1050 Ti.

First of all, the party menu sometimes turns very dark and is unplayable. It can also glitch up quite badly. This seems to happen when first piloting the ship, but is fine in other cases. It seems to be random, but it's consistent.

![image](https://user-images.githubusercontent.com/1408749/51486257-37b92780-1d6e-11e9-8dc7-abb5fc2c2f90.png)

![image](https://user-images.githubusercontent.com/1408749/51486594-1c025100-1d6f-11e9-882e-fc878513e5e3.png)

There are no dark outlines in the pause menu option when sailing. Or maybe the dark outline is just covering the whole screen.

![image](https://user-images.githubusercontent.com/1408749/51486558-05f49080-1d6f-11e9-94ce-05314565f7e0.png)

Next, I can't see where I'm going when piloting the ship. When pushing forward on the analog stick, it changes the view to look down, as well as moving forward. So visibility is destroyed, affecting playability.

Edit: This is apparently because I map Analog 1 to Digital. I like to use the Stick for some DPad games. But DC has both analog and dpad. Is this something that can be ignored by Reicast?

![image](https://user-images.githubusercontent.com/1408749/51486457-ba41e700-1d6e-11e9-86a7-81948aa2fb25.png)

During Fina's dream sequence, there is supposed to be some texture blended in to make it look hazy. But it appears as a semi-transparent corrupted texture. Also it doesn't fade to black when it should.

![image](https://user-images.githubusercontent.com/1408749/51486640-3b997980-1d6f-11e9-9add-3a91b963c0cf.png)

**Comment by flyinghead** [comment]
Is it with per-pixel sorting? If not, does enabling per-pixel sorting makes things better, worse or unchanged?

Do you think this is a regression?

Can you upload one or more save states corresponding to these issues to help reproduce them?

Thanks

**Comment by bryc** [comment]
Here's a state right before menu corruption happens: [Arcadia_state.zip](https://github.com/libretro/reicast-emulator/files/2783197/Arcadia_state.zip) (rename zip to 7z)

Steps to reproduce the issue

1. Load state
2. Talk to pony tail guy to enter sailing mode
3. Press X to open party menu (it should be OK) then exit.
4. Press start/pause (it should be dark like in my 3rd screenshot). Then exit.
5. Press X again to open party menu (it should be corrupted now).

Per-pixel sorting doesn't change the issue, and I don't know if it's a regression.

And here's the state just before the dream sequence: [Arcadia_state2.zip](https://github.com/libretro/reicast-emulator/files/2783903/Arcadia_state2.zip) (rename to 7z).

**Comment by flyinghead** [comment]
I was able to load your savestate and could reproduce the issues. I don't know yet what's causing this.

Regarding your mapping of analog stick onto DPad, the easiest way to do this is to change the RetroArch Controls in the Quick Menu: set `User 1 Analog To Digital Type` to `Left Analog` (or `Right Analog`) when you want to use the stick for DPad. Set it to `None` for games that need both analog and DPad.

**Comment by flyinghead** [comment]
This should be fixed in the next core update. You will have to enable the `Enable RTT Buffer` core option for the menus to display correctly.

**Comment by flyinghead** [comment]
I believe this is fixed. Please reopen if not
