### ISSUE TITLE
ngen_FailedToFindBlock [XU4]

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#473]
Hello flyinghead,

Just recompiled lr-reicast to the most recent today and the build is crashing. This is on the Odroid XU4. I tried Dreamcast CDI and Naomi ZIP which both crashed. Let me know if you need more info.

https://pastebin.com/raw/fpXzt1Wh

**Comment by flyinghead** [comment]
Same problem as Issue #471. Should be fixed with PR #472

**Comment by blisstik** [comment]
Fixed. Thanks!
