### ISSUE TITLE
lr-reicast no sound on RPi3

### ISSUE THREAD

**Issue by martinx72** [libretro/flycast#474]
I managed to build the working lr-reicast.so on retropie 4.4 for RPi3. All works great but no sound at all.

**Comment by Liontek1985** [comment]
here the same problems on RPI3 and Orange PI PC

update:
my problem is like this
https://github.com/libretro/reicast-emulator/issues/258

**Comment by martinx72** [comment]
> I managed to build the working lr-reicast.so on retropie 4.4 for RPi3. All works great but no sound at all.

Ok, looks like i update the retroarch and all suddently works for me now on RPi3

**Comment by Liontek1985** [comment]
the update help yes :)

**Comment by ghost** [comment]
@martinx72 consider closing if resolved.
