### ISSUE TITLE
Quick Menu freezes

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#479]
Hi Flyinghead,

Using the latest build of lr-reicast and RetroArch v1.7.6 branch, when I go into Quick Menu, it works but when I try to Resume to the game, it freezes.

Any fixes?

**Comment by flyinghead** [comment]
There is a deadlock related to audio when resuming from the Quick Menu.
A workaround is to enable the menu sounds: Settings -> Audio -> Menu Sounds -> enable Mixer

**Comment by blisstik** [comment]
It's now fixed by RetroArch
