### ISSUE TITLE
reicast on android (firetv) doesn't work in RetroArch

### ISSUE THREAD

**Issue by DieterLasers** [libretro/flycast#482]
– starting games crashes RetroArch
– when RetroArch doesn't crash the games start but are not playable due to choppy video and sound
– for comparison: reicast downloaded from the google play store and installed on the FireTV works okay

– Disabling DSP helps with the game film sequences but not in the game
– switching from per-triangle to per-strip alpha sorting makes it even worse

i also tried:
– Enable Div Matching
– Decrease resolution
– threaded rendering ON
– synchronous rendering ON
– framerate normal

in the quickmenue. but the games are still not playable

**Comment by DieterLasers** [comment]
will this pull request from @swingflip help with this problem?
https://github.com/libretro/reicast-emulator/pull/475

**Comment by DieterLasers** [comment]
the non-oit version was showing a performance degression, already
https://github.com/libretro/reicast-emulator/issues/385

**Comment by BananaRama203** [comment]
Yeah this will, what platform do you build with? @DieterLasers

**Comment by DieterLasers** [comment]
I don't build with any platform, sorry. I just tried the reicast core in RetroArch 1.7.6 on a FireTV Stick 2nd gen. I opened this Issue, because I saw that it was working okay with the reicast app from the google play store (some games better than others). Added GPU additions and oit support are nice  features for better systems. But it would be great to have an option to use it on less powerful systems, which is why i appreciate your work

**Comment by barbudreadmon** [comment]
@DieterLasers You are asking for a miracle here : 
- I know what you mean by "reicast app is working okay" : you mean a few games, while having awful frameskipping, are somehow playable. 
- Those FireTV sticks are awful pieces of hardware, i had reports of them being unable to run full speed fbalpha games running full speed on a rpi2 @ 900Mhz.

**Comment by DieterLasers** [comment]
ps1 games run pretty fine on the reARMed core, but you are right. I also heard that people seem to grind their teeth with some special issues with the firetv, some permission problems. i don't know enough about it

on the other hand: REZ works pretty well :) and bangai-o. illbleed also seemed to work ok except for crackly sound. I'm looking forward trying @swingflips miracle work and be good with what i get :)

**Comment by BananaRama203** [comment]
@barbudreadmon this is the lowend and lowres mode added running on a low end PSC https://www.youtube.com/watch?v=pmAJI9rXXUA

it will absolutely help but of course it won't be perfect by any means. However some games will be playable especially 2D based games that don't rely heavily on 3d rendering.

@DieterLasers if you can link me to the download that you use then I can look

**Comment by barbudreadmon** [comment]
@swingflip Yeah, the frameskipping is really noticeable as i said, you might be around 20 rendered frame per second (in my experience, it starts being really noticeable below 30), but it appears to be playable. I'm curious, did you try aggressive cflags and/or building with clang ? (i noticed a few days ago that some drivers in fbalpha performs a lot better when built with clang)

**Comment by DieterLasers** [comment]
@swingflip you mean the reicast core i use? its the one i can download from within current RetroArch (1.7.6, 32-bit, android)

**Comment by DieterLasers** [comment]
hi!
so, [twinaphex](/twinaphex) merged commit [`c4a792c`](/libretro/reicast-emulator/commit/c4a792c79ab25210b45bd8fd55ae4c60de9c51f8) into libretro:master  [5 days ago](/libretro/reicast-emulator/pull/475#event-2138619874)

i just tried reicast 0.1 61bd27d but its not part of the core, yet. can i download the android core somewhere? thanks!

**Comment by flyinghead** [comment]
https://buildbot.libretro.com/nightly/android/latest/armeabi-v7a/reicast_libretro_android.so.zip
but you should be able to use the Online Updater

**Comment by ghost** [comment]
I can at least say, that with Fire Tv Gen2 almost all Games run smoothly with 720p. Of course Fire Tv stick and TV Box Gen2 are completey different from specs

**Comment by flyinghead** [comment]
Closing as resolved. Reopen as needed
