### ISSUE TITLE
Android TV (Nvidia shield) - Aarch64 - Core crashes with DSP

### ISSUE THREAD

**Issue by kikeminchas** [libretro/flycast#483]
DSP cannot be enabled with Aarch64 core version on Android. 32 bit version works fine with or without DSP. 64 bit version loads game if DSP is disabled but crashes Retroarch if enabled (not even BIOS loads)

Core version:   9837518

**Comment by flyinghead** [comment]
What CPU/GPU/SoC/phone are you using?

**Comment by kikeminchas** [comment]
It's a NVIDIA Shield TV. SoC is Tegra X1.

**Comment by flyinghead** [comment]
This issue should now be fixed

**Comment by kikeminchas** [comment]
Tested and working indeed. Thanks flyinghead!
