### ISSUE TITLE
Reicast won't load/run "lupinshoo"

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#484]
As noted in the title, Reicast core won't load or run from commandline the SH-4 arcade game "lupinshoo" from a merged MAME set that only includes its parent "lupinsho".  Doesn't the reicast core support merged sets?

Also, noticed a reference to this set [here](https://github.com/libretro/reicast-emulator/pull/477/commits/8659d95fa4fa8ce0fe57942fb980796d6e76a344).  Why do sets need to be manually added, won't reicast simply load/run any zipfile from the commandline?

Finally as a side-note, the above commit also supports "virnbapa" which is not supported in mame 0.206 (contrary to the title) though it should be supported in 0.207.

**Comment by barbudreadmon** [comment]
I'll take a look when i have some time, however i don't think i did a mistake when copying from MAME sources.

Sets need to be manually added so that we can map files contained in their zip file to memory.

PS : yeah i noticed i misnamed my commit after committing it xD

**Comment by barbudreadmon** [comment]
That's the commit i copied : https://github.com/mamedev/mame/commit/95bdda86f3504cf07aa88007eb4cb9498bf64d8b#diff-6b1ef57220ef0131d0ef0d81a736cc60 .
Basically, old lupinsho became lupinshoo and lupinsho is a new romset. It doesn't seem like i did any mistake when copying. However i didn't try those roms since i didn't have them, maybe i should, i'll let you know if i figure out something.

**Comment by flyinghead** [comment]
I haven't been able to find this new "rom" but since it's a GD-Rom game, it doesn't share anything with its parent. The zip file only contains the GD-Rom decryption key, which is different from the parent.
I haven't been able to test this set but make sure you have the GD-Rom (gds-0018.chd) in the right folder (lupinshoo).

**Comment by Shoegzer** [comment]
@flyinghead The issue occurs whether the GD-Rom is in the parent (lupinsho) or lupinshoo folder.  Ideally reicast _should_ support either storage method since MAME does as well, in case it doesn't now, but that's a separate issue.

@barbudreadmon thanks for looking into this.

**Comment by blisstik** [comment]
I think the line `lupinshoo` below needs to be removed.

```
    // Lupin The Third - The Shooting (GDS-0018)
    {
        "lupinshoo", <-- delete this line
        "lupinsho",
        0x4000,
        0,
        "naomi",
        GD,
        REGION_AUSTRALIA,
        {
            { "317-0325-jpn.pic", 0, 0x4000 },
            { NULL, 0, 0 },
        },
        "gds-0018",
},
```

**Comment by barbudreadmon** [comment]
@6alileo The first member of the struct is the name of the romset, what you suggest would at best make the romset unusable, at worst prevent the project from building

@Shoegzer The other day on discord, @flyinghead started this game without issue, he had to put `gds-0018.chd` in the `lupinshoo` folder though, which is indeed an issue, both parent & clone folders should be scanned for the chd.

**Comment by Shoegzer** [comment]
@barbudreadmon thanks, but it the chd works fine in mame and not here, and I've tried in both folders (for mame it works in both, for reicast, works in neither).  Perhaps there's some logging we can look at to see what's going on?

**Comment by blisstik** [comment]
The line lupinsho needs to be deleted for gds-0018 (non a) as I pasted above. I put the wrong delete line. That should fix this issue. Gds do not use parent / child. They are all essentially parents.

**Comment by barbudreadmon** [comment]
> Gds do not use parent / child. They are all essentially parents.

They have parents in mame though, see https://github.com/mamedev/mame/commit/95bdda86f3504cf07aa88007eb4cb9498bf64d8b#diff-6b1ef57220ef0131d0ef0d81a736cc60R11202, and mame will check parent folder for the chd, which is not implemented yet in reicast.

@Shoegzer This issue is weird and will need more investigation since @flyinghead was able to launch the game when he tried, could you post the verbose logging ?

**Comment by Shoegzer** [comment]
@6alileo I compiled against those changes myself but unfortunately they didn't work.  I do appreciate your help though.

@barbudreadmon actually I discovered the issue: I pass a custom command to my frontend which auto-loads the game using:

retroarch -L cores/reicast_libretro.so "/home/mame/$ID$.zip" 

Where $ID$ is the ROM name.  This works in mosts cases except where sets are merged (lupinshoo, but also others as I've just discovered after more digging, such as cvs2mf) because in those cases it calls e.g. "lupinshoo.zip" but the set is merged to "lupinsho.zip", so the set is never found.  Apparently then, successfully loading such sets seems restricted to very limited use cases where the set must be completely unmerged.  Again, this works in mame since mame fully supports merged sets in combination with chds.  Adding more complete support for merged sets to the reicast core should fix this issue.

Here's a basic log showing what happens (I think the line attempting to load 315-6301.ic11 can be ignored since no such dump exists - this happens in mame too):
```
11:24:10.296: stdout[#8]: nullDC-Naomi rom loader v1.2
11:24:10.296: stdout[#8]: File: /home/mame/lupinshoo.zip
11:24:10.616: stdout[#8]: OpenArchive: failed to open /home/mame/lupinshoo.zip
11:24:10.617: stdout[#8]: Cannot open /home/mame/lupinshoo.zip
11:24:10.618: stdout[#8]: Cannot load /home/mame/lupinshoo.zip: error 2
11:30:37.094: stderr[#9]: 315-6301.ic11 NOT FOUND (NO GOOD DUMP KNOWN) (tried in lupinsho naomigd segadimm)
11:30:37.095: stderr[#9]: WARNING: the machine might not run correctly.
11:30:37.327: stdout[#9]: Real PIC binary found
```

**Comment by barbudreadmon** [comment]
@Shoegzer Did my PR fix your issues ? It's now working perfectly well for me : 
```
nullDC-Naomi rom loader v1.2
File: ./lupinshoo.zip
OpenArchive: failed to open ./lupinshoo.zip
Opened lupinsho
Mapped 317-0325-jpn.pic: 4000 bytes at 0000000
Real PIC binary found
key is c1b6d6802cd59ebf
chd: parsing file .//lupinsho/gds-0018.chd
TRACK:1 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:1042 PAD:150 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0
TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:43958 PAD:41825 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0
TRACK:3 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:504150 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0
```
No lupinshoo.zip, and the chd is in the lupinsho folder.

**Comment by Shoegzer** [comment]
@barbudreadmon It did indeed fix this issue, tested and working fine.  Thank you!  I'll close it now.
