### ISSUE TITLE
Knuckles Fighting Gloves Audio Issue

### ISSUE THREAD

**Issue by ghost** [libretro/flycast#485]
In Sonic Adventure 1, after getting knuckles fighting gloves, charging his ability stops any audio from playing until he glows. 

Windows 10 Pro

Ryzen 3
GTX 1070 Ti

Retroarch 1.7.6 Nightly/ Reicast 0.1 9837518

[Sonic Adventure (USA).zip](https://github.com/libretro/reicast-emulator/files/2858938/Sonic.Adventure.USA.zip)

**Comment by ghost** [comment]
I can reproduce the issue here.

**Comment by ghost** [comment]
@flyinghead is this something that happens upstream as well? i dont see any issues related to this so probably not. i will build on linux tonight and see if i can get it to replicate there.

**Comment by flyinghead** [comment]
There are many audio issues in SA1 in upstream although I'm not sure about this specific one.

Just go to the sound test in the game options. There you can listen to pretty much all sounds of the game. And many of them have loop or other issues.

**Comment by ghost** [comment]
I think i found it. 04/0/04 is the charge in sound test. strange it does it in game.

**Comment by flyinghead** [comment]
There's been significant improvements in sound emulation and this might be fixed. An update would be appreciated.

**Comment by ghost** [comment]
> There's been significant improvements in sound emulation and this might be fixed. An update would be appreciated.

Issue resolved on my end.
