### ISSUE TITLE
Compile lr-reicast on odroid xu4, fault segmentation at runtime

### ISSUE THREAD

**Issue by karatoso** [libretro/flycast#492]
Hello community, first of all a big thank you for everything you do! I do not have much programming knowledge, I am trying to compile lr-reicast on Odroid Xu4, you speak of a variable CC-PREFIX that I can not define for this material. I do not know what value to put, Where can I find my compiler prefix ? Second problem, I tried to compile the emulator by this command:
platform=odroid ARCH=arm make

The compilation is going well, but "segmentation fault" when I start it.

What can I do to integrate this emulator with Retropie? Thanks for your help !

maybe it's linked, but I can not install libasound (unable to locate package), it's the only package I can not install

**Comment by AreaScout** [comment]
You do not need a ``CC_PREFIX`` unless you are cross compiling

that's all you need:

``platform=odroid BOARD=ODROID-XU4 ARCH=arm make -j8``

RG

**Comment by MastaG** [comment]
Same here.. when I launch a game using reicast, the screen goes black for a second, then it segfaults.
I've built it natively using: platform=odroid ARCH=arm make -j8

**Comment by AreaScout** [comment]
Then it must have something to do with native gcc or distro, because I have cross compiled it and it works but meveric told me that he get illegal instructions on debian

**Comment by MastaG** [comment]
I just got it to work.
It appears that I had to set ARCH with all caps.
The first time I built with arch=arm instead of ARCH=arm.

Now it works on my Xu3.
Verified it on RetroArch on both DRM and Wayland (Gnome).

Still some games like Sonic Adventure 2 are not yet full speed.. but thats beyond this issue.

**Comment by AreaScout** [comment]
Good that it works now for you :)
