### ISSUE TITLE
Rayman 2 - The Great Escape missing transition effects

### ISSUE THREAD

**Issue by Sterophonick** [libretro/flycast#498]
When playing Rayman 2 - The Great Escape, you can notice that the swirly screen transition effects are completely absent from the game.

**Comment by flyinghead** [comment]
Are you referring to this effect at startup?
<img width="1284" alt="screen shot 2019-03-05 at 12 12 15" src="https://user-images.githubusercontent.com/16261910/53819308-14be8d80-3f40-11e9-8e8c-c0962b041258.png">

**Comment by Sterophonick** [comment]
Yes. At least, when I play it, they are absent. Running OpenGL.

**Comment by flyinghead** [comment]
I just checked and this effect does appear (tested on MacOS). Make sure you're using the latest reicast core build.
What platform are you on? (OS, CPU, GPU)

**Comment by Sterophonick** [comment]
Windows 10
Intel Core i3-4160T CPU @ 3.10 GHz
Intel HD Graphics 4400

**Comment by flyinghead** [comment]
I just checked on Windows 10, Intel Core i5-7260U CPU @ 2.20 GHz, Intel Iris Plus Graphics 640 and the swirly screen transition effect above is visible.

I also tried to change the core options to no avail.

**Comment by flyinghead** [comment]
assuming this is resolved
