### ISSUE TITLE
I can not launch Naomi Mame roms

### ISSUE THREAD

**Issue by legluondunet** [libretro/flycast#500]
Hello,

I can not launch Mame roms, I don't know if it is a bug or if I did something wrong:
- I updated the libretro reicast module today from RA interface
- I copied naomi.zip file from mame roms in /system/dc folder
- I tried to launch mame roms, Crazy driver and Cosmic Smash, but it doesn't work

This is the RA log:
[RADebug.log](https://github.com/libretro/reicast-emulator/files/2949360/RADebug.log)

For example, the command line I used for Cosmic Smash:
`$ ./retroarch -v --log-file RADebug.log -L '/home/legluondunet/Autres_applications/Jeux/Emulateurs/RetroArch/Lien vers retroarch config/cores/reicast_libretro.so' /home/legluondunet/Bureau/csmash.zip `

The rom size csmash.zip: 35,5 Mo (35 526 439 octets) md5sum: ba223ddde569d84f2ff99dddea06c6ec CRC32: b85d8093

This rom contains this files:
csmash-key.bin
epr-23428a.ic22
mpr-23420.ic1
mpr-23421.ic2
mpr-23422.ic3
mpr-23423.ic4
mpr-23424.ic5
mpr-23425.ic6
mpr-23426.ic7
mpr-23427.ic8

Thank you for your help.

**Comment by flyinghead** [comment]
It looks like the core fails to create the Open GL context:
```
[INFO] Requesting core OpenGL context (3.0).
[INFO] Environ SET_HW_RENDER.
[INFO] Requesting OpenGL context.
[ERROR] Échec du chargement du fichier.
```
Did you update retroarch or your display drivers recently?

**Comment by legluondunet** [comment]
I see, I use RA with Vulkan drivers. If I change RA video drivers config to opengl, Naomi Mame roms launch correctly.
So libretro Reicast module is not Vulkan compatible?

**Comment by flyinghead** [comment]
No, only Open GL

**Comment by legluondunet** [comment]
ok thank you (one more time) for your help.
