### ISSUE TITLE
Odroid XU3/4 rendering problem in Sonic Adventure

### ISSUE THREAD

**Issue by MastaG** [libretro/flycast#506]
Hi, I was playing around a bit with Sonic Adventure.
I got it to run fast by disabling DSP emulation.
But I noticed some rendering problem.

When sorting per-strip Sonic's model looks OK but the subtitle text gets disorted.
I don't have a screenshot, but I can make one.

When sorting per-triangle the text becomes OK but Sonic's model will have random polygons not connecting around edges (especially under his eyes).
![Schermafdruk van 2019-03-21 15-40-05](https://user-images.githubusercontent.com/15012115/54761745-f5d42280-4bf2-11e9-904d-38ddd69b609b.png)
![Schermafdruk van 2019-03-21 15-42-29](https://user-images.githubusercontent.com/15012115/54761756-fa98d680-4bf2-11e9-93b4-9c22e4d56802.png)

Also on a side note, is it possible to use the OpeGL ES 3.0 renderer on the Odroid XU4?
I've built RetroArch with support for it, but Reicast seems to default to GlesV2.

**Comment by barbudreadmon** [comment]
> is it possible to use the OpeGL ES 3.0 renderer on the Odroid XU4?

There is no gles3 renderer, the per-pixel alpha sorting is opengl only

**Comment by flyinghead** [comment]
Unfortunately there isn't much we can do here. Both per-strip and per-triangle are approximations of how the real console GPU works. Depending on the game, or scene, per-strip or per-triangle will give better results. In some cases, some elements of the same scene will render better in one mode and other elements worse.

The only "pixel-perfect" method is the per-pixel renderer, which is not available with GLES.

By the way the reicast core will use GLES3 if available, which is the case on Odroid.

**Comment by MastaG** [comment]
@flyinghead 
Thanks for the clarification.
Does that mean, that for odroid we should also set:
HAVE_CORE = 1
HAVE_GL3 = 1
followed by:
FORCE_GLES = 1

**Comment by barbudreadmon** [comment]
> HAVE_CORE = 1
HAVE_GL3 = 1

Nope, the odroid doesn't have OpenGL 3 and OpenGL Core.

**Comment by MastaG** [comment]
Alright thank you @barbudreadmon :+1: 

I'll close this issue then.
