### ISSUE TITLE
Android:Threaded rendering on freeze onscreen overlay input

### ISSUE THREAD

**Issue by lim2222** [libretro/flycast#512]
Whenever threaded rendering is turn on, onscreen overlay input became partly freeze and sometimes no function at all.Recent nightly update couse the issue,it works fine on stable build.

**Comment by flyinghead** [comment]
This is a known issue. Go to RA Settings - Input and change Poll type behavior to Early or Late depending on your current setting.

**Comment by lim2222** [comment]
Yeah,Early works for me.Close now.
