### ISSUE TITLE
Virtual On (vonot): Missing "R Right" in retroarch controls menu

### ISSUE THREAD

**Issue by ziltama** [libretro/flycast#515]
I was trying to map both sticks to my dual analog pad and noticed "R Right" is missing.

Without any remapping, moving the 2nd player joystick does work in moving right.

**Comment by blisstik** [comment]
If I remember correct, turn off Allow Naomi Service Menu

**Comment by ziltama** [comment]
That doesn't do anything. R Right still ends up being missing.

**Comment by ziltama** [comment]
Nevermind, it works now. I had to restart and then saw the R Right replaced Service. Strange it would do that though.
