### ISSUE TITLE
Reicast core dumps at start of Sonic Adventure 1 Tails level "Casinopolis"

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#517]
Crashing always occurs within a few seconds after entering this level, rendering Sonic Adventure 1 unplayable.  Full terminal log is [here](https://pastebin.com/TMA0KaHz).

Also below is a VMU save with Tails as a playable character right before this stage (you have to fly up to the big button above the casino to open the door, then go into the casino to start the level).  

[vmu_save_A1.zip](https://github.com/libretro/reicast-emulator/files/3027308/vmu_save_A1.zip)

@flyinghead hopefully you have some ideas for how to fix this but just let me know if you need anything else from me that might help.

**Comment by flyinghead** [comment]
Thanks for the vmu. I tried and unfortunately it doesn't crash for me when I enter the Casino.

I did detect some weirdness wrt memory access at the start of the level but that shouldn't cause a crash.

The version of the game I tested seems to be strictly identical to the one you're using (serial, version, region)

Also played with core options to no avail

**Comment by Shoegzer** [comment]
Thanks @flyinghead.  I should note that the crash occurs no matter what version of the game is tested.   Also the test system is Linux Mint 19.1 x64 with kernel 4.19, with a core I compiled from the buildbot script using GCC 7.3.0.  Is that somewhat comparable to what you're using?  Also do you see anything abnormal from looking at the logs I provided?  Any other suggestions you have for nailing this one down would be greatly appreciated.

**Comment by flyinghead** [comment]
Assuming this is resolved. Reopen if not

**Comment by EpicVector** [comment]
I am having this issue. At the start of the level i progress up the slope and just before the giant fan the game crashes. It makes Tail's story impossible to finish beyond 20% completion. Everyone else's  stories have worked so far (100% with Sonic and Big)

**Comment by quorrafromtron** [comment]
I too am also encountering this issue, specifically either right as the level starts and tails touches the ground, or near the end when tails touches the water in the shallow pool area with spikey balls.
