### ISSUE TITLE
Silver (France) crash

### ISSUE THREAD

**Issue by dukeblooders** [libretro/flycast#522]
Hello,

The game crashes after the MpegCodec logo (I tried the game on another emulator and it starts correctly).

I use the latest nighly builds of Reicast and Retroarch (on Windows 10).
The full name of the file is 'Silver (France) (Fr,It,Pt).gdi'

Log file :
[log.txt](https://github.com/libretro/reicast-emulator/files/3065732/log.txt)

**Comment by flyinghead** [comment]
Set broadcast to PAL and region to Europe. It looks like this game doesn't like the default settings.

**Comment by dukeblooders** [comment]
Yes, it works with these settings. Thanks !
