### ISSUE TITLE
Reicast core dumps on loading any NAOMI rom

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#527]
Tested against build f59c772f00e5e706a06eb5ec9d041c97aa221f15, compiled on linux 4.18 x64.  Older builds tested at least a few months ago worked, not sure exactly when but could bisect if necessary.  

Loading any NAOMI rom returns the following:

```
$ ./retroarch -L cores/reicast_libretro.so "pstone.zip"
[reicast]: Got size: 640 x 480.
Creating dir: /home/shoegazer/Emulation/Emulators/RetroArch/system/dc/data
Linux paging: 00001000 00001000 00000FFF
MAP 00800000 w/ 50331648
MAP 20000000 w/ 50331648
MAP 04000000 w/ 33554432
MAP 06000000 w/ 33554432
MAP 0C000000 w/ 0
A8
vmem reserve: base: 0x7f8c26d70000, aram: 0x7f8c46d70000, vram: 0x7f8c2ad70000, ram: 0x7f8c32d70000
Resetting mem
Sh4 Reset
recSh4 Init
Freeing fpcb
nullDC-Naomi rom loader v1.2
File: (null)
SIGSEGV @ 0x7f8c5ecdd5a1 ... (nil) -> was not in vram (dyna code 0)
DEBUGBREAK!
SIGSEGV @ 0x7f8c48685b47 ... 0x7f8c48685b47 -> was not in vram (dyna code 0)
DEBUGBREAK!
Illegal instruction (core dumped)
```

**Comment by barbudreadmon** [comment]
```
...
File: (null)
...
```
reicast doesn't see your rom, try with full path or without ""

**Comment by Shoegzer** [comment]
Thanks @barbudreadmon.  Tried with full path and without "" and got the same results.  I can do an "ls" of the rom and I can see results too, so the file is definitely there.  I've tried with various other roms too and getting the same results.  I used to use this command all the time and it worked fine not too long ago.  Can you replicate?

**Comment by barbudreadmon** [comment]
> Can you replicate?

Nope, reicast see my roms, what's your full path ? Are there spaces or other special characters ?
Could you post the full log by adding `-v` to the command line ?

**Comment by Shoegzer** [comment]
@barbudreadmon Sure thing - check [here](https://pastebin.com/i3A7cQrv).  To be sure it wasn't a path issue, I moved "pstone.zip" to the retroarch folder itself as you can see from the output.  This same file boots just fine in MAME 0.208.

Also, in case it makes a difference - I'm using GNU/Linux, not sure if you are?

**Comment by barbudreadmon** [comment]
> [INFO] Environ GET_VARIABLE reicast_boot_to_bios:
[INFO]  enabled

You are booting to bios, it won't work with naomi (i guess we could add some safety mecanism), change that and it should be ok.

**Comment by Shoegzer** [comment]
Ah, naturally!  Good catch - and yes, it works now so I will close this out.  As a side note, I wonder how hard it would be to enable the core to trap such a condition (since DC BIOS is meaningless in NAOMI context) and optionally throw an exception to the UI rather than terminal.

Thanks so much for your help.
