### ISSUE TITLE
Reicast doesn't move past the system menu

### ISSUE THREAD

**Issue by treymerkley** [libretro/flycast#53]
I've been trying to get this set up to play a couple of .cdi files, but both files loaded say "Please insert game disc". Both games do this, and they do it regardless of the region flash I use. I have the time set up, and I've tried loading the games from the terminal and from the GUI. I've also tried loading the Utopia boot disc, but poking around I'm realizing that Utopia is for physical Dreamcasts and isn't needed in emulation. 

I'm using the latest git of Reicast on Manjaro Linux. 

Any idea what I need to do? Thanks!

**Comment by inactive123** [comment]
@bparker06 Can you provide some basic troubleshooting perhaps?

**Comment by flyinghead** [comment]
Assuming this resolved. Reopen as needed
