### ISSUE TITLE
Reicasr core crashing soon after game launch 

### ISSUE THREAD

**Issue by mpmua** [libretro/flycast#534]
When I try to play any dreamcast game with the reicast core, the dreamcast logo/bios runs fine and the game itself launches thereafter, however the touch screen controls become unresponsive a few seconds after the game launches and it eventually throws up the 'Retroarch is not responding' error, I've tried the snes core and that works fine.

The log file is as follows:

https://pastebin.com/9ZzfCnj2

Expected behavior

[What you expected to happen]

For Retroarch not to crash.
Actual behavior

Retroarch crashes.

[What is actually happening]
Steps to reproduce the bug

    Launch game
    Wait for crash

Version/Commit

I have tried various versions of retroarch, tried it from the playstore, gave the nightlys a go, tried both the standard and 64 bit versions, same thing keeps happening.
Environment information

    OS: Android Pie and Android Oreo (error occurred on both a phone and tablet respectively).

**Comment by flyinghead** [comment]
This sounds like the common input poll issue. It should now be fixed
