### ISSUE TITLE
Shadow Man - crashes when TV (RGB or Composite) output is used.

### ISSUE THREAD

**Issue by hiddenasbestos** [libretro/flycast#535]
~~The core is lagging behind the upstream emulator - Shadow Man (US) works on it but in this core it crashes to desktop (on Windows x64).~~

(btw. what sort of effort is involved to sync things @twinaphex ?)

**Comment by inactive123** [comment]
I have given @flyinghead (pretty much the main dev of reicast at this point) full admin rights over this repo, and he regularly updates it.

**Comment by hiddenasbestos** [comment]
no worries - was just wondering if I could commit to lending a hand but if it's active then I'll probably just get in the way, so happily to sit back and be patient!

**Comment by inactive123** [comment]
Nah, you won't get in the way - if there are commits for you to backport then I'm sure @flyinghead would also appreciate that as more hands makes for lighter work.

**Comment by flyinghead** [comment]
@hiddenasbestos if you find something missing from upstream please let me know.

I normally regularly backport everything from upstream but I might miss something.

**Comment by inactive123** [comment]
Try reading this too maybe - 

https://github.com/libretro/reicast-emulator/issues/80

**Comment by hiddenasbestos** [comment]
duplicate of #80

**Comment by hiddenasbestos** [comment]
FYI - recast upstream also has crash with this mode, so I've closed the bug!

**Comment by hiddenasbestos** [comment]
btw, @flyinghead and @twinaphex , apologies if I came across blunt / arrogant with the premise of my bug - big assumption on my part that the crash was it being out of date, rather than it being a known issue.

**Comment by inactive123** [comment]
No problem.
