### ISSUE TITLE
Reicast-WinCE: Sega Rally 2 Severe Stuttering Ingame

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#540]
First, tremendous thanks @flyinghead for such a critical feature as WinCE support.  This must not have been easy to implement.

As the title implies, going ingame on Sega Rally 2 produces severe stuttering where the entire game seems to halt for one second, progress for two seconds, halt for another second and so on.  Can assist with any logs etc. as needed, just let me know.

Tested on Linux x64, kernel 4.18 and compiled from fh/wince branch at commit 156da0748ec5d4fa77fe5482c4395d339d1890d5

**Comment by flyinghead** [comment]
Can you post some logs? Also what hardware are you running on?

A periodic one-second freeze shouldn't happen on any platform though.

**Comment by Shoegzer** [comment]
Sure, [here](https://pastebin.com/h7Wa955U) is a verbose log but if you need anything else please let me know.  

The test system is a i7-7820HK (mobile) cpu, with NVIDIA GTX 1070 and driver 390.116.

Playing the game again, it's more accurate to say the stuttering occurs about every quarter-second, with a half-second in between.  The only other WinCE-based game I own is Armada, and while that runs at maybe 15fps, it doesn't stutter.

**Comment by Shoegzer** [comment]
As of commit 4649dcf566445deaf168e8a7973d337e083877a1, the stuttering is now completely gone, and the game plays perfectly.  Closing this issue.  Seriously amazing work @flyinghead.  

Are there any blockers preventing your merging your reicast_wince branch into main?

**Comment by flyinghead** [comment]
No real blockers put it needs to be done without affecting the performance of the master branch.

**Comment by Shoegzer** [comment]
Got it.  I didn't notice any performance issues after your latest series of commits, but I haven't tested thoroughly yet.
