### ISSUE TITLE
Reicast-WinCE: Half Life crashes on load

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#541]
As the title implies, Half Life cdi crashes after the WinCE splash screen.  Can assist with any logs etc. as needed, just let me know.

Tested on Linux x64, kernel 4.18 and compiled from fh/wince branch at commit 156da0748ec5d4fa77fe5482c4395d339d1890d5

**Comment by flyinghead** [comment]
This is probably due to a hacked CDI. The half-life CDI I have uses the boot sector of Crazy Taxi (!) and is not recognized as a WinCE games, hence the crash.

**Comment by Shoegzer** [comment]
Interesting, I wonder why it's listed as playable [here](https://www.libretro.com/index.php/reicast-wince-libretro-experimental-core-released/).  @twinaphex do you know?  Perhaps whomever reported success could post the checksum here for comparison's sake.

**Comment by flyinghead** [comment]
I have a half-life GDI that works fine. Also the CDIs work if you force Windows CE mode (but this option is not exposed to end users)

**Comment by Shoegzer** [comment]
Ah yes, quite right.  I'm closing this issue but I need to re-open another graphiics-related one I discovered (more on that soon).
