### ISSUE TITLE
Reicast Aspect Ratio seems wrong (Windows X64)

### ISSUE THREAD

**Issue by hostile1975** [libretro/flycast#544]
Hi,
The aspect ratio of Reicast core is weird for me
For exemple 1:1 PAR is 3:4 (DAR) instead of 4:3 (DAR)
Is it working nice for you ?

Thanks

**Comment by Awakened0** [comment]
Maybe something to do with this commit?

https://github.com/libretro/reicast-emulator/commit/f327c19e4c4aaa71864d8dc2678fcdec28e3d64a

**Comment by flyinghead** [comment]
This looks suspicious (core/libretro/libretro.cpp:2048):
```
info->geometry.base_width   = screen_height;
```
@barbudreadmon Would you mind double checking?

**Comment by 2play** [comment]
i confrim same, compiled today for rpi and retroarch has Aspect Ratio 1:1 PAR is 3:4
Squeezed in the middle

**Comment by Scenekakashi** [comment]
Im getting the same Issues aswell, from the latest Reicast core for Retroarch.
and if you choose the widescreen hack option then it gets even more narrow

**Comment by 2play** [comment]
it can be fixed only by editing the retroarch settings by applying correct ratio. I have a FHD 16:9.
Previous core was having correct ratio.
So its def compile settings.
regards to all!

**Comment by barbudreadmon** [comment]
@flyinghead indeed, i commited the fix directly

**Comment by Awakened0** [comment]
PAR looks good to me now!

**Comment by hostile1975** [comment]
Tried this morning, and all is fine now
Thanks everybody
I close it now
