### ISSUE TITLE
Reicast-WinCE: Half-Life loading screen graphics issues

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#546]
Half-life looks mostly fine, though when you enter the room with the rotor (where things start to go awry in the game), you'll be directed to "climb up and turn on the rotors".  This will require you to ascend a ladder to the immediate left of the computer terminal on the ground.  However, the ladder, as well as the platform it connects to, is missing.

Tested on Linux x64, kernel 4.18 and compiled from fh/wince branch at commit 156da07

**Comment by flyinghead** [comment]
The missing graphics (ladders, platforms) should be fixed by this commit https://github.com/libretro/reicast-emulator/commit/f09bf6603ce45ff39ad69bc370ca47e6e5ea728b

**Comment by Shoegzer** [comment]
Indeed, nice improvement!  Before I close this issue though - I noticed that during the loading sequences, the game briefly shows the loading screen (with the word "Loading" on it), but then it flickers off while the orange loading bar is displayed, instead of showing both of them at once.  Should I keep this issue open as a placeholder for resolving that one, or is that part of a larger, known issue?

**Comment by flyinghead** [comment]
I noticed this problem. You can keep this issue open to track it, but you might want to rename it to something more specific.

**Comment by Shoegzer** [comment]
Thanks - done.  I can't confirm at the moment if this is also a problem on a real Dreamcast, though perhaps someone else can.  This game was a "beta" release after all.

**Comment by flyinghead** [comment]
The loading screen progress bar is drawn by directly writing to the framebuffer vram, which isn't supported at the moment. Other issues are fixed
