### ISSUE TITLE
Reicast Shader Issue. Mac OsX High Sierra

### ISSUE THREAD

**Issue by dragonstory** [libretro/flycast#548]
Hello

Retroarch 1.7.7 
Reicast core always crashes when i try to load any shader. 
Mac OSX High Sierra.
Normal Version not Metal version.

Reicast doesnt work with Metal.

This is from the Retroarc --verbose
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
Segmentation fault: 11

Process:               RetroArch [38557]
Path:                  /Applications/RetroArch.app/Contents/MacOS/RetroArch
Identifier:            libretro.RetroArch
Version:               1.7.6 (1.7.6)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           RetroArch [38557]
User ID:               501

Date/Time:             2019-05-12 14:05:04.224 +0300
OS Version:            Mac OS X 10.13.6 (17G6030)
Report Version:        12
Anonymous UUID:        A9B417FE-B7A8-A918-0D6E-DDADC002BEEF

Sleep/Wake UUID:       861F4E72-3D66-4E51-8555-61CC75652FCF

Time Awake Since Boot: 140000 seconds
Time Since Wake:       630 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00007ffee86acf0f
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0x7ffee86acf0f:
    MALLOC_TINY            00007fa166800000-00007fa166900000 [ 1024K] rw-/rwx SM=PRV  
--> STACK GUARD            00007ffee4ead000-00007ffee86ad000 [ 56.0M] ---/rwx SM=NUL  stack guard for thread 0
    Stack                  00007ffee86ad000-00007ffee8ead000 [ 8192K] rw-/rwx SM=PRV  thread 0

**Comment by flyinghead** [comment]
Assuming this is fixed. Reopen as needed
