### ISSUE TITLE
Bangai-O BGM Takes A Few Seconds To Start Playing (Redump (USA) Version)

### ISSUE THREAD

**Issue by Awakened0** [libretro/flycast#550]
It's quickest to notice this on the title screen or "Enter Initials" screen. The BGM, which I think is CD audio, takes a few seconds to start playing instead of playing immediately. I think the Japanese version has this issue too, but maybe not the PAL version. It's been awhile since I tested those two. I've found this issue with the USA version in both GDI and CHD formats.

This video appears to be the USA version recorded on real hardware and you can hear the audio change BGM instantly around the linked time: https://youtu.be/FyX8QDoEoZ8?t=533

**Comment by flyinghead** [comment]
I'm unable to reproduce this. I only tested the title screen, "Enter Initials" and the following screen.
On both USA and EU versions, the CDDA music starts playing as soon as the screen is displayed.

By the way this is logged by reicast. You should see a message like this when the cd starts playing:
```
param_type=1
cdda.StartAddr=400531
cdda.EndAddr=405533
cdda.repeats=15
cdda.playing=1
cdda.CurrAddr=400531
```
It would be interesting to check if and when you see these messages in the log.

**Comment by Awakened0** [comment]
That shows up in the log immediately on the title screen, then a second or so later the music starts playing. It's a redump verified GDI dump, so I don't think it's that...

**Comment by flyinghead** [comment]
No I don't think it's due to a bad dump. More likely something on your system is causing this.

Have you noticed audio lagging during games or other audio issues?

**Comment by Awakened0** [comment]
No. Never noticed anything like this in any other DC games I've tried. I don't have any audio issues comparable to this in any other cores I use either. CD audio is perfect in Beetle Saturn, Beetle PSX and GPGX. The only audio related one I have at all is just a regression in Sameboy that affects one game in specific situations that hasn't been fixed yet.

**Comment by flyinghead** [comment]
Any core setting that could cause this? Fast GD-ROM Loading enabled, DSP disabled, ...

**Comment by Awakened0** [comment]
Fast GD-ROM Loading is off, DSP is on. Audio buffer is at 1024, which I think is the default. Tried 2048 and it didn't help.

**Comment by flyinghead** [comment]
Can you test this issue again with the latest core version? Does using HLE BIOS make a difference?

**Comment by Awakened0** [comment]
Tried 66caec0eafe6424e1d970d47cf489f40cc57997e with HLE BIOS on and off and still get the music delay either way.

**Comment by flyinghead** [comment]
Thanks for your prompt answer. Unfortunately I did test it again on my end and still cannot reproduce the issue.

**Comment by Awakened0** [comment]
Yeah, strange. I'll be happy if someone else can at least reproduce it one day.

**Comment by bbbradsmith** [comment]
I had this issue just now with the ROM from the "RedumpSegaDreamcast20160613" set. I can reproduce the same problem with Demul, however, so I am inclined to think it's a problem with the dump?

I did not have the same issue with a different dump from "DreamcastCollectionByGhostwareMulti-region", or a third dump from an unknown source.

**Comment by Awakened0** [comment]
Thanks for posting your findings!

When I initially made this issue I was using a Bangai-O (USA) dump verified from the 2016 Redump set. And I've tested a newer bin/cue 2019 Redump one that also has the delay. You're right though; the Ghostware one (Bangai-O v1.001 (2000)(Crave)(NTSC)(US)[!]) doesn't have the delay.

I would think the latest Redump bin/cue would be the cleanest/proper dump to use. Maybe @flyinghead or someone knowledgeable can compare the dumps and see if it's something with the dump or the emulator. Redump uses all .bins for the audio tracks, while Ghostware uses mostly .raw. The Redump .cue [looks like this](http://redump.org/disc/22064/), while the Ghostware's .gdi looks like this:
```
37
1 0 4 2352 track01.bin 0
2 600 0 2352 track02.raw 0
3 45000 4 2352 track03.bin 0
4 240211 0 2352 track04.raw 0
5 250125 0 2352 track05.raw 0
6 251398 0 2352 track06.raw 0
7 256338 0 2352 track07.raw 0
8 260383 0 2352 track08.raw 0
9 265868 0 2352 track09.raw 0
10 279695 0 2352 track10.raw 0
11 292658 0 2352 track11.raw 0
12 298807 0 2352 track12.raw 0
13 312225 0 2352 track13.raw 0
14 324639 0 2352 track14.raw 0
15 339175 0 2352 track15.raw 0
16 346593 0 2352 track16.raw 0
17 354785 0 2352 track17.raw 0
18 359333 0 2352 track18.raw 0
19 369096 0 2352 track19.raw 0
20 378987 0 2352 track20.raw 0
21 389919 0 2352 track21.raw 0
22 394765 0 2352 track22.raw 0
23 400381 0 2352 track23.raw 0
24 405533 0 2352 track24.raw 0
25 410170 0 2352 track25.raw 0
26 411232 0 2352 track26.raw 0
27 415248 0 2352 track27.raw 0
28 420519 0 2352 track28.raw 0
29 425910 0 2352 track29.raw 0
30 440249 0 2352 track30.raw 0
31 448151 0 2352 track31.raw 0
32 456528 0 2352 track32.raw 0
33 466183 0 2352 track33.raw 0
34 476956 0 2352 track34.raw 0
35 486182 0 2352 track35.raw 0
36 493042 0 2352 track36.raw 0
37 499070 4 2352 track37.bin 0
```

**Comment by flyinghead** [comment]
I've never been able to reproduce this issue but my copy is named Bangai-O v1.001 (2000)(Crave)(NTSC)(US)[!] so it's likely not the Redump release.

**Comment by Awakened0** [comment]
Yep, that rules out my PC being the problem at least. Hope you get some time to try out the Redump version.

**Comment by flyinghead** [comment]
I just pushed a fix that I hope will take care of this issue. Please retest and report.

**Comment by Awakened0** [comment]
Yes, that fixes the bin/cue dump. The gdi converted to chd still has the gap though; I'm guessing a similar change would have to be made to gdi.cpp and/or chd.cpp?

**Comment by flyinghead** [comment]
GDI is another issue because it seems Redump gdis are different. I'm not sure the fix for CUE files is correct but I can't do the same for GDI as it will break all working GDIs.

**Comment by Awakened0** [comment]
I'm going to close this since a (USA) bin/cue converted to chd doesn't have this issue with the latest upstream core.
