### ISSUE TITLE
Keyboard input for Naomi games broken

### ISSUE THREAD

**Issue by Rheph** [libretro/flycast#552]
Naomi games that use keyboard inputs (Typing of the Dead, Lupin III: The Typing) do not recognize any keystrokes when controller is set to 'keyboard'. I have made sure Game Focus is on and the 1P controller is 'Keyboard'. 
I know at least Lupin Typing used to work, but I am not sure when this issue began.
I am using the latest version of Retroarch (1.7.7) for Windows.

**Comment by flyinghead** [comment]
PR #553 should fix the problem

**Comment by cubatilles** [comment]
Hi @flyinghead ,

I opened an issue [#537](https://github.com/libretro/reicast-emulator/issues/537) some weeks ago, very similar to this one. Lightgun movements are not responding on Naomi (dreamcast is fine). Gun trigger works but aiming isn't. Other pepople on libretro forums have had the same issue, so it's not a problem from my side.

Would you look at it? Greetings.

**Comment by Rheph** [comment]
Works perfect now, thanks!
