### ISSUE TITLE
Reicast-WinCE: Starlancer stuck at WinCE bootup screen

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#554]
As the title implies, Starlancer is stuck at the WinCE bootup screen. Curiously, if you wait about 10 seconds after the screen first appears and press "A" on the controller, you can hear a sound effect - not sure what that's from though.  I can assist with any logs etc. as needed, just let me know.

Tested on Linux Mint / Cinnamon x64, kernel 5.0 and compiled from fh/wince branch at commit e2b6e442a48ede31d02ab7d088d7f1d153d5b182

**Comment by flyinghead** [comment]
I tested both the US and EU releases and they won't boot with broadcast set to Default. You have to specify the broadcast standard explicitly.
In the case of the EU release, it won't boot with broadcast=PAL but works fine with broadcast=NTSC. No idea why.

**Comment by Shoegzer** [comment]
Very odd.  Normally I'd say it's a problem with the Reicasts' ability to detect the correct broadcast mode in Default, but with the EU release issue I'm not so sure.  In any event I've tested your observation and concur, so I'll close this out.  Thanks.

**Comment by flyinghead** [comment]
These issues don’t happen with upstream. Probably something I forgot to backport from upstream. Already spotted something but I will give it another look.
