### ISSUE TITLE
All WinCE games crash Retroarch to desktop

### ISSUE THREAD

**Issue by boomercore** [libretro/flycast#559]
Was able to get these working a few builds ago, back when it was a separate core for WinCE specifically, but I no longer see that core available on the updater.  I presume now that this functionality is part of the main Reicast core now.  Correct me if I'm mistaken.

At this point all WinCE games make it to the WinCE splash screen, then dump to desktop regardless of region and broadcast.  Made sure non-WinCE Dreamcast games still play, and they do. 

Logs all end with the following:  

[libretro INFO] Verify Failed  : !(state.cpu.is_delayslot && OPCODE_SETPC(OpDesc[op]->type))
 in dec_DecodeBlock -> core/hw/sh4/dyna/decoder.cpp : 1025 
[libretro INFO] Fatal error : iNimp reached

**Comment by flyinghead** [comment]
No, the WinCE core hasn't been merged into the main core yet. The WinCE core should still exist but this may be a side effect of the recent renaming

**Comment by flyinghead** [comment]
Should work now. Please reopen as needed.
