### ISSUE TITLE
Typing of the Dead: No Keyboard Input

### ISSUE THREAD

**Issue by Nine-H** [libretro/flycast#56]
I suspect that we don't have keyboard support and this might have something to do with it.

**Comment by Nine-H** [comment]
It came good, however it boots to a black screen that reads "You need a Dreamcast Keyboard to play..."

**Comment by Kondorito** [comment]
Hey Nine-H! I was wondering the same thing. Do you have any news about this? There is no way of selecting keyboard as the input at the moment, right?

**Comment by Nine-H** [comment]
I have no idea, upstream doesn't appear to have keyboard support (in fact TOTD segfaults upstream) so it's not as simple as wiring in the retroarch keyboard implementation and I have no idea a) how the dreamcast implemented keyboards, or b) how reicast works, I just kind of black box test and file bugs.

edit: there's a PC port that's kind of sucky but I recall it sort of worked on windows 7.

**Comment by Nine-H** [comment]
One thing to do for this bug is find a project that documents the dreamcast keyboard interface, so an open adaptor that connects a dreamcast keyboard to ps/2 or usb or an open adaptor that connects a normal keyboard to a dreamcast, it's important that it's open, because we want the code.

**Comment by Kondorito** [comment]
Makes sense. I will look it up, see what I can find.

**Comment by Nine-H** [comment]
ok, afaict it's just a PC keyboard w/ a DC plug. I found a dude that did a converter to PC with an ATmega and he just reads the keycodes straight into the usb input buffer with the same function he reads controller bytes with.

Project: http://www.raphnet.net/electronique/dreamcast_usb/index_en.php
Code: https://github.com/raphnet/dreamcast_usb
Keyboard commit: https://github.com/raphnet/dreamcast_usb/commit/c8068983551763c508e7dafdeff91ccabaed45eb

this page documents the JP version http://mc.pp.se/dc/kbd.html

**Comment by inactive123** [comment]
Did NullDC have keyboard support? Maybe we can backport it from that?

**Comment by Shoegzer** [comment]
@twinaphex yes, it does.

**Comment by Nine-H** [comment]
closing this because we have enough input to boot now and #284 tracks the missing keys issue.

**Comment by joshterrill** [comment]
For whatever it's worth, I am playing Typing of the Dead on Flycast MacOS, version 1.0 (1) from this release on another fork: https://github.com/flyinghead/flycast/releases/tag/v1.3 and I was able to change the settings under Settings -> Controls. As long as I had keyboard set in Port A on top and Device A under Dreamcast Devices on bottom, it works just fine.

<img width="635" alt="Screen Shot 2022-07-13 at 5 48 44 PM" src="https://user-images.githubusercontent.com/5368757/178861178-39729425-2e1a-4fef-b5ef-26ee419203bf.png">
