### ISSUE TITLE
Atomiswave light gun games missing controls

### ISSUE THREAD

**Issue by toccata10** [libretro/flycast#564]
Here are my tests related to ligh gun games with atomiswave: there are some missing controls: I go to the the test menu then change the controls to "light gun", and use my mouse to test (with this procedure, I'm able to play most naomi light gun games with 1 mouse (as multi-mouse doen't work at the moment #562)). 
1) rangrmsn: I can make the pump + start buttons recognized, but I can't fire and I can't move the mouse.
2) sprtshot: in test mode: I can calibrate the light gun (a bit clumsy but works). In game: it works for player 1. For player2: I can shoot but I can't mouse the cursor, so it's always in the center.
3) xtrmhunt: in test mode: I can make the pump + start buttons recognized, but I can't fire (the trigger status seems to change quickly from 0 to 1 when I'm not pressing anything). The mouse is moving for players 1 and 2.
4) xtrmhunt2: "100 netbd not respond" error message (doesn't boot)

**Comment by r3tro80** [comment]
@toccata10 

How did you managed to play lightgun games with a mouse? If i set the control to "lightgun" i have no others buttons working so i cannot insert coin or start game! Instead if i set control to "controller" i can't move the pointer with my digital dpad.

Another question is: do the Gunsight works for you? If i enable it i can't see any Gunsight on screen.

Thanks!

**Comment by toccata10** [comment]
In retroarch: Input>User 1 binds: adjust "user 1 mouse index" (error-try method).
Then you can set the Gun controls. Depending on the game, the "reload" might be "Aux A".
Then when you're in the game, you can select "lightgun" as the controller to play with the mouse.
![Capture_035](https://user-images.githubusercontent.com/7478580/61268366-7ec32b00-a79b-11e9-86d6-31b3fbd18df4.jpg)

**Comment by r3tro80** [comment]
Thank you, now i can start game with Coin & Start.
My problem now is that the trigger is stuck at the upper left corner and i can't shot in any other spot! I will investigate!

PS: i tried only House of The Dead 2.

**Comment by flyinghead** [comment]
Only xtrmhunt2 still isn't working. All other atomiswave lightgun games are playable.
