### ISSUE TITLE
Core segfault when open a game in Android aarch64

### ISSUE THREAD

**Issue by Marukesu** [libretro/flycast#565]
Whenever I open a game the emulator closes instantly ever before the bios load.

Here's the log: https://pastebin.com/EqVEtRvN

**Comment by flyinghead** [comment]
I tested flycast in both arm32 and aarch64 android without issue. Try to uninstall/reinstall retroarch and make sure to use latest versions for retroarch and flycast.

**Comment by Marukesu** [comment]
Now he open but the controls doesn't work. Even if it's a gamepad or the touchscreen

**Comment by flyinghead** [comment]
Go to `Settings -> Input -> Poll Type Behavior` and set it to `Early`

**Comment by Marukesu** [comment]
That worked, thanks
