### ISSUE TITLE
Naomi 15khz dipswitch

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/flycast#569]
A core option was added to enable this dipswitch in https://github.com/libretro/flycast/commit/eee231901c4ef18b5cad75b6e6517b97ebc5a608, but the thing is we don't know much about it.
The things we know : 
- Some games won't work with this dipswitch enabled (there is an explicit message asking to set the cabinet to 31khz)
- Most games will render at 480i with this dipswitch
- 1 game seems to render at 240p with this dipswitch (wldkickspw)

Are we missing something to make games natively rendering at 240p ? Or was it only possible through an I/O board to convert vga signal to rgb on original cabinet ? We lack informations, maybe someone can help (@p1pkin ?).

Don't try setting resolution to 320x240 in core options, it will only downscale the 480i signal and the result will be awful.

**Comment by p1pkin** [comment]
in short - NAOMI games designed for 31kHz VGA displays, 15kHz is an option. if I'm not mistaken, all original dedicated game or common Sega JVS cabs was 31kHz.

in general, almost all Dreamcast games works in 480i if use TV/15kHz display, and quite few uses 240p.
in several Capcom's 2D games you may hold buttons combo while booting to change display modes.

**Comment by barbudreadmon** [comment]
So you confirm there is no way to force the naomi board to output 240p directly ? `wldkickspw` is just an oddball ?

**Comment by p1pkin** [comment]
right, there is no way. most if not all NAOMI games hardcoded to 480i in case of 15kHz display.
