### ISSUE TITLE
Flycast CE crashing on content loading (Win x64)

### ISSUE THREAD

**Issue by stuken** [libretro/flycast#573]
As per title, build acb9677 is crashing as soon as a gdi is loaded. The bios screen is not displayed and retroarch completely crashes out. Attaching log and crash log.

[out.log](https://github.com/libretro/flycast/files/3357854/out.log)
[crash-190703-233034.log](https://github.com/libretro/flycast/files/3357855/crash-190703-233034.log)

**Comment by flyinghead** [comment]
Good catch! and thank you for the detailed logs.

Should be fixed by https://github.com/libretro/flycast/commit/fec186e9e9e6a1ec31b9d38b160cf78fc5932f72

**Comment by dukeblooders** [comment]
I tried a few games, it seems to be good on my side.

**Comment by stuken** [comment]
Fix confirmed. No more crashing.
