### ISSUE TITLE
Games Crash on loading under Arch linux

### ISSUE THREAD

**Issue by Lampwick** [libretro/flycast#574]
I can't get any games to load. I have the correct bios files and they are in the right location. I've attached a logfile.
[retroarch.log](https://github.com/libretro/flycast/files/3361045/retroarch.log)

**Comment by flyinghead** [comment]
Can you try the fh/wince branch?

I have no idea what's going on so perhaps the wince branch will tell us more. It's encountering an invalid sh4 instruction very early on so something is wrong with the memory or dynarec.

**Comment by Lampwick** [comment]
Same result with fh/wince.

[retroarch.log](https://github.com/libretro/flycast/files/3370529/retroarch.log)

**Comment by flyinghead** [comment]
Assuming resolved. Reopen as needed
