### ISSUE TITLE
Sega Rally 2 fails to load(Win x64)

### ISSUE THREAD

**Issue by stuken** [libretro/flycast#575]
Sega Rally 2 USA currently will not load. After a few moments sitting on the loading screen the game is kicked back to the bios. A few attempts can usually be made to try reload through the play option but it will randomly attempt to load and fall pack to the bios again or freeze retroarch completely.
Attaching log but it doesn't appear to have any useful info or errors noted. 
[out.log](https://github.com/libretro/flycast/files/3362798/out.log)

**Comment by flyinghead** [comment]
I noticed it as well. Going back in time I cannot find any version that loads the game correctly so something must be wrong in my environment.

Apparently it boots fine if I don't have any controller attached (like selecting None or Keyboard as input). Can you try this on your side?

**Comment by elcorsico** [comment]
boots fine , but crash et reload in bios dreamcast 
test in controller attached et test in keyboard

**Comment by stuken** [comment]
With all input disabled the game displays a warning about requiring space to save. this prompt requires confirmation so I connected a controller. This results in a freeze as the loading screen fades out but no falling back to the bios.
With input 1 set to keyboard I get the same freeze as the loading screen fades out. In both cases retroarch does not completely freeze and flycast can be cleanly exited.

I've also tried a vmu file created in demul with a save for the us version on it. This will display a prompt to load the game which after confirming results in the same freeze as the above. Attaching the save as it might be useful as a breakpoint to debug from.
[vmu_save_A1.zip](https://github.com/libretro/flycast/files/3370098/vmu_save_A1.zip)

**Comment by devi77** [comment]
Latest working version
[flycast_wince_libretro.zip](https://github.com/libretro/flycast/files/3425940/flycast_wince_libretro.zip)

**Comment by mrneo240** [comment]
its a hardware consistent issue due to malformed maple packets.

**Comment by flyinghead** [comment]
Could one of your vmu files be corrupted? One of mine was 32 MB (!), probably the result of an earlier problem. After I deleted it, Sega Rally booted just fine.

I tried the the vmu save from demul and it loaded fine.

**Comment by stuken** [comment]
It's still jumping back to the bios. Both with the attached vmu and in a totally clean retroarch installation.

**Comment by medievil1** [comment]
bios here too...was helping someone on discord with it and discovered the issue was with flycast and not his setup(both doing the same thing) when it boots back to bios... 6 to 8 of 10 times a close content will crash Retroarch as well

**Comment by flyinghead** [comment]
should be fixed by https://github.com/libretro/flycast/commit/b5331915f7b85d025c70b4bc021b4e4fc50f7cff

**Comment by stuken** [comment]
Confirmed working after the latest nightly build.
