### ISSUE TITLE
Flycast crashes after a few seconds

### ISSUE THREAD

**Issue by enolp** [libretro/flycast#576]
Flycast (and Retroach) crashes a few seconds (some times one second) after a game is loaded, if fast forwarding or slow motion are enabled, this does not happen. It seems to be related to Xorg server but I attach the debug info from the verbose output for more information.
I'm using Arch Linux and the "gl" video driver, using "glcore", "gl1" video drivers I got the same problem

[log.txt](https://github.com/libretro/flycast/files/3364186/log.txt)

**Comment by flyinghead** [comment]
That might be an issue with the video driver. Try to downgrade or upgrade the mesa driver and see if it helps.

**Comment by enolp** [comment]
I've updated my graphical stack to git versions but I'd got the same problem. However, I got a different X error. See the end of file:

[log.txt](https://github.com/libretro/flycast/files/3365730/log.txt)

**Comment by enolp** [comment]
More findings, on a Wayland session this problem does not occur and all it's working as expected
