### ISSUE TITLE
Flycast Core - Sprites Glitches

### ISSUE THREAD

**Issue by techjune** [libretro/flycast#577]
First of all thank you for making such a great core
just have one problem and I seek advice.

Game : Capcom vs SNK 2
Problem : 2D character sprites is split and spaced. (1 Pixel?)
Hardware : Amazon Fire TV Stick 4K

**Remarks :**
The problem only occurs at a specific internal resolution : **640x480**
(Perfect at all different internal resolutions)

**Comment by flyinghead** [comment]
Could you post a picture? I don't see any issue.

![Capcom vs  SNK 2 - Millionaire Fighting 2001 v1 001 (2001)(Capcom)(NTSC)(JP)(en) ! -190707-130321](https://user-images.githubusercontent.com/16261910/60767399-c40a9d00-a0b7-11e9-8cb8-ab5e9b6bb22d.png)

**Comment by techjune** [comment]
![cvs2-190707-161018](https://user-images.githubusercontent.com/32924449/60767869-e1139000-a0f8-11e9-80e3-18e78fa72af9.png)
![cvs2-190707-161000](https://user-images.githubusercontent.com/32924449/60767870-e1139000-a0f8-11e9-86bf-8f2d78c45de6.png)

It's perfect except 640x480 internal resolution, sir

**Comment by Philps** [comment]
i did see this with the liberto reicast core, when switching to flycast i could see lots of improvements on 2D Games eg. Capcom vs SNK, MvC2 

HW: Amazon Fire TV Gen2
Resolution: 640x
Widescreenhack enabled

**Comment by flyinghead** [comment]
Tested today with latest core version and I don't see any artifact at native resolution (640x480).

Please retest and let me know.
