### ISSUE TITLE
flycast not working now

### ISSUE THREAD

**Issue by elcorsico** [libretro/flycast#578]
hi dev , please delete bug in flycast 
now another game dreamcast CE are no working , why
test in X64 v1.7.7 _ Game : sega rally 2.chd

thanks for reply ;-)
tchuss

**Comment by flyinghead** [comment]
duplicate of #575

**Comment by flyinghead** [comment]
should be fixed by https://github.com/libretro/flycast/commit/b5331915f7b85d025c70b4bc021b4e4fc50f7cff
