### ISSUE TITLE
Flycast crashes immediately after loading content on RetroArch Android

### ISSUE THREAD

**Issue by DylwinTFTW** [libretro/flycast#579]
When I try to load my Sonic Adventure .gdi file in flycast it crashes. I keep the files in my roms folder. I have tried relaunching, moving my bios files to the system folder, creating a BIOS folder, and opening the zip file. The first two crash the app, but the zip file opened it once but didn't show the option for flycast or saying failed to load content. When I first boot up RetroArch, the .gdi file doesn't even appear, and I have to select the .bin file instead, and it says failed to load content and opens the Mupen64Plus-Next core for some reason. I then load flycast again and this time it shows it. Does anyone have any suggestions?

**Comment by flyinghead** [comment]
The `dc_boot.bin` and `dc_flash.bin` firmware files need to be in a directory named `dc` in RetroArch's system directory.

Do not open .bin or .zip files directly. Only open .gdi files.

**Comment by DylwinTFTW** [comment]
Thaky you, but now the screen is black.

**Comment by Philps** [comment]
Check the Documentation about the pre-requisites: http://docs.libretro.com/library/flycast/

**Comment by flyinghead** [comment]
Assuming resolved. Reopen as needed
