### ISSUE TITLE
Flycast controls: Digital to Analog support... when?

### ISSUE THREAD

**Issue by r3tro80** [libretro/flycast#580]
Will be ever available a controls support to map digital dpad/buttons to analog controls in order to use a simple joystick or button for steering, accelerate, move gunsight, etc..?

**Comment by barbudreadmon** [comment]
You can do that using RA's remap menu. It's not recommended for obvious reasons though.

**Comment by r3tro80** [comment]
Do you mean the "Analog to Digital" option in the Input menu or RA?
What i meant was the contrary.
A Digital to Analog option to be able to play driving and gun games with a digital stick (without any analog controls).

**Comment by barbudreadmon** [comment]
No, i mean simple remapping, in this menu you can select actions for each button, as an example you can associate "Analog X-" & "Analog X+" to "D-Pad Left" & "D-Pad Right" (maybe not in this order). Afaik "Analog to Digital" is actually useless, confusing, and it could also be harmful for games using dpad & analog for different purpose, imho it should be removed.

> be able to play driving and gun games with a digital stick (without any analog controls).

This is a big overstatement, digital inputs are different from analog inputs, and there is a reason for those games to use analog inputs. Would you drive your car using a snes controller ? I don't think so.
