### ISSUE TITLE
Apk crashing upon launching

### ISSUE THREAD

**Issue by RaduNastase** [libretro/flycast#581]
Hello, i have a Galaxy Note 3 with 4.4.2 KitKat Android and both Flycast_Dreamcast and Flycast_Naomi install ok, but crash when i try to open the emu.  Reicast work well, no problems.

Thanks for the hard work! :D

**Comment by flyinghead** [comment]
If you're using standalone flycast then please use my repo to report issues: https://github.com/flyinghead/flycast/issues

That being said, I just tested Flycast on Android 4.4.4 without issue. I will need more information to help you: hardware platform, version tested, game tested, logs, ...
