### ISSUE TITLE
Geom GLSL Shader Drop Performance drastically - Amazon Fire TV Gen2 - Marvel vs. Capcom 2

### ISSUE THREAD

**Issue by Philps** [libretro/flycast#585]
First of all. Big shout-out and kudos!

The Game Performance and Compatibility increased notably from reicast -> flycast !

I can run "MvC2" and "SNK vs Capcom" in Full Speed with the default settings on a Fire Tv Gen2 with X360 Controller without having glitches and using WideScreen Hack.

As for the shader, when i enable the Geom Shader (640x Resolution) it looks notably nicer but Audio Stutters and Frame Rate drops dramatically. 

Is this shader related or can there be something done in FlyCast?

**Comment by flyinghead** [comment]
That's good to hear!

As for the crt-geom shader (I assume that's the one you're using) or any retroarch shader, there's nothing the core can do as this is a post-processing pass done by RA.
