### ISSUE TITLE
Feature Request: Make Customer Texture Folder configurable

### ISSUE THREAD

**Issue by Philps** [libretro/flycast#587]
Due to problems with moving RetroArch to SD Card [ See: https://github.com/libretro/RetroArch/issues/8353 ] there is limited amount of space on most of the Android Boxes, so custom texture would need to be outsourced to an SD Card.

Unfortunately this is not configureable.

At the moment they all need to go into RetroArch System Folder

**Comment by flyinghead** [comment]
Unfortunately this can't be done in the core: core options can only have a limited number of values. There's no way to select a directory or input text with a keyboard.

RetroArch and the libretro API would have to be modified for this so fixing the referenced issues is probably an easier target.
