### ISSUE TITLE
(Naomi) World Kicks

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#588]
The gunsur2 and gunsur2j fix from WinCE branch also fixed the booting issue for wldkicks, wldkicksu but there are control issues. It also crashed after a few minutes of gameplay.

https://github.com/libretro/flycast/commit/4a091d84ee57b8d708a73ec32c1d9ef900ae8e89

**Comment by blisstik** [comment]
World Kicks issue details:
- ~~Character always moves to the top left of the screen.~~ Needs config in GAME TEST MODE
- In GAME TEST MODE, the 1P controller can control other player buttons
- In GAME TEST MODE, there seems to be an input for the direction of the kick buttons that can't be mapped
- In GAME TEST MODE, both kick buttons are ON by default and turn off when controller is pressed. I think it should be reversed
- Some graphical glitches that can cause a crash

**Comment by r3tro80** [comment]
> World Kicks issue details:
> 
> * During gameplay, the character always moves to the top left of the screen.
> * In test mode, the 1P controller can control other player buttons
> * Some graphical glitches that can cause a crash

The "top left" bug maybe affects some other naomi games with analog controls... Alien Front for example always turn left and house of the dead 2 has the gun trigger stuck at the top left position.

**Comment by flyinghead** [comment]
Alien Front Online works fine if you map controls correctly. Same for hotd2 if you use a lighgun.
World Kicks controls are not currently supported so there’s no way to map them correctly iirc.

**Comment by blisstik** [comment]
@fastpop72 - try putting these eeprom and nvmem files along side the alienfnt.zip

http://s000.tinyupload.com/index.php?file_id=86236612936964466665

**Comment by blisstik** [comment]
@flyinghead  - I've updated my findings for World Kicks input

**Comment by barbudreadmon** [comment]
Could probably be solved by my custom eeprom loading stuff. I'll take a look soon.

**Comment by r3tro80** [comment]
@blisstik thanks you for your eeprom files... Now Alien Front works and can be played with a digital stick too. You got others eeproms?

I managed to work hotd2 too with a mouse. The only issue is i can't enable the gunsight! @flyinghead how the "gunsight enable" option works?

**Comment by flyinghead** [comment]
Inputs should now work after this: https://github.com/libretro/flycast/commit/bfb9ccea4a7292f70266efecbd5eaf1a670f7999. The ball kick emulation might need some refinement.

However there are still huge graphic glitches
