### ISSUE TITLE
analog triggers only work over 50% of full range

### ISSUE THREAD

**Issue by mickski56** [libretro/flycast#59]
analog triggers only work from 50%  to 100% of their full range, ie trigger has to be half way to full defection before it starts to work.

This is with retroarch git ca3b8149a8 and reicast core git 13dacb00.
OS is linux, retroarch input driver is udev tried sdl2 too.
Tested with V rally2 (europe) and metropolis street racer (europe)
pads tested  xbox 360 wired and Dualshock3 bluetooth.

**Comment by mickski56** [comment]
Um this may be an issue with the way retroarch assigns axes, eg  -0 +0 for the first x axis left and right with 0 being in the centre, which doesn't make as much sense for a trigger . It doesn't seem to have a way to assign the entire axis. So probably not a reicast bug as such.

**Comment by Shoegzer** [comment]
@mickski56 Interesting.  I can replicate with linux/udev/ds4 pad as well.  It's easily seen in the Daytona USA "analog calibration" section where the gas jumps from 0% to 100%.

I'm not convinced this is an RA core issue though - if so, this would have been a major issue for people using the beetle-psx core - I've personally played several games with that core that make heavy use of analog triggers such as Gran Turismo 2, and IIRC it's just fine there.  

Edit: Actually, the triggers on the original PS1 dualshock controller were pressue-sensitive, not full analog.  So it's possible the lack of true analog range didn't matter to most people in that case - and so it may very well be an RA-generalized issue.

Anyway, could you please reopen this issue or at least make a new one for RA itself?

@hiddenasbestos any thoughts here?

**Comment by hiddenasbestos** [comment]
Ignore my original comment. 

Triggers should work. Could be a front-end issue? core seems fine to me and doesn't have a 50% deadzone as described in the original report.

F355 Challenge has a very handy calibration display - try that?

**Comment by mickski56** [comment]
Just tried F355 Challenge's calibration display, I'm still getting 50% deadzone.
@hiddenasbestos  do you use controller autoconfig ? I do the relavent lines in mine are

input_l2_axis = "+2"
input_r2_axis = "+5"

which is where the problem comes from as evtest confirms l2 axis is of the form -2 0 +2
I tried just putting 2 but no joy.

**Comment by hiddenasbestos** [comment]
I use an Xbox One pad on Windows 10 with the "dinput" input driver and "xinput" joypad driver and yes I believe it's auto-configured in RetroArch as I've done bind default all.

for me the triggers are:
input_l2_axis = "+4"
input_r2_axis = "+5"

The core is expecting a value of 0 -> 32767 from the front-end, if it's not getting that the triggers aren't going to work correctly. Not really sure how I can help you - this sounds like a Linux / front-end problem, not a bug in the core.

**Comment by mickski56** [comment]
I agree definitely not a bug in the core. I'll stop posting here.
I was just trying to work out which bit was giving me trouble.
Thanks for the replies.

**Comment by Shoegzer** [comment]
Thanks for your thoughts.  So it's an RA issue after all, it seems.  @twinaphex who would be the best person to look into this further?
