### ISSUE TITLE
Silent Scope not working

### ISSUE THREAD

**Issue by dukeblooders** [libretro/flycast#591]
The game freezes on the first mission (but sound keeps playing).

- PAL version (.gdi file, tried with USA et Europe regions, also tried with per-pixel or per-triangle alpha sorting).
- Windows 10 x64

Nothing particular in the logs unfortunately.

**Comment by flyinghead** [comment]
Should be fixed by https://github.com/libretro/flycast/commit/81f69198f9a013dc7a5c20a9c01e2fc40e21ff60

I assume this is with the WinCE core (shouldn't happen with the regular one). Also, only happens if Threaded Rendering is on.

**Comment by dukeblooders** [comment]
Tested with latest nightly, works fine. Thanks !
