### ISSUE TITLE
Tomb Raider - Last Revelation, Flycast WinCE regression

### ISSUE THREAD

**Issue by paivaleonardo** [libretro/flycast#593]
The game starts, does not display the Eidos logo cg, only sound, and then hangs forward.
Windows x64 core.

**Comment by flyinghead** [comment]
should be fixed by https://github.com/libretro/flycast/commit/b5331915f7b85d025c70b4bc021b4e4fc50f7cff

**Comment by flyinghead** [comment]
Closing, reopen if problem persists
