### ISSUE TITLE
fails to open zip files

### ISSUE THREAD

**Issue by Kallin** [libretro/flycast#594]
I have some Dreamcast games stored in Zips with .gdi, .bin and .raw files included. When I try to load content directly with this core retroarch crashes. If I first extract content and then load the gdi file directly, it works. On all other platforms I've tested I can load zip files directly, and it would be very convenient (and space saving) to be able to do so with this core as well.

**Comment by barbudreadmon** [comment]
duplicate of https://github.com/libretro/flycast/issues/421
