### ISSUE TITLE
Small sprite glitch in Marvel vs. Capcom 2

### ISSUE THREAD

**Issue by Immersion95** [libretro/flycast#596]
Hi,

There is a small glitch in this game, it happens during Ryu's "Shinku Hadoken".

It is really not a big deal, I just thought it deserved to be reported :)

Thanks for all of your work, Flycast is by far my the best DC emulator for me !

![Marvel vs  Capcom 2 - New Age of Heroes (Japan)-190804-181207](https://user-images.githubusercontent.com/47425204/62426336-bdd20580-b6e3-11e9-800f-5afb4d7fc7d7.png)

**Comment by ToniBC** [comment]
That error is quite common when using resolutions larger than the original or some texture filter. You would have to specify the settings you use.

If it's something I said before, I think the solution is complicated.

**Comment by Immersion95** [comment]
> That error is quite common when using resolutions larger than the original or some texture filter. You would have to specify the settings you use.
> 
> If it's something I said before, I think the solution is complicated.

The glitch is present on all the resolutions and with "per-pixel" too.

**Comment by ToniBC** [comment]
Yes, you are right, I checked it with several resolutions, without filters and they really give them that error.

I don't know if you also published it in the Reiscats git, but it would be nice to publish it there too, since it is more likely to be repaired in the other.

**Comment by Immersion95** [comment]
As I posted in the reicast github, this issue is there on almost all the emulators except for Redream

https://twitter.com/inolen/status/1039226899250262017

**Comment by flyinghead** [comment]
Tested today with latest flycast version and there is no artifact when rendering at native resolution (640x480). Please test again and let me know.

**Comment by ToniBC** [comment]
These errors continue to appear with the latest version Flycast 0.1 66caec0.

With the native resolution 640x480 no black stripes come out but if white and with more resolution they remain black.

The cutting areas are seen.

![Marvel vs  Capcom 2 - The New Age of Heroes (USA)-190919-235758](https://user-images.githubusercontent.com/45365478/65284439-c9657880-db39-11e9-8b70-e3882275f353.png)
![Marvel vs  Capcom 2 - The New Age of Heroes (USA)-190919-235803](https://user-images.githubusercontent.com/45365478/65284448-cd919600-db39-11e9-8dba-1cf92c789c89.png)

**Comment by Immersion95** [comment]
Thanks for your input @ToniBC

**Comment by Immersion95** [comment]
Is it still there ?

I can close the issue then.

**Comment by ToniBC** [comment]
I keep observing the same error with resolutions higher than the native, the black stripes are still present in the game with certain attacks.

With the native resolution of 640x480 it seems that the error has already been solved.

**Comment by HebuSan** [comment]
Hi. I can confirm I also suffer this issue for more than two years, not matter the core version of flycast / retroarch.
Tested on three different laptops, on windows, with various Nvidia GPU ( 960, 970 and 3060).
Checked today again, with latest versions available of retroarch (1.9.14) and latest flycast core.
Any resolution greater than 640 * 480 produces the bug.
I don't have the skills to fix the issue, but I am ready to help testing any patch if it can help.
