### ISSUE TITLE
Threaded Rendering causes problem with "Street Fighter III: 2nd Impact - Giant Attack"

### ISSUE THREAD

**Issue by Immersion95** [libretro/flycast#598]
Hi,

When the "Threaded rendering option" is on, the game framerate stutter a lot (like 0/1 FPS per second).

The strange thing is that it displays all the FPS when the throttle option is off.

No problem with "Threaded rendering option" being off but the Shield TV isn't strong enough to play it at full speed then :(.

**Comment by Immersion95** [comment]
Update : The problem seems to be related to Vsync+Threaded rendering instead.

When vsync is off, it does work as intended !

The problem is that it becomes choppy :p

**Comment by Immersion95** [comment]
Update : I can almost close this issue as the Flycast WinCE core solves this in Android.
I'm waiting for the fusion of both cores to check if it still work and I'll close it.

**Comment by flyinghead** [comment]
They have been merged: you can use the regular flycast core from now on.

**Comment by Immersion95** [comment]
Hi, I will wait for the new core to be built as I tried the latest regular Flycast core and it still doesn't work. No problem with Flycast WinCE though.

**Comment by Immersion95** [comment]
It works thanks !
