### ISSUE TITLE
Black screen with sound on Indie releases (Gunlord, NeoXYX, Last Hope etc)

### ISSUE THREAD

**Issue by PanosPl** [libretro/flycast#599]
When loading certain "indie" releases like Gunlord, Last Hope etc, the screen becomes black (just after the boot AND the Sega logo) while I can hear sounds and the controller seems to respond.
Windows 10 64bit - Retroarch (latest nightly build) on OpenGL - flycast (latest build).

Tried setting to VGA from TV(RGB) that cured the white screen in the past, but no change.

**Comment by flyinghead** [comment]
Last Hope works fine on my end.

Gunlord and Neo XYX do show a black screen after boot.
