### ISSUE TITLE
RPi2 build | FORCE_GLES=1 | error: 'GLint64' has not been declared

### ISSUE THREAD

**Issue by 5schatten** [libretro/flycast#60]
This patch broke RPi2 builds with "make platform=rpi2 FORCE_GLES=1" for me:

https://github.com/libretro/reicast-emulator/commit/38617bab9af61243acec4356fc56e9f2abe4e040#diff-7c14a3377162d5719dbb03caca6d2544

In file included from core/rend/gles/gles.h:4,
                 from core/rend/gles/gles.cpp:9:
core/libretro-common/include/glsm/glsmsym.h:467:3: error: 'GLint64' has not been declared
   GLint64 * data);
   ^~~~~~~
make: *** [Makefile:611: core/rend/gles/gles.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from core/rend/gles/gles.h:4,
                 from core/rend/gles/gldraw.cpp:1:
core/libretro-common/include/glsm/glsmsym.h:467:3: error: 'GLint64' has not been declared
   GLint64 * data);
   ^~~~~~~
make: *** [Makefile:611: core/rend/gles/gldraw.o] Error 1
In file included from core/rend/gles/gltex.cpp:9:
core/libretro-common/include/glsm/glsmsym.h:467:3: error: 'GLint64' has not been declared
   GLint64 * data);
   ^~~~~~~
make: *** [Makefile:611: core/rend/gles/gltex.o] Error 1
^Cmake: *** [Makefile:611: core/rec-cpp/rec_cpp.o] Interrupt

**Comment by inactive123** [comment]
Try this commit -

https://github.com/libretro/reicast-emulator/commit/dc25a1ed8743ce356a4c81e30046febc29249ae0

**Comment by 5schatten** [comment]
It's fixed
