### ISSUE TITLE
ARM Build for RPi4

### ISSUE THREAD

**Issue by microadam** [libretro/flycast#607]
Hello,

I am wondering if there is a way to get Flycast updated on the latest nightly of Lakka for RPI4? 

I am specifically interested in trying out the new features mentioned here:

https://www.libretro.com/index.php/flycast-progress-report-hle-bios-no-longer-requires-external-bios/

Is the only way to do this to compile from source for that platform? 

Many thanks

**Comment by magicseb** [comment]
Hi,
I can give you a compiled binary. https://we.tl/t-EltTLN03B5

Put it in your cores folder

**Comment by microadam** [comment]
Amazing! Will give this a go, thank you!

Did you compile it directly on a Pi?

**Comment by microadam** [comment]
doesn't work for me though unfortunately.

```
[ERROR] Failed to open libretro core: "/tmp/cores/flycast_libretro.so"
[ERROR] Error(s): /usr/lib/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/cores/flycast_libretro.so)
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0x34659c
[INFO] [MIDI]: Initializing ...
ALSA lib /mnt/data/PROJECTS/Lakka-LibreELEC/build.Lakka-RPi4.arm/alsa-lib-1.1.9/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
[ERROR] [MIDI]: snd_seq_open failed with error -2.
[ERROR] [MIDI]: Initialization failed (list of input devices unavailable).
```
any thoughts?

**Comment by magicseb** [comment]
Hi.

You can get my own build image with libreelec here. https://github.com/magicseb/LibreELEC.tv/releases/tag/f63e73f

Even, i will compile with lakka basis later.

I made cross compile this :=)

**Comment by magicseb** [comment]
Get this one : https://we.tl/t-muvl6ca8L7

**Comment by microadam** [comment]
Thanks for supplying! Same errors unfortunately though:

```
[ERROR] Failed to open libretro core: "/tmp/cores/flycast_libretro.so"
[ERROR] Error(s): /usr/lib/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/cores/flycast_libretro.so)
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0x34659c
[INFO] [MIDI]: Initializing ...
ALSA lib /mnt/data/PROJECTS/Lakka-LibreELEC/build.Lakka-RPi4.arm/alsa-lib-1.1.9/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
[ERROR] [MIDI]: snd_seq_open failed with error -2.
[ERROR] [MIDI]: Initialization failed (list of input devices unavailable).
[INFO] SRAM will not be saved.
```
Looks like perhaps something is hardcoded to your machine and you have a different version of some libraries? Just trying to run it on one of the newest nightlies of Lakka

**Comment by magicseb** [comment]
Yes i build the Lakka-9.2 branch, the master one doesn't build on my setup

https://we.tl/t-Ein4tOTPHy

Here is the full image, should be burned on another SD if you want.

**Comment by 5schatten** [comment]
On which version is your nightly based? The 9.2 branch of Lakka uses glibc 2.29 and should work fine.

`[ERROR] Error(s): /usr/lib/libc.so.6: version GLIBC_2.28` not found` implies that your system provides an older glibc which as needed.

**Comment by flyinghead** [comment]
Hoping RPi4 is now ok
