### ISSUE TITLE
Limit RetroArch Options to Dreamcast

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#608]
Hello,

I'm wondering if it would be possible to only show the VMU and Gun Crosshair Colors in RetroArch Options to Dreamcast games only?

There is an open issue that gun crosshairs don't work in Naomi games. So it would be better for it to be limited to Dreamcast or make it work for Naomi/Atomiswave systems as well.

**Comment by flyinghead** [comment]
This is not possible because the list of core options is fixed and cannot depend on the current game type (Naomi vs. Dreamcast)

**Comment by barbudreadmon** [comment]
@flyinghead that's not true (core options can even be on a per-game basis, that's how it's done for DIPS in fbneo), however having dynamic core options, especially with core options v2 and its translation system, can quickly become messy, i don't recommend it for this core.

**Comment by flyinghead** [comment]
Thanks for the info.

**Comment by barbudreadmon** [comment]
btw, that's how it's done in fbneo : https://github.com/libretro/FBNeo/blob/master/src/burner/libretro/retro_common.cpp

The general idea is to : 
1. declare `retro_core_option_definition` structs which represents single core option (L78-L229)
2. push them into a vector after we know what game/system is running (L354-L425)
3. send them (L427-L528)

NB : the function `set_environment` is called at the end of `retro_load_game`, "classic" cores would do this stuff in `retro_set_environment` (which is called before `retro_load_game`) but thankfully it is not mandatory.

My algorythm doesn't account for translations, things would get ugly if it did so i don't plan working on it.

**Comment by flyinghead** [comment]
Done: https://github.com/libretro/flycast/pull/632
