### ISSUE TITLE
Sturmwind crashes after 1st stage

### ISSUE THREAD

**Issue by fluffymadness** [libretro/flycast#61]
Tested with newest reicast-oit.
After playing stage 1 in arcade mode, a screen shows saying press start to go to the next stage.
After pressing start it just hangs there and doesn't continue anymore.

**Comment by inactive123** [comment]
Have you tried with the generic_recompiler instead?

**Comment by fluffymadness** [comment]
Yes. Right now. Doesn't seem to change anything sadly

**Comment by fluffymadness** [comment]
Oh ok....just pressing start ingame crashes the core.
It shows the pause menue screen, then it hangs. (generic_recompiler)

**Comment by inactive123** [comment]
Could be copy protection, apparently this and other retail independent games had that.

https://japanese-cake.livejournal.com/10056.html

**Comment by fluffymadness** [comment]
I just tested the latest reicast ci build on android (e6afd22    2018-06-25T14:36:20.000Z) sturmwind doesn't crash there when i press start ingame.

**Comment by inactive123** [comment]
Could be a dynarec bug then in x64. Maybe the same issue that makes Shenmue 2 crash right now, no support for self-recompiled code. There is a bounty open for fixing this.

**Comment by inactive123** [comment]
Did you get to level 1-2 before? I just played it after merging this -

https://github.com/libretro/reicast-emulator/commit/47e162af5d735be0fc797109586f3c91b3364b49

and I could get to level 1-2. 

Try to retest this and see if it still crashes.

**Comment by fluffymadness** [comment]
Thx. Will test this and psyvariar 2 tomorrow.

**Comment by fluffymadness** [comment]
Hmm tested arcade mode in sturmwind with newest reicast oit. Sadly still the same for me. As soon as i press start ingame it freezes. Can anyone else reproduce this ?

**Comment by inactive123** [comment]
I have reason to believe something might be different now after this commit -

https://github.com/libretro/reicast-emulator/commit/14c0140201ba9142ac96d30857bee1fcbb0d7da3

Can you test this out again?

**Comment by flyinghead** [comment]
Could this be related to #135?
This game also stops rendering any frame when paused.

**Comment by Shoegzer** [comment]
@fluffymadness actually, see my above referenced issue - please set framerate to "fullspeed" and confirm that it stops the freezing.  It did for me - and I confirmed that it still froze with framerate set at "normal" even after the commit posted above from @twinaphex.

**Comment by flyinghead** [comment]
Closing as resolved: Use threaded rendering or framerate=Fullspeed
