### ISSUE TITLE
Flycast Full Screen Crashes

### ISSUE THREAD

**Issue by TradeDraft** [libretro/flycast#610]
When I am play Dreamcast Game and I press Fullscreen and then Dreamcast Crashes.

Here is the Log from when it Happened

https://pastebin.com/9RTeD3Zq

So how to Fix It?

**Comment by BroKill** [comment]
Change video driver to gl or vulkan.

**Comment by barbudreadmon** [comment]
@TradeDraft Make sure you are using the latest versions of RA & flycast. Also, many hardware-accelerated cores have issues when switching between windowed & fullscreen, i think that's the case for flycast too, if you want to play fullscreen it's recommended to have it enabled from launch.

**Comment by flyinghead** [comment]
This should now be fixed. Reopen as needed
