### ISSUE TITLE
Fail in Retroarch 1.77. Naomi, Atomiswave 

### ISSUE THREAD

**Issue by sirmagb00** [libretro/flycast#611]
I found freezes, in several games of sega naomi, atomiswave. The failures are random, although in the example video, with that game, it always fails.
The data to understand the problem: Retroarch version: 1.77
Core: Flycast 0.1 ceda229
Operating System: Ubuntu 18.04 ~ amd64
Graphics card: Ati Gigabyte R9 270
Here the link to the video where you can see the bug:
https://youtu.be/ASKoU3fuK9Y

Thank you very much for your work. regards

**Comment by barbudreadmon** [comment]
Try disabling threaded rendering in core options

**Comment by sirmagb00** [comment]
https://youtu.be/vdG2bQR4NPE
Test performed, now the game is not frozen, now the emulator is closed.

**Comment by flyinghead** [comment]
I can reproduce this last crash. Happens with standalone too.

**Comment by flyinghead** [comment]
Assuming resolved. Reopen if needed
