### ISSUE TITLE
automatic mode for the 'region' option [naomi,atomiswave]

### ISSUE THREAD

**Issue by strodown** [libretro/flycast#612]
Hello everyone
certain games naomi and atomiswave need to specify the `REGION` in the parameters of the cores if not correctly set the game launch on `error 2 this game is not acceptable by main board` :

Examples:

- Street Fighter Zero 3 => need `REGION=JAPAN`

- Dead Or Alive 2 => need `REGION=USA`

for my parts the other games works with the option `REGION=DEFAULT`

is it possible to create an `AUTO` mode to avoid this change?

thank you for your work

**Comment by barbudreadmon** [comment]
Use mame roms, as recommended, and everything should be ok.

**Comment by flyinghead** [comment]
barbudreadmon is right
