### ISSUE TITLE
intermittent short pause during gameplay on Odroid N2

### ISSUE THREAD

**Issue by dewenhsu** [libretro/flycast#615]
For example NAOMi game Asian Dynamite, the initial game demo will randomly short pause few seconds, if you use faster microSD card ( on Odroid N2 running TheRA ), the pause frequency and duration will decrease but still exist, if you use U1 card the pause will increase.
It seems like a read/write process ( cache / buffer ? ) take whole CPU resource and slowdown/pause the game system. Is it possible to load the whole game data to memory at the beginning to reduce the frequent read from microSD and cause "pause" ? or add the loading memory buffer ?
Thank you.

**Comment by flyinghead** [comment]
Naomi roms are loaded into memory at startup and never read when the game is running. So these short pauses are caused by something else.

This PR has a fix that might help the situation: https://github.com/libretro/flycast/pull/616

**Comment by dewenhsu** [comment]
Thank you so much !  the pause issue was fixed ! amazing !
