### ISSUE TITLE
The Shenmue Bug

### ISSUE THREAD

**Issue by Nine-H** [libretro/flycast#62]
Shenmue crashes after the first cutscene, you can sort of work around it by setting the core to interpreter, this bug was on the old issue tracker but I'm bringing it forward because it's a core title for the platform.

**Comment by inactive123** [comment]
This is a known issue, I have a bounty open for it here -

https://github.com/reicast/reicast-emulator/issues/1167

**Comment by inactive123** [comment]
This is fixed now as of https://github.com/libretro/reicast-emulator/commit/47e162af5d735be0fc797109586f3c91b3364b49 thanks to @skmp.
