### ISSUE TITLE
'Failed to open libretro core' (WinCE/Win7x64)

### ISSUE THREAD

**Issue by evedenlijuen** [libretro/flycast#620]
This occurs everytime I try to load a game (WinCE/non-WinCE) with the WinCE core.

I think the last WinCE working core is the b533191. Any core who came after this one fails to load on my system.

Non-WinCE cores work properly.

RetroArch 1.7.8
Windows 7 x64

Best regards.

**Comment by barbudreadmon** [comment]
> Any core who came after this one fails to load on my system.

The next commit is only about arm64 though, not sure what could be the issue

**Comment by flyinghead** [comment]
Just tested latest (852e91309878a5e404fb7e9245da70166943d8bd) on windows 10 with no issue.

Can you get a verbose log?

**Comment by evedenlijuen** [comment]
Sure.
https://pastebin.com/KPfMpSsd

I'm not the only one who has this issue.
https://forums.libretro.com/t/flycast-win-ce-failed-to-open-core/23970

The issue is here too on fresh installs with RA 1.7.7, 1.7.8, and nightly.

**Comment by flyinghead** [comment]
Should be fixed by 866449fa4186c9ed43bbb9110c528e3c541ef00c

**Comment by evedenlijuen** [comment]
OK, waiting for the buildbot.

**Comment by evedenlijuen** [comment]
I confirm it's fixed.

Nice. :)

**Comment by evedenlijuen** [comment]
@flyinghead what is the point of the new core option 'Force Windows CE mode'? Is it for games that aren't detected as WinCE ones, or something else?

**Comment by flyinghead** [comment]
It is for games not detected as WinCE ones. This is useful for many CDIs, and for compilations/samplers that include a WinCE game.

**Comment by evedenlijuen** [comment]
OK, thanks. :)
