### ISSUE TITLE
How to achieve perfect audio/video sync (Retroarch android)

### ISSUE THREAD

**Issue by RaduNastase** [libretro/flycast#628]
Flycast works really well in Retroarch android. Everything is full speed and virtually zero graphical glitches on the games i play, Atomiswave, DC or Naomi (Capcom vs Snk 1 and 2, Marvel VS Capcom 2, Guilty Gear X, XX, Street Fighter 3 upper, Project Justice).

One thing though, is that i can not achieve PERFECT audio and video smoothness. With the Flycast Core settings: Threaded Rendering ON, Synchronous Rendering ON and General Retroarch settings: Audio Sync ON, i get perfect audio and "almost" perfect video, with very slight stutter when scrolling, unnoticeable in gameplay. If i disable Audio Sync in Retroarch, i get perfect Video scrolling, but the audio has a lot of clicks and slight distorsions.

Any way to have both perfect audio and video?

**Comment by MastaG** [comment]
I dont think its possible to get full speed on libretro-flycast in demanding games such as the first stage in Sonic Adventure 2 (where he skates down the hill in san fransisco).

I get the same issues with the same settings on the XU4 and even the more powerfull N2.

I guess for this reason most retro OS's include the standalone version of reicast because that one is capable of achieving  (near) fullspeed.

**Comment by flyinghead** [comment]
You should try the flycast WinCE core on android. It has some optimizations of the dynarec that may help non-WinCE games as well.

**Comment by RaduNastase** [comment]
Can the normal (august) flycast core and the fllycastWinCE core, coexist? I'd love to try the new core, but I'd like to keep the normal core as well, as i managed to get almost perfect sync with a lot if trial and error. I will explain "how" in an upcoming post for anyone interested.

**Comment by flyinghead** [comment]
Yes, you can have both cores installed and choose which one to use when starting a game.

**Comment by RaduNastase** [comment]
Thank you!

**Comment by flyinghead** [comment]
not relevant anymore
