### ISSUE TITLE
Metropolis Street Racer - Cannot Load/Save

### ISSUE THREAD

**Issue by Nine-H** [libretro/flycast#63]
there's something wrong with how MSR saves and loads, because the game either cannot read or write the memory card you can't create a new game without selecting "proceed without saving" any save after that will be lost too.

**Comment by flyinghead** [comment]
Can't reproduce anymore. Reopen if the problem persists

**Comment by zkvsky** [comment]
currently the game doesn't progress past the cinematic intro hle or no hle, does it need special config?

**Comment by flyinghead** [comment]
This game currently doesn't run with HLE BIOS. Make sure to disable the option and to have the dc_boot.bin file in the right location

**Comment by flyinghead** [comment]
This game currently doesn't run with HLE BIOS. Make sure to disable the option and to have the dc_boot.bin file in the right location

**Comment by zkvsky** [comment]
@flyinghead  got it, thanks
