### ISSUE TITLE
Libretro x86_64 sega rally won't load

### ISSUE THREAD

**Issue by meeuuh92** [libretro/flycast#633]
Hi, Sega Rally 2 (win ce games) won't load on my configuration (intel nuc under debian stretch x86_64). The crash happens after logo screen... For the rest, everything is ok (dreamcast games, naomi and atomiswave), it's works like a charm.. (Except some mappings in naomi and crash under retroarch menu)

**Comment by flyinghead** [comment]
Are you sure you're using the Flycast WinCE core? Which version?

**Comment by meeuuh92** [comment]
I'm using flycast from git, compiled via retropie-setup script.. Wince is not included ?? Le 12 sept. 2019 11:51, flyinghead <notifications@github.com> a écrit :Are you sure you're using the Flycast WinCE core? Which version?

**Comment by flyinghead** [comment]
No, you need to build the branch `fh/wince`

**Comment by meeuuh92** [comment]
Ah... Ok, always thought it was a part or reicast/flycast code. So, it's not an issue... : -)

**Comment by flyinghead** [comment]
It will soon replace the regular flycast core

**Comment by meeuuh92** [comment]
Ok.. Thanks..   : -)Le 12 sept. 2019 19:02, flyinghead <notifications@github.com> a écrit :It will soon replace the regular flycast core
