### ISSUE TITLE
Some NAOMI games crashing with latest version of the cores (Both WinCE and non-WinCE cores)

### ISSUE THREAD

**Issue by BloodRaynare** [libretro/flycast#636]
Tried Virtual-On: Oratorio Tangram (ver. 5.66) and Virtua Striker 2 Ver. 2000 (both are NAOMI versions) and the game would crash no matter if it was run on WinCE or non-WinCE cores.

Here's the log files for the both of games (I reverted the core settings to default).
[retroarch__2019_09_13__19_24_44.log](https://github.com/libretro/flycast/files/3610054/retroarch__2019_09_13__19_24_44.log)
[retroarch__2019_09_13__19_25_37.log](https://github.com/libretro/flycast/files/3610055/retroarch__2019_09_13__19_25_37.log)

**Comment by flyinghead** [comment]
Are they crashing at a specific moment or randomly?

I've been playing vonot for a good 30 mins without a crash. I'm on linux though.

**Comment by BloodRaynare** [comment]
It happens after the NAOMI bootscreen. It goes to black screen for about 10-15 seconds then it crashes.

Edit: It seems after reupdated the cores to the commit 5adf5516ec011bb4378dfb72a926cb2f776130c4 those games no longer crashes.

**Comment by evedenlijuen** [comment]
Lots of Dreamcast games (e.g: Crazy Taxi, F355 challenge, Test Drive Le Mans, and more...) crashed for me too during splash screens with WinCE core before the last update, and some of those games and some others had some 1 pixel lines artifacts on those splash screens.

Haven't tried it with the updated core, but i'll be able to post some screenshots and logs if it still happens.

**Comment by evedenlijuen** [comment]
Tested with the latest cores. No crashes anymore with the WinCE, but the lines artifacts are still here.

Crazy Taxi (US)
![Crazy Taxi v1 004 (1999)(Sega)(NTSC)(US) ! 10S 51035 -190914-132601](https://user-images.githubusercontent.com/54717095/64907555-5fda0a00-d6f4-11e9-9bcb-9cfa7e4df0d9.png)

Sonic Adventure (US)
![Sonic Adventure v1 005 (1999)(Sega)(NTSC)(US)(M5) ! 24S 51000A -190914-132815](https://user-images.githubusercontent.com/54717095/64907564-7a13e800-d6f4-11e9-9b42-c3baa1fa93b5.png)

Everything's fine with non-WinCE core.

Maybe I could open a new issue for that, although it's quit minor?

**Comment by barbudreadmon** [comment]
> Maybe I could open a new issue for that?

@evedenlijuen yeah, and don't forget to mention your hardware and settings, logs could be useful too.

**Comment by evedenlijuen** [comment]
OK

**Comment by flyinghead** [comment]
Closing as resolved. Re-open if needed
