### ISSUE TITLE
(WinCE core) some 1 pixel width lines artifacts on splash screens

### ISSUE THREAD

**Issue by evedenlijuen** [libretro/flycast#638]
This doesn't occurs with non-WinCE core.

i72700K@stock
GTX780ti with updated drivers
Win7x64
RA 1.7.8v3
glcore
Core settings : HLE bios + per-pixel 
Cores 5ceffc3 (WinCE) and 5adf551 (non-WinCE)

Here is 2 examples

Crazy Taxi (Dreamcast/US)
![Crazy Taxi v1 004 (1999)(Sega)(NTSC)(US) ! 10S 51035 -190914-132601](https://user-images.githubusercontent.com/54717095/64907555-5fda0a00-d6f4-11e9-9bcb-9cfa7e4df0d9.png)

Sonic Adventure (Dreamcast/US)
![Sonic Adventure v1 005 (1999)(Sega)(NTSC)(US)(M5) ! 24S 51000A -190914-132815](https://user-images.githubusercontent.com/54717095/64907564-7a13e800-d6f4-11e9-9b42-c3baa1fa93b5.png)

Log (Crazy Taxi) :
https://pastebin.com/0XCwYj2E

**Comment by MastaG** [comment]
This was also present before the wince merge on the regular core.
But since its mostly on splash-screens / game-menu's I didnt really bother...

**Comment by blisstik** [comment]
this should be fixed now... at least in our experience with the N2 running at 720p

**Comment by evedenlijuen** [comment]
I'll test it with the new merged core when i get a chance.

**Comment by evedenlijuen** [comment]
Just tested with WinCE merged core 741eaee.

It's still here.

**Comment by MastaG** [comment]
I'm running flycast on the N2 in 1280x720. The lines are still there  just open the Stage Select screen in Sonic Adventure 2.

However since the WinCE merge its finally fullspeed, even in the demanding areas.

So @flyinghead, thanks a lot bro!

**Comment by flyinghead** [comment]
Should be fixed by https://github.com/libretro/flycast/commit/f54976ccc3f6ba4bf6e62fadaad114fc381e55f8.

**Comment by evedenlijuen** [comment]
Confirmed.

Nice job. Thanks!
