### ISSUE TITLE
8 VMUs?

### ISSUE THREAD

**Issue by Denshadego** [libretro/flycast#643]
Hello! I'm a happy user of Flycast on RA, and let me tell you, it's amazing. My most played game is Fire Pro Wrestling D, runs great! however, the 4 VMU option doesn't cut it for this game.

With the almost 100 DLC moves available, plus the space needed for system, custom wrestler, promotion data, etc, it screams for 8 VMUs. The game menu shows a blank space for the second socket VMUs, fifth to eight, but the emulator is capped at 4. Is it possible to implement something like this?

**Comment by flyinghead** [comment]
Disabling purupuru will free space for one more VMU per controller, for a total of 8.

**Comment by Denshadego** [comment]
Thank you, it works!
