### ISSUE TITLE
Tokio Xtreme Racer 2 incorrect aspect ratio

### ISSUE THREAD

**Issue by damianshrinivas** [libretro/flycast#644]
Aspect ratio in this game is incorrect.
So here's how it should look (from Redream):
![Redream (correct)](https://user-images.githubusercontent.com/19475260/65147470-7ba81d80-da1e-11e9-8c6d-0b7f2ca89eb7.png)
And how it looks now (Flycast):
![Flycast (incorrect)](https://user-images.githubusercontent.com/19475260/65147516-937fa180-da1e-11e9-9e0e-3082757f0582.png)
Win10, default settings

**Comment by Panderner** [comment]
Are you set to 4:3?

**Comment by flyinghead** [comment]
It seems to be a game bug and not an emulator one. When played in VGA the game has normal aspect ratio but the aspect ratio is wider in TV Composite mode.

Both emulators display the same but redream defaults to VGA while flycast defaults to TV composite.
