### ISSUE TITLE
Button remapping does not work

### ISSUE THREAD

**Issue by jstolarek** [libretro/flycast#646]
I am running Flycast core version 741eaeec under Linux and button remapping does not work. Let's say I load Capcom vs SNK 2 arcade rom (`cps2.zip`) and then enter Quick Menu -> Controls. "User 1 Device Type" is marked as an "Arcade Stick" (correct - I am using Mayflash F101 in XInput mode). However, all Player 1 inputs are makred with `---` and unavailable for remapping:

![retroarch](https://user-images.githubusercontent.com/1597921/65164084-12cba000-da34-11e9-81b9-59584646174c.jpg)

Interestingly, Player 2 buttons can be remapped without problems:

![retroarch1](https://user-images.githubusercontent.com/1597921/65164088-16f7bd80-da34-11e9-8770-083473b53f43.jpg)

I tried to be smart: I remapped Player 2 buttons the way I wanted to, saved the remap to a file, opened it with a text editor and replaced all `input_player2_btn_FOO` with `input_player1_btn_FOO` but none of this seems to have any effect.

**Comment by flyinghead** [comment]
Try setting "User 1 Device Type" to a regular gamepad instead. Arcade Stick is for dreamcast games only.

**Comment by jstolarek** [comment]
Indeed, that works. Thanks!
