### ISSUE TITLE
Graphical glitches in NeoGeo Battle Coliseum

### ISSUE THREAD

**Issue by jstolarek** [libretro/flycast#647]
What the title says, lots of glitches:
![ngbc-190918-175341](https://user-images.githubusercontent.com/1597921/65169089-c08f7c80-da3d-11e9-8185-e9a2e046de74.jpg)
![ngbc-190918-175426](https://user-images.githubusercontent.com/1597921/65169207-fdf40a00-da3d-11e9-80c5-0e0777e24df8.jpg)

Notice Ralph in the background:
![ngbc-190918-175105](https://user-images.githubusercontent.com/1597921/65169111-cbe2a800-da3d-11e9-90ee-f919b113d24b.jpg)

**Comment by barbudreadmon** [comment]
Seems to me like this game only works properly with OIT enabled (aka "Alpha Sorting" set to "per pixel"). I'm not sure it was the case previously, it might be a regression (?).

**Comment by jstolarek** [comment]
Indeed, with that setting works as expected. Thanks!

**Comment by jstolarek** [comment]
Btw, is there any documentation on these kind of game-specific issues and required settings? I wouldn't want to report a bug every time I run into such a problem only to learn it is a matter of some specific settings.

**Comment by barbudreadmon** [comment]
Nope, generally we try to force specific settings needed for specific games, however in this case OIT requires OpenGL 4.3, which is only available with "modern" gpus (since 2012, except if you made the mistake of getting a macosx computer or an intel gpu), so we can't really force it, furthermore it requires a gpu with decent performances.

If your device is powerful enough, there is no reason to use anything besides per-pixel alpha sorting.

**Comment by rafaelmartines** [comment]
I set Alpha Sorting Per-pixel and still got graphic glitches, like you can see in the background :( is there any other options? Do I need to restart the game after set it?
![Captura de tela de 2020-06-29 09-44-22](https://user-images.githubusercontent.com/8183691/86007001-32ddb600-b9ed-11ea-8c8c-f88f63e0d03d.png)

**Comment by flyinghead** [comment]
No need to restart the game. I'm not seeing any glitch in per-pixel mode with this game though.

What GPU are you using? Open GL or Vulkan?

**Comment by rafaelmartines** [comment]
@flyinghead the default one (gl), can I use Vulkan for everything?

**Comment by flyinghead** [comment]
Try Vulkan as it may helps. If a core doesn't support Vulkan, RA should switch to Open GL automatically.

What graphic hardware do you have?

**Comment by rafaelmartines** [comment]
> Try Vulkan as it may helps. If a core doesn't support Vulkan, RA should switch to Open GL automatically.

I'll try that and give the feedback

> What graphic hardware do you have?

That's the amazing and shocking part, my video is a onboard one (Intel HD Graphics 4600) and most all the games, Naomi works really good, even Marvel vs. Capcom 2 and Capcom vs. SNK 2 works perfectly:

![Captura de tela de 2020-06-28 14-32-58](https://user-images.githubusercontent.com/8183691/86015884-84d80900-b9f8-11ea-8817-9cc4945f376a.png)

The only issues I noticed:
 
- Capcom vs. SNK and Capcom vs. SNK Pro: When you KO normally, the KO letter is glitched, but nothing really annoying.
- Samurai Shodown VI works really well, but with framerate issue
- NeoGeo Battle Coliseum with those graphical issues I've mentioned.

The King of Fighter XI, Neowave and Metal Slug 6, AFAIK are perfect :D

**Comment by rafaelmartines** [comment]
> Try Vulkan as it may helps. If a core doesn't support Vulkan, RA should switch to Open GL automatically.
I just tried it and nothing changed... but it's ok maybe is my graphic card, I can live without Samurai Shodown VI and NeoGeo BC :D I wasn't expecting the other games to work in the first place :P

Thanks for the help \o

**Comment by rafaelmartines** [comment]
> Try Vulkan as it may helps. If a core doesn't support Vulkan, RA should switch to Open GL automatically.

Just tried it and it worked :D with a bit of slowdown, in this case, mighty be my graphic card :D thanks for the help \o

**Comment by barbudreadmon** [comment]
@rafaelmartines intel driver's opengl implementation is just plain broken, i heard their vulkan implementation is slightly better.
