### ISSUE TITLE
OpenGL and Input questions

### ISSUE THREAD

**Issue by MastaG** [libretro/flycast#648]
There's no dedicated forum for flycast on retroach right?
So I'm going to ask it here.

I'm trying out retroarch + flycast on Linux (Fedora 31) on Intel graphics:
......
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 
OpenGL core profile version string: 4.6 (Core Profile) Mesa 19.3.0-devel
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
.......

So I've compiled todays rev: https://github.com/libretro/flycast/commit/f54976ccc3f6ba4bf6e62fadaad114fc381e55f8 with the following options:
HAVE_OIT=1 HAVE_CORE=1
Now it works when retroarch is set to use the "gl" video driver but if I select the "glcore" driver in retroarch, games will boot to a black screen only?

So should I set HAVE_CORE=1 in the first place? if yes, why doesn't the glcore driver in retroach work then?

Also I'm trying to play the house of the dead 2 (naomi).
I got the naomi.zip and hod2bios.zip and the game boots fine.
Only I'm having two problems.
First of all how do I setup the controls so I can use my mouse as a light gun?
Also how can I "insert a coin" ?

Second problem I'm having is that the game has no gore enabled.
I downloaded the USA version of the game and according to the wiki it should feature red blood.

Sorry for all the questions..

**Comment by flyinghead** [comment]
These questions are probably better asked on the retroarch forum, or on Discord.

The glcore driver currently has some issues with flycast so it's best not to use it until they are resolved (See issue #625).

**Comment by MastaG** [comment]
Ah yes per pixel-pixel seems to work!
thanks!

I'll close this issue and ask on discord for the controls and gore settings.
