### ISSUE TITLE
RPi2 build: undefined symbol: ngen_FailedToFindBlock

### ISSUE THREAD

**Issue by 5schatten** [libretro/flycast#65]
Looks like some unedfined symbols causes a segfault?

[INFO] Loading dynamic libretro core from: "/tmp/cores/reicast_libretro.so"
[ERROR] Failed to open libretro core: "/tmp/cores/reicast_libretro.so"
[ERROR] Error(s): /tmp/cores/reicast_libretro.so: undefined symbol: ngen_FailedToFindBlock

supervisedthinking@mintBS:~$ nm -u /home/supervisedthinking/le90-Remix/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.0-devel/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/lib/reicast_libretro.so |grep ngen*
         U glDepthRangef
         **U ngen_AllocateBlock
         U ngen_FailedToFindBlock
         U _Z14ngen_terminatev**

When I compile it for x86-64 builds they aren't missing:

nm -u /home/supervisedthinking/le90-Remix/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/reicast_libretro.so |grep ngen*
                 U glDepthRange

Any hints are welcome!

**Comment by inactive123** [comment]
It doesn't currently build for Raspberry Pi or other ARM-based systems.

Somebody needs to take on this bounty first for that to happen -

https://github.com/libretro/reicast-emulator/issues/12

**Comment by rcaridade145** [comment]
@5schatten are you compiling with -flto? Can you please try without?

**Comment by rcaridade145** [comment]
@twinaphex @5schatten  https://github.com/reicast/reicast-emulator/blob/master/core/rec-ARM/rec_arm.cpp#L345 We're missing these lines on libretro reicast.

**Comment by 5schatten** [comment]
Well I disabled lto with this & will see if still symbols are missing

```
--- a/Makefile
+++ b/Makefile
@@ -487,8 +487,8 @@
 	LDFLAGS        += -DNDEBUG
    RZDCY_CFLAGS += -flto
    RZDCY_CXXFLAGS += -flto
-   CFLAGS += -flto
-   CXXFLAGS += -flto
+#   CFLAGS += -flto
+#   CXXFLAGS += -flto
 endif
 
 RZDCY_CFLAGS	+= $(CFLAGS) -c $(OPTFLAGS) -DRELEASE -ffast-math -fomit-frame-pointer -D__LIBRETRO__
@@ -556,10 +556,10 @@
 	CFLAGS += -fprofile-use
 endif
 
-ifeq ($(LTO_TEST),1)
-	CFLAGS += -flto -fwhole-program 
-	LDFLAGS +=-flto -fwhole-program 
-endif
+#ifeq ($(LTO_TEST),1)
+#	CFLAGS += -flto -fwhole-program 
+#	LDFLAGS +=-flto -fwhole-program 
+#endif
 
 ifeq ($(HAVE_GL), 1)
 	ifeq ($(GLES),1)
```

**Comment by rcaridade145** [comment]
@5schatten please see my previous post also https://github.com/libretro/reicast-emulator/issues/65#issuecomment-400636299 . That fixes the ngen_FailedToFindBlock

**Comment by 5schatten** [comment]
Okay after applying the patch:

```
--- a/core/rec-ARM/rec_arm.cpp
+++ b/core/rec-ARM/rec_arm.cpp
@@ -333,6 +333,9 @@
 extern "C" void ngen_LinkBlock_cond_Branch_stub();
 extern "C" void ngen_LinkBlock_cond_Next_stub();
 
+extern "C" void ngen_FailedToFindBlock_();
+void (*ngen_FailedToFindBlock)()=&ngen_FailedToFindBlock_;  // in asm
+
 #include <map>
 
 map<shilop,ConditionCode> ccmap;

```
ngen_FailedToFindBlock_ isn't missing anymore. So what about U ngen_AllocateBlock?

nm -u /home/supervisedthinking/le90-Remix/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.0-devel/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/lib/reicast_libretro.so |grep ngen*
         U glDepthRangef
         U ngen_AllocateBlock
         U _Z14ngen_terminatev

**Comment by rcaridade145** [comment]
@5schatten 
ngen_AllocateBlock -  https://github.com/reicast/reicast-emulator/blob/master/core/rec-ARM/rec_arm.cpp#L2337 

Z14ngen_terminatev - is #ifdef at the end of the file  maybe @twinaphex  can help here.

glDepthRangef - smells like opengl issues. Have to take a better look :) But time to lunch..30 min into my lunch hour lol.

**Comment by BananaRama203** [comment]
FYI I am working on the same thing right now too but for our Nintendo Mini platform.

I am building for Cortex A7 HardPoint ARM with DYNAREC and forcing GLES. I had the same runtime error as described above.

I have the standalone built and work so I will run some tests my end and let you know how far I get. I am on the libretro programming channel in discord if you want to @ me under same name we can chew the fat.

**Comment by inactive123** [comment]
glDepthRangef is not available on GLES2 and later, it's glDepthRange there. I can at least push a commit for that, the other stuff is kinda for you guys to figure out, hence the bounty for it.

**Comment by inactive123** [comment]
OK, I took a look at the current code -

GLES = 1

You need to define this for your Makefile target if you want to build with GLES support instead of GL (desktop GL). This will magically make the glDepthRangef errors go away.

**Comment by BananaRama203** [comment]
@twinaphex yeah I am already doing this. My cloud dev is cooking right now.

**Comment by rcaridade145** [comment]
Nice to hear @swingflip . Do you have the same glDepthRangef  issue?

**Comment by rcaridade145** [comment]
Can we get ARM running today :+1:  @swingflip @twinaphex @5schatten

**Comment by BananaRama203** [comment]
@rcaridade145 it runs...ish. Core loads into RA fine, when running game DYNAREC runs. Fails on glDepthRangef...

Using a custom make though...

I will link to my make.

```
Creating dir: /etc/libretro/system/dc/data
context_reset.
ARM VFP-Run Fast (NFP) enabled !
Linux paging: 00001000 00001000 00000FFF
MAP 00800000 w/ 25165824
MAP 20000000 w/ 25165824
MAP 04000000 w/ 16777216
MAP 06000000 w/ 16777216
MAP 0C000000 w/ 0
A8
vmem reserve: base: 8E100000, aram: ae100000, vram: 92100000, ram: 9A100000
Resetting mem
Mem alloc successful!Loaded /etc/libretro/system/dc/dc_boot.bin as bootrom

Loaded /etc/libretro/system/dc/dc_flash.bin as nvram

[libretro INFO] Using Recompiler
Sh4 Reset
recSh4 Init
Freeing fpcb
readm helpers: up to AF3E7250
Shader: failed to compile 
0:6: L0002: Undeclared variable 'gl_FragDepth'
Shader linking: failed to link 
 (61 bytes), - L0101 All attached shaders must be compiled prior to linking
 -
[libretro INFO] Fatal error : shader compile fail

 in gl_CompileAndLink -> core/rend/gles/gles.cpp : 346 
DEBUGBREAK!
RetroArch FAILED to run using the test rig at Thu Jan  1 05:10:10 UTC 1970```

**Comment by BananaRama203** [comment]
@rcaridade145 https://github.com/HakchiCloud/reicast-emulator/blob/60190d6d1c9e42e4e806ce41bf104ccd8412a1ff/Makefile#L166 Hit me up in the discord if possible, it's easier.

**Comment by BananaRama203** [comment]
@rcaridade145 worked it out. This makefile sucks... lol I am working on it as we speak. I will let you know when I have something of interest.

**Comment by rcaridade145** [comment]
@swingflip yay.. Currently at work sorry :) I'll try and get on discord later on. Any help you might need till then let me know :)

**Comment by BananaRama203** [comment]
@rcaridade145 unfortunately hit a brick wall now. Everything seems to work up to the point of:

```
reios: IP.bin is 'SEGA SEGAKATANA SEGA ENTERPRISES0495 GD-ROM1/1   U      0799A10 MK-51096  V1.00120000919        1ST_READ.BIN    SEGA ENTERPRISESSEGA MARINE FISHING                                                                                                             '
reios: Hardware ID is: SEGA SEGAKATANA 
reios: Maker ID is:    SEGA ENTERPRISES
reios: Device info is: 0495 GD-ROM1/1  
reios: Area symbols is:  U      
reios: Peripherals is: 0799A10 
reios: Product number is: MK-51096  
reios: Product version is: V1.001
reios: Release date is: 20000919        
reios: Boot filename is: 1ST_READ.BIN    
reios: Software company is: SEGA ENTERPRISES
reios: Software name is: SEGA MARINE FISHING                                                                                                             
reios: loading ip.bin from FAD: 45150
reios: bootfile is '1ST_READ.BIN    '
reios: iso9660 PVD found
reios: iso9660 root_directory, FAD: 45170, len: 20480
Found 1ST_READ.BIN at 000093
filename len: 14
file LBA: 548295
file LEN: 1443760
[libretro INFO] [LUT]: Product number: MK-51096  .
retroarch: symbol lookup error: /etc/libretro/core/reicast_libretro.so: undefined symbol: ngen_AllocateBlock
RetroArch FAILED to run using the test rig at Thu Jan  1 05:47:24 UTC 1970
```
Turns out the make needs some work but I have frigged it to the point where I can build it properly against GLES without issue at the moment.

```
/* This is declared outside the #if so that any
   the .s file will still build and run in an infinity
   loop if ngen_terminate is not available */
unsigned int ngen_required = true;

#if HOST_OS==OS_LINUX

void ngen_terminate(void)
{
        printf("ngen_terminate called\n");
        ngen_required = false;
}

#endif

RuntimeBlockInfo* ngen_AllocateBlock()
{
    return new DynaRBI();
};

#endif

``` 
doesn't seem to have any benefit either...

**Comment by rcaridade145** [comment]
Are you using -flto? Perhaps it is there but not visible..

https://stackoverflow.com/questions/43484056/c-undefined-symbol-at-runtime

**Comment by 5schatten** [comment]
at least bd2b7f0 isn't missing 

U ngen_AllocateBlock
U ngen_FailedToFindBlock
U _Z14ngen_terminatev

anymore so I guess that issue is solved.
