### ISSUE TITLE
Problem with Capcom Games since WinCE merge

### ISSUE THREAD

**Issue by Immersion95** [libretro/flycast#652]
Hi,

Since the WinCE merge, there are problems with some Capcom games :

Capcom vs. SNK 2 - The game hangs with a loading error message
Marvel vs. Capcom 2 - The game works fine except that it doesn't recognize the VMU save

Thanks for your help !

Apart from this, I'm loving this new update as the emulation's speed increased a lot ! I can play Naomi/Atomiswave games full speed on my Shield TV !

Fantastic work !

**Comment by flyinghead** [comment]
Can you move your vmu files to a safe place and retest these games without them?

I want to make sure this is not due to a corrupted vmu file.
If this is due to a corrupted vmu file, please post it here.

**Comment by jstolarek** [comment]
I'll just add that I can run both games without problems - both the Dreamcast versions and the arcade ones.

**Comment by Immersion95** [comment]
> Can you move your vmu files to a safe place and retest these games without them?
> 
> I want to make sure this is not due to a corrupted vmu file.
> If this is due to a corrupted vmu file, please post it here.

Yes it was corruption, it works again when I deleted and redid the saves. Sorry for bothering you with this stupid issue, I should have tried it before posting it :p
