### ISSUE TITLE
[Naomi] massiv performance regression since WinCE merge

### ISSUE THREAD

**Issue by 5schatten** [libretro/flycast#653]
I tried to run MS6 with the latest flycast master versions but end up with extreme low performance of less than 30fps http://ix.io/1W0E when I revert to https://github.com/libretro/flycast/commit/5adf5516ec011bb4378dfb72a926cb2f776130c4 the game runs flawless & at full speed so ~60fps http://ix.io/1W0Q

I haven't changed the package so the build process is equal for both core versions.

**Comment by flyinghead** [comment]
You shouldn't use these Atomiswave to Naomi conversions: they are very unstable. A copy I have crashed several times during my tests. I did notice the frame rate drop though.

Please use the original atomiswave rom (`mslug6.zip`) and the corresponding bios (`awbios.zip`) and you won't have frame rate issues.

**Comment by 5schatten** [comment]
Indeed it runs flawless with `mslug6.zip` & `awbios.zip` bios. I was still using a config from last year https://www.libretro.com/index.php/reicast-libretro-now-supports-naomi-other-additions/ which worked without problems until the WinCE merge.

Maybe it's a good idea too to update https://docs.libretro.com/library/flycast/ and make sure user remove the leftovers like naomi bios files if they were not used anymore.

**Comment by barbudreadmon** [comment]
The old dump format has been basically deprecated since support for MAME roms was added, it never worked perfectly in the first place (lots of issues with naomi games using special boards & "naomiswave" games), for backward compatibility the support was kept but imho it's causing more issues than it solves.

**Comment by 5schatten** [comment]
Though I must admit that I never had any trouble running MS6 with Reicast ehrm Beetle-DC eherm Flycast... well until the merge of the WinCE branch :wink: 

Anyway updating the docs & adding some notes like "after commit xxxx use`MAME_rom.zip` & `yy_bios.zip`" would be suitable. The libretro docs still list `naomi.bin` so is this necessary for any games until today?
