### ISSUE TITLE
Samurai Shodown VI - missing background?

### ISSUE THREAD

**Issue by jstolarek** [libretro/flycast#654]
Here's a screenshot taken after winning a fight in Samurai Shodown VI arcade version:

![samsptk-190920-173617](https://user-images.githubusercontent.com/1597921/65347782-a093c080-dbd7-11e9-8b56-7ebb4e4ef2f7.jpg)

Notice how text is displayed against the main background. Looking at YT videos I'm guessing it should be on a black background: https://youtu.be/3nMFMYLLrQc?t=2m58s

**Comment by flyinghead** [comment]
This game is using extremely high depth values, which cause many problems with modern open gl drivers.

Flycast has been tuned to display correctly the fighting scenes but many problems remain in opening and closing scenes. To be able to properly display all screens will require some innovative techniques...

**Comment by barbudreadmon** [comment]
Weirdly, the per-strip alpha sorting seems to work best with this game

**Comment by flyinghead** [comment]
It's a hit or miss, depending on the stage/scene

**Comment by flyinghead** [comment]
Not much can be done here. Closing...
