### ISSUE TITLE
Samurai Shodown VI - significant performance hit with texture upscaling

### ISSUE THREAD

**Issue by jstolarek** [libretro/flycast#655]
I am running my games with Texture Upscaling (xBRZ) set to x4 and Texture Upscaling Max. Filtered Size set to 256 (the default, I believe?). In Capcom vs SNK 1/2 and Marvel vs Capcom 2 this works correct and I am getting a nice 60FPS. In Samurai Shodown VI however upscaling only works if I bump Max. Filtered Size to at least 512, at which point the performance drops dramatically to 10FPS or less. I am guessing this by itself is not a bug, but rather a usual performance hit one could expect from upscaling textures. However, from a layman's perspective, it looks strange that visually similar games like CvS1/2 and MvsC2 handle upscaling without problems with a lower max size, whereas SS6 needs a higher max filtered size. Is that expected?

**Comment by flyinghead** [comment]
Many fighting games draw in ram and transfer the resulting image(s) to vram to be used as a texture.
Sometimes each fighter, or effect, is an individual texture but sometimes the entire screen, or background, is itself a texture, updated every frame. There's no performance penalty on dreamcast/naomi for frequently updating textures.

SS6 is probably updating a large texture at every frame, which has to be upscaled each and every time and this hurts performance a lot. Upscaling a 512x512 texture takes as much time as upscaling four 256x256 textures.

**Comment by flyinghead** [comment]
Working as expected
