### ISSUE TITLE
Naomi massive performance drop since WinCE merge (?)

### ISSUE THREAD

**Issue by JBDaz** [libretro/flycast#657]
I tried many different settings/ setting-combinations, but Naomi performance is down the drain for Metal Slug 6 and Samurai Showdown VI for example. Looks like an 80+% fps-drop compared to previous versions (60fps @4k > ~12fps @640x480 in some scenes).

Just using an old (non-WinCE core, same settings otherwise) of flycast brings back the great performance. 

Is this "normal behaviour" due to more precise emulation from now on, or is this a known bug which might be fixed in the future ?

- fresh install Retroarch 1.7.8 Win64, i7-8700k @5Ghz, 16GB, 1080Ti

**Comment by barbudreadmon** [comment]
duplicate of https://github.com/libretro/flycast/issues/653 maybe ?

**Comment by JBDaz** [comment]
You're absolutely right, #653 totally fixed it for me. Thank you very much !
