### ISSUE TITLE
Flycast stop working

### ISSUE THREAD

**Issue by Adancete23** [libretro/flycast#658]
Hello!

Flycast stop working for me at all ( I have Atomiswave and Sega Naomi with retroarch) after the last update of the core.Any game is not working.

It was working perfect two days ago, any suggest or help?.

Thanks!.

**Comment by flyinghead** [comment]
Are you using MAME roms?

**Comment by alejandromunozes** [comment]
In my case, it works fine as long as I don't switch to fullscreen or windowed mode. If I do, then the screen gets black and the game sound still works.

**Comment by Adancete23** [comment]
Yes, mame roms.It looks like the core dont working for me, because is not black screen or so, simply nothing, dont start.

**Comment by flyinghead** [comment]
Assuming resolved. Retest and reopen as needed
