### ISSUE TITLE
Regression - random hangs after recent updates

### ISSUE THREAD

**Issue by mlnlbrt** [libretro/flycast#66]
I have noticed that reicast core for linux x64 (2018-06-25 and 2018-06-22 nightly builds, probably those between are affected too) hangs randomly (like 9/10 times) in exact places:

- Cosmic Smash right after the first screen (the one with HISCORE and some japan characters)
- Soulcalibur in intro when camera starts to look down on the ground or right after a fight begins

It usually ends with high CPU usage and sometimes a big memory usage (memory leak?). I have tried to launch retroarch with -vvvv switch but debug does not contain anything useful at the time the core hangs.

Maybe it affects more titles, but I have tested only the above so far and only with non-OIT core. 

I don't know which exact commit introduced this regression, but this one built from scratch:
https://github.com/libretro/reicast-emulator/commit/6f3c594ca8525c13db29042a63fc35db43732472 seems to work fine.

**Comment by inactive123** [comment]
Cannot really reproduce, you need to be a lot more specific.

Try to narrow it down to a single commit or date.

**Comment by inactive123** [comment]
Cosmic Smash doesn't crash for me on Windows.

**Comment by mlnlbrt** [comment]
I will try to build some commits after https://github.com/libretro/reicast-emulator/commit/6f3c594ca8525c13db29042a63fc35db43732472 and before https://github.com/libretro/reicast-emulator/commit/2fe63fad9e54e16a5944cb2eecc4bb31e58f4539 and will let you know.

**Comment by inactive123** [comment]
Hopefully you can do this bisect sooner rather than later because I'm not about to wait with pushing commits since I personally cannot detect any regressions on Windows.

**Comment by inactive123** [comment]
Tried Soul Calibur on Arch Linux x64 - no crash whatsoever. Ran it for over 6 stages now. Not a single issue.

Reicast build is straight from the buildbot (non-OIT, 50d969e).

**Comment by toccata10** [comment]
With the latest core, ArchLinux, r9 fury: soulcalibur works fine for me.

**Comment by inactive123** [comment]
No idea what ‘pb’ even means, please make these bug reports understandable.

**Comment by inactive123** [comment]
Alright, I understand what you wrote now in your edited comment.

**Comment by rcaridade145** [comment]
@mlnlbrt do you have Shemnue 1? Can you please test it also? I've seen that behaviour at the start when the door opens before entering the garden.

**Comment by mlnlbrt** [comment]
@twinaphex sorry it took so long, I have Athlon64-class machine for hacking ;-)

I have narrowed it down to https://github.com/libretro/reicast-emulator/commit/e37a87a3aa59dfd81d45cd0bd28a71fb02c58b9f. It looks that something is wrong with Multipass switch. I had it disabled all the time and after narrowing down to this particular commit I have enabled it. It fixed the issue even with the most recent nightly core.

@rcaridade145 I don't have Shenmue 1 but I think it does not work with libretro-reicast anyway.

**Comment by inactive123** [comment]
Hi, 

@flyinghead tells me that I should just enable multipass at all times and that it shouldn't hurt. So I can probably remove the multipass switch and always enable it.

**Comment by inactive123** [comment]
Alright, pushed this -

https://github.com/libretro/reicast-emulator/commit/b3db322977781baace62573316df2dc8175621a5

Multipass should be enabled at all times with Reicast non-OIT.

@mlnlbrt Let me know if the stability issues are gone with this.

**Comment by mlnlbrt** [comment]
@twinaphex thank you, with Multipass enabled stability issues are gone.

However, if it is enabled I'm having some geometry issues in Cosmic Smash:
![cosmic smash japan -180624-101854](https://user-images.githubusercontent.com/11428910/42052522-53b8b68c-7b0f-11e8-9933-515fcd64806a.png)

You can see them sometimes when starting / finishing a level. If Multipass is disabled these issues are not happening (if I am able to start the game somehow, because as I said, with Multipass disabled it usually hangs at the very beginning).

**Comment by inactive123** [comment]
Yeah, I think Cosmic Smash needs a special workaround for the non OIT renderer that I havent backported yet from @flyinghead. let me get on that.

**Comment by mlnlbrt** [comment]
Random hangs are gone so I am closing the issue.
