### ISSUE TITLE
Flycast WinCE Games stuck at WinCE Boot Logo on armv7 32bit System

### ISSUE THREAD

**Issue by Philps** [libretro/flycast#661]
I've never gotten WinCE to work on Fire TV Gen2 [32bit][armv7]

Are these Android Version suppose to be supported using WinCE Games?

Latest Flycast Core loads the Game onto the WinCE Logo Screen then stops

System: Fire TV Gen2 - 32bit RetroArch v1.7.8 v4 - armv7

**Comment by flyinghead** [comment]
Sadly, Windows CE is only supported on 64-bit architectures.

**Comment by Philps** [comment]
OK Thanks. Keep up the good work!
