### ISSUE TITLE
Flycast won't load M3U files (multidisc)

### ISSUE THREAD

**Issue by Denshadego** [libretro/flycast#662]
When loading a m3u file (containing filenames of a set of CDI, le: Shenmue) through load content in RA, Flycast core option is absent, only other cores with CD support are shown to be chosen (Psx, Sat).

**Comment by flyinghead** [comment]
M3U files are supported but it looks like RetroArch doesn't know about it: the flycast core info file doesn't mention m3u as a supported format.

**Comment by flyinghead** [comment]
This should fix it: https://github.com/libretro/libretro-super/pull/1137

**Comment by Denshadego** [comment]
Fixed, thanks!
