### ISSUE TITLE
No i386 Linux version?

### ISSUE THREAD

**Issue by requeijaum** [libretro/flycast#663]
Doesn't appear in RetroArch's v1.7.8 Core Downloader running from Lubuntu 18.04.3.

**Comment by flyinghead** [comment]
I don't see anything being built for this platform on the buildbot. The few cores available there are 3-year old. Only 64-bit linux is available.

**Comment by barbudreadmon** [comment]
i confirm the buildbot has no linux 32-bit support at all, you'll have to use 64-bits (or build 32-bits yourself)

**Comment by requeijaum** [comment]
I can try building it! 
Just did that yesterday with ParaLLEl (Nintendo 64 core) and worked amazingly well.

Is there something worth mentioning before I do that?

**Comment by flyinghead** [comment]
x86/32 is deprecated
