### ISSUE TITLE
All Atomiswave King of Fighters run very slow (half speed) Retroarch

### ISSUE THREAD

**Issue by RaduNastase** [libretro/flycast#664]
I'm on Android 9 (One Plus 7), and while every other Dreamcast/Naomi/Atomiswave game i tested runs perfectly full speed 60/60 (for example: Capcom vs Snk 1 and 2 both Dreamcast and Naomi, Guilty Gear X both Dreamcast and Naomi, Project Justice, Rumble Fish 1 and 2, Street Fighter Upper), these 3 games: King of Fighters XI, King of Fighters Neowave and Neo Geo Battle Colliseum, run very slow, 20/60 fps. 

I tried with latest Flycast_WinCE Retroarch core.

**Comment by flyinghead** [comment]
The Flycast WinCE core has been merged into the regular Flycast core so it's no longer being updated. To have all the latest features and bug fixes, use the regular Flycast core from now on.

**Comment by RaduNastase** [comment]
Same issue man, no difference. Quite strange.

**Comment by kage2051** [comment]
Some devices get stutters with the Guilty Gear X games also. Example those with SD625. I'm guessing some GPUs can handle formats that others cannot handle at all or load very slowly. Even happens on some SoCs with Mali GPUs as well.

**Comment by RaduNastase** [comment]
I understand that some low-end devices (sd625) might have issues with some games, but OnePlus 7 is quite a different story and plays any Naomi game, 2d or 3d, flawlessly. It is definitely 'not' about the CPU/GPU here. It could be a simple on/off setting to fix these games, though i haven't been able to find out what that is.

**Comment by RaduNastase** [comment]
Managed to solve the issue. 

My workaround is a bit messy, but here it is for anyone that can not solve it any other orthodox way in Retroarch:
 
So my issues were that:
1 - The games were running extremely slow on a high end hardware.
2 - Flycast did not (and still does not) properly install as a Core. As a result i could ONLY use it when loading anything OTHER than archives .zip
I could/can perfectly load Dreamcast images, Naomi .lst or. bin or .dat and Atomiswave2Naomi .lst. 
But I could NOT load Mame Atomiswave roms because after Loading Core - Loading Content - Selecting game (.zip) i would be thrown again to the choose a Core menu, where i could see all cores EXCEPT for flycast (which was downloaded from repo as any core).

What i did, was to manually download flycast core from libretro nightlies, >rename it as an existing core from the nightlies list, that i didn't have installed< (i chose Fbalpha2012 core's exact name) and then manually install it from Install Core menu. 

Now i use the Fbalpha2012 core (which is as i said, the flycast core) , Load Content, chose .zip Mame Atomiswave rom, it takes me back again to "Choose a Core" and there i chose yet again Fbalpha2012 core, and everything runs well, full speed.

**Comment by Tatsuya79** [comment]
Did you try to update the core info files? that's probably what you're missing for the new core to get zip associated.

**Comment by RaduNastase** [comment]
Well, that would have been maybe the "orthodox" method :))

Confusing thing is, that i never had to do this for any other core as they all installed with no issues.

**Comment by DenisKim12** [comment]
friend explains to me right how to rename the core and how you did 100% to the same mistake I am Brazilian tried to do but unsuccessfully explains how you did to remomedo if you can pass the core you renamed because I can not get my friend so slow kofs .

cel Samsung Galaxy s9 snapdragon.

**Comment by RaduNastase** [comment]
If Flycast does not properly install for you, download the core manually from libretro site, put it in Retroarch - Downloads folder, rename it to fbalpha2012_libretro_android.so, and then install it from Retroarch - Install Core (you have this option in the Load Core menu). Exit Retroarch, and then open it again.

Use mame .zip Atomiswave roms and it should work now.

**Comment by DenisKim12** [comment]
Thanks my Friend.

**Comment by DenisKim12** [comment]
A verçao nova agora flycast  0.1 cddf94b tá lento as kof denovo mesmo as roms zip com vcs também? Qual a solução.
