### ISSUE TITLE
Neo-geo Battle Coliseum graphical issue

### ISSUE THREAD

**Issue by RaduNastase** [libretro/flycast#668]
Hello, 

There 's a little graphical issue with the layer order, where the background (Ralph's leg) overlaps the playing characters.

![Screenshot_20190927-111358](https://user-images.githubusercontent.com/18061144/65754945-ca3e7180-e11a-11e9-9980-39e116fe30fb.jpg)

Is there a fix for this, or is this a yet to be fixed issue?

Thanks!

**Comment by barbudreadmon** [comment]
> Is there a fix for this

Using per-pixel alpha sorting, however it's only available on desktop computer with modern opengl

**Comment by RaduNastase** [comment]
Oh, i understand. Hopefully it'll make it's way onto Android as well.

Thank you!

**Comment by barbudreadmon** [comment]
> Hopefully it'll make it's way onto Android as well.

Apart from nvidia shield, no android device supports opengl, and i think backporting OIT (aka per-pixel alpha sorting) to opengles is impossible.
The only way to get around this would probably be a vulkan renderer (would still require a modern device though).

**Comment by jstolarek** [comment]
> Apart from nvidia shield

Does this mean it wouldn't be available with AMD cards?

**Comment by flyinghead** [comment]
No, he was referring to the Android platform only. OIT works with AMD and Intel GPUs.

**Comment by RaduNastase** [comment]
So then, a Vulkan renderer wold be a possible fix...

**Comment by flyinghead** [comment]
Same issue as #741
