### ISSUE TITLE
(Naomi/Atomiswave) Missing C (button 3)

### ISSUE THREAD

**Issue by toccata10** [libretro/flycast#67]
1st of all: it's incredible to finally have some atomiswave games in reicast.
You probably already know that but just in case:
In MetalSlug6, here's the current control mapping:
X: fire (A button on Atomiswave)
Y: jump (B button on Atomiswave)

A: slug suicide (D button on Atomiswave)
B: change weapons (E button on Atomiswave)
L: test switch (system menu)
R: service button (validates in system menu; gives credit in normal game)
So, the Atomiswave's C button (grenade) is not mapped.
Tried on Dolphin Blue: seems the same as I can't launch Special attacks.
Test switch is cool as it allows to access the System Menu in which we can change the region (for metal slug 6: you can have it in english), combined with the service button.
You can also remap there the button affected to button 3 to something else (like button 4 which is less usefull) and it works. But we're still missing a button 3. MetalSlug6 needs 5 buttons and we can use only 4 for now.
Keep on the excellent work !

**Comment by barbudreadmon** [comment]
@toccata10 how did you get atomiswave working ? Is there some other special bios to put in `<system_dir>/dc` ?

**Comment by toccata10** [comment]
Following #85 , I'm now able to configure and use the C button (or button 3). Excellent !
So, I'm closing this
