### ISSUE TITLE
Sturmwind and GunLord not run on new version

### ISSUE THREAD

**Issue by dewenhsu** [libretro/flycast#670]
Use old version ( Flycast 0.1 5adf551 )can run Sturmwind and GunLord ( Dreamcast game ),
but after update to Flycast 0.1 63e16f2, it can not run Sturmwind and GunLord,
See SEGA Logo ( this is independent game ) then quit
the option is not changed.
use Odroid XU4. The RA 3.1.2 Public. RetroArch 1.7.6

for Sturmwind(US) :
==============
Cable Type VGA 
Broadcast NTSC 
Region USA
Language English
Threaded Rendering : On
==============
Thank you.

**Comment by flyinghead** [comment]
Added a commit to https://github.com/libretro/flycast/pull/671 that should fix this regression
