### ISSUE TITLE
No widescreen support for native resolution

### ISSUE THREAD

**Issue by Dogway** [libretro/flycast#674]
It seems that for enabling widescreen you have to go HD (720p+). Is it possible to add native resolution widescreen (854x480)?

Here's an old custom build with the addition. [link](https://github.com/libretro/flycast/issues/5#issuecomment-505255131)

**Comment by flyinghead** [comment]
There's been some very recent changes in this area so make sure to update the core. Some platforms are not even built yet.

All internal rendering resolutions are now 4:3.

To enable widescreen you have two possibilities:

- Widescreen hack (previously the only option) This will widen the internal resolution to 16:9. So if you chose 640x480, the internal resolution will actually be 853x480.
- Widescreen cheats: This enables cheats that allow some games to render in anamorphic widescreen format. The internal resolution stays in a 4:3 pixel format but is displayed at a 16:9 aspect ratio.

**Comment by Dogway** [comment]
I was testing with latest build downloaded an hour ago, but the widescreen resolutions fooled me thinking it still worked like the last time. I did a retest and it works for 640x480.

**Comment by Dogway** [comment]
I had some more time to test and that behavior only happens on native resolution.
When using increased internal resolutions (ie. 1440x1080), the widescreen hack stretches the images instead of widening the view. I'm not sure if this is intended. Edit: I'm still on 1.7.7 if that matters.

**Comment by flyinghead** [comment]
Do you have Widescreen Cheats enabled? If that's the case and if there's a cheat available for the game you're playing, then the screen will be stretched. However the 3D objects are supposed to be rendered at the right ratio.

**Comment by Dogway** [comment]
Sorry couldn't reply before due to a general blackout.
I don't get widescreen with only the hack setting.
Here's an image with aspect ratio set as "Core provided" and the following core settings.

https://pasteboard.co/IzPqmDl.png


```
reicast_allow_service_buttons = "disabled"
reicast_alpha_sorting = "per-pixel (accurate)"
reicast_analog_stick_deadzone = "15%"
reicast_audio_buffer_size = "1024"
reicast_boot_to_bios = "disabled"
reicast_broadcast = "Default"
reicast_cable_type = "VGA (RGB)"
reicast_cpu_mode = "dynamic_recompiler"
reicast_custom_textures = "disabled"
reicast_delay_frame_swapping = "disabled"
reicast_digital_triggers = "disabled"
reicast_div_matching = "disabled"
reicast_dump_textures = "disabled"
reicast_enable_dsp = "enabled"
reicast_enable_naomi_15khz_dipswitch = "disabled"
reicast_enable_purupuru = "enabled"
reicast_enable_rtt = "enabled"
reicast_enable_rttb = "enabled"
reicast_force_wince = "disabled"
reicast_frame_skipping = "disabled"
reicast_framerate = "fullspeed"
reicast_gdrom_fast_loading = "enabled"
reicast_hle_bios = "disabled"
reicast_internal_resolution = "1440x1080"
reicast_language = "English"
reicast_lightgun1_crosshair = "Red"
reicast_lightgun2_crosshair = "Red"
reicast_lightgun3_crosshair = "Red"
reicast_lightgun4_crosshair = "Red"
reicast_mipmapping = "enabled"
reicast_oit_abuffer_size = "2GB"
reicast_per_content_vmus = "disabled"
reicast_region = "USA"
reicast_render_to_texture_upscaling = "2x"
reicast_screen_rotation = "horizontal"
reicast_synchronous_rendering = "enabled"
reicast_system = "auto"
reicast_texupscale = "off"
reicast_texupscale_max_filtered_texture_size = "512"
reicast_threaded_rendering = "enabled"
reicast_trigger_deadzone = "0%"
reicast_vmu1_pixel_off_color = "DEFAULT_OFF 01"
reicast_vmu1_pixel_on_color = "DEFAULT_ON 00"
reicast_vmu1_screen_display = "disabled"
reicast_vmu1_screen_opacity = "100%"
reicast_vmu1_screen_position = "Upper Left"
reicast_vmu1_screen_size_mult = "1x"
reicast_vmu2_pixel_off_color = "DEFAULT_OFF 01"
reicast_vmu2_pixel_on_color = "DEFAULT_ON 00"
reicast_vmu2_screen_display = "disabled"
reicast_vmu2_screen_opacity = "100%"
reicast_vmu2_screen_position = "Upper Left"
reicast_vmu2_screen_size_mult = "1x"
reicast_vmu3_pixel_off_color = "DEFAULT_OFF 01"
reicast_vmu3_pixel_on_color = "DEFAULT_ON 00"
reicast_vmu3_screen_display = "disabled"
reicast_vmu3_screen_opacity = "100%"
reicast_vmu3_screen_position = "Upper Left"
reicast_vmu3_screen_size_mult = "1x"
reicast_vmu4_pixel_off_color = "DEFAULT_OFF 01"
reicast_vmu4_pixel_on_color = "DEFAULT_ON 00"
reicast_vmu4_screen_display = "disabled"
reicast_vmu4_screen_opacity = "100%"
reicast_vmu4_screen_position = "Upper Left"
reicast_vmu4_screen_size_mult = "1x"
reicast_volume_modifier_enable = "enabled"
reicast_widescreen_cheats = "disabled"
reicast_widescreen_hack = "enabled"
```

Actually even setting the resolution to 1920x1080 (16:9) along the hack seems to render at a wrong aspect ratio.

Comparison:

1920:1080 WS ON (old builds)
https://pasteboard.co/IzPqGlet.png
640:480 WS ON
https://pasteboard.co/IzPqOwg.png
1920:1080 WS ON
https://pasteboard.co/IzPqUIH.png
1440:1080 WS ON
https://pasteboard.co/IzPr0Nj.png

**Comment by flyinghead** [comment]
Make sure you are using the latest core update. 1920x1080 is a 16:9 resolution and should not appear anymore in the internal resolution list.

**Comment by Dogway** [comment]
Working great now, I think I was using the build just before the latest commits.
