### ISSUE TITLE
Default to HLE bios if real bios not found

### ISSUE THREAD

**Issue by paradadf** [libretro/flycast#676]
Hi and congrats for the great core!
I‘d like to suggest that the core use the HLE bios automatically if no real bios is found inside the system_dir/dc folder (and maybe also check for system_dir too). The user would have then for „Use real bios“ auto/force_hle/no_hle options to pick from, being auto auto the default.

**Comment by barbudreadmon** [comment]
> I‘d like to suggest that the core use the HLE bios automatically if no real bios is found inside the system_dir/dc

It already does

**Comment by paradadf** [comment]
Ohh really? I should have tested it before asking, but I read
`‘HLE BIOS’ is now enabled by default. If you wish to disable it and rely on a real external BIOS, you go to Quick Menu -> Options, and disable ‘HLE BIOS’ there.` and thought that would still be valid. Anyway, thank you!
