### ISSUE TITLE
Is a SH3 board fork too difficult to do, seeing how it's a shared architecture?

### ISSUE THREAD

**Issue by RaduNastase** [libretro/flycast#677]
Hello guys, can the SH3 hardware be emulated in the future with this emu?

**Comment by barbudreadmon** [comment]
Afaik flycast should already be able to emulate a SH-3 cpu for the most part, but a system is more than its main cpu, there's also audio & video.
I guess it's about cv1k (actually i don't know any other system using a SH-3), i don't think you'll get it implemented without using the bounty system.

**Comment by RaduNastase** [comment]
Yes, cv1000 is the only one that uses that hardware. Word is, the video part of the emulation is the hellish one #_#

Thanks man!

**Comment by flyinghead** [comment]
Closing in favor of #418
