### ISSUE TITLE
Music volume issue in many visual novels

### ISSUE THREAD

**Issue by RaouleMenard** [libretro/flycast#679]
Hello, in multiple japanese visual novels with the option to change the volume of the music, the volume is either 100% or 0%.
At 100% the music is too loud to hear the voices, and at 0% there is no music at all. All intermediary values are equivalent to 100%.
You can check that on the game "Elysion" (Japanese), on the title screen select "CONFIG", then the 3rd option (it is in Japanese) that will open the volume options, the "BGM" one is the music, notice that setting it to any value from 1 to 100 results in the same very loud music, and setting the value to 0 will mute the music completely.
This happen similarly in other Japanese visual novel games with a music volume option.
Tested on the 64-bit RetroArch on Android on a GPD XD+.
Any chance for a fix? I want to lower the music volume to around 50% so that I can hear the voices with the music. Basically right now it is either the voices or the music. Thanks!

**Comment by Shaneus2k2** [comment]
This issue is also happening with Metropolis Street Racer on the Switch build, so I assume it occurs with all games using redbook audio, and across all platforms.

**Comment by flyinghead** [comment]
I was able to reproduce the issue and it only happens with the arm dynarecs (both 32 and 64 bits).
No problem with the x64 dynarec or the interpreter.

PS: Neither Elysion nor Metropolis Street Racer use CDDA/redbook audio.

**Comment by flyinghead** [comment]
It seems to be a problem due to DIV Matching being enabled. Can you re-test with it disabled?

**Comment by Shaneus2k2** [comment]
Not sure exactly what DIV matching does, but it definitely fixed the problem!Thanks for the info on the audio too :)

**Comment by RaouleMenard** [comment]
> It seems to be a problem due to DIV Matching being enabled. Can you re-test with it disabled?

I also confirm that disabling DIV matching fixes the issue. Thanks a lot!

**Comment by flyinghead** [comment]
should be fixed by https://github.com/libretro/flycast/commit/f9f3249192f487b9d8de0a06531af331d4207fee
