### ISSUE TITLE
Metropolis Street Racer - can't activate rear view mirror

### ISSUE THREAD

**Issue by Nine-H** [libretro/flycast#68]
I thought this one was interesting: turning on the mirror in MSR doesn't work and every other frame is blank. I guess this means theres some sort of buffer, masking, or interlacing mode that isn't emulated correctly, because I think every other frame means there's 2-passes that aren't completing correctly.

**Comment by flyinghead** [comment]
Very interesting: when activating the mirror, MSR uses clipping to alternatively render the mirror and the rest of the screen. However, the screen is cleared between each pass so it blinks. It's not even using multipass rendering.

**Comment by flyinghead** [comment]
Yes, MSR is rendering the screen twice to the same VRAM location. I suppose it relies on clipping to avoid overwriting the previous rendering (since clipping is defined in multiple of the tile size). Then the whole thing is displayed at the next vblank.

**Comment by rcaridade145** [comment]
@Nine-H Does this happen on every type of "connection", RGB, TV,etc.. ?

**Comment by Nine-H** [comment]
Connection|Effect
--|--
VGA | flicker
TV (RGB)| Black screen
TV(VBS/Y+S/C)|Black screen

I think VGA enables some kind of sync (or 60hz display mode) so you get the flicker instead of the blank composited frame.

**Comment by inactive123** [comment]
I strongly suspect the SPG code still isn't correct, because I noticed similar display sync/flickering issues with certain Naomi games (best case in point still is the Naomi bootup screen, flickering very erratically). Note that Reicast libretro deviates a bit from the mainline Reicast/nulldc code there since I tried incorporating some code from MAME since the values they came up with for the SPG clock led to better frame pacing on my end, but I think both implementations (reicast libretro and reicast mainline/nulldc) are still not accurate for these modes, which leads to all these deviations when changing the TV type.

For instance, in order to get Quake 3 Arena to even work on reicast right now, I have to set connection to VGA. In order to get Shadowman to work, same story. And even after I get through the intro cutscene in ShadowMan, it just outputs a black screen except for one part of the HUD being visible and the Start menu being triggerable.

**Comment by rcaridade145** [comment]
Display mode | Resolution (pixels) | Interlace mode
-- | -- | --
NTSC_320×240NI | 320×240 | Non-interlaced
NTSC_320×240I | 320×240 | Single interlaced
NTSC_640×240NI | 640×240 | Non-interlaced
NTSC_640×240I | 640×240 | Single interlaced
NTSC_640×480 | 640×480 | Double interlaced
PAL_320×240NI | 320×240 | Non-interlaced
PAL_320×240I | 320×240 | Single interlaced
PAL_640×240NI | 640×240 | Non-interlaced
PAL_640×240I | 640×240 | Single interlaced
PAL_640×480 | 640×480 | Double interlaced
VGA | 640×480 | Non-interlaced


Ragister name | NTSC   Non-interlace | NTSC   Interlace | PAL   Interlace | PAL   Interlace | VGA
-- | -- | -- | -- | -- | --
  | 320x240   640x240 | 320x240   640x240   640x480 | 320x240   640x240 | 320x240   640x240   640x480 | 640x480
SPG_LOAD | 0x01060359 | 0x020C0359 | 0x0138035F | 0x0270035F | 0x020C0359
SPG_HBLANK | 0x007E0345 | 0x007E0345 | 0x008D034B | 0x008D034B | 0x007E0345
SPG_VBLANK | 0x00120102 | 0x00240204 | 0x002C026C | 0x002C026C | 0x00280208
SPG_WIDTH | 0x03F1933F | 0x07D6C63F | 0x07F1F53F | 0x07D6A53F | 0x03F1933F
SPG_CONTROL | 0x00000140 | 0x00000150 | 0x00000180 | 0x00000190 | 0x00000100
VO_STARTX | 0x000000A4 | 0x000000A4 | 0x000000AE | 0x000000AE | 0x000000A8
VO_STARTY | 0x00120011 | 0x00120012 | 0x002E002E | 0x002E002D | 0x00280028
VO_CONTROL | In case of 320：   0x00160100   In case of 640：   0x00160000 | In case of 320：   0x00160100   In case of 640：   0x00160000 | In case of 320：   0x00160100   In case of 640：   0x00160000 | In case of 320：   0x00160100   In case of 640：   0x00160000 | 0x00160000

**Comment by flyinghead** [comment]
There might be some sync related problems on top of that but the renderer in its current state doesn't support this kind of multiple rendering anyway.

**Comment by rcaridade145** [comment]
@flyinghead  how can i send you a doc i have on the dreamcast without being through here?

**Comment by flyinghead** [comment]
@rcaridade145 you should be able to drop it there: https://www.dropbox.com/request/WLy2MSdUXx0euqg3CzYh

**Comment by rcaridade145** [comment]
@flyinghead  ERR_TUNNEL_CONNECTION_FAILED :-1:

**Comment by flyinghead** [comment]
I guess dropbox has issues... Try this: https://script.google.com/macros/s/AKfycbytWUDD-al2fTr6fyH8uSuluAH33yPtS96m2DU42w/exec

**Comment by rcaridade145** [comment]
@flyinghead i found that info a while back hope you find it useful..

**Comment by flyinghead** [comment]
I just had a quick glimpse over it but it looks very interesting. Thanks a bunch!

**Comment by flyinghead** [comment]
Interestingly, after the fix for San Francisco Rush about clipping scissor test, you can now see the rear view mirror content displayed. However it renders alternatively the front and rear views and this produces lots of flickering.

**Comment by inactive123** [comment]
Time to test the rear view window in MSR again after the most recent commits.

**Comment by flyinghead** [comment]
It's not completely fixed as it still flickers but it should be noticeably better

**Comment by Nine-H** [comment]
I tested 31c1caf and it appears to be working with some issues, I couldn't find a frame where the mirror flickered and I'm not sure if it was the same issue or something to do with the lighting in the render view. I did notice serious issues on stages where there's fog: the mirror would sometimes be fully opaque with fog colour.

**Comment by Shoegzer** [comment]
Haven't had a chance to look into this one myself but if I'm interpreting the commit notes correctly, it seems this might be fixed as of commit e2b6e442a48ede31d02ab7d088d7f1d153d5b182.   @Nine-H can you please confirm and close this if so?

**Comment by flyinghead** [comment]
@Shoegzer you're spot on

Note that right now this fix is only in the WinCE core/branch. It is not related to Windows CE but it may have unwanted side effects or affect performance. Feedback is welcome.

**Comment by Shoegzer** [comment]
@flyinghead thanks much.  Good point about the WinCE branch, I forgot to mention that here for others testing.  I'll also keep hammering away at things myself as per usual, with your comments in mind, and let you know what significant bits pop out.

**Comment by flyinghead** [comment]
This requires the Threaded Rendering and Delay Frame Swapping options to be enabled and it only works in Open GL atm. Closing for now.
