### ISSUE TITLE
The King of Fighters Dream Match 1999 - Sprites glitch

### ISSUE THREAD

**Issue by mochardi** [libretro/flycast#680]
Hi, 
New guy here! 

I was wondering about this issue...

https://github.com/libretro/flycast/issues/172#issue-340832730

The odd thing is that the sprites glitch only occur in the animations before, between and the end of rounds. (Not during the round itself.) And even at 640x480, the native resolution of the Dreamcast.

I'm thinking that these animations maybe are played in 320x240, or maybe this whole game runs at that resolution internally, and then upscaled to 640x480 by the dreamcast. 

Pre round...
![King of Fighters, The - Dream Match 1999 v1 004 (1999)(SNK)(US)(M4) ! -191002-010722](https://user-images.githubusercontent.com/55611450/66173651-a0f47880-e627-11e9-83f3-917f57eafc73.png)

One second later...
![King of Fighters, The - Dream Match 1999 v1 004 (1999)(SNK)(US)(M4) ! -191002-010726](https://user-images.githubusercontent.com/55611450/66173658-a81b8680-e627-11e9-9aae-51a83359041b.png)

Sorry for my english

**Comment by flyinghead** [comment]
This game is one of the few ones that has a native resolution of 320x240. This is why you see this glitches when running at 640x480.

The core doesn't switch automatically to the game's native resolution.

**Comment by flyinghead** [comment]
Working as expected
