### ISSUE TITLE
Capcom vs. SNK 2 (NTSC-J) hangs

### ISSUE THREAD

**Issue by litaniast** [libretro/flycast#685]
When I tried to load CVS2 Dreamcast version, after the Sega logo, it says 'オートロード中です…' and freezes.

I deleted vmu file but no changes.

NAOMI version works well, but DC version doesn't.

platform : RockPro64 
OS : TheRA ( RetroArch 1.7.8 )
core verison: Flycast (0.1 a628b32)
Core option : tried HLE BIOS on /off, Force WinCE mode on/off

platform : Windows 10
OS : RetroArch 1.7.8 
core verison: Flycast (0.1 45a1520)
Core option : tried HLE BIOS on /off, Force WinCE mode on/off

**Comment by litaniast** [comment]
Sorry. I only deleted per-game vmu file. after I delete the vmu file in DC folder, it finally works.

**Comment by flyinghead** [comment]
Thank you for the updated information. Closing as it seems resolved.
