### ISSUE TITLE
Gunlord not working (black screen)

### ISSUE THREAD

**Issue by DarishZone** [libretro/flycast#686]
On previous source version of Flycast Gunlord was working, now with the build 45a1520 the game show black screen, thus i can hear sounds and music.
I confirm issue persist even on new 6df581c build.

Tested on Rpi3 under RetroPie.

**Comment by DarishZone** [comment]
I confirm issue persist even on new 6df581c build.

**Comment by flyinghead** [comment]
Hopefully commit bd01bee447da83eede171f1ae9e6474e1a6e862a should fix this issue.

**Comment by DarishZone** [comment]
I confirm 0643e6a build resolved issue. Thanks!

**Comment by flyinghead** [comment]
Closing as resolved
