### ISSUE TITLE
xBRZ texture scalling produces border artifacts on sprites

### ISSUE THREAD

**Issue by jstolarek** [libretro/flycast#688]
Enabling xBRZ texture scalling in various games that use sprites produces black border artifacts. I did a little bit of investigation and here's what I found. Firstly, a reference image with no texture scalling:

![1](https://user-images.githubusercontent.com/1597921/66707398-cc6a1800-ed37-11e9-8f16-36c2444522fc.jpg)

This is Mai Shiranui's leg from Capcom vs SNK 2. Setting xBRZ texture scalling to x4 results in multiple black pixels on the sprite border:

![2](https://user-images.githubusercontent.com/1597921/66707400-d1c76280-ed37-11e9-9929-5c42446c67fc.jpg)

And not just on the border; notice in the image above that there are two black pixels close to left image border, completely separate from the rest of the sprite. I downloaded a program for testing xBRZ scaller from the project webpage ([here](https://sourceforge.net/projects/xbrz/files/)) to see whether the same thing happens, but with that program everything works as expected:

![4](https://user-images.githubusercontent.com/1597921/66707404-d724ad00-ed37-11e9-89f2-0c82c1229acb.png)

Flycast currently uses xBRZ version 1.5, the latest version is 1.7, and the ScallerTest program was most likely built using xBRZ 1.6 (guessing by the dates). I tried replacing xBRZ version in flycast with the latest version (this requires enabling C++14 in the Makefile on line 977) and here's the result:

![3](https://user-images.githubusercontent.com/1597921/66707405-dbe96100-ed37-11e9-9907-dc5edd84bd6c.jpg)

The black pixels are gone but now there are random transparent pixels inside the sprite. In case it isn't obvious from the above picture, here's how Mai's head looks:

![5](https://user-images.githubusercontent.com/1597921/66707413-ed326d80-ed37-11e9-9af0-ead92be41bc8.jpg)

After some investigation I found out that the difference between the two types of artifacts boils down to the definition of RGB version of `makePixel` in `core/deps/xbrz/xbrz_tools.h`. In the current version of flycast it looks like this:

```
inline uint32_t makePixel( unsigned char r, unsigned char g, unsigned char b)
   { return 0xFF000000 | (b << 16) | (g << 8) | r; }
```
And this produces black pixels on the borders. Starting with version 1.6 this has been modified to:

```
inline uint32_t makePixel( unsigned char r, unsigned char g, unsigned char b)
   { return             (r << 16) | (g << 8) | b; }
```
which makes the black pixels go away but produces transparent pixels instead. I conjecture that the scaller itself is correct but something goes wrong when it is applied to sprites by flycast. I don't know where to go from here, this is above my paygrade. I hope that this investigation is helpful in some way and will allow to pin down the bug because, frankly speaking, it is very annoying.

**Comment by jstolarek** [comment]
A few more thoughts and questions regarding the contents of `xbrz.cpp` file:

1. The `makePixel` function mentioned above is used in `gradientRGB` function that does alpha-blending of foreground and background. I would assume that foreground is the sprite and background is whatever is behind it, but looking at the code I am now not sure of it. `gradientRGB` is called from `alphaGrad` function, which updates the background pixel:
```
struct ColorGradientRGB
{
    template <unsigned int M, unsigned int N>
    static void alphaGrad(uint32_t& pixBack, uint32_t pixFront)
    {
        pixBack = gradientRGB<M, N>(pixFront, pixBack);
    }
};
```
And notice that it is the background that is updated, at least according to the names. Weird.

2. In the updated xBRZ scaler, i.e. the one that produces transparent pixels inside the sprite, notice that these pixels appear only on the corners. Here's the original sprite:

![6](https://user-images.githubusercontent.com/1597921/66708206-c6c6ff00-ed44-11e9-8de3-cfa21e9299c8.jpg)

and after scaling:

![7](https://user-images.githubusercontent.com/1597921/66708207-cb8bb300-ed44-11e9-9ca2-8acdd06b0ed8.jpg)

3. I wrote that the current version of scaler used in flycast produces black pixels on the edges, but that is not exactly true. The pixels aren't black, just dark. It seems as if one of the arguments passed to alpha blending is indeed black and then it is averaged with a lighter colour to become a dark version of that colour.

I am not sure how (2) and (3) are possible. Meaning, these are things internal to the scaler. I would imagine that flycast hands the texture to the scaler, which then does its job and returns an upscaled image. However, it seems that the way the scaler is used in flycast causes some unexpected interactions between different scaler passes, which lead to the artefacts described above.

**Comment by flyinghead** [comment]
Some textures were mistakenly upscaled without their alpha channel. This should now be fixed.

**Comment by jstolarek** [comment]
Indeed, now things work correctly.
