### ISSUE TITLE
VMU problems on Switch

### ISSUE THREAD

**Issue by josereyesjrz** [libretro/flycast#689]
I'm having problems loading VMUs in the Switch core. I was trying to load 8 VMUs for Fire Pro Wrestling D, but it only ever works with the Per-Game VMUs on OFF but it only loads the first 4 VMUs anyway. If I turn Purupuru off, all VMUs appear empty. With Per-Game turned on VMUs always appear empty, with or without Purupuru on.

**Comment by flyinghead** [comment]
Closing in favor of #693
