### ISSUE TITLE
All games made by NG:DEV TEAM run too fast

### ISSUE THREAD

**Issue by litaniast** [libretro/flycast#695]
I tested some games made by NG:DEV TEAM (Fast Striker, Gunlord, Last Hope/Last Hope Pink Bullets, NEO-XYX) but they run too fast.

(only NEO-XYX with Vertical.S screen is ok for playing. others are too fast)

platform : RockPro64
OS : TheRA ( RetroArch 1.7.8 )
core verison: Flycast (0.1 0643e6a)
Core option : tried HLE BIOS on /off, Force WinCE mode on/off

**Comment by flyinghead** [comment]
Should be fixed by https://github.com/libretro/flycast/pull/710/commits/42bb73ece4e07e8908e1c914a760084b66aeaecb

**Comment by flyinghead** [comment]
assuming it's fixed
