### ISSUE TITLE
Slow/stuttering on 2D Fighting Games - Nintendo Switch 

### ISSUE THREAD

**Issue by tabnk** [libretro/flycast#697]
2D Games such as Marvel vs. Capcom 2, SNK vs. Capcom 1, etc. Mostly stuttering and unable to reach full speed.

However, 3D fighting game seem to play very well.

**Comment by Panderner** [comment]
SNK Games on Atomiswave struggles on low end ARM devices including a Nintendo Switch. However guilty gear, Melty Blood, fist of the north star, The Rumble Fish worked well. Marvel vs Capcom on Naomi version is slower than a Dreamcast version.

**Comment by tabnk** [comment]
Using switchroot LineageOS 15.1, as it run much better and full speed.
