### ISSUE TITLE
[Feature Request] Better VMU positioning

### ISSUE THREAD

**Issue by IceLancerSR** [libretro/flycast#698]
[Feature Request] Better VMU positioning
If possible..
![20191016181047](https://user-images.githubusercontent.com/4452102/66941404-1a885f80-f047-11e9-83cf-7a1d3e932d97.jpg) 
Image above is from demul with rocketlauncher
on flycast right now all i can get is VMU on top of main screen ,cutting part of it and where there is fmv its worse because it stretches a lot

NDS (desmume) has solved that by making "hybrid" screen and u can choose how to set it up. Similar or same for flycast would be awesome
![abb96ee74a8ee06ea84bfafca9964b4b97f0ad01](https://user-images.githubusercontent.com/4452102/66941736-d9447f80-f047-11e9-9cb0-d5396ad5dd0d.png)

**Comment by Sanaki** [comment]
Came to request this exact thing. The overlay is frustrating when you have off-screen space unused. Especially in games where it covers HUD elements.
![Ecco](https://user-images.githubusercontent.com/1374333/71536982-a05d3c80-290d-11ea-963d-19d232460348.png)

**Comment by flyinghead** [comment]
Closing in favor of #265
