### ISSUE TITLE
Rayman 2 - Missing bump-mapping

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#70]
![image](https://user-images.githubusercontent.com/1075274/42037570-03a1a828-7ae9-11e8-81b2-e8c8711af46c.png)

This is how the ground texture is rendered right now. 
Apparently, this texture is supposed to look far more detailed by way of bump mapping, like this -

![image](https://user-images.githubusercontent.com/1075274/42037607-1d51184e-7ae9-11e8-8173-5be102a04573.png)

There is another known game that uses bump-mapping as well. Shenmue 2 uses it for rendering certain coins.

Both OIT and non-OIT renderers are currently missing this.

**Comment by inactive123** [comment]
I traced back the commit which added the 'fake' implementation for bump mapping -

https://github.com/reicast/reicast-emulator/commit/d70617f9dcff2d5974a3cb62e8cfb9fc2d866ab5

**Comment by flyinghead** [comment]
Here is a first implementation: https://github.com/flyinghead/reicast-emulator/commit/69263eddc0b87f1232a566bc2c6c94977cdcdf1c
Hard to tell if it's right or not. It looks similar to screenshots and videos of Rayman I've looked up though.

**Comment by inactive123** [comment]
Awesome! I will be back in about two hours and then I will immediately get on with backporting this. I will also give the master backports another try - I think I might have screwed up before there.

**Comment by inactive123** [comment]
This is now implemented in both OIT and non OIT renderers.
