### ISSUE TITLE
On-Screen Controls input bug

### ISSUE THREAD

**Issue by Panderner** [libretro/flycast#701]
There's a bug when I play crazy taxi using on screen controls the analog stick looks weird

Analog in the left:
![Screenshot_2019-10-22-22-33-18-48_a845f06d2c9842610668be6995f9e34f](https://user-images.githubusercontent.com/37503397/67297367-63935480-f51c-11e9-9858-383df93efade.png)

Analog in the right:
![Screenshot_2019-10-22-22-37-14-27_a845f06d2c9842610668be6995f9e34f](https://user-images.githubusercontent.com/37503397/67297484-8faed580-f51c-11e9-9f64-7852a9479d92.png)

I tried DC and Naomi versions, this does not occur when I connected to my controller

**Comment by i8890321** [comment]
hmmm although i m not playing the same game but i defintiely having input issue similar to you 

i was playing DC game 90 mins sega champion soccer.

When i move my on screen Left stick to the right direction, i can see that it press the R Button together.

It makes my player in the game rush forward and lose the ball control. Its quite obvious. I tried with another Emu , no such thing happened.

**Comment by flyinghead** [comment]
I just realized I have the same issue. One work-around is to enable digital triggers in the flycast core options.

**Comment by Panderner** [comment]
> I just realized I have the same issue. One work-around is to enable digital triggers in the flycast core options.

I enabled digital trigger but same results

**Comment by Panderner** [comment]
When I press r2 push analog to the left it refuse to accelerate
![Screenshot_2020-02-16-21-43-06-98_a845f06d2c9842610668be6995f9e34f](https://user-images.githubusercontent.com/37503397/74605716-84a03680-5105-11ea-9e35-30c160baa332.png)

**Comment by Panderner** [comment]
also happens in all games

**Comment by Panderner** [comment]
https://streamable.com/ij4pps here's a video that it happened

**Comment by Panderner** [comment]
This must be retroarch bug. It happens other cores closing
