### ISSUE TITLE
Sonic clipping off track segments

### ISSUE THREAD

**Issue by ghost** [libretro/flycast#706]
There is an issue with Sonic falling off the tracks in Windy Valley. You cannot get past the second sequence (after the tornado). 

This issue was once present in reicast/reicast-emulator#1489 and was fixed by @flyinghead 

The save state posted below is just before one of the loops that sonic can't complete as he falls off.

I have tried this on a mix of stable and nightly builds using Windows 10 build, Lakka 2.3 build xu4, and lakka generic x86_x64.

**Comment by ghost** [comment]
[Sonic Adventure (USA) (En,Ja,Fr,De,Es).zip](https://github.com/libretro/flycast/files/3790739/Sonic.Adventure.USA.En.Ja.Fr.De.Es.zip)
just before one of the loops that sonic falls off.

**Comment by flyinghead** [comment]
The upstream fix you mention has been ported to the flycast core already. Does this problem only occur with the core and not with upstream?

**Comment by ghost** [comment]
I’m not sure about upstream, if your referring to reicast I have not tried. I’ve only tested the flycast core on many of retroarch’s platforms and it seems to be consistent across the board. Does he complete the loop in the save state I provided? could it be a setting I have?

**Comment by flyinghead** [comment]
Did you reproduce the problem on arm or arm64? I'm thinking of an x86-specific issue but that would rule it out.

I haven't tested your savestate but I assume I'd have the same issue.

Make sure to disable DIV matching. That's the only setting I can think of that could make a difference.

**Comment by flyinghead** [comment]
Same problem happens with upstream, with both dynarec and interpreter, but only on x86. Arm is not affected.

**Comment by flyinghead** [comment]
Should be fixed by https://github.com/libretro/flycast/pull/709/commits/8442b8b1589f4eb84fa70841c535cca392bdfc52

**Comment by ghost** [comment]
I will test this today, and also when it is merged into lakka. As for arm I’ll retry my savestate with an xu4 and my Nintendo switch. Thank you for looking into it.

**Comment by flyinghead** [comment]
I wasn't able to reproduce the problem on arm, so this fix is x86-only.

Let me know if the issue also happens on arm.

**Comment by MastaG** [comment]
For the record, I've been playing sonic adventure 1 on my xu4 (arm32) with last weeks build and I didn't have any problems completing windy valley.

**Comment by ghost** [comment]
Awesome work @flyinghead, thank you for all the work you have put into this awesome emulator, works perfect now.

issue closed.

**Comment by tails101** [comment]
@flyinghead i can confirm it is a x86 issue only
i can reproduce it every time on my 4770k but work perfectly on shield tv (arm tegra x1)
