### ISSUE TITLE
Street Fighter Alpha 3 Crashes after SEGA logo

### ISSUE THREAD

**Issue by Denshadego** [libretro/flycast#707]
Street Fighter Alpha 3 Crashes after SEGA logo, using the last Flycast Core con PC

**Comment by flyinghead** [comment]
It works for me. Please provide more details.

**Comment by Denshadego** [comment]
Logging through RA doesn't write anything. Using the latest Windows 86_64 RA nightly on windows 10 64 bits and latest Flycast core, RA crashes after this screen:
![imagen](https://user-images.githubusercontent.com/47835860/68060309-896be680-fcde-11e9-8f15-ea1199126774.png)
I should mention that the game used to work before, and it works actually on android, just not on my PC. Every other game works, even similar Capcom fighters.

The specific CDI used is the one found on replayers . org (if mentioning this is against a rule, go ahead and edit/delete the reply). RA crashes be it CDI or CHD, even when deleting the config, core overrides.

**Comment by flyinghead** [comment]
Just tried on windows 10 and it works fine. Try deleting/moving your vmu files and/or dc_nvmem.bin file.

**Comment by QkiZMR** [comment]
It crashing in same moment on Android (Retroarch).

**Comment by Denshadego** [comment]
Hi! Change the Cable type in options to TV (Composite) and close
content/load the game again. That solved it on my end.



*Ilustrador / Diseñador Gráfico**+56 9 8185 7163*
https://www.instagram.com/demo.danza
https://www.facebook.com/demo.danza/
<https://www.instagram.com/demo.danza>http://demodanza.tumblr.com/
<https://www.youtube.com/user/demodanza>

**Comment by flyinghead** [comment]
This game doesn't support TV (RGB) which used to be the default

**Comment by QkiZMR** [comment]
@demodanza thx. It works now.
