### ISSUE TITLE
Bomberman Online - Glitching title screen

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#71]
@flyinghead Could be more YUV corruption issues maybe - the title screen seems to be a looping FMV video that plays over and over. Certain parts of this video are rendered correctly, but at specific intervals it glitches out.

![image](https://user-images.githubusercontent.com/1075274/42040390-c93ac4e2-7aef-11e8-9d72-543d66e730f7.png)

Glitches -

![image](https://user-images.githubusercontent.com/1075274/42040464-f5b08dc2-7aef-11e8-8161-a371f5228440.png)

**Comment by inactive123** [comment]
Happens with both Reicast OIT and non-OIT.

**Comment by flyinghead** [comment]
Yep, happens on my fork as well. Could be a DMA timing issue or some sync problem.

**Comment by rcaridade145** [comment]
@flyinghead @twinaphex Maybe the yuv dma is not being correctly terminated, or its detection if faulty. It uses the ch2-dma. If you look at the page 57 of that doc i've sent you.

**Comment by flyinghead** [comment]
Actually it's a bug I introduced myself... Sorry
See https://github.com/flyinghead/reicast-emulator/commit/f18aa63a670248ff6595e37f3eb3940f295afa56

**Comment by rcaridade145** [comment]
Great job @flyinghead :1st_place_medal: 
Yesterday i compared spg from reicast master and libretro. There are some differences on CalculateSync but i'm not sure which one is more correct, or not being correct works best on reicast

**Comment by flyinghead** [comment]
Thanks!
There is still a remaining problem though: the first FMV video hangs at this point:
![bomberman online usa rdc -180629-125310](https://user-images.githubusercontent.com/16261910/42088935-a00e89a8-7b9b-11e8-83fe-887f9726de57.png)
It happens both in upstream and in the libretro OIT core.
The game doesn't hang and pressing start leads you to the title screen. After a while the first FMV video is played again, but doesn't hang this time...

**Comment by rcaridade145** [comment]
@flyinghead talking about a  cliffhanger. :rofl: This with dynarec? Any difference with interpreter?  If not it may be a DMA issue.

**Comment by flyinghead** [comment]
Same with generic recompiler

**Comment by inactive123** [comment]
Some of the SPG changes I carried over from MAME. The only thing I happened to notice as a result was that I got better frame pacing in the core vs. before.

**Comment by inactive123** [comment]
Anyway, awesome commit. I will be sure to backport soon.

**Comment by inactive123** [comment]
Backported the PR. Seems to work fine now.

Weirdly enough though, the FMV intro doesn't hang for me at all. 

Try to see if the EG hack is being applied to your copy of the game -

https://github.com/libretro/reicast-emulator/blob/master/core/rom_luts.h#L49

**Comment by flyinghead** [comment]
Indeed, it wasn't applied. And that fixes it. Thanks!

**Comment by inactive123** [comment]
If you had to add another entry, let me know what line you had to add so i can add it to the list.

**Comment by flyinghead** [comment]
I'm running the USA release but it's been "renumbered": RDC-0117

**Comment by inactive123** [comment]
Hmm sucks, from looking at it, it seems that this serial number corresponds to another game - 

RDC-0117| The king of Fighters '96 Collection (NEO4ALL RC4)

Can we find some other heuristic to more accurately identify games by? Seems a lot of the GD-ROM rips were renumbered/mislabelled.

**Comment by flyinghead** [comment]
Well I confirm its id is RDC-0117 although it should be RDC-0120 according to a reference I found by googling...
Using the Software name would be fine in this case: "BOMBERMAN ONLINE"

**Comment by inactive123** [comment]
OK, let me see if we can maybe catch both of them at the same time through a software name lookup instead.

**Comment by inactive123** [comment]
I will close this for now since the main issue is fixed. Reminder to self: I still need to add the heuristic for detecting both versions of Bomberman Online.
