### ISSUE TITLE
CHDs converted from new Redump set (cue+bin) don't work

### ISSUE THREAD

**Issue by luke-70it** [libretro/flycast#711]
CHDs converted from previous Redump set (gdi+bin) work fine.
Not sure if it's a Flycast or a chdman issue.

**Comment by flyinghead** [comment]
Can you post the result of `chdman info` on the converted CHD?

**Comment by luke-70it** [comment]
Ciao flyinghead,
i paste output for both cue+bin converted CHD and gdi+bin, and content of cue file and gdi file. Please note that bin files are exactly the same.

cue version (not working):
chdman - MAME Compressed Hunks of Data (CHD) manager 0.215 (mame0215)
Input file:   Sonic Adventure (Europe) (En,Ja,Fr,De,Es).chd
File Version: 5
Logical size: 1,276,915,968 bytes
Hunk Size:    19,584 bytes
Total Hunks:  65,202
Unit Size:    2,448 bytes
Total Units:  521,616
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     918,052,708 bytes
Ratio:        71.9%
SHA1:         0e2c550493fa92e9d880513ea1e1d9fb5a99ea78
Data SHA1:    1ce5d73f1d281898d67889b1788a3d0cb2894c59
Metadata:     Tag='CHT2'  Index=0  Length=92 bytes
              TRACK:1 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:11361 PREGAP:0 PG
Metadata:     Tag='CHT2'  Index=1  Length=90 bytes
              TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:6100 PREGAP:150 PGTYP
Metadata:     Tag='CHT2'  Index=2  Length=93 bytes
              TRACK:3 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:504150 PREGAP:0 P


gdi version (working):
chdman - MAME Compressed Hunks of Data (CHD) manager 0.215 (mame0215)
Input file:   G:\ROMS\Sega - Dreamcast\Sonic Adventure (Europe) (En,Ja,Fr,De,Es).chd
File Version: 5
Logical size: 1,344,333,888 bytes
Hunk Size:    19,584 bytes
Total Hunks:  68,645
Unit Size:    2,448 bytes
Total Units:  549,156
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     918,091,469 bytes
Ratio:        68.3%
SHA1:         50217f935cd273dc31c31137ca7844f84c61d955
Data SHA1:    c30498011683816e8a4e0557dea587c348d79890
Metadata:     Tag='CHGD'  Index=0  Length=98 bytes
              TRACK:1 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:11361 PAD:0 PREGA
Metadata:     Tag='CHGD'  Index=1  Length=98 bytes
              TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:33639 PAD:27539 PREGA
Metadata:     Tag='CHGD'  Index=2  Length=99 bytes
              TRACK:3 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:504150 PAD:0 PREG

Here is cue content:
REM SINGLE-DENSITY AREA
FILE "Sonic Adventure (Europe) (En,Ja,Fr,De,Es) (Track 1).bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
FILE "Sonic Adventure (Europe) (En,Ja,Fr,De,Es) (Track 2).bin" BINARY
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
REM HIGH-DENSITY AREA
FILE "Sonic Adventure (Europe) (En,Ja,Fr,De,Es) (Track 3).bin" BINARY
  TRACK 03 MODE1/2352
    INDEX 01 00:00:00

And here is the gdi content:
3
1     0 4 2352 "Sonic Adventure (Europe) (En,Ja,Fr,De,Es) (Track 1).bin" 0
2 11361 0 2352 "Sonic Adventure (Europe) (En,Ja,Fr,De,Es) (Track 2).bin" 0
3 45000 4 2352 "Sonic Adventure (Europe) (En,Ja,Fr,De,Es) (Track 3).bin" 0

Thank you very much!

**Comment by flyinghead** [comment]
I might be mistaken but I don't think chdman can convert from cue-gdrom to chd.
A GD-ROM has exactly 549,156 sectors, as shown in the gdi-chd:
```
Total Units: 549,156
```
whereas the cue-chd shows:
```
Total Units: 521,616
```
Also the second track (audio) is much shorter on the CUE version (6100 sectors vs. 33639)

**Comment by luke-70it** [comment]
You are right!
I opened an issue on mame github (#5866), but it seems that mamedev team doesn't plan to support gdrom conversion to chd from cue+bin format.
