### ISSUE TITLE
Capcom vs Snk 2 glitch

### ISSUE THREAD

**Issue by ghost** [libretro/flycast#713]
Capcom vs snk 2 have a weird glitch on the ice stage, everything gets blue.

Platorm: S905X
Emuelec -  Libretro Flycast Latest Retroarch.
2Gb Ram 16GB rom!

**Comment by flyinghead** [comment]
https://github.com/libretro/flycast/pull/717 should take care of the issue. Please test and close accordingly. Thanks

**Comment by barbudreadmon** [comment]
Closing, it seems this person deleted his/her account.
