### ISSUE TITLE
Sega Naomi 2: any plan to support?

### ISSUE THREAD

**Issue by zanac** [libretro/flycast#715]
What about a bounty for support Naomi 2?

**Comment by flyinghead** [comment]
The main issue here is the lack of documentation about the Naomi 2 T+L Elan chip.

**Comment by barbudreadmon** [comment]
The bottleneck for naomi 2 support is that we can't find any documentation about its elan chip (its 3rd graphic processor), MAME doesn't support it, demul is closed-source, reverse engineering it is not an option.

**Comment by barbudreadmon** [comment]
If we could find a dieshot and someone well-versed in electronics, maybe it would be possible to figure something out, i'm wondering if the demul guys (@p1pkin ?) have some dieshot to share about this chip ?

**Comment by zanac** [comment]
but repository https://github.com/p1pkin/demul is not the right place to study it?

**Comment by barbudreadmon** [comment]
No, this is a really old snapshot of the code, afaik from way before naomi 2 got supported, demul is neither open-source not gpl. The repo is only used to track issues.

**Comment by p1pkin** [comment]
> reverse engineering it is not an option

I'm honestly wondering why ?

> have some dieshot to share about this chip ?

no, all the progress is result of pure software reverse engineering (neither of Demul team members had real Naomi 1 or 2)

**Comment by zanac** [comment]
why not to contribute or share info for flycast? Naomi 2 under Linux is a dream..... If just demul has a decent linux porting, wine is not an option ;)

> > reverse engineering it is not an option
> 
> I'm honestly wondering why ?
> 
> > have some dieshot to share about this chip ?
> 
> no, all the progress is result of pure software reverse engineering (neither of Demul team members had real Naomi 1 or 2)

**Comment by p1pkin** [comment]
> why not to contribute or share info for flycast?

why me do that ?
also, thats wrong with RE'ing it by yourself ? for example MAME emulate dozens (if not hundreds) of hardware platforms, which had no any documentation available. prehaps it is right time to do some real work and grab a bounty for it ? (not just leeching on someone's else work)

**Comment by barbudreadmon** [comment]
> I'm honestly wondering why ?

@p1pkin Well, i was mainly thinking about hardware reverse engineering, so basically producing a dieshot and understanding the circuit, but we don't have the knowledge & tools to do that.

> all the progress is result of pure software reverse engineering

So that's possible ? Isn't it a complex chip though ? Can you give us some hints about the method you applied ?

**Comment by flyinghead** [comment]
> prehaps it is right time to do some real work and grab a bounty for it ? (not just leeching on someone's else work)

WTF?
closing in favor of #418
