### ISSUE TITLE
Reicast OIT Crashes to Desktop

### ISSUE THREAD

**Issue by CHjMP** [libretro/flycast#72]
When launching any game using the Reicast OIT libretro core, RetroArch loads the game to a black screen for a second, then crashes to the desktop.

[retroarch-log.txt](https://github.com/libretro/reicast-emulator/files/2147730/retroarch-log.txt)

**Comment by gfc83** [comment]
same issue. gtx 980ti sli 4790k.

**Comment by ghost** [comment]
This is the same as issue #79.

**Comment by inactive123** [comment]
Can you provide us a better log? This one doesn't really tell us much? For further instructions on how to get a more verbose log, see the previous issue #79.

**Comment by CHjMP** [comment]
Sure, here is my log file after following those instructions. Also, I don't have a GTX 980 Ti as the other user, I have an AMD R9 380. Let me know if you need any more information.

[retroarch-log.txt](https://github.com/libretro/reicast-emulator/files/2152235/retroarch-log.txt)

**Comment by inactive123** [comment]
Can you try it again with the latest cores from the buildbot?

**Comment by CHjMP** [comment]
It's not crashing on start up now, but I'm only getting audio and no video. I posted a log here: https://github.com/libretro/reicast-emulator/issues/79#issuecomment-404358537

Edit: Both Reicast and Reicast OIT aren't displaying video, just a black screen while audio plays.

**Comment by CHjMP** [comment]
Never mind, I've since reinstalled RetroArch and it is now working, not sure what broke it.
