### ISSUE TITLE
The next tetris online doesn't start.

### ISSUE THREAD

**Issue by Innomen** [libretro/flycast#720]
Not sure if that's the kind of thing I should report but it was always my favorite version of tetris and I've never gotten it to work on any DC emulator.

It just stays on the sega white screen forever. Is there anything I can try? I know there's a whole slew of options but I've no idea where to begin if that's the problem.

**Comment by flyinghead** [comment]
What platform are you on?

**Comment by flyinghead** [comment]
What platform are you on?

**Comment by Innomen** [comment]
I completely forgot is was on other platforms, my bad, retroarch v1.8.1, win10 ultimate x64.

**Comment by flyinghead** [comment]
This game should work on windows. Use default core options except for Threaded Rendering (on) and Synchronous Rendering (on).

Try deleting your dc_nvmem.bin file and your VMU files (after backup...)

Known issues: the intro FMV sequences are glitchy and online connection fails.

**Comment by Innomen** [comment]
No joy, perhaps my image is crap. I'll try to find another. I couldn't find Synchronous Rendering.

**Comment by flyinghead** [comment]
Synchronous Rendering depends on Threaded Rendering so if you just enabled it, you need to close and re-open the quick menu to make it appear.

**Comment by Innomen** [comment]
Hmm ok found one and it plays the super choppy cinematics but then hangs solid black. Also threaded is on, but in this image's case, syncro still isn't an option. It was for the other image though. I'll keep trying ones I can find.

**Comment by flyinghead** [comment]
![image](https://user-images.githubusercontent.com/16261910/68957117-a8cc3e80-07c9-11ea-8978-3f9d80f135a2.png)

also you need to restart RA for this option to appear

**Comment by Innomen** [comment]
Ok got it to appear on the three variants of the rom I can find. I can only try two of them, one of them wants ancient hardware/software. (cdrwin)

So 1, hangs at the sega white screen, 2, hangs after the fmvs, including start skipping the final tetris animation, and 3 I can't attempt at all because I need a time machine. 

I guess it's not the core's fault. Thanks for trying to help man.

**Comment by flyinghead** [comment]
Assuming resolved. Reopen as needed

**Comment by Innomen** [comment]
Where do I even get a confirmed image to test with?

**Comment by flyinghead** [comment]
There was a recent fix for .CUE files, which prevented win ce games to boot. Now all formats should work but avoid CDI.

**Comment by flyinghead** [comment]
And use the NTSC/US version, not the PAL/EU one

**Comment by Innomen** [comment]
Do you have a twitter or anything?

**Comment by flyinghead** [comment]
Discord? https://discord.gg/Z6tJ45
