### ISSUE TITLE
Power Stone 1&2: Hang on load

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#721]
Loading these games causes Retroarch itself to hang after the "SEGA" logo is shown.  No other games tested exhibit this behavior.  These are uncompressed GDI, not CHD, and the Dreamcast versions, not NAOMI.

Tested on Linux Mint 19.2 with kernel 5.0, self-compiled using GCC 9.2.1 with flycast core at commit
8cbfd817338f52c0cce9832fb3a2fa11c57341fa.  Can furnish logs etc. if needed.

**Comment by flyinghead** [comment]
Both games work fine here. Try resetting all settings to default, delete vmu files, dc_nvmem.bin, etc.

If that doesn't help, verbose log is the next step, bisecting second.

**Comment by Shoegzer** [comment]
@flyinghead ah yes thanks, deleting the vmu fixed it.  Mine must have gotten corrupted somehow.  I should have done that before reporting, I guess it's just been a while since I last tested these games and assumed it might have been a regression.  My bad.  Thanks again, closing.
