### ISSUE TITLE
(Naomi) Doesnt Work with retroarch latest build on android.

### ISSUE THREAD

**Issue by mugininja** [libretro/flycast#723]
I have problem when loading naomi (mame format) on android tv (nvidia shield tv pro 2019). I'm using retroarch v 1.81 (32 and 64 version) and latest flycast core. When i trying to load the content and run it. Retroarch crash and put me back to android tv main menu screen. The game that i used to run is Street Figther Zero 3 Upper.

**Comment by flyinghead** [comment]
Does the crash happen immediately when opening the content or is there some delay before it happens?

**Comment by mugininja** [comment]
It's depends.. if there is many Content inside the folder then there is delay. If i put only 1 content to play then its immediately kick out of program.

**Comment by flyinghead** [comment]
Check that you have the bios file `naomi.zip` in the right location:
`<system folder>/dc/naomi.zip`

Also the CHD and Zip files should be located like:
```
sfz3ugd.zip
sfz3ugd/gdl-0002.chd
```

**Comment by mugininja** [comment]
yup bios with md5 checked with correct location.
its showed that naomi.zip is present.

also the chd and zip file is located in one folder as per structured.

funny thing is ... on my android phone, its working well with the same configuration.

the only difference is my phone is android 8.0 whereas my android tv nvidia shield is android 9.0 

after i put all the bios file. It's change the load time there is delay and kick out to main android tv.

**Comment by mugininja** [comment]
okay ..i found the culprit.. its because of playstation ds3 bluetooth causing to shutdown when i run naomi games...but other emulator work fine with ps3 ds3 paired to my nvidia shield.
