### ISSUE TITLE
Per pixel Support for Nvidia Shield TV

### ISSUE THREAD

**Issue by mugininja** [libretro/flycast#724]
How can i enable per pixel for alpha sorting on android (nvidia shield)? I can tell the device support per pixel sorting because reicast stand alone emulator support it on my android device.

**Comment by barbudreadmon** [comment]
I guess you would need a custom build of both retroarch & flycast, default builds for android are using gles, because afaik the nvidia shield is the only android device with opengl support (and retroarch builds can't have both gles & opengl enabled at the same time)

**Comment by mugininja** [comment]
@barbudreadmon on my retroarch the there is only three option for my video driver which is
1.gl
2.vulkan
3.null

maybe i need to custom build only flycast?

**Comment by flyinghead** [comment]
No, you need a custom build of both because the core doesn't handle the OpenGL context initialization. This is done by RA.
So both RA and flycast must be changed.

**Comment by barbudreadmon** [comment]
@mugininja gl video driver in RA stands for both gles and opengl, depending on what flag was enabled at build time.

**Comment by mugininja** [comment]
i see thanks @barbudreadmon  @flyinghead. i'll try to build both.
