### ISSUE TITLE
Some game for certain region will just boot into bios

### ISSUE THREAD

**Issue by iokzero** [libretro/flycast#725]
There's a weird bug in flycast / reicast that the same game from one region will boot just fine into the game, while a different region copy will boot into the bios. 

Gauntlet Legend for instant, the PAL version boot just fine, while the USA version will just boot into the bios. Try various copy in all format possible, cdi, gdi, chd.... all the same. 

Note: pretty much all the version I tried including the last of flycast acting this way. not sure why. 

Thanks for the great work.

**Comment by flyinghead** [comment]
Gauntlet Legends doesn't like the `TV (RGB)` cable type setting and will boot into the bios. Any other cable type should be fine.

The same happens with other games so I recommend not using `TV (RGB)` and use `TV (Composite)` instead.

**Comment by iokzero** [comment]
That's indeed the case, Thank you so much for your help!

**Comment by flyinghead** [comment]
seems resolved
