### ISSUE TITLE
Naomi games showing corrupted graphics when minimizing and going back

### ISSUE THREAD

**Issue by carlhr93** [libretro/flycast#726]
So, I have a Poco F1 with Stock everything, no crazy root, kernel or other stuff and when using Flycast to play Naomi/AtomisWave games they run great and everything but when I "minimize" (I don't really know the term in Android, but basically when you press the Home Button) and go back to the app it shows corrupted graphics, like no textures, black logos, characters or lifebars with no textures, stuff like that and I only have tried FBNeo and Flycast but this doesn't happen on FBNeo.

I've tried disabling game mode and changing battery saving settings but I think is just Flycast because FBNeo works perfectly, am I the only one with this issue?

**Comment by flyinghead** [comment]
Yes, I can reproduce the issue

**Comment by flyinghead** [comment]
Flycast version 63e3aa7a60abdf88db2f8edcc2d6eb4710e677a4 fixed it for me

Can you try on your side? Thanks

**Comment by carlhr93** [comment]
Still see some black portraits for characters and other anomalies, but it kinda improved, less stuff is disappearing, I'll leave some screenshots: 
![Screenshot_2019-12-01-12-10-55-486_com retroarch](https://user-images.githubusercontent.com/10605180/69918840-e240b300-1433-11ea-864b-1dec42177dea.jpg)
![Screenshot_2019-12-01-12-10-28-781_com retroarch](https://user-images.githubusercontent.com/10605180/69918841-e240b300-1433-11ea-91ab-8631ad17e547.jpg)
![Screenshot_2019-12-01-12-08-46-312_com retroarch](https://user-images.githubusercontent.com/10605180/69918842-e240b300-1433-11ea-8359-4fc99a1c04bf.jpg)
![Screenshot_2019-12-01-12-04-58-574_com retroarch](https://user-images.githubusercontent.com/10605180/69918843-e240b300-1433-11ea-8cb1-5f0073157ab8.jpg)
![Screenshot_2019-12-01-12-04-23-577_com retroarch](https://user-images.githubusercontent.com/10605180/69918844-e240b300-1433-11ea-8b31-36eced6a2ba6.jpg)

**Comment by flyinghead** [comment]
Hopefully the last two commits will fix the remaining issues: https://github.com/libretro/flycast/commit/ff1fa78440d11f76d1542a6ea86af8db997af3b7

Thanks for retesting

**Comment by carlhr93** [comment]
> Hopefully the last two commits will fix the remaining issues: [ff1fa78](https://github.com/libretro/flycast/commit/ff1fa78440d11f76d1542a6ea86af8db997af3b7)
> 
> Thanks for retesting

Its perfect now, at least in those 3 games that I tested, also, my bad for that last screenshot, that's the way its supposed to look (the black diagonal line in the background of the characters roster), lol, and THANK YOU for doing this.
