### ISSUE TITLE
Lacking of NAOMI / Atomiswave Info

### ISSUE THREAD

**Issue by iokzero** [libretro/flycast#727]
Tried to Launch a .bin NAOMI file, it works fine, but got a message saying, should upgrade to the MAME set or expected issues. 

Got some old MAME NAOMI / Atomiswave roms around to try (forget which version of MAME they are under) None of them seems to works, but the file names match. 

Is there a full list of NAOMI and Atomiswave games from MAME we can references to? and which MAME version the roms should be under?

Sorry if this is wrong places to ask, and please move it to its rightful place. 
In general, there's seem to be a lot of useful tricky information that well know by the developers, but treasure hunt for end user. and many seems like a bug on first sight.  Would love to help documenting those, maybe in a Q&A or something, if that helps. 

Thanks for the great work!

**Comment by carlhr93** [comment]
I just use the latest mame roms, older roms seem to work aswell, the problem is the bios files, it's a tricky situation, you need the dc folder in /System and in that dc folder you need the bios files themselves but I don't think I can post them here.

**Comment by iokzero** [comment]
You are right about the bios, it is indeed tricky. I tried some old bios.
doesn't work, and then tried some newest one, doesn't work. But ultimately
found something in between that works. hahaha.

It is understood that bios file itself shouldn't be posted. but my thought
is that maybe we can document the version number and checksum for the one
that found to be working. Maybe retroarch doc page can get a update or
something.

Thank you so much for the help!

**Comment by flyinghead** [comment]
The list of supported Naomi / AW roms is here: https://github.com/libretro/flycast/blob/master/core/hw/naomi/naomi_roms.h
Not really a user-friendly format but at least it's up to date.

Any relatively recent mame romset should work. (I've used 0.197 successfully but older versions might also work)

There has been recent changes to support romset 0.206 so make sure your flycast core is up to date.

**Comment by barbudreadmon** [comment]
> You are right about the bios, it is indeed tricky

I don't think there is anything tricky here, the rule with retroarch arcade cores is : if they aren't vintaged (i.e there is no `20XX` at the end), the latest romsets & bioses are to be used, flycast is no exception.
Afaik, any `naomi.zip` from 2010 (when the H bioses got dumped) to today should work.

Edit : after verifying, i confirm we are currently in sync with latest MAME naomi/atomiswave romsets (version 0.216), slightly older romsets should also work though.

**Comment by iokzero** [comment]
I did tried the one from around 2010, and maybe it is just a bit too old,
and that one didn't work.
Than I try the naomi.zip from MAME 0.216. and that one didn't seem to work
neither. That's why I am said it seem a bit tricky.

But everything in between seem working ok. Maybe someone can take a look at
the MAME 0.216 naomi.zip. It can be just me got a corrupted file or
something.

Thanks for the help.

**Comment by iokzero** [comment]
Oh and forget to ask this.

Do the game and the naomi.zip need to be from the same set? or it is ok if
they come from a different MAME version?

Thanks

**Comment by barbudreadmon** [comment]
> It can be just me got a corrupted file or something.

Probably, as i said we are in sync with latest MAME romsets/bioses, and actually MAME's `naomi.zip` didn't change for years.

> Do the game and the naomi.zip need to be from the same set? or it is ok if they come from a different MAME version

Again, we are in sync with latest MAME romsets, using anything older can either work or not, the only thing i can tell is that naomi romsets don't change a lot over years in MAME.

**Comment by iokzero** [comment]
Got it, Thanks
