### ISSUE TITLE
Retroarch crashes on Pi4 when loading Naomi CHD files

### ISSUE THREAD

**Issue by chunksin** [libretro/flycast#730]
I'm using a 2GB Pi4 with Retroarch 1.8.1 in X Windows (buster lite with openbox & lightdm) with GLES3 support and the latest Flycast core, regular mame .zip roms and disc based .bin roms work OK but Flycast either won't load the content or crashes Retroarch when using CHD images, I've also tested Lakka with the same result.

**Comment by barbudreadmon** [comment]
That's not how you use naomi chd, let's say you want to play ikaruga, your setup has to look like this : 
- `ROM_FOLDER/ikaruga.zip`
- `ROM_FOLDER/ikaruga/gdl-0010.chd`

The file you must launch is `ikaruga.zip`, which contains the key that will decrypt `gdl-0010.chd`, which will be read internally by the core.

**Comment by chunksin** [comment]
That's exactly how I have set it up to run, I followed the instructions perfectly! For reference I use border down to test, rom name bdrdown

Will upload images and video as supporting evidence if required, please reopen issue.

**Comment by chunksin** [comment]
My compile flags for reference:

Retroarch: CFLAGS='-mfpu=neon -mtune=cortex-a72 -march=armv8-a' ./configure --disable-opengl1 --enable-neon --enable-opengles3 --enable-opengles --disable-videocore

Flycast: make platform=rpi4

**Comment by barbudreadmon** [comment]
Ok, the way you phrased it was very misleading, let's continue in the other issue since you opened a new one...
