### ISSUE TITLE
Retroarch crashes on Pi4 when loading Naomi CHD files

### ISSUE THREAD

**Issue by chunksin** [libretro/flycast#731]
I'm using a 2GB Pi4 with Retroarch 1.8.1 in X Windows (buster lite with openbox & lightdm) with GLES3 support and the latest Flycast core, regular mame .zip roms and disc based .bin roms work OK but Flycast either won't load the content or crashes Retroarch when using CHD images, I've also tested using Lakka with the same result.

I am testing using Border Down rom as follows:

romfolder\bdrdown.zip
romfolder\bdrdown\gdl-0023a.chd

My compile flags for reference:

Retroarch: CFLAGS='-mfpu=neon -mtune=cortex-a72 -march=armv8-a' ./configure --disable-opengl1 --enable-neon --enable-opengles3 --enable-opengles --disable-videocore

Flycast: make platform=rpi4

Let me know if I can provide any test evidence like log files or screenshots

**Comment by barbudreadmon** [comment]
> I can provide any test evidence like log

Yes, please provide them

**Comment by chunksin** [comment]
Please find the crash log attached
[retroarch.log](https://github.com/libretro/flycast/files/3941209/retroarch.log)

**Comment by chunksin** [comment]
Also here is successful load using the Border Down .bin file
[retroarch.log](https://github.com/libretro/flycast/files/3941221/retroarch.log)

**Comment by chunksin** [comment]
Just tested with CVS2 and that works fine, tried a different romset (bdrdown.zip is 7MB instead of 2KB) and it works fine - must be a romset issue. Sorry to waste time here! And thank you for a wonderful emulation core!

**Comment by barbudreadmon** [comment]
Always make sure you are using the latest mame romset with flycast, FWIW the latest `bdrdown.zip` is 1.3KB and works perfectly. Anyway i'll be closing since you fixed your bad romset issue somehow.
