### ISSUE TITLE
[Vulkan] Retroarch crashes upon attempts to use Vulkan driver

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#733]
Setting the RA driver to "vulkan" from "gl" and starting a DC game with flycast core, RA crashes.  These games launch with "gl" driver without issue.  Vulkan works on this test system - other emulators that rely on it launch games without issue.

Tested on linux mint 19.2, kernel 5.0, nvidia 1070M with driver 440.36 tested against commit 485b85682a4157cb9b5722626d17a4b46cc9bc5e, compiled against gcc 9.2.1.  Can provide logs if needed.

**Comment by flyinghead** [comment]
Yes, a log would be useful starting point

**Comment by barbudreadmon** [comment]
Posting your core options might be a good idea too, i don't think they can be seen in logs.

**Comment by barbudreadmon** [comment]
Just making sure since you said you built it yourself, did you add the `HAVE_VULKAN=1` flag to make ?

**Comment by Shoegzer** [comment]
@barbudreadmon Ah, I just used the buildbot script which only has HAVE_OIT=1 but not HAVE_VULKAN=1.  That would explain it.  I'll modify a local copy to test and be sure, but should the master buildbot script be updated for vulkan?

Update: I added HAVE_VULKAN=1 to the local buildbot script and tested, but RA still crashes on game load.  [Here](https://pastebin.com/0X82jQqb) is a log.

**Comment by flyinghead** [comment]
I was hesitating about asking what version of RA you were using but ... you need to upgrade to 1.8.1. It won't work otherwise.

**Comment by zkvsky** [comment]
Just tested it and it works, with games that I've tried so far, with all the whistles, RADV/ACO, VK_LAYERS hud, you name it
[ Linux 5.4, mesa 20, retroarch 1.8.1 ]

Amazing job

**Comment by Shoegzer** [comment]
After upgrading RA to 1.8.1 I've gotten it wokring too, so I'll close the issue.  Thanks @flyinghead for this great work, it must not have been easy but it's really nice to have vulkan!

**Comment by Anths2016** [comment]
Why I can't use Vulkan? If I set vulkan the emu automatically switch to glcore.
