### ISSUE TITLE
DOA 2 crashes during the attract mode.

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/flycast#735]
Naomi version crashes at the same spot in the attract mode, a few minutes in, right before it shows the stage with the machinery parts. Can reproduce it every time.

**Comment by barbudreadmon** [comment]
Seems like a duplicate of https://github.com/libretro/flycast/issues/184 for me

**Comment by Tasosgemah** [comment]
> 
> 
> Seems like a duplicate of #184 for me

You are right, didn't notice because i wasn't talking about the millennium version. Seems the same crash occurs in the regular version then.

**Comment by flyinghead** [comment]
Closing in favor of #184
