### ISSUE TITLE
Armada: Crash on start of game

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#740]
As of commit 6dd6013ead6cbfc5c101c91e54276b1c756ff3b5, Armada now crashes before going ingame.  This did not happen on a build compiled against yesterday's commits so it's quite possible the above commit is the cause (Armada is my favorite Dreamcast game so I test against [this](https://github.com/libretro/flycast/issues/642) issue whenever there's any changes that have a chance of affecting SH4 clock speed).

Tested on linux mint 19.2 with kernel 5.0, self-compiled using gcc 9.2.1.

**Comment by flyinghead** [comment]
Good catch! Should be fixed by https://github.com/libretro/flycast/commit/3725492fa67ce4b233e19d30b8d9e6e3cb097d45

**Comment by Shoegzer** [comment]
Awesome!  Thanks for the fix, tested and working fine now.  Closing issue.
