### ISSUE TITLE
Crazy Taxi - Face buttons affect camera after Pause

### ISSUE THREAD

**Issue by hiddenasbestos** [libretro/flycast#742]
Steps to reproduce:

1. Load game, select Arcade + Arcade Rules + Axel
2. Observe that, by default, A/B buttons switch between forward and reverse gears.
3. Press START to pause, then START again to unpause.
4. Observe that A/B buttons now switch between gears AND change camera view.
5. This behaviour continues even when quitting and starting a new game from the menu.
6. Changing control type from the in-game menu does not affect anything.

Expecting the camera not to change with these buttons.

Tested with Dreamcast US and European version.
RetroArch 1.8.1
Flycast: 14th December build.

**Comment by flyinghead** [comment]
This probably because your game or keyboard is used for both Player 1 and Player 3. The player 3 gamepad controls the camera, but this is only enabled after pressing Start on said controller.

**Comment by hiddenasbestos** [comment]
> This probably because your game or keyboard is used for both Player 1 and Player 3. The player 3 gamepad controls the camera, but this is only enabled after pressing Start on said controller.

Thank you so much for the quick reply, this is precisely what had happened!
