### ISSUE TITLE
Faster Than Speed — Wheel input not working properly

### ISSUE THREAD

**Issue by kage2051** [libretro/flycast#745]
Even when using an external Bluetooth keyboard, the wheel doesn't react as expected. This issue was reproduced by using both default and custom settings for the controls (assigned wheel to arrow keys).

Before someone asks, latest RA on Android was used.

**Comment by flyinghead** [comment]
Can you describe the problem?

**Comment by kage2051** [comment]
The wheel supposedly should respond after setting it up by making the keyboard's arrow keys act as it. What I did was remap the entire left analog via input options for the game. However, the result is similar to when using virtual buttons, only accel. button is working. Cannot select a stage nor steer the car because of this.

Other games which make use of analog, such as Monkey Ball, don't suffer from this issue.

**Comment by flyinghead** [comment]
I tested on both desktop and Android and I don't have any issue with the wheel. The brake and accelerator must be rebound though.
![device-2019-12-17-222318](https://user-images.githubusercontent.com/16261910/71035588-10a0dc80-211c-11ea-95fd-acc39a0d7942.png)
![device-2019-12-17-222254](https://user-images.githubusercontent.com/16261910/71035589-11397300-211c-11ea-940a-96056fe68539.png)

**Comment by kage2051** [comment]
Do you mind showing a screenshot of the input bounds you tested? To be sure I'm mapping them right.

**Comment by flyinghead** [comment]
I didn't rebind anything. This is the default unless I messed around:
![image](https://user-images.githubusercontent.com/16261910/71118595-bb76d080-21d8-11ea-9e10-75dd0e952595.png)

**Comment by kage2051** [comment]
Finally got this sorted out. For anyone who want to get the wheel working, you need to access Service mode, and in Test option select I/O Test. There you find an option named 'Control Calibration' or something like that. Select it, press Start and follow the instructions shown at the top.

So, closing the issue.
