### ISSUE TITLE
King of Fighters Neowave issues (broken)

### ISSUE THREAD

**Issue by RaduNastase** [libretro/flycast#746]
In latest Flycast Vulkan (android OnePlus7), the game has the following issues.

With Alpha Sorting per-pixel (and Threaded Rendering off), it displays the character select screen like in the pic
![Screenshot_20191218-103954](https://user-images.githubusercontent.com/18061144/71077268-c6594300-218f-11ea-9916-2fa4f22c2d88.jpg)
and when the battle begins, Retroarch crashes completely to homescreen.

With Alpha Sorting per-triangle, and Threaded Rendering on, the game displays correctly, it enters the fight, but the performance is very choppy 45 - 50 fps with sound issues as well (i use the correct mame rom, so it's not related to the known rom issue where using .lst format resulted in a very bad performance 10 - 15 fps). 

The performance saw a severe downgrade for this game, which is puzzling as other similar games run full speed with plenty room to breathe.

**Comment by flyinghead** [comment]
It could be another driver problem: I can only reproduce it on Adreno.

**Comment by RaduNastase** [comment]
Yes, most likely. GL has no issues with the game. Also, the recent core is smoother in terms of frame pacing in GL render as well it seems (Retro64 version). Great job man!

I've been continuously testing various games in the past hours, and i can say for sure that Vulkan and Threaded Rendering are not playing nice. 

In Vulkan, games play noticeably better/faster with Threaded Off (though the transitions between the loading screens/menus/intros, are choppier and show my touch overlay distorted for a couple of seconds). Threaded On, produces constant frame drops, in the low 50 range. In GL this is not an issue.

**Comment by flyinghead** [comment]
Try enabling Synchronous Rendering along with Threaded Rendering. Otherwise, you might get a high number of frames dropped. The current algorithm to detect if a frame should be dropped doesn't play well with Vulkan, but Synchronous Rendering helps mitigate the problem.

**Comment by RaduNastase** [comment]
If there's a difference with Synchronous On, i honestly don't see it. It's still very choppy and uneven. 

Gonna test more games and report any issues i find!

**Comment by flyinghead** [comment]
There's now a workaround for Adreno GPUs.

**Comment by flyinghead** [comment]
Resolved
