### ISSUE TITLE
Ooga Booga crashes on multiplayer (offline and online)

### ISSUE THREAD

**Issue by Hunter-MDK** [libretro/flycast#749]
What steps will reproduce the problem?

1: Launch game in GDI format (only format game works in)
2: Select "Offline Skirmish" (or go to the multiplayer servers)
3: Program crashes

**Comment by Hunter-MDK** [comment]
The log console is flooded with this line when the crash occurs.
`[libretro ERROR] 00:25:033 libretro/common.cpp:84 E[COMMON]: [GPF]Unhandled access to : 000000011da42940`

**Comment by Hunter-MDK** [comment]
Offline has been fixed and works great now, thanks for that. But now a new issue exists. When posting an online match the game hangs but gives no errors to the log console.

However when loading into the the lobby creator the following warnings are given.

`[libretro WARN] 01:16:617 hw/pvr/helper_classes.h:22 W[PVR]: List overrun for list idx`
`[libretro WARN] 01:16:627 hw/pvr/helper_classes.h:22 W[PVR]: List overrun for list verts`
`[libretro WARN] 01:16:635 hw/pvr/helper_classes.h:22 W[PVR]: List overrun for list idx`
`[libretro WARN] 01:16:644 hw/pvr/helper_classes.h:22 W[PVR]: List overrun for list verts`
`[libretro WARN] 01:16:654 hw/pvr/helper_classes.h:22 W[PVR]: List overrun for list idx`

**Comment by flyinghead** [comment]
The fix isn't available on the buildbot yet. Please try updating the core again in 24h or so.

**Comment by Hunter-MDK** [comment]
I tried the first fix already, i copied your code and manually built it. Offline works now but theres still an issue with multiplayer. Unless there was another change that isn't listed here?

**Comment by flyinghead** [comment]
Yes, I can reproduce the hang as well. Investigations are underway.

**Comment by flyinghead** [comment]
Can you try the last commit?
I can successfully post a game with it.

**Comment by Hunter-MDK** [comment]
I cant at the moment but i can at about 1pm EST today. I'll give you my results.

**Comment by Hunter-MDK** [comment]
Just tested it, posting a game works just fine. I have yet to test if actually playing with other people works yet.

**Comment by flyinghead** [comment]
Great. Don't forget to forward UDP port 6001 to your PC

**Comment by Hunter-MDK** [comment]
oooh thanks for the heads up, i had no idea i needed to port forward

**Comment by Hunter-MDK** [comment]
Just tested it with some friends, it works great. Thanks so much for your time.
