### ISSUE TITLE
Skies of Arcadia - Minor Audio Issues

### ISSUE THREAD

**Issue by Boviligg** [libretro/flycast#75]
In Skies of Arcadia, during the intro - certain brass notes in the soundtrack are meant to be held for longer, instead they play for a second and then cut out. This was a problem in older DC emus too but has been fixed in Demul.
This can be heard as the enemy battle ship is chasing the girl in the smaller ship during the intro sequence approx 28 seconds after hitting "new game".

**Comment by flyinghead** [comment]
This commit should help: https://github.com/libretro/flycast/commit/f118d3a95d80196dc83ffd6c37915ceeade95d15
The DSP wasn't working for this game

**Comment by flyinghead** [comment]
This should now be fixed on the wince core
