### ISSUE TITLE
Silent Scope — weird graphical issue on Adreno 506

### ISSUE THREAD

**Issue by kage2051** [libretro/flycast#753]
![Screenshot_2019-12-25-09-00-15-404](https://user-images.githubusercontent.com/25725203/71447583-aed10b80-26f5-11ea-9e81-94fd30c31c82.jpeg)

As you can see in the image above, the enemies' sprites don't display at the right position when played on Adreno 506 devices, making it unable to shoot them. Happens on both renderers (and per-strip sorting used).

**Comment by kage2051** [comment]
DIV Matching set to Auto or On causes the above. I even reproduced it on a Redmi Note 7 which uses SD660 chipset. With that setting disabled, the game works as expected, independently of the hardware you use. So, closing.

However, the standalone app for some reason still suffers from this.

**Comment by flyinghead** [comment]
should be fixed by https://github.com/libretro/flycast/commit/f9f3249192f487b9d8de0a06531af331d4207fee
