### ISSUE TITLE
Twinkle Star Sprites Issues

### ISSUE THREAD

**Issue by Panderner** [libretro/flycast#757]
I have issues running Twinkle Star Sprites running in this emulator, The Game is too fast and no sound.

**Comment by flyinghead** [comment]
Works fine for me. More details needed.

**Comment by Panderner** [comment]
I'm using Realme C2 and redump's bin and cue files, Redream works well

**Comment by flyinghead** [comment]
There's probably an issue with the sound in RetroArch. Have you tried other cores? Have you changed any RA or flycast setting?

**Comment by Panderner** [comment]
I'm using default settings

**Comment by flyinghead** [comment]
Happens only on arm and with DSP enabled.

**Comment by flyinghead** [comment]
This should be fixed in the latest core

**Comment by Panderner** [comment]
I updated the latest core now, the sounds works and game speed works properly I'm closing now.
