### ISSUE TITLE
(OIT-only) Dino Crisis - Inventory screen

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#76]
Tested version: f3678213292546b3724a8dc1f86e1b11f9a39f61

The inventory screen is rendered incorrectly with the OIT renderer.

![image](https://user-images.githubusercontent.com/1075274/42119932-b9be7f3a-7c12-11e8-9d66-3e7450cad755.png)

Go to 13:03 in this video:

https://www.youtube.com/watch?v=j3PDhFqE6Bo

You can see there how the menu is supposed to be displayed on a real Dreamcast.

**Comment by inactive123** [comment]
It is rendered correctly with the non-OIT renderer -

![image](https://user-images.githubusercontent.com/1075274/42119973-7ef4ec94-7c13-11e8-9cb7-0a2fe49d74e0.png)

**Comment by flyinghead** [comment]
Should be fixed by my latest commits as well

**Comment by inactive123** [comment]
Cannot proceed unfortunately due to this issue -

0(150) : error C1317: qualified actual parameter #1 cannot be converted to less qualified parameter ("pixel.22")

I tried removing const in a bunch of places and it just isn't working.

GL_DEBUG in RetroArch is not helping either pinpoint the exact corresponding line.

**Comment by inactive123** [comment]
Fixed as of this commit @flyinghead - thanks!

https://github.com/libretro/reicast-emulator/commit/a239ea4ff8371a6b5bad45565b6f51e2e744c382
