### ISSUE TITLE
Trigger Heart Exelica - hellish input delay

### ISSUE THREAD

**Issue by daninthemix** [libretro/flycast#761]
Not sure if there are any settings that can solve this, but Trigger Heart Exelica has massive input delay (over 3 seconds).

**Comment by Panderner** [comment]
Naomi or Dreamcast Version?

**Comment by daninthemix** [comment]
Naomi.

**Comment by Panderner** [comment]
It's a duplicate of #414

**Comment by flyinghead** [comment]
Yes, it’s a known issue. Let’s keep the discussion in #414
