### ISSUE TITLE
[SWITCH] graphic glitches in SoulCalibur using RetroArch core  

### ISSUE THREAD

**Issue by mtoensing** [libretro/flycast#762]
In all retroarch flycast cores it shows this error in Soul Calibur 

https://www.youtube.com/watch?v=4CduUUoSYc0

![2019122820485600-EAD9CDD267F449963C89657382E411AE](https://user-images.githubusercontent.com/136737/71548881-defa0200-29b4-11ea-90c9-cc3866d31f72.jpg)
![2019122820494000-EAD9CDD267F449963C89657382E411AE](https://user-images.githubusercontent.com/136737/71548885-fafda380-29b4-11ea-9f89-38815fdb6057.jpg)

![2019122820492300-EAD9CDD267F449963C89657382E411AE](https://user-images.githubusercontent.com/136737/71548887-06e96580-29b5-11ea-87e9-16d5f75e97de.jpg)

**Comment by mtoensing** [comment]
The problem was fixed in this core. 

https://twitter.com/m4xwdev/status/1192395802469191680?s=21

But when will this be available in retroarch via the „download core“ option?

**Comment by flyinghead** [comment]
This is now available via the core updater.

**Comment by mtoensing** [comment]
So I update cores in Switch RetroArch 8.5 and receive an update?

**Comment by flyinghead** [comment]
Yes
