### ISSUE TITLE
Threaded rendering  halves FPS

### ISSUE THREAD

**Issue by zkvsky** [libretro/flycast#766]
Retroarch 1.8.2. Flycast 8126040. Platform: Linux  x86_64. GPU: AMD RAVEN APU. 

Since turning threaded rendering hides framerate options I'm unsure if it's intended behavior or not. But when TR is enabled in games like Shenmue or MSR, fps is capped at 30 fps and a bit stuttery, without it sits comfortably at fluid 60 fps

[ t seems to be the same with standalone with no easily discernible way to turn off threaded ]

**Comment by flyinghead** [comment]
Both Shenmue and MSR run at 30 FPS on a real dreamcast. Threaded rendering is more accurate.

**Comment by zkvsky** [comment]
> Both Shenmue and MSR run at 30 FPS on a real dreamcast. Threaded rendering is more accurate.

Gotcha, it's intended. gonna close it then
