### ISSUE TITLE
Problem KoF Neowave

### ISSUE THREAD

**Issue by Anths2016** [libretro/flycast#767]
It stops at the initialization screen.

**Comment by flyinghead** [comment]
Please provide more information

**Comment by Anths2016** [comment]
https://i.postimg.cc/2Sbwf6mV/kofnw-200104-110441.png

**Comment by BroKill** [comment]
I got that screen too but it's a 40 seconds ( more or less ) thingy, then the game starts and all is good!
A lot of Naomi/Atomiswave games have that screen but as I said before, the game starts, you need to wait a bit.

**Comment by Anths2016** [comment]
You are right. I close.
