### ISSUE TITLE
(OIT-only) Resident Evil 3: Nemesis - Costume select screen

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#77]
Tested version: f3678213292546b3724a8dc1f86e1b11f9a39f61

This is how it's supposed to look like on a real Dreamcast, and this is how it currently looks like with the non-OIT renderer. The non-OIT renderer seems to be rendering this correctly -

![image](https://user-images.githubusercontent.com/1075274/42120009-4ffc6f42-7c14-11e8-9785-f21ba61c4c77.png)

For confirmation on this, go to 4:03 in this Youtube video (which I believe is captured off  a real Dreamcast) -

https://www.youtube.com/watch?v=cR0rBx4qORk

On Reicast OIT, we instead get a faulty image where the background image of the previous title screen is still in the background -

![image](https://user-images.githubusercontent.com/1075274/42120013-75976dec-7c14-11e8-8e86-53d9100a7492.png)

**Comment by flyinghead** [comment]
@twinaphex  This is a consequence of the hack I did for Psyvariar. But I think I finally got it right. 
See https://github.com/flyinghead/reicast-emulator/commit/3ddcc272bf948e8d94043fce4fb1f3d4eb03ac8c.
This should fix the non-OIT version. More work is needed for the OIT branch.

**Comment by inactive123** [comment]
OK, well, non-OIT displayed this correctly. But sure, I'll check this out.

On another note,

https://github.com/flyinghead/reicast-emulator/commit/0a4cdfb973f520911ab9e51bc3512b45e885f66f

Do you happen to know why I get this GLSL compiler error when trying to backport this? Is there any known fix?

**Comment by flyinghead** [comment]
> Do you happen to know why I get this GLSL compiler error when trying to backport this?

I haven't had time to look at this yet. It could be a variable that's declared `const` and passed to a function that doesn't specify `const`. You can try to remove the const qualifiers as they are for optimization only.

**Comment by inactive123** [comment]
Posted a solution here that works for me -

https://github.com/flyinghead/reicast-emulator/commit/8e309b01aac0564005a6e22b00c04fc28a927fe8#commitcomment-29555037

With that extra change applied on top of the diff patch you provided me in that comment ,it will work now.

**Comment by inactive123** [comment]
Fixed as of this commit @flyinghead - thanks!

https://github.com/libretro/reicast-emulator/commit/a239ea4ff8371a6b5bad45565b6f51e2e744c382
