### ISSUE TITLE
Resident Evil 2 (Black Screen) in Retroarch 1.8.2

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/flycast#770]
Hydro Thunder (Black Screen) in Retroarch 1.8.2

Windows 10 

the game is a good copy I have more game with the black screen but maybe if this one gets fixed it may fix the other ones as well. 

![Capture](https://user-images.githubusercontent.com/21169038/71799180-7096ee80-3009-11ea-92d0-4976ee1d1085.jpg)

**Comment by flyinghead** [comment]
Set Broadcast to NTSC or PAL depending on your edition of this game. Do not set it to Default.

**Comment by Cibomatto2002** [comment]
Thank you !!! :)

**Comment by Cibomatto2002** [comment]
I have another game with the black screen Resident Evil 2 changing Broadcast to NTSC does nothing for this game still a black screen.

**Comment by flyinghead** [comment]
Please open a different issue for RE2 and post the relevant info there: core settings, log, ...

Thanks

**Comment by marcrobledo** [comment]
Just a small note.
I couldn't make Hydro Thunder PAL get past the Sega screen. Tried setting broadcast to PAL with no luck. However it worked correctly when I set it to NTSC.

**Comment by flyinghead** [comment]
Hydro Thunder PAL needs a real BIOS, doesn't support HLE.

**Comment by marcrobledo** [comment]
I'm using the real BIOS.

EDIT: Nevermind. It now works even when Broadcast is set to Default for some reason O_O
