### ISSUE TITLE
(Android 32bit) Crash on successive load content (nvmem/mprotect error)

### ISSUE THREAD

**Issue by jdgleaver** [libretro/flycast#774]
I've encountered a peculiar issue that only seems to affect the 32bit Android build (64bit Android is absolutely fine, as are the 64bit desktop builds).

If you open RetroArch and load content with the Flycast core, everything runs correctly. If you then close content and try to load another item of content with the Flycast core, there is a very high probability that RetroArch will crash. I've reproduced this on 2 devices: one has a 32bit OS, and this always crashes on the second load content; the other has a 64bit OS, and the crash occurs arbitrarily on the second or third load content.

In all cases, the pertinent section of the RetroArch log file is as follows:

```
File extension is: .chd
[Environ]: GET_PREFERRED_HW_RENDER.
[Environ]: SET_HW_RENDER.
Requesting Vulkan context.
[Environ]: SET_HW_RENDER_CONTEXT_NEGOTIATION_INTERFACE.
00:00:377 hw/mem/_vmem.cpp:530 W[VMEM]: Warning! nvmem is DISABLED (due to failure or not being built-in
Fatal error : mprotect  failed...
 in mem_region_unlock -> /home/buildbot/buildbot/android/libretro-flycast/jni/../core/libretro/vmem_utils.cpp : 59 

00:00:471 libretro/libretro.cpp:3200 E[COMMON]: DEBUGBREAK!
00:00:471 libretro/common.cpp:373 E[COMMON]: SIGSEGV @ c2536428 ... 0xc2536428 -> was not in vram (dyna code 0)
Fatal error : segfault
 in signal_handler -> /home/buildbot/buildbot/android/libretro-flycast/jni/../core/libretro/common.cpp : 374 

00:00:471 libretro/libretro.cpp:3200 E[COMMON]: DEBUGBREAK!
```

(When content loads successfully, we get the regualar `hw/mem/_vmem.cpp:547 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB` nvmem init message)

So on the first load content, `vmem_platform_init()` is successful, but on subsequent loads it seems to fail... I guess something mysterious is going wrong either here:

https://github.com/libretro/flycast/blob/294de6b6e5516ff2ee89dcf5f61b824482a06433/core/libretro/vmem_utils.cpp#L151

or here:

https://github.com/libretro/flycast/blob/294de6b6e5516ff2ee89dcf5f61b824482a06433/core/libretro/vmem_utils.cpp#L166

**Comment by flyinghead** [comment]
It seems that the 512MB+ reserved memory space is not properly returned to the OS when the core is unloaded, which on a 32bit platform could quickly exhaust the available address space.

**Comment by flyinghead** [comment]
I just pushed a tentative fix

**Comment by jdgleaver** [comment]
Ah, that's fantastic! Thanks for looking into this  :)

I'll test it as soon as the buildbot version updates (I don't have root on any device that can run Flycast properly, and the normal 'sideload core' option doesn't seem to work for me any more... apparently a permissions issue - I'll have to look into that at some point...)

**Comment by jdgleaver** [comment]
I can confirm that the fix completely resolves the issue.

Brilliant stuff! Thanks again  :)
