### ISSUE TITLE
Windows CE games will not load

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/flycast#776]
Every Windows CE game I have will not load Resident Evil 2, Wild Metal. Resident Evil 2 stays on the Windows CE screen. Wild Metal has a black screen. I have more Windows CE games but I see no reason to post them all.

In the Log folder I have nothing to post. the games are Redump.org checked.

**Comment by barbudreadmon** [comment]
Are you really looking for help ? As far as we are concerned, winCE games work properly, if you provide **no additional information at all**, how are we supposed to help ?

**Comment by flyinghead** [comment]
Please post your RA and core settings as well as a verbose retroarch log. Details about your platform/environment are also useful.

**Comment by Cibomatto2002** [comment]
Sorry about not giving more info.

Retroarch 1.8.2 I think the only thing I changed in the core settings was Broadcast to NTSC

[retroarch.log](https://github.com/libretro/flycast/files/4033892/retroarch.log)


Operating System
	Windows 10 Home 64-bit
CPU
	AMD Ryzen 7
	Summit Ridge 14nm Technology
RAM
	16.0GB Dual-Channel Unknown @ 1197MHz (17-17-17-39)
Motherboard
	Dell Inc. 0VYXHD (AM4)
Graphics
	ELEFW328 (1360x768@60Hz)
	4096MB ATI AMD Radeon RX 580 (Dell)
Storage
	931GB Seagate ST1000DM010-2EP102 (SATA )
Optical Drives
	No optical disk drives detected
Audio
	High Definition Audio Device

**Comment by flyinghead** [comment]
I didn't spot any problem in the log. Are you sure the game is frozen? Some winCE games take a long time to boot, esp. on Windows.

**Comment by Cibomatto2002** [comment]
On the Log console I get this C:\Users\Jason\Desktop\New folder\Resident Evil 2 (USA) (Disc 1).cue: Bad image format. Could that be it?

I let the winCE games for for 5 mins.

Here is a video of me waiting for it to load up.

https://www.youtube.com/watch?v=qC_5D3JILQI&feature=youtu.be

I'm going to wait for Retroarch 1.8.3 to come out and see if it fixes it.

**Comment by flyinghead** [comment]
I was able to reproduce the problem by using a Redump.org .CUE file: the game is stuck on the Sega license screen.
Using a GDI or CHD works fine.

I suppose there's an issue with the handling of .cue files in flycast.

**Comment by Cibomatto2002** [comment]
Another problem for me was when I was trying to get it to Scan the Directory RetroArch could find the Cue files but could not tell what emulator they was for so I had to do a Manual Scan to find my games same thing happen on my Playstation one games I'm guessing if I use cue files I will run into this problem for every CD or DVD game.

Good now I know it was not on my end. thanks for your time.

**Comment by barbudreadmon** [comment]
> I suppose there's an issue with the handling of .cue files in flycast.

They were working last time i used them (maybe 2 weeks ago ?), would that be specific to winCE dumps using cue ?

**Comment by MastaG** [comment]
but bin/cue are used for burning games on regular cd-r discs.
when the original games exceed the 700meg limit, stuff gets downsampled or just removed.
also many of the more recent games have copy-protection (lba) checks which got patched to make them boot from cd-r discs (e.g. lba 0,11700/0,11702) and can sometimes upset the emulator.
therefore it's better to just use original gdi dumps instead.

**Comment by flyinghead** [comment]
> would that be specific to winCE dumps using cue ?

Yes, this is an issue I fixed for GDIs a while back when starting WinCE support. It just hasn't been fixed in the CUE parser yet

**Comment by flyinghead** [comment]
Fix pushed

**Comment by Cibomatto2002** [comment]
It's working now :)

**Comment by jclsn** [comment]
I have the same problem with GDIs on my Raspberry Pi 4 with LAKKA. Has the problem been fixed only for CUE files? I know it will take some time for Nathan to push this to LAKKA, so I can't tell if it has been fixed yet.

**Comment by flyinghead** [comment]
You have a different issue: The Raspberry Pi 4 is running a 32-bit OS and Windows CE games are only supported on 64-bit environments.

**Comment by jclsn** [comment]
Thank you! Makes sense. I just read that there is only an experimental 64-bit kernel available. So I guess it is a little early, but something to look forward to!
