### ISSUE TITLE
Kiss Psycho Circus EU hang[Solved - Change VGA to TV]

### ISSUE THREAD

**Issue by backgamon** [libretro/flycast#779]
The european version of Kiss Psycho Circus hang on boot at the Windows CE logo.
The USA version boot fine.

Retroarch 1.8.2
Flycast Core - (0.1 05c3693)
![retroarch 2020-01-10 10-32-46-819](https://user-images.githubusercontent.com/39404647/72142379-d3371400-3394-11ea-9623-d45b43a34088.jpg)
![retroarch 2020-01-10 10-32-40-392](https://user-images.githubusercontent.com/39404647/72142384-d6ca9b00-3394-11ea-90f6-276e4e1ab8cb.jpg)

-
Windows 10 pro x64 1909[18363.535]
8700K@4.7Ghz
Gigabyte 2070 RTX 8Go OC [441.87]
32gb DDR4 Trident Z RGB 3466Mhz[@3200XMP]

**Comment by flyinghead** [comment]
This game, like many other Windows CE games, needs the Broadcast to be set correctly. Here it must be set to PAL.
Also it won't boot in HLE BIOS and requires a real BIOS.

**Comment by backgamon** [comment]
It doesn't work with just changing broadcast.
I tryed some others changes, and change only VGA[RGB] to TV[RGB] make it work.
Problem solved.

**Comment by flyinghead** [comment]
Good to know.

Generally I suggest you use TV (Composite), which is the default, instead of TV (RGB) or VGA for best compatibility.
