### ISSUE TITLE
Typing of the Dead - No hiragana/katakana

### ISSUE THREAD

**Issue by danada** [libretro/flycast#781]
I'm running typing of the dead (Dreamcast version) on an Nvidia shield and everything is working very well with the exception of missing kanji/hiragana/katakana above the words that are to be typed.

I saw this was working in the keyboard support video, so I'm wondering if it's something specific with the shield or perhaps there's some graphical setting that needs to be tweaked to get this working.

High score input, as well as the question/answer boss question text doesn't render which makes getting past those bosses very challenging 😅

I've attached a picture (sorry, it's of my TV) to explain what's missing.
![IMG_20200112_223720](https://user-images.githubusercontent.com/157375/72219785-165bd780-358d-11ea-92bd-09fad20abd0f.jpg)

**Comment by flyinghead** [comment]
You need a real BIOS to get the  kanji/hiragana/katakana characters. The HLE BIOS just has US/ASCII characters.

**Comment by danada** [comment]
Thanks! Submitted PR to add some documentation on this.
