### ISSUE TITLE
Transparency Issues in RE: Code Veronica and Dead or Alive 2 

### ISSUE THREAD

**Issue by mochardi** [libretro/flycast#782]
I've noticed some transparency issue on the characters heads in these two games. Like there is a little "extra" transparency in the back of their heads.

Running Retroarch 1.8.3
Flycast Core a37ee3c
Nvidia Geforce gtx 1060 6 GB (Drv. 441.66)
Internal Res.
Alpha Sorting: Per-Pixel

![Resident Evil - Code Veronica v1 000 (2000)(Capcom)(US)(Disc 1 of 2) ! -200115-015621](https://user-images.githubusercontent.com/55611450/72406720-f61e4b00-373b-11ea-8e1d-c282cb6edba9.png)
![Resident Evil - Code Veronica v1 000 (2000)(Capcom)(US)(Disc 1 of 2) ! -200115-015745](https://user-images.githubusercontent.com/55611450/72406721-f6b6e180-373b-11ea-817e-f3b9f7a6975b.png)
![Dead or Alive 2 v1 100 (2000)(Tecmo)(US) ! -200115-020037](https://user-images.githubusercontent.com/55611450/72406725-f880a500-373b-11ea-9b38-882fbcb7ea09.png)

**Comment by barbudreadmon** [comment]
Is it vulkan or opengl ?

**Comment by flyinghead** [comment]
I can reproduce it with Vulkan, not Open GL.

**Comment by backgamon** [comment]
Some games have that issue i think, as i allready see The Grinch are impacted too:
![2](https://user-images.githubusercontent.com/39404647/72423409-7e284300-3784-11ea-8f7f-836b7f9322d1.jpg)

**Comment by flyinghead** [comment]
This should fix the issue: https://github.com/libretro/flycast/commit/b3eb4402377800717c009e49dc35dec862cf3e8f

**Comment by mochardi** [comment]
Wow, that was fast! 
I forgot to write that i was using vulkan, sorry for that

Maybe a silly question, but i´m trying to update the core to b3eb440, and retroarch is telling me that i'm running  lastest version  a37ee3c (i am running latest Nightly, btw)

**Comment by flyinghead** [comment]
You probably have to wait a little until the build is available

**Comment by mochardi** [comment]
@flyinghead Thank you for your hard work!!!

![Resident Evil - Code Veronica v1 000 (2000)(Capcom)(US)(Disc 1 of 2) ! -200115-234333](https://user-images.githubusercontent.com/55611450/72489089-aef29180-37f1-11ea-8f8c-5d83ea1eb7e6.png)
![Dead or Alive 2 v1 100 (2000)(Tecmo)(US) ! -200115-234501](https://user-images.githubusercontent.com/55611450/72489091-b0bc5500-37f1-11ea-8f9b-decdaf90344b.png)
