### ISSUE TITLE
[Naomi] Loud voices but barely noticeable music or Sfx in Street Fighter Zero 3 Upper

### ISSUE THREAD

**Issue by Denshadego** [libretro/flycast#783]
Weirdly the narrator and character voices are super loud but the music and sound effects are almost nonexistent, if you turn up the volume to hear them the voices will blow your ears out. I have seen videos of the game being played in the arcade and emulated in flycast on the libretto channel, but you can hear the music and effects there. 

It's there an option I have to check for this especiffic game to make it sound normal or it's something related to the latest builds?, because in the version shown on video sounds fine.

For the record, other Naomi, DC and atomiswave games sound normal. I am testing on Android ATM.

**Comment by flyinghead** [comment]
Does enabling/disabling the DSP option make any difference?

**Comment by Denshadego** [comment]
Not really, I'll try recording audio from it when I get to my PC.

**Comment by flyinghead** [comment]
It looks like a DIV Matching issue. Try with it disabled.

More generally, when something isn't working, always disable this hack (and others like Fast GDROM) before reporting an issue.

**Comment by Denshadego** [comment]
Yes, that was it. I had it set to auto, turning it off fixed the audio inconsistencies. Thank you!

**Comment by flyinghead** [comment]
should be fixed by https://github.com/libretro/flycast/commit/f9f3249192f487b9d8de0a06531af331d4207fee

**Comment by flyinghead** [comment]
Resolved
