### ISSUE TITLE
Windows CE games boot but get stuck on Sega screen on Pi 4

### ISSUE THREAD

**Issue by quicksilver7837** [libretro/flycast#794]
Running flycast on a raspberry pi4. Windows CE games will boot but get stuck on Sega/windows CE screen. The emulator is not frozen because I can still properly exit the game. Tried turning windows CE mode on in retroarch menu but it doesn't help. Is there something else needed to make windows CE games work?

**Comment by kage2051** [comment]
The Pi 4 build is probably running in 32-bit mode, and WinCE compatibility is available for 64-bit builds exclusively.

**Comment by quicksilver7837** [comment]
Gotcha, thanks for the info
