### ISSUE TITLE
Adding some missing Widescreen Cheats Codes

### ISSUE THREAD

**Issue by backgamon** [libretro/flycast#795]
Can u add somes codes to the Cheats.cpp?

{ "T17703D 50", nullptr,    { 0xCD8950, 0 }, { 0x3F111111 } },		// Suzuki Alstare Extreme Racing

{ "HDR-0074", nullptr,    { 0x1FF60C, 0x1FF610, 0x1FF5DC, 0 }, { 0x3F400000, 0x3F800000, 0x43DC0000 } },	//Rent a Hero n°1

{ "T-9502D-50    ", nullptr,    { 0xBDE9B0, 0xBDE9C4, 0 }, { 0x3F400000, 0x3FA00000 } },	// Nightmare Creatures II (PAL)

All are checked and working.

**Comment by flyinghead** [comment]
Done. Thanks

**Comment by backgamon** [comment]
Thanks at u :)
