### ISSUE TITLE
Shadowman (USA) - Black screen when game begins

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#80]
NOTE: You need to set Cable Type to VGA (RGB) in order to get this game to boot at all.

Once it has booted, go through all the menu screens and select New Game. Skip the intro sequences. Once you are ingame, you will notice that the screen appears for a split second before it goes to black. If you press up on the D-pad, it will show a target reticule (displayed in the picture). You can toggle this on/off by tapping D-pad up again. By pressing down, the inventory screen will appear. Pressing start also works. Beyond this, the screen stays black.

![image](https://user-images.githubusercontent.com/1075274/42130501-6e7e7d92-7ce7-11e8-8f99-8f0ddca42032.png)

This is what the game reports -

https://hastebin.com/arocezumob.pas

**Comment by flyinghead** [comment]
Same on my fork. It doesn't seem to be a rendering problem. Once ingame, the game stops sending anything to the TA, except when the reticule or inventory is displayed.
It could a sound problem: when ingame you don't hear any sound except bells. You should hear water splash sounds when moving the character. I tried enabling EGHack but it didn't help.

**Comment by flyinghead** [comment]
And I hear sudden volume changes in the intro as described here: https://gitlab.com/inolen/redream/issues/151

**Comment by inactive123** [comment]
@skmp Didn't this game work before on Reicast/nulldc? I seem to see Reicast/nulldc compatibility lists where there were no reported issues with this game. Got any leads?

**Comment by skmp** [comment]
Gamedb shows it booting http://gamedb.reicast.com/games/shadow-man. Not sure about ingame.

**Comment by inactive123** [comment]
Yeah, that automated test does not go far enough. You would have to select Start New Game, skip through two cut scenes by pressing Start in order to get to the spot where gameplay begins.

**Comment by inactive123** [comment]
This now works with VGA cable type, not sure if it was because of the floating point commit (-fno-sqrtfs) or the YUV improvements.

**Comment by flyinghead** [comment]
It was a sqrt precision problem. Probably x86 only.

**Comment by hiddenasbestos** [comment]
Currently the core crashes to desktop on Windows after the SEGA license screen if TV (Composite or RGB) output is selected; VGA fixes this crash.

(edit: this matches upstream behaviour.)
