### ISSUE TITLE
Will not compile on Nvidia Jetson Nano

### ISSUE THREAD

**Issue by kotomoness** [libretro/flycast#801]
`core/libretro/common.cpp:258:2: error: #error Unsupported HOST_CPU
 #error Unsupported HOST_CPU
  ^~~~~
core/libretro/common.cpp:368:2: error: #error JIT: Not supported arch
 #error JIT: Not supported arch
  ^~~~~
Makefile:1091: recipe for target 'core/libretro/common.o' failed
make: *** [core/libretro/common.o] Error 1
make: *** Waiting for unfinished jobs....
`

I understand the CPU in the Jetson Nano may not be fully supported yet and the board not fully tested either.  I figure I could try this board out as a single board arcade machine, what with it being a Tegra chip.    

Is there anyway around this or will supporting the Jetson Nano require greater changes?  

Thanks.

**Comment by flyinghead** [comment]
Are you compiling with `make platform=jetson-nano`?

**Comment by kotomoness** [comment]
I was not.  Thank you, this worked.  Apologies for not realizing the platform options in the Makefile.
