### ISSUE TITLE
32 bit support for WinCE

### ISSUE THREAD

**Issue by Panderner** [libretro/flycast#802]
Issues when the 32 bit devices doesn't support WinCE Games but why WinCE Games are exclusive to 64 Bit Devices like Dolphin Emulator?

**Comment by flyinghead** [comment]
Which 32-bit platform(s) do you want to run Windows CE games on?

**Comment by Panderner** [comment]
Look #661 and #794

**Comment by flyinghead** [comment]
Neither the Fire TV nor the Raspberry Pi 4 are fast enough to run Windows CE games.

Even the fastest arm64 platforms available today (SD855) aren't powerful enough to run Windows CE games.

**Comment by Panderner** [comment]
Yeah the mmu emulation is CPU intensive. what x86 CPU is minimum requirement to run wince games full speed?

**Comment by flyinghead** [comment]
It's hard to say. It will also depend on the OS: ironically Windows will run Windows CE games slower than Linux or macOS do.
Any recent >2.5GHz intel cpu should be OK.

**Comment by Panderner** [comment]
I think is demul is a 32 bit windows app it able to run wince games a 32 bit version of Windows running on a core 2 quad 9650 runs ok?

**Comment by flyinghead** [comment]
You should ask the demul team

**Comment by Panderner** [comment]
And how about 32 bit version of Windows running on a i7 CPU?

**Comment by barbudreadmon** [comment]
> And how about 32 bit version of Windows running on a i7 CPU?

The real question is : is there a point in having a 32 bit OS on an i7 cpu ?

**Comment by Panderner** [comment]
> > And how about 32 bit version of Windows running on a i7 CPU?
> 
> The real question is : is there a point in having a 32 bit OS on an i7 cpu ?

Yes 64 bit CPUs can install a 32 bit OS It can. some modern budget android phones running a 64 bit CPU but it is using a 32 bit os

**Comment by barbudreadmon** [comment]
> Yes 64 bit CPUs can install a 32 bit OS It can

Too bad for them, maybe they could have played winCE games if they installed a 64-bits OS.

> modern budget android phones

Too bad for them, with their cheap phone they won't be able to play winCE games anyway.

The point is : any device that has the specs to run those winCE games has or can install a 64-bits OS, and there is no reason to do otherwise.

**Comment by Panderner** [comment]
> > Yes 64 bit CPUs can install a 32 bit OS It can
> 
> Too bad for them, maybe they could have played winCE games if they installed a 64-bits OS.
> 
> > modern budget android phones
> 
> Too bad for them, with their cheap phone they won't be able to play winCE games anyway.
> 
> The point is : any device that has the specs to run those winCE games has or can install a 64-bits OS, and there is no reason to do otherwise.

Why? How about 32 bit version of Windows running on 3.8 GHz Pentium 4 and core 2 duo E8600 and older xeon CPUs?

**Comment by barbudreadmon** [comment]
> How about 32 bit version of Windows running on 3.8 GHz Pentium 4 and core 2 duo E8600 and older xeon CPUs?

They can install 64-bits instead.

**Comment by flyinghead** [comment]
Yes, it can be done, but I don't think it's worth my time for the reasons exposed above. Now if someone is up to the task, I'll be very happy to merge a PR.
