### ISSUE TITLE
Guilty Gear X - Graphical glitch on title screen

### ISSUE THREAD

**Issue by ghost** [libretro/flycast#803]
Title screen of Guilty Gear X on Dreamcast has graphical glitch.
No glitch on Naomi with cores of Flycast and MAME 0.217.
I can't tell if is an issue of Flycast or also on real hardware.
(tested with Redump cue / bin)

Naomi screenshot with MAME 0.217
![ggx-200204-200448](https://user-images.githubusercontent.com/55448675/73871659-8721a700-484e-11ea-883c-8f1e8ed5aabd.png)

Naomi screenshot with Flycast
![ggx-200205-150131](https://user-images.githubusercontent.com/55448675/73871717-a28cb200-484e-11ea-8b15-0b03f8216697.png)

Dreamcast screenshot with Flycast
![Guilty Gear X (Japan)-200204-202408](https://user-images.githubusercontent.com/55448675/73871757-b59f8200-484e-11ea-87b2-46e176d2ba15.png)

**Comment by flyinghead** [comment]
Please check with real hardware (youtube is your friend here) and report precisely which glitch(es) you see.

**Comment by ghost** [comment]
Share information doesn't mean necessary make more that already done in anticipation on initial publication (including youtube).
Therefore, It will not happen.

**Comment by barbudreadmon** [comment]
Issue confirmed on real hardware.

**Comment by leilei-** [comment]
for what it's worth, the recent Y-filter shader masks the speckles pretty well, and with a NTSC shader of some sort on top of that filtered output, and should appear less obnoxious
![ggxsvideoyfiltered](https://user-images.githubusercontent.com/6590431/74016948-48c8dc80-4961-11ea-847b-3bee670f37c8.jpg)
