### ISSUE TITLE
Power Stone - Blocked in Button Config Menu

### ISSUE THREAD

**Issue by ghost** [libretro/flycast#805]
We are blocked in Button Config Menu on Power Stone. When you try to exit, you hear a wrong sound and Dreamcast gamepad on menu become translucent.
(tested with USA Redump cue / bin and Europe Tosec gdi)

Only solution. Either we must change controller in RetroArch menu (back step on main option menu) by the game, eitheir we must use internal command of Dreamcast to return on Title screen or Bios menu (hold A + B + X + Y + Start). Buttons configuration will not be saved.

I can't tell if it's issue of Flycast or bug by Capcom for Power Stone.

Dreamcast screenshots
![Power Stone (USA)-200204-211539](https://user-images.githubusercontent.com/55448675/73875156-129e3680-4855-11ea-8a35-3a4eea95bde9.png)

![Power Stone (USA)-200204-211548](https://user-images.githubusercontent.com/55448675/73875168-17fb8100-4855-11ea-8f84-949358b8d7f1.png)

**Comment by flyinghead** [comment]
You need to scroll down to EXIT and press A on *both* controllers

**Comment by ghost** [comment]
Ok, thanks very much.
