### ISSUE TITLE
Virtua Fighter 3 - Title Screen

### ISSUE THREAD

**Issue by cbo2188** [libretro/flycast#806]
Great emulator!  Just wanted to mention this just in case..  In Virtua Fighter 3 (Dreamcast), Shun's beard has a waterfall effect in the title screen.  Attached a pic of what happens.  Thank you for all your hard work!

![image](https://user-images.githubusercontent.com/49599556/73893217-feebd380-4846-11ea-8759-8e99a7aaca51.png)

**Comment by flyinghead** [comment]
The picture quality is not that great but it looks like the same is happening on a real console: https://youtu.be/Bb-0nixyEjQ?t=119

**Comment by flyinghead** [comment]
Quite obvious here: https://youtu.be/BDNLoCtlUdg?t=10
Demul: https://youtu.be/TtLDs1NU4Qw?t=148
Not sure this is a real console: https://youtu.be/t1xB532b2U8?t=9

**Comment by cbo2188** [comment]
Thanks and sorry about that.  Looked strange but apparently normal.

**Comment by flyinghead** [comment]
No problem
