### ISSUE TITLE
(Naomi) Hokuto No Ken crashes when inserting coins

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/flycast#81]
Here is the output before crashing : 

> naomi?WTF? WriteMem: 5F7070 <= 7, 4
naomi?WTF? WriteMem: 5F7074 <= 0, 4
naomi?WTF? WriteMem: 5F7070 <= 7, 4
naomi?WTF? ReadMem: 5F7074, 4
naomi?WTF? WriteMem: 5F7070 <= 7, 4
naomi?WTF? WriteMem: 5F7074 <= 1, 4
naomi?WTF? WriteMem: 5F7070 <= 7, 4
naomi?WTF? ReadMem: 5F7074, 4
unknown MAPLE Frame
Unknown 0x86 : SubCommand 0x1 - State: Cmd 0x0 Mode :  0x0 Node : 0x0
Command : 0x86,Data : 4 bytes
00000001 
new tactx
new tactx
Unknown 0x86 : SubCommand 0x13 - State: Cmd 0x14 Mode :  0x0 Node : 0x1
Command : 0x86,Data : 12 bytes
20070113 02210202 00000222 
unknown CAP 21
unknown CAP 21
naomi?WTF? WriteMem: 5F705C <= 4, 4
naomi?WTF? WriteMem: 5F705C <= 4, 4
naomi?WTF? WriteMem: 5F705C <= 4, 4
naomi?WTF? WriteMem: 5F705C <= 4, 4
naomi?WTF? WriteMem: 5F705C <= 4, 4
naomi?WTF? WriteMem: 5F705C <= 4, 4
Freeing fpcb
Freeing fpcb
Invalid (NAOMI)GD-DMA start, SB_GDEN=0.Ingoring it.
Freeing fpcb
Freeing fpcb
[libretro INFO] Fatal error : ParamType_Object_List_Set
 in ta_main -> core/hw/pvr/ta_vtx.cpp : 395 
DEBUGBREAK!
SIGSEGV @ 0x7f602af26873 (signal_handler + 0x0x15476413) ... (nil) -> was not in vram
[libretro INFO] Fatal error : segfault
 in signal_handler -> core/libretro/common.cpp : 392 
DEBUGBREAK!

**Comment by inactive123** [comment]
@barbudreadmon Can you see what happens if you comment out line 395 in core/hw/pvr/ta_tx.cpp? And then recompile and test again.

**Comment by barbudreadmon** [comment]
Error became this : 
> Freeing fpcb
Freeing fpcb
Invalid (NAOMI)GD-DMA start, SB_GDEN=0.Ingoring it.
Freeing fpcb
Freeing fpcb
TA: Invalid state, ignoring VTX data
TA: Invalid state, ignoring VTX data
TA: Invalid state, ignoring VTX data
...
TA: Invalid state, ignoring VTX data
TA: Invalid state, ignoring VTX data
TA: Invalid state, ignoring VTX data
List overrun for list verts
List overrun for list global_param_tr
[libretro INFO] Fatal error : Unhandled parameter
 in ta_main -> core/hw/pvr/ta_vtx.cpp : 485 
DEBUGBREAK!
SIGSEGV @ 0x7f407e440873 (signal_handler + 0x0x1443db63) ... (nil) -> was not in vram
[libretro INFO] Fatal error : segfault
 in signal_handler -> core/libretro/common.cpp : 392 
DEBUGBREAK!

**Comment by inactive123** [comment]
Try commenting out line 485 in core/hw/pvr/ta_vtx.cpp as well.

**Comment by barbudreadmon** [comment]
> ...
TA: Invalid state, ignoring VTX data
TA: Invalid state, ignoring VTX data
TA: Invalid state, ignoring VTX data
TA: Invalid state, ignoring VTX data
SIGSEGV @ 0x7f10448de268 (signal_handler + 0x0x18d3518) ... 0x7f10448de268 -> was not in vram
[libretro INFO] Fatal error : segfault
 in signal_handler -> core/libretro/common.cpp : 392 
DEBUGBREAK!

**Comment by barbudreadmon** [comment]
The issue also happens after a few minutes during demo play if you don't press anything.

**Comment by inactive123** [comment]
OK, so there is no way to get it to simply work then by just stubbing out debug lines.

**Comment by barbudreadmon** [comment]
Also, this game works properly on the old nullDC.

**Comment by barbudreadmon** [comment]
This issue seems fixed after your last commits. I close.

**Comment by inactive123** [comment]
Just for reference's sake, according to @Tatsuya79 this is what fixed it -

https://github.com/libretro/reicast-emulator/commit/130cee6ba26018eaf14fee6f642d2d3218ac5ec7
