### ISSUE TITLE
Loading content in flycast core crashes Retroarch to Desktop

### ISSUE THREAD

**Issue by chrisdb** [libretro/flycast#811]
**System configuration:**

- Windows 10, 64bit
- Retroarch x86, 1.8.4
- latest flycast_libretro core
- `RetroArch\system\dc` contains _**dc_boot.bin**_ (`MD5: e10c53c2f8b90bab96ead2d368858623`), _**dc_flash.bin**_ (`MD5: 0a93f7940c455905bea6e392dfde92a4`) and _**naomi.zip**_
- _Desktop Menu - Core Info_ shows that all three bios files are recognized

**Steps to reproduce:**

- starting retroarch `.\retroarch.exe --verbose`
- Load Core "Sega - Dreamcast/NAOMI (Flycast)"
- Load Content: any Dreamcast game (tested several *.gdi, *.chd and *.cdi files - all tested *.gdi files work just fine in DEmul)

**Obeserved behaviour:**

- Retroarch crashes to desktop
- Console output: `Exception code=0xc0000005 flags=0x0 at 0x157A2979. Access violation - attempting to read data at address 0xA0000000`

**Detailed log-file output:**

>[...]
>[INFO] === Build =======================================
>[INFO] CPU Model Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
>[INFO] Fähigkeiten:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
>[INFO] Built: Jan 15 2020
>[INFO] Version: 1.8.4
>[INFO] Git: f425d8dc8b
>[INFO] =================================================
>[INFO] Loading dynamic libretro core from: "F:\LaunchBox\RetroArch\cores\flycast_libretro.dll"
>[INFO] [Overrides] no core-specific overrides found at F:\LaunchBox\RetroArch\config\Flycast\Flycast.cfg.
>[INFO] [Overrides] no content-dir-specific overrides found at F:\LaunchBox\RetroArch\config\Flycast\Armada (USA).cfg.
>[INFO] [Overrides] no game-specific overrides found at F:\LaunchBox\RetroArch\config\Flycast\Armada (USA).cfg.
>[INFO] [Environ]: GET_LANGUAGE: "4".
>[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL.
>[INFO] [Environ]: SET_CONTROLLER_INFO.
>[INFO] [Remaps]: remap directory: F:\LaunchBox\RetroArch\config\remaps
>[INFO] Speicherdaten umleiten in "F:\LaunchBox\RetroArch\saves\Armada (USA).srm".
>[INFO] Spielstand umleiten in "F:\LaunchBox\RetroArch\states\Armada (USA).state".
>[INFO] [Environ]: GET_LOG_INTERFACE.
>[INFO] [Environ]: GET_PERF_INTERFACE.
>[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
>[INFO] [Environ]: SET_KEYBOARD_CALLBACK.
>[INFO] [Environ]: UNSUPPORTED (#57).
>[INFO] [Environ]: SET_DISK_CONTROL_INTERFACE.
>[INFO] Laden des Inhalts übersprungen. Die Implementierung wird ihn selbst laden.
>[INFO] [Environ]: GET_RUMBLE_INTERFACE.
>[libretro INFO] Rumble interface supported!
>[INFO] [Environ]: SYSTEM_DIRECTORY: "F:\LaunchBox\RetroArch\system".
>[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
>[...]
>[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
>[libretro INFO] File extension is: .gdi
>[INFO] [Environ]: GET_PREFERRED_HW_RENDER.
>[INFO] [Environ]: SET_HW_RENDER.
>[INFO] Requesting core OpenGL context (3.0).
>[libretro INFO] 00:00:000 hw/mem/_vmem.cpp:547 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
>[libretro INFO] 00:00:065 nullDC.cpp:152 N[BOOT]: [LUT]: Product number: T40301N 00.
>[libretro INFO] 00:00:065 nullDC.cpp:156 N[BOOT]: Enabling Full MMU and Extra depth scaling for Windows CE game
>[INFO] [Environ]: SET_ROTATION: 0
>[INFO] [RCHEEVOS]: ext_hash 0b887659 ('gdi')
>[INFO] Überspringe Laden des SRAM..
>[INFO] Version der libretro-API: 1
>[INFO] Kompiliert gegen API: 1
>[INFO] [Cheats]: Load game-specific cheatfile: F:\LaunchBox\RetroArch\cheats\Flycast\Armada (USA).cht
>[INFO] [RCHEEVOS]: Load task finished
>[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
>[INFO] [Video]: Video @ fullscreen
>[INFO] [Video]: Using HW render, OpenGL driver forced.
>[INFO] [Video]: Using configured "gl" driver for GL HW render.
>[INFO] [GL]: Found GL context: wgl
>[INFO] [GL]: Detecting screen resolution 1920x1080.
>[INFO] [WGL] extensions: WGL_ARB_buffer_region WGL_ARB_create_context WGL_ARB_create_context_no_error WGL_ARB_create_context_profile WGL_ARB_create_context_robustness WGL_ARB_context_flush_control WGL_ARB_extensions_string WGL_ARB_make_current_read WGL_ARB_mult
>[INFO] [WGL]: Adaptive VSync supported.
>[INFO] [WGL]: wglSwapInterval(1)
>[INFO] [GL]: Vendor: NVIDIA Corporation, Renderer: GeForce GTX 960/PCIe/SSE2.
>[INFO] [GL]: Version: 4.6.0 NVIDIA 432.00.
>[INFO] [GL]: Using Core GL context, setting up VAO...
>[INFO] [GL]: Using resolution 1920x1080
>[INFO] [GL]: Default shader backend found: glsl.
>[INFO] [Shader driver]: Using GLSL shader backend.
>[INFO] [GLSL]: Checking GLSL shader support ...
>[WARN] [GL]: Stock GLSL shaders will be used.
>[INFO] [GLSL]: Found GLSL vertex shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Found GLSL fragment shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Linking GLSL program.
>[INFO] [GLSL]: Found GLSL vertex shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Found GLSL fragment shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Linking GLSL program.
>[INFO] [GLSL]: Found GLSL vertex shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Found GLSL fragment shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Linking GLSL program.
>[INFO] Setting up menu pipeline shaders for XMB ... 
>[INFO] [GLSL]: Compiling ribbon shader..
>[INFO] [GLSL]: Found GLSL vertex shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Found GLSL fragment shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Linking GLSL program.
>[INFO] [GLSL]: Compiling simple ribbon shader..
>[INFO] [GLSL]: Found GLSL vertex shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Found GLSL fragment shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Linking GLSL program.
>[INFO] [GLSL]: Compiling snow shader..
>[INFO] [GLSL]: Found GLSL vertex shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Found GLSL fragment shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Linking GLSL program.
>[INFO] [GLSL]: Compiling modern snow shader..
>[INFO] [GLSL]: Found GLSL vertex shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Found GLSL fragment shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Linking GLSL program.
>[INFO] [GLSL]: Compiling bokeh shader..
>[INFO] [GLSL]: Found GLSL vertex shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Found GLSL fragment shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Linking GLSL program.
>[INFO] [GLSL]: Compiling snowflake shader..
>[INFO] [GLSL]: Found GLSL vertex shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Found GLSL fragment shader.
>[INFO] [GLSL]: Using GLSL version 130.
>[INFO] [GLSL]: Linking GLSL program.
>[INFO] [GL]: Using 1 textures.
>[INFO] [GL]: Loaded 1 program(s).
>[INFO] [GL]: Initializing HW render (1024 x 1024).
>[INFO] [GL]: Max texture size: 16384 px, renderbuffer size: 16384 px.
>[INFO] [GL]: Supports FBO (render-to-texture).
>[INFO] [XInput]: Found XInput v1.4.
>[INFO] [XInput]: Found controller, user #0
>[INFO] [XInput]: Pads connected: 1
>[INFO] [DINPUT]: Enumerating joypads ...
>[INFO] [DINPUT]: Device #0 PID: {09CC} VID:{054C}
>[WARN] [DINPUT]: Strong rumble unavailable.
>[WARN] [DINPUT]: Weak rumble unavailable.
>[INFO] [Autoconf]: 141 profiles found.
>[INFO] [DINPUT]: Device #1 PID: {028E} VID:{045E}
>[INFO] [DINPUT]: Done enumerating joypads ...
>[INFO] [XInput]: Attempting autoconf for "Wireless Controller", user #0
>[INFO] [XInput]: Attempting autoconf for "XInput Controller (User 1)", user #1
>[INFO] [DINPUT]: Found XInput pad at index 0 (DINPUT index 1)
>[INFO] [XInput]: Found VID/PID (045E/028E) from DINPUT index 1 for "XInput Controller (User 1)", user #1
>[INFO] [XInput]: Attempting autoconf for user #2
>[...]
>[INFO] [XInput]: Attempting autoconf for user #15
>[INFO] [Joypad]: Found joypad driver: "xinput".
>[INFO] [Font]: Using font rendering backend: freetype.
>[INFO] [Video]: Found display server: win32
>[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
>[INFO] [Autoconf]: selected configuration: F:\LaunchBox\RetroArch\autoconfig\xinput\DUALSHOCK_4.cfg
>[INFO] [Autoconf]: 141 profiles found.
>[INFO] [Autoconf]: selected configuration: F:\LaunchBox\RetroArch\autoconfig\xinput\XInput_Controller_User_1.cfg
>[INFO] [Menu]: Found menu display driver: "gl".
>[INFO] [Font]: Using font rendering backend: freetype.
>[INFO] [Font]: Using font rendering backend: freetype.
>[INFO] [Font]: Using font rendering backend: freetype.
>[INFO] [Font]: Using font rendering backend: freetype.
>[INFO] [LED]: LED driver = 'null' 00B0EDB0
>[INFO] [MIDI]: Initializing ...
>[INFO] [MIDI]: Input disabled.
>[INFO] [MIDI]: Output disabled.
>[INFO] [MIDI]: Initialized "winmm" driver.
>[INFO] Lade Verlaufs-Datei: [F:\LaunchBox\RetroArch\content_history.lpl].
>[INFO] Lade Verlaufs-Datei: [F:\LaunchBox\RetroArch\content_music_history.lpl].
>[INFO] Lade Verlaufs-Datei: [F:\LaunchBox\RetroArch\content_video_history.lpl].
>[INFO] Lade Verlaufs-Datei: [F:\LaunchBox\RetroArch\content_image_history.lpl].
>[INFO] Loading favorites file: [F:\LaunchBox\RetroArch\content_favorites.lpl].
>[INFO] [GL]: VSync => on
>[INFO] [WGL]: wglSwapInterval(1)
>[INFO] [Font]: Using font rendering backend: freetype.
>[INFO] [Font]: Using font rendering backend: freetype.
>[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
>[libretro ERROR] 00:00:760 libretro/common.cpp:84 E[COMMON]: [GPF]Unhandled access to : a0000000

**Comment by flyinghead** [comment]
Are you running a 32-bit version of RetroArch?

If that's the case, you need to use the 64-bit version for Windows CE games such as Armada.

**Comment by chrisdb** [comment]
Thanks, that actually was the issue.

**Comment by Lensman76** [comment]
> 
> 
> Are you running a 32-bit version of RetroArch?
> 
> If that's the case, you need to use the 64-bit version for Windows CE games such as Armada.

This is happening to me with all my Dreamcast titles (Crazy Taxi, Chuchu Rocket, Daytona USA, Dead or Alive 2, etc...) and always with a similar message:
...
[INFO] [GL]: VSync => off
[INFO] [WGL]: wglSwapInterval(0)
[INFO] [Playlist]: Written to playlist file: F:\PortableEmulationStation\.emulationstation\systems\retroarch\content_history.lpl
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
Exception code=0xc0000005 flags=0x0 at 0x104F9E09. Access violation - attempting to read data at address 0xA0000000
[libretro ERROR] 00:00:569 libretro/common.cpp:83 E[COMMON]: [GPF]Unhandled access to : a0000000
...

The 64bit version works fine, however I would prefer to use the 32bit version for various reasons, so why doesnt the 32bit version work, is there an actual reason or is it defunct now?

Thanks.
