### ISSUE TITLE
Analog stick issue with Ubisoft games

### ISSUE THREAD

**Issue by krocoster** [libretro/flycast#817]
The up and left axis don't respond in the games Rayman 2 and Donald Duck Goin' Quackers when you are in a level. In the main menu they work fine, but as soon as the actual game part starts they stop working. I'm using Retroarch 1.84 with version 0.1 4565fe0 of the core. I'll provide more info if necessary.

**Comment by flyinghead** [comment]
Disable div matching. Also try with a real BIOS file if applicable

**Comment by krocoster** [comment]
Disabling div matching did it, thank you very much! Already using a real BIOS file. Just for curiosity, is this a new bug or is it written down somewhere?

**Comment by flyinghead** [comment]
I recently came accross the Rayman 2 issue. But Donald Duck is a new one

**Comment by flyinghead** [comment]
Actually DIV Matching is automatically disabled for Rayman 2 in the version of the core you're using. Are you using a CDI? In some cases they use the wrong game ID and the core can't recognize it.

**Comment by krocoster** [comment]
I enabled div matching in general before playing the games thinking it'll boost performance however I didn't notice any differences. It's a GDI image. I found another bug: Save stating while in the hub corrupts said state and it'll crash the game when attempting to load it. Again for both games. Now I remembered there's a minor graphical glitch when you are given the choice to choose a VMU. The cursor is out of the squares that selects a VMU. It can be bypassed by simply moving to the right.

**Comment by RibShark** [comment]
Might be worth testing these bugs on Disney's Dinosaur too, as it runs on an (albeit later) [revision of the same engine](https://github.com/byvar/raymap/wiki/List-of-OpenSpace-games).

**Comment by flyinghead** [comment]
I just did a quick test with disney's dinosaur and it seems the joystick is working properly with Div matching enabled. Thanks for the tip though.

**Comment by flyinghead** [comment]
Div Matching cannot be forced on anymore
