### ISSUE TITLE
MvC2 Stuttering

### ISSUE THREAD

**Issue by very-hidden-squid** [libretro/flycast#819]
Running MvC2 through Flycast in Retroarch. The game runs perfectly in the menus but is unplayable due to stuttering and audio lag. The frame rate in the top right somehow rises into the 2000s, rendering the game unplayable. Is there a way to stop this? It runs perfectly on my desktop.

**Comment by flyinghead** [comment]
Platform, OS, versions, RA and core settings, etc.
If it runs perfectly on your desktop, what’s the problem then??

**Comment by very-hidden-squid** [comment]
Windows PC, running Windows 10.
Laptop is XPS 13 with i7
Desktop has i7 also
Running Retroatch 1.8.4
Using Flycast Naomi Core
No special settings enabled
The frame rate in the top right has gone into the thousands, would that be causing the stutters and if so, how would that be fixed?

**Comment by flyinghead** [comment]
There's probably an issue with the audio on your laptop. Flycast uses the audio output to slow down the emulated cpu. Without audio, or if the audio output doesn't block when the output buffer is full, the emulator will run at full speed.

**Comment by very-hidden-squid** [comment]
No audio seemed to help, but the game still stuttered. Flycast is also the only Retroarch core that seems to display a frame counter, and during gameplay it often rises into the thousands. Could capping the frame rate stop this issue?

**Comment by flyinghead** [comment]
The frame counter is displayed by RetroArch and is controlled by a RetroArch setting. The core has no control on this.

The frame rate (and emulation speed in general) is normally limited by the audio stream so that's probably where the problem is.

**Comment by very-hidden-squid** [comment]
Found a solution. I went and copied every single setting I had on my desktop version to my laptop. I believe the issue was to be found in Audio Latency. On desktop it was 64, and on my laptop it was set to 512. Once I fixed all the settings, I opened the game again and it runs perfect. Closing this thread, hopefully this helps anyone else with this issue.
