### ISSUE TITLE
[Dreamcast] The King of Fighters - Dream Match 1999 - Texture issue

### ISSUE THREAD

**Issue by blisstik** [libretro/flycast#826]
Latest version at 640x480. It happens during character poses where it looks like it goes out of focus and the tiles start to appear.

https://cdn.discordapp.com/attachments/402207118704508928/680454139083358306/IMG_1234.jpg

**Comment by mochardi** [comment]
The game runs at native 320x240 

Look here: 
https://github.com/libretro/flycast/issues/680
https://github.com/libretro/flycast/issues/172

**Comment by blisstik** [comment]
Thanks. I'll close then
