### ISSUE TITLE
cant seem to open anygame.

### ISSUE THREAD

**Issue by kosukito** [libretro/flycast#828]
I was using everything fine yesterday and today i just took my notebook to the work and cant seem to open anygame and closes.

i fresh install retroarch and installed the bioses on the DC directory the logs tells me it recognizes the games and the bioses but gives me this error on everygame

[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[libretro ERROR] 00:01:274 libretro/common.cpp:84 E[COMMON]: [GPF]Unhandled access to : 0000000059b39000

here is the full log https://pastebin.com/pYdj6fs5
can anybody give me some advice? thank you.

**Comment by flyinghead** [comment]
This should be fixed in the new build

**Comment by kosukito** [comment]
thank you, its a common problem to everyone?

**Comment by flyinghead** [comment]
It only happened on windows.

**Comment by flyinghead** [comment]
Please close the issue if fixed. Thanks

**Comment by kosukito** [comment]
Theproblem was fixed thank you
