### ISSUE TITLE
after commit 1c3366e2 Dreamcast games fail to run

### ISSUE THREAD

**Issue by mickski56** [libretro/flycast#83]
No Dreamcast game will load tried it with a few different ones. The only Naomi game i have loads just fine.
using reicast-libretro.so

reios: Hardware ID is: SEGA SEGAKATANA 
reios: Maker ID is:    SEGA ENTERPRISES
reios: Device info is: 7B0C GD-ROM1/1  
reios: Area symbols is:  U      
reios: Peripherals is: 0799A10 
reios: Product number is: T40211N   
reios: Product version is: V1.002
reios: Release date is: 20000912        
reios: Boot filename is: 1ST_READ.BIN    
reios: Software company is: SEGA LC-T-402   
reios: Software name is: TOKYO XTREME RACER 2                                                                                                            
reios: loading ip.bin from FAD: 45150
reios: bootfile is '1ST_READ.BIN    '
reios: iso9660 PVD found
reios: iso9660 root_directory, FAD: 45170, len: 2048
Found 1ST_READ.BIN at 000093
filename len: 14
file LBA: 548314
file LEN: 1403044
[libretro INFO] [LUT]: Product number: T40211N   .
Get MemPtr unsupported area : addr=0xA0000000
Get MemPtr unsupported area : addr=0xA000001C
[libretro INFO] Verify Failed  : data==0 || data==0x001fffff || data==0x42fe
 in sb_write_gdrom_unlock -> core/hw/holly/sb.cpp : 140 
DEBUGBREAK!

**Comment by inactive123** [comment]
Tokyo Xtreme Racer 2 (USA) works fine for me with the latest build -

![image](https://user-images.githubusercontent.com/1075274/42134317-83eeaf38-7d39-11e8-91bc-a28c8d5e07f1.png)

**Comment by mickski56** [comment]
still seeing it @130cee6b

**Comment by inactive123** [comment]
Don't know what to tell you though, that game just works on my end. Maybe you have not set up your VMU properly in the BIOS screen?

**Comment by inactive123** [comment]
reios: Hardware ID is: SEGA SEGAKATANA
reios: Maker ID is:    SEGA ENTERPRISES
reios: Device info is: 7B0C GD-ROM1/1
reios: Area symbols is:  U
reios: Peripherals is: 0799A10
reios: Product number is: T40211N
reios: Product version is: V1.002
reios: Release date is: 20000912
reios: Boot filename is: 1ST_READ.BIN
reios: Software company is: SEGA LC-T-402
reios: Software name is: TOKYO XTREME RACER 2                                                                                                                               
reios: loading ip.bin from FAD: 45150
reios: bootfile is '1ST_READ.BIN    '
reios: iso9660 PVD found
reios: iso9660 root_directory, FAD: 45170, len: 2048
Found 1ST_READ.BIN at 000093
filename len: 14
file LBA: 548314
file LEN: 1403044
[libretro INFO] [LUT]: Product number: T40211N   .

**Comment by inactive123** [comment]
Can you do a bisect and tell me from which commit this started, and which commit still worked for you?

**Comment by mickski56** [comment]
f948454e working
94806e16 not working
This is on linux 64bit using a gdi image if that helps.

**Comment by inactive123** [comment]
See if this fixes it -

https://github.com/libretro/reicast-emulator/commit/b3e2b29d796fcea8a4955755f52c4a1581f2736f

**Comment by mickski56** [comment]
I'm  away from my computer til the weekend. I will test then & let you know how it goes. Thanks for looking into this.

**Comment by mickski56** [comment]
I tried the latest git and can confirm that dreamcast games are loading again. Let me know if you want confirmation of commit b3e2b29 being the the specific commit that fixes the issue.
Thanks and close issue.
