### ISSUE TITLE
Tony Hawk's Pro Skater 2 broken shadow

### ISSUE THREAD

**Issue by HelicopterP** [libretro/flycast#842]
Start the career mode, go down the first slope in hangar and you will see broken shadow.
I've tried to play around with settings, but nothing seems to fix it.
I'm running windows 10 and latest flycast version in vulkan mode

**Comment by leilei-** [comment]
THPS2 uses render-to-texture for shadows, and for me to reproduce your problem, I had to turn that off after starting the game.  Is this enabled? 

I imagine you're seeing something like this
![thps2shadow](https://user-images.githubusercontent.com/6590431/76726640-21b3b680-6728-11ea-977e-fd79f5751c9f.jpg)

**Comment by HelicopterP** [comment]
Ok, you are right. Sorry for invalid bug report.

**Comment by Joai27373** [comment]
> THPS2 usa renderização para textura para sombras e, para reproduzir seu problema, tive que desligá-lo após iniciar o jogo. Isso está habilitado?
> 
> Imagino que você esteja vendo algo assim ![thps2shadow](https://user-images.githubusercontent.com/6590431/76726640-21b3b680-6728-11ea-977e-fd79f5751c9f.jpg)

no meu celular eu ligando e desligando aquela opção escrito v ram deu certo pra tirar esse problema aí das sombras mas no meu mi Stick não deu certo continua com a sombra
