### ISSUE TITLE
Black textures with SoulCalibur when Texture Upscaling is enabled

### ISSUE THREAD

**Issue by jvhellraiser** [libretro/flycast#844]
I notice that in the latest release lots of games are broken, like in soulcalibur stages are missing, in other games have random missing textures etc really weird.

Build: flycast-win_x64-fast-bb345bf291208f5786f9db1b79683b291a326bce [3/17]

**Comment by flyinghead** [comment]
What was the last build that worked?

**Comment by jvhellraiser** [comment]
Stages on Soulcalibur are working just fine on build flycast-win_x64-fast-39af255335b7792d310277e2dd5784ab2c254b4e [39af255] [3/16]

I have no idea what happen but i delete the emu.cfg and the game started loading just fine.

**Comment by flyinghead** [comment]
Were you using Vulkan and now using Open GL?

**Comment by jvhellraiser** [comment]
i always use Opengl/Direct3D11 i can't use Vulkan.

**Comment by flyinghead** [comment]
Texture Upscaling?

**Comment by jvhellraiser** [comment]
pretty sure what you mention was the problem, thanks...

**Comment by flyinghead** [comment]
closing then
