### ISSUE TITLE
Samurai Spirits Tenkaichi Kenkakuden Crashes

### ISSUE THREAD

**Issue by Panderner** [libretro/flycast#845]
When I starting the game the Emulator Crashes after Clearing Backup Data

**Comment by flyinghead** [comment]
Try deleting all `samsptk.zip.nvmem` and `samsptk.zip.nvmem2` files from your content directory (or configured Savefile directory if different)

**Comment by Panderner** [comment]
> Try deleting all `samsptk.zip.nvmem` and `samsptk.zip.nvmem2` files from your content directory (or configured Savefile directory if different)

I've trying to play this game for first time. I don't have `samsptk.zip.nvmem` and `samsptk.zip.nvmem2` in save directory

**Comment by flyinghead** [comment]
What platform are you using?

**Comment by Panderner** [comment]
> What platform are you using?

I'm using 64 bit Android

**Comment by flyinghead** [comment]
I can't reproduce the issue. Can you post a retroarch log and your retroarch/core options?

**Comment by Panderner** [comment]
My phone is not rooted, I don't have a PC. I'm using default settings

**Comment by flyinghead** [comment]
You don't need a rooted phone or a PC to get retroarch logs. Go to `Settings > Logging` and enable `Log To File` and `Logging Verbosity` and set both logging levels to Debug.

The log file will be created in the `logs` folder in RA main folder.

**Comment by Panderner** [comment]
I'm going to close this because the latest version is working and i can reach in game

**Comment by Panderner** [comment]
But it crashes when I enable RTT (Render to Texture) Buffer and PowerVR2 Post-Processing Filter
