### ISSUE TITLE
[Issue] Digital triggers option doesn't produce anything

### ISSUE THREAD

**Issue by Immersion95** [libretro/flycast#846]
Hi,

The commit https://github.com/libretro/flycast/commit/25fb12324e52e187d36bee92ba778a163077f00a introduces a problem with the digital trigger option.

It  doesn't work anymore. I understand the aim of that commit but this option was really useful.

**Comment by flyinghead** [comment]
Can you tell me more about your input device and configuration/bindings?

**Comment by Immersion95** [comment]
It's the default layout (x360 pad)

Also, I'm using Windows 10 x64.

**Comment by flyinghead** [comment]
Previously, flycast was using L/R for 100% trigger and L2/R2 for 50% trigger. Now it's only using L2/R2 for 100% trigger. So you might need to remap L/R onto L2/R2.

**Comment by Immersion95** [comment]
> Previously, flycast was using L/R for 100% trigger and L2/R2 for 50% trigger. Now it's only using L2/R2 for 100% trigger. So you might need to remap L/R onto L2/R2.

I'll try remapping L/R to L1/R1 for 100% trigger.

I'm taking this opprtunity to thank you flyinghead for what you are doing for the DC emulation world :)

**Comment by flyinghead** [comment]
You're welcome. Let me know if you still have input issues.

**Comment by Immersion95** [comment]
Yes it works when you reassign the button in Retroarch, I think this option can disapear as it's useless at the moment.

Should I close this issue ?

**Comment by flyinghead** [comment]
I think the Digital Triggers options might be useful for gamepads that don't have analog triggers but I may be wrong.

Feel free to close the issue if you think it's solved.

**Comment by Immersion95** [comment]
Yes I like this option, unfortunately it doesn't work right now. We can directly change the input config for the moment.

Will it be solved ? If not, it's best to delete it right now.

Thanks :)
