### ISSUE TITLE
flycast no longer works using the gles renderer?

### ISSUE THREAD

**Issue by MastaG** [libretro/flycast#851]
Hi just compiled the latest Retroarch (--enable-opengles --enable-opengles3) and Flycast build (platform=odroid BOARD=ODROID-XU4 ARCH=arm HAVE_CLANG=1).

RetroArch works (gbm/gles), but when I attempt to load a game in flycast it will crash with:

[libretro INFO] 00:03:667 hw/pvr/Renderer_if.cpp:102 N[PVR]: Creating Open GL per-triangle/strip renderer
[95B blob data]
[libretro WARN] 00:03:668 rend/gles/gles.cpp:491 W[RENDERER]: Shader: failed to compile
0:1: P0007: Language version '130' unknown, this compiler only supports up to version '320 es'
0:43: L0001: Typename expected, found 'smooth'
0:43: L0001: Expected token 'identifier', found 'lowp'
[libretro WARN] 00:03:669 rend/gles/gles.cpp:491 W[RENDERER]: Shader: failed to compile
0:1: P0007: Language version '130' unknown, this compiler only supports up to version '320 es'
0:25: L0002: Undeclared variable 'gl_FragDepth'
[libretro WARN] 00:03:669 rend/gles/gles.cpp:539 W[RENDERER]: Shader linking: failed to link
 (45 bytes), - Link failed because of invalid vertex shader. -
[libretro WARN] 00:03:669 rend/gles/gles.cpp:540 W[RENDERER]: VERTEX:
#version 130
#define TARGET_GL GL3
#define pp_Gouraud 1
#define GLES2 0
#define GLES3 1
#define GL2 2
#define GL3 3
#if TARGET_GL == GL2
#define highp
#define lowp
#define mediump
#endif
#if TARGET_GL == GLES2 || TARGET_GL == GL2
#define in attribute
#define out varying
#endif
#if TARGET_GL == GL3 || TARGET_GL == GLES3
#if pp_Gouraud == 0
#define INTERPOLATION flat
#else
#define INTERPOLATION smooth
#endif
#else
#define INTERPOLATION
#endif
/* Vertex constants*/
uniform highp vec4      scale;
uniform highp vec4      depth_scale;
uniform highp float     extra_depth_scale;
uniform highp float sp_FOG_DENSITY;
/* Vertex input */
in highp vec4    in_pos;
in lowp  vec4     in_base;
in lowp vec4     in_offs;
in mediump vec2  in_uv;
/* output */
INTERPOLATION out lowp vec4 vtx_base;
INTERPOLATION out lowp vec4 vtx_offs;
              out mediump vec2 vtx_uv;
#if TARGET_GL == GLES2
              out highp float fog_depth;
#endif
void main()
{
        vtx_base=in_base;
        vtx_offs=in_offs;
        vtx_uv=in_uv;
        high
[libretro INFO] Fatal error : shader compile fail
 in gl_CompileAndLink -> core/rend/gles/gles.cpp : 543
[libretro ERROR] 00:03:669 libretro/libretro.cpp:3230 E[COMMON]: DEBUGBREAK!
[libretro ERROR] 00:03:669 libretro/common.cpp:376 E[COMMON]: SIGSEGV @ a145a098 ... 0xa145a098 -> was not in vram (dyna code 0)
[libretro INFO] Fatal error : segfault
 in signal_handler -> core/libretro/common.cpp : 383
[libretro ERROR] 00:03:669 libretro/libretro.cpp:3230 E[COMMON]: DEBUGBREAK!

Full log: https://pastebin.com/A2eZFBhL

Any ideas?

**Comment by flyinghead** [comment]
It seems it's not detecting the Open GL flavor and version. Normally the log should show these two lines:
```
[libretro INFO] 00:02:671 hw/pvr/Renderer_if.cpp:102 N[PVR]: Creating Open GL per-triangle/strip renderer
[libretro INFO] 00:02:671 rend/gles/gles.cpp:414 N[RENDERER]: OpenGL ES 3.1 v1.r12p0-04rel0.f9ea82e6bf7f0bb7544260636f375425
```
instead I see this
```
[libretro INFO] 00:03:667 hw/pvr/Renderer_if.cpp:102 N[PVR]: Creating Open GL per-triangle/strip renderer
[95B blob data]
```
This detection is done in `findGLVersion()`. Perhaps try to put some printf's to figure out what's going on.

**Comment by MastaG** [comment]
Thanks, but that's a bit beyond my knowledge as I'm not familiar with the code base and opengl functions in general.

For the record I've first tried another emulator (parallel64) to ensure it's not retroarch causing the problems.
And I ran DK64 fine, so that's not it.

Then I tried a random older rev: f9f3249192f487b9d8de0a06531af331d4207fee
Which is working fine.

So instead I'll try to find the commit where it broke the GLES renderer.

**Comment by MastaG** [comment]
Well it started segfaulting here: https://github.com/libretro/flycast/commit/e0ca9a83ed90900780f5baf080a2a87edf5c6062

But with a different error:
mrt 31 21:12:05 odroidxu4 retroarch[19256]: [INFO] [Environ]: GET_PREFERRED_HW_RENDER.
mrt 31 21:12:05 odroidxu4 retroarch[19256]: [INFO] [Environ]: SET_HW_RENDER.
mrt 31 21:12:05 odroidxu4 retroarch[19256]: [INFO] Requesting OpenGLES2 context.
mrt 31 21:12:05 odroidxu4 retroarch[19256]: [libretro INFO] 00:00:213 hw/mem/_vmem.cpp:547 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
mrt 31 21:12:05 odroidxu4 retroarch[19256]: /usr/local/bin/retroarch: symbol lookup error: /home/odroid/.config/retroarch/cores/flycast_libretro.so: undefined symbol: __exp2_finite

**Comment by flyinghead** [comment]
Not sure what's going on here. Did you upgrade your OS version or compiler/stdlib recently?

The GLES renderer is working fine on Android (just checked the latest core just in case.) Can you try later commits to see if it helps?

**Comment by MastaG** [comment]
Yes, I did upgrade my OS to Fedora 32 which ships with gcc 10 and clang 10.
I tried both a clang and gcc build and they both segfault with the same message:

[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[libretro INFO] 00:03:947 hw/pvr/Renderer_if.cpp:102 N[PVR]: Creating Open GL per-triangle/strip renderer
[libretro INFO] 00:03:947 rend/gles/gles.cpp:414 N[RENDERER]: OpenGL version: (null)
[libretro ERROR] 00:03:947 libretro/common.cpp:376 E[COMMON]: SIGSEGV @ b3aff9c8 ... (nil) -> was not in vram (dyna code 0)
[libretro INFO] Fatal error : segfault
 in signal_handler -> core/libretro/common.cpp : 383
[libretro ERROR] 00:03:947 libretro/libretro.cpp:3230 E[COMMON]: DEBUGBREAK!
[libretro ERROR] 00:03:947 libretro/common.cpp:376 E[COMMON]: SIGSEGV @ a183893c ... 0xa183893c -> was not in vram (dyna code 0)
[libretro INFO] Fatal error : segfault
 in signal_handler -> core/libretro/common.cpp : 383
[libretro ERROR] 00:03:947 libretro/libretro.cpp:3230 E[COMMON]: DEBUGBREAK!


It's hard to find a working revision after: https://github.com/libretro/flycast/commit/e0ca9a83ed90900780f5baf080a2a87edf5c6062

I;ve also tried to build against mesa's and libglvnd headers vs the mali (ARM) GL headers..
But that also doesn't make a difference.

**Comment by flyinghead** [comment]
As far as I know gcc 10 hasn't been released yet, and clang 10 was released less than a week ago. You are deep in uncharted territory. I'd suggest reverting back to a stable OS version.

**Comment by MastaG** [comment]
Fixed it !
It wasn't caused by the compiler at all.
It was linking with mesa's libGLESv2 instead of the mali one I have installed in /usr/lib/mali.

I guess this was always the case, even before I upgraded to Fedora 32 (along with GCC/Clang to version 10).

But it's just that after some of your latest changes it now matters if it's linked against mesa vs mali's GLESv2 for the final binary.

Because in older revs (at least before https://github.com/libretro/flycast/commit/e0ca9a83ed90900780f5baf080a2a87edf5c6062) it worked fine when linking with mesa because it would just load the mali library when executing it (according to my ld config in /etc/ld.so.conf.d/00-mali.conf).

But after this revision, I now HAVE to link with mali's libGLESv2 during compilation or else it will segfault.

I do have pkgconfig configured to pick up the mali one when looking for the "glesv2.pc" package, however implementing pkgconfig in the Makefile just for looking up the GLESv2 library would be overkill ;)

I guess you can merge the PR since it's unrelated to this issue, and I'll simply add my own "-L/usr/lib/mali" flag to LDFLAGS when building it locally :)

**Comment by roslof** [comment]
FWIW: Same issue is occurring with current Retropie building from source. Issue started around the build @MastaG posted above. I actually thought it was related to recent VRAM changes. (I was wrong).

Not sure if Retropie scripts need to be adjusted to account for the change.

**Comment by MastaG** [comment]
@roslof 
I think I figured it out.

@flyinghead correct me if I'm wrong.
When the emulator is linking with the OpenGL library (in my case libGLESv2) it will now copy some symbols to the final flycast_libretro.so binary.

So you'll have to make sure that you link with the correct library (e.g. the one you're going to use when running the emulator).
So you cannot link with mesa's libGL/GLEsv2 and load some other (mali's libGLESv2) library when running the emulator.

Also in my case, when linking with mali's libGLESv2, I have to use GCC and disable link time optimzation when building.

So I have to run:

make ARCH=arm platform=odroid BOARD=ODROID-XU4 HAVE_LTCG=0

That will give me a working binary.

I've updated my PR to reflect this.

**Comment by MastaG** [comment]
In case anyone would to like to give it a go.
Here's a test build for the XU3/4 based on the latest master: https://mega.nz/#!P5VhAKIQ!1vLuyxGaYxQ1sNkxPhcXBuYHsWJ7UQ1mnG-noAnqT9Q

**Comment by flyinghead** [comment]
Good job figuring this out.

Flycast links with the GL library but only uses standard OpenGL functions. So it should work with any library named libGLESv2 in the LD_LIBRARY_PATH as long as it exports the needed OpenGL functions. If there's a function missing at load time you would get an `undefined symbol` error so there's something fishy somewhere.

**Comment by MastaG** [comment]
Well I took a look at the filesize of the final flycast_libretro.so binary and it seems it's 20MB large after stripping.

Should that be the case?

parallel_n64 is only 2MB.

Perhaps it's statically linking the libGLESv2 library ?

**Comment by flyinghead** [comment]
It's around 25MB on android so it's not surprising, and no, there's no way to link libGLESv2 statically

**Comment by MastaG** [comment]
Alright, then I'll leave it for now since it works :)

For the record LTO is now disabled by default on the XU3/4, so if the builder is using GCC and linking with mali's libGLESv2.. it should work :-)

But that should be the case for most image-builders.

Closing this, thanks Flyinghead!
