### ISSUE TITLE
Sideways rotation of certain games

### ISSUE THREAD

**Issue by curtistn73** [libretro/flycast#855]
The vertical games (Trizeal, Ikaruga, Under Defeat) are rotated sideways. I've tried the March31 build of Flycast on Linux and on macOS. Alas, both show the same problem. How to fix?

**Comment by flyinghead** [comment]
Are you using Mame roms in zip format?

**Comment by curtistn73** [comment]
Yes, I'm using Mame roms in zip format.

**Comment by flyinghead** [comment]
Normally these 3 games automatically rotate the RetroArch screen when run. 

You can rotate it manually in Settings > Video > Output > Rotate Video. I don't explain why it doesn't happen automatically.

**Comment by curtistn73** [comment]
I'm not using RetroArch, but the standalone Flycast executable/application instead.

**Comment by flyinghead** [comment]
Ah! For standalone, use https://github.com/flyinghead/flycast/issues instead.

Standalone doesn't have this automatic rotation feature, so you need to rotate manually in `Settings > Video > Rotate Screen 90°`

**Comment by curtistn73** [comment]
Ok, thanks for your help.
I found the ROT270 part in core/hw/naomi/naomi_roms.h for these games, and was wondering why the rotation didn't happen.

**Comment by flyinghead** [comment]
I backported the whole rom list from the libretro core but this flag is ignored right now. My bad. I'll fix this at some point.

**Comment by curtistn73** [comment]
No worries. I just found out that I can add
[TRIZEAL]
rend.Rotate90 = yes
to emu.cfg and it does the rotation automatically. (and other games, too).
Thank you for all your work! I'm so happy to finally play NAOMI games on my homemade arcade.
