### ISSUE TITLE
Vulkan crashes when "per pixel" option is selected

### ISSUE THREAD

**Issue by LuismaSP89** [libretro/flycast#858]
When using "per pixel" option under video settings, and then trying to run a game. The emulator just crashes. This doesn't happen with other options, only with "per pixel" under vulkan.

This option is working fine in opengl with no problems.

My specs:

Windows 10 x64
16GB DDR3
i7 4790k
GTX 970

**Comment by backgamon** [comment]
I always use "per pixel" with Vulkan...and no crash with this here.

Windows 10 Pro x64 (1909 18363.752)
I7 8700K@4.7Ghz
32Gb DDR4 3466Mhz{@3200Mhz XMP]
Gigabyte 2070 RTX 8G Oc [445.75]

**Comment by LuismaSP89** [comment]
Closing and reopening in the stand-alone issues tab.
