### ISSUE TITLE
Emulator hangs when pressing exit button

### ISSUE THREAD

**Issue by LuismaSP89** [libretro/flycast#859]
No matters what configuration is used, the emulator hangs all the time, I need to kill the process in order to close it. Else it works ingame with all my Dreamcast library.

Note: Using with the stand-alone executable, not integrated in the retroarch.

Specs:
Windows 10 x64
GTX 970
i7 4790k
16GB DDR3

**Comment by flyinghead** [comment]
For stand-alone issues, use this github instead: https://github.com/flyinghead/flycast/issues

Now, this problem has been fixed so get the latest build and report. Thanks.

**Comment by LuismaSP89** [comment]
Thanks a lot, I was using a build from 2 days ago, this fix was so fast implemented : )

Closing.
