### ISSUE TITLE
(Naomi/Atomiswave conversion) King of Fighters New Wave - glitches during round

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#86]
During the first stage, it will show a glitched out background at some point (without any of the sprites on top of it) and then crash. 

This is the crash log -

https://hastebin.com/zamedogaya.sql

**Comment by inactive123** [comment]
@flyinghead Update on this - after all the commits from today, I believe we have come closer to identifying the actual cause when this crash happens -

Now instead of crashing the entire emulator - it hangs instead - when it hangs - it shows only the background and none of the characters or HUD. I only see this in the log -

> Warning: data sent to TA prior to ListInit. Ignored

**Comment by flyinghead** [comment]
It might be an unusual/unsupported way to send graphic data to the TA/GPU. With the latest TA commits, instead of crashing we ignore it but obviously it's not the correct way to handle it.
I've been looking at what Test Drive Le Mans does in this area and hopefully this will help other games.

**Comment by flyinghead** [comment]
Same happens with upstream. Nothing in the log that would help, except the "data sent to TA" warning but it might just be a consequence of the actual problem.

**Comment by flyinghead** [comment]
@twinaphex See https://github.com/flyinghead/reicast-emulator/commit/517c225c39955f2518ea84dfaa3a8e2f415ad431 and let me know how it works for you.
This is still a hack and the problem remains: some frame sequences have missing geometry and sometimes the screen goes black for a few frames.

**Comment by inactive123** [comment]
Yeah thanks for the workaround. It fixes the crashes. As you say, the graphics glitch still happens and some frames of the screen go missing because of it.

I guess the real root of the problem - namely why the context is being lost - is what needs investigating, since it seems the TA context is being lost during this game when it shouldn't.

**Comment by flyinghead** [comment]
Atomiswave rom should work fine
