### ISSUE TITLE
fps in GDI is lower than with CDI (win10, gl)

### ISSUE THREAD

**Issue by weslyth** [libretro/flycast#860]
I have a CDI image of a DC game (MKG rerelease 1.06. See link below) which runs in flycast at 60 fps with upscaled resolution. Nothing wrong sofar! 

I also have a GDI image of the exact same game (and same version), but that one runs at 50 fps in flycast with the same settings as the above CDI-test (huh, that seems weird).

But if I run the GDI image in NullDC and Redream...then it plays fine at 60 fps (so the issue is not the GDI image). 

My only conclusion is that flycast is handling GDI images differently than CDI images (with a possible bug in fps logic). Is this even possible? Can someone redo this test?

I'm using the windows 10 64bit platform with video driver: GL (since my card doesn't fully support Vulkan).
I even tried setting broadcast to NTSC or using native resolution, but the GDI then still plays at 50fps (and CDI at 60 fps).

**Comment by flyinghead** [comment]
(I edited your post to clean it up but I got the info I needed)

If you set Broadcast to Default, it will often default to PAL, hence the 50 FPS. I believe Redream defaults to using VGA so it will be 60 FPS. Not sure about nullDC.

If you set Broadcast to NTSC (and restart) you will get 60 FPS, same if you choose VGA.

**Comment by weslyth** [comment]
> (I edited your post to clean it up but I got the info I needed)
> 
> If you set Broadcast to Default, it will often default to PAL, hence the 50 FPS. I believe Redream defaults to using VGA so it will be 60 FPS. Not sure about nullDC.
> 
> If you set Broadcast to NTSC (and restart) you will get 60 FPS, same if you choose VGA.

I thought so too. But even with setting broadcast to NTSC (and using VGA), the GDI then still plays at 50fps (and CDI at 60 fps)

**Comment by flyinghead** [comment]
If I set Cable to TV (Composite), Region to USA and Broadcast to NTSC, i get 60 FPS in game. Same for VGA.

Are you loading a savestate? If that's the case the above settings are ignored and the ones from the savestate are used instead.

**Comment by weslyth** [comment]
> If I set Cable to TV (Composite), Region to USA and Broadcast to NTSC, i get 60 FPS in game. Same for VGA.
> 
> Are you loading a savestate? If that's the case the above settings are ignored and the ones from the savestate are used instead.

You are right. After deleting all state files I'm getting 60 fps with GDI now aswell!
Really strange that:
- the configurations in the UI didn't reflect the settings in the states 
- the settings in the states were not affecting the CDI version too

Thanks @flyinghead Lets close this ticket! 👍
