### ISSUE TITLE
Crazy Taxi black textures when Texture Upscaling is enabled

### ISSUE THREAD

**Issue by jvhellraiser** [libretro/flycast#862]
i been having this crazy issue and i am not sure whats going on,
i get black textures out of Flycast maybe you guys know whats going on?
![Annotation 2020-04-08 210804](https://user-images.githubusercontent.com/16488761/78847671-77a11480-79dd-11ea-9d19-ae9bb9d8bbaa.jpg)

Build : flycast-win_x64-fast-55b26fa28f2b53d6e20f8383c9711b4bed6651d9.zip

settings are : 
Horizontal stretching = 142
Texture Upscaling = 2
Frame skip = 1

**Comment by flyinghead** [comment]
This is due to Texture Upscaling. This setting should only be used with pixelized 2D games.

**Comment by jvhellraiser** [comment]
Oh ok  thanks  this seems to fix the problem.
