### ISSUE TITLE
I can't change any service mode settings for SNK Atomiswave games

### ISSUE THREAD

**Issue by Panderner** [libretro/flycast#867]
When I change any settings at service mode in Any SNK Games on a Atomiswave hardware. I'm stuck when I exiting the service mode after I changed the settings.

**Comment by blisstik** [comment]
Here’s the secret trick. Don’t exit service mode via menu but rather quit retroarch. If it’s retropie, simply use start plus select. 

It will write those nvmem files. Save them for future use. Now you can have English games for AW.

**Comment by Panderner** [comment]
I'm using Android phone but I don't want to exit Retroarch. It might have issues for service mode

**Comment by flyinghead** [comment]
This should be fixed in build 6a940fd. Please test and report

**Comment by Panderner** [comment]
I̶ ̶u̶p̶d̶a̶t̶e̶d̶ ̶t̶o̶ ̶l̶a̶t̶e̶s̶t̶ ̶b̶u̶i̶l̶d̶ ̶b̶u̶t̶ ̶i̶t̶ ̶s̶t̶i̶l̶l̶ ̶n̶o̶t̶ ̶f̶i̶x̶e̶d̶
I updated to latest build it's now working! I'm closing now
