### ISSUE TITLE
(Naomi/Atomiswave conversion) Samurai Showdown VI - Graphics glitches/black screen during fight

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#87]
Plenty of bugs here -

Using this video for reference -

https://www.youtube.com/watch?v=RB91t7-ifs4

Should normally (probably) show Press Start or Insert Coin OSD text here -

![image](https://user-images.githubusercontent.com/1075274/42134696-43f5a3c0-7d41-11e8-8d28-8b029ae44ac6.png)

No background color here it seems -

![image](https://user-images.githubusercontent.com/1075274/42134699-4acc3cd6-7d41-11e8-8304-87ad5571e85b.png)

World map stage before fight doesn't render properly -

![image](https://user-images.githubusercontent.com/1075274/42134706-59582e72-7d41-11e8-8e36-62402633655b.png)

Once ingame, the game just outputs black. It responds to input and you can hear sound but you can't see anything.

HUD, sprites and backgrounds all seem to be not being drawn.

**Comment by inactive123** [comment]
Progress in Samurai Shodown VI now too (a Naomi-to-Atomiswave conversion) as of this commit -

https://github.com/flyinghead/reicast-emulator/commit/cbaaaaf970f7047d8a0bbd7a5648d3f0ec9b504e

 the background is beginning to appear now -

![image](https://user-images.githubusercontent.com/1075274/42223264-a40a4030-7ed7-11e8-96d6-ad9fdae8f1af.png)

Still no foreground sprites on top of the background though (the player characters, HUD, etc.)

**Comment by inactive123** [comment]
Hmm, it might have been only one particular stage that shows this background though - some of the others still show nothing but a black screen.

**Comment by blisstik** [comment]
This is also true for non-OIT core compiled in ARM.

**Comment by inactive123** [comment]
Yeah the cause of this issue is still unknown.

**Comment by inactive123** [comment]
I get much better results now with this game @flyinghead - 

![image](https://user-images.githubusercontent.com/1075274/45000240-8a629480-afc3-11e8-8ee3-61e485a07013.png)

You can still see some layering issues perhaps but sprites show now at least and so do most of the UI elements and 2D graphics.

**Comment by inactive123** [comment]
You can still see some tiles missing in some of the sprites -there might also still be some other glitches. Not sure which of the commits was responsible for these improvements in rendering - maybe a combination of the recent fogging commits along with the changes to pvr_mem.cpp.

**Comment by flyinghead** [comment]
The vram mapping change in pvr_mem.cpp is probably helping a lot here. I've seen improvements in several NAOMI games.
However this game is still mostly black for me...

**Comment by flyinghead** [comment]
After closer look, the main issue with this game seems to be a depth issue.
I'm seeing Z values from 1e-5 (background plane) to 1e30 (! for sprites)
So the commit https://github.com/libretro/reicast-emulator/commit/8f5706bbbae3f79d5525bf6d94753aba70ebef18 does help a lot by clamping very high Z values.
But there's probably some depth sorting issues as a result.

**Comment by flyinghead** [comment]
I came up with a new setting to scale down (or up) Z values: https://github.com/reicast/reicast-emulator/commit/f202b3b14396d53382a576be8b16c11fa7c32aba

Using 1e26 for the scale, almost everything seems to be displayed correctly:
![samurai](https://user-images.githubusercontent.com/16261910/45045012-1501cd00-b072-11e8-96ea-1030e4bcfccb.png)
![samurai2](https://user-images.githubusercontent.com/16261910/45045015-19c68100-b072-11e8-8407-b75ac9d919be.png)
![samurai3](https://user-images.githubusercontent.com/16261910/45045040-23e87f80-b072-11e8-8ffe-05c9fa485774.png)

**Comment by blisstik** [comment]
This renders correctly using the new option but still very choppy audio, causing FPS to be very slow. On non-OIT ARM cpu.

**Comment by furiadeoso** [comment]
I've tried this game and I can confirm that it's getting low fps during fights. Guilty gear series is perfect with the same windows pc.

**Comment by barbudreadmon** [comment]
Closing since nowaday we don't recommend those dumps/conversions.
