### ISSUE TITLE
Vertical option doesn't work correct 

### ISSUE THREAD

**Issue by mrcmunir** [libretro/flycast#875]
Seems it's inverted backwards
Tested in Ikaruga 
![Screenshot from 2020-04-19 16-10-30](https://user-images.githubusercontent.com/1274014/79690618-92844c00-825b-11ea-94af-9947fac2f94d.png)

Platform : nvidia jetson nano 
S.O Linux AARCH64

**Comment by flyinghead** [comment]
Just tested it and it rotates fine on my end. Please provide more details on your platform/config/game.

**Comment by mrcmunir** [comment]
It's Nvidia jetson nano with Opengl desktop core ¿ARM or driver specific?. 
I try all diferents modes and not helped.
![Screenshot from 2020-04-19 17-45-22](https://user-images.githubusercontent.com/1274014/79692511-cfedd700-8265-11ea-8e68-06d661afc6c3.png)
Also happen in vulkan renderer.

**Comment by barbudreadmon** [comment]
> I try all diferents modes and not helped.

I think that's the main problem here, you try a lot of things instead of following the instructions on the screen (bottom left corner).
Follow those instructions, reset your configuration to default (because you probably did a mess in there), and it should work properly : flycast should auto-rotate properly naomi games if they are from MAME romsets, **there should be no need to tinker with anything**.

**Comment by mrcmunir** [comment]
> I try all diferents modes and not helped.
> 
> I think that's the main problem here, you try a lot of things instead of following the instructions on the screen (bottom left corner).
> Follow those instructions, reset your configuration to default (because you probably did a mess in there), and it should work properly : flycast should auto-rotate properly naomi games if they are from **MAME** **romsets,** there should be no need to tinker with anything.

I reset retroarch configuration and it has this problem to rule out that it if cause was some custom configuration.
It's kind of weird I wanted to wait a few months to see if it was temporary but I've always had this problem.
And Now I found what happen it's with .bin .dat images conversion. Sorry for that.
