### ISSUE TITLE
paranoia crash at start

### ISSUE THREAD

**Issue by soredake** [libretro/flycast#878]
Archlinux, retroarch 1.8.5
game https://www.moddb.com/mods/paranoia/downloads/dreamcast-paranoia
```
❯ retroarch
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
[CDROM] No sg devices found and sg kernel module is not loaded.
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
terminate called after throwing an instance of 'SH4ThrownException'
fish: “retroarch” terminated by signal SIGABRT (Abort)
```

**Comment by flyinghead** [comment]
This is one of the few cases where you need to Force Windows CE mode in the core settings. This is true for all Half-Life mods.

**Comment by MastaG** [comment]
nice game :)

**Comment by soredake** [comment]
Paranoia mod seems to work fine now with default settings.

**Comment by flyinghead** [comment]
Yes, Flycast now has a more robust way to detect Windows CE games and the Force Windows CE option is no longer needed.

**Comment by soredake** [comment]
Closing then!
