### ISSUE TITLE
[Bug]Super Street Fighter II X for Matching Service (Japan)

### ISSUE THREAD

**Issue by Immersion95** [libretro/flycast#888]
The Character Select Screen is really really slow.
I tried to change the regions, dc_flash to the japanese one, video signal but it doesn't solve anything.

Changing the bios to HLE makes it work correctly but I think it would be great to investigate the behavior with the real bios.

Apparently the issue is there with a real dreamcast and backups (CDR/GDEMU/USB-GDROM) :

[Example 1](https://www.reddit.com/r/dreamcast/comments/98fb1c/anyone_know_if_the_nobsdc_rip_of_super_street/)
[Example 2](https://www.reddit.com/r/dreamcast/comments/4cyx77/super_street_fighter_ii_x_jpn_character_select/)

I have a real copy and I remembered that it didn't work correctly on my PAL DC but only on my JAP DC. Unfortunately the PAL DC only accepts PAL games now....

Please try it with an unmodified DC backup (Redump) and not the modified translated version.

**Comment by flyinghead** [comment]
I can't reproduce this issue with the GDI I have, which I believe is the original JP version. I tried both standalone and the lr the core, threaded rendering on/off, etc. It stays at 60 FPS on the character select screen.

**Comment by Immersion95** [comment]
I'm on Win 10 x64, I tested the CHD version with the Redump dump.

http://redump.org/disc/69674/

HLE BIOS OFF

Edit : Tested with the uncompressed CUE version and it the same behavior
Edit 2 : Tested on a clean install on Windows & Android and the same thing happen. dc_boot.bin & dc_flash with the correct md5.

**Comment by flyinghead** [comment]
The one I'm using is T1235M (version V1.003) so that's probably why I can't reproduce the problem.

**Comment by Immersion95** [comment]
> T1235M

Are you sure ? This is the code for Vampire Chronicle.

http://redump.org/disc/42518/

Can I send you a link by mail with my dump ?

I would also like to try yours.

**Comment by flyinghead** [comment]
Yes, wrong game. My bad

**Comment by flyinghead** [comment]
When testing the correct game, the problem is much easier to reproduce :P

It's a consequence of flycast patching the disc at boot to fool the BIOS into thinking that the game supports all regions. This doesn't happen with HLE since there's no bios to fool. I wonder if this patching is needed when the user sets the correct BIOS region.

**Comment by Immersion95** [comment]
> When testing the correct game, the problem is much easier to reproduce :P
> 
> It's a consequence of flycast patching the disc at boot to fool the BIOS into thinking that the game supports all regions. This doesn't happen with HLE since there's no bios to fool. I wonder if this patching is needed when the user sets the correct BIOS region.

The option to change region isn't really faithful unlike Mednafen for example.

Would it be possible to have these options in Region ?

Region Free -->Current behavior
Japan -->Would use no hack & correct dc_flash.bin (5f92bf76)
Europe -->Would use no hack & correct dc_flash.bin (b7e5aeeb)
USA-->Would use no hack & correct dc_flash.bin (c611b498)

**Hashes :**
https://github.com/retropie/retropie-setup/wiki/Dreamcast

As of today, Flycast only requests the USA dc_flash.bin (or the one named dc_flash.bin as there is no CRC checks) and hacks it to be region free.

It would be great to make it use the following naming :

- dc_flash.bin (no change as it would be compatible with everyone)
- dc_flash_jp.bin (optional)
- dc_flash_eu.bin (optional)

**Comment by flyinghead** [comment]
dc_flash.bin is no longer needed and there's nothing in it that cannot be recreated. This file will disappear soon.

That being said, I don't think the patch hack is still needed since flycast automatically selects the BIOS region depending on the game being run. So there's currently no way to run a game with an unsupported BIOS region.

**Comment by Immersion95** [comment]
> dc_flash.bin is no longer needed and there's nothing in it that cannot be recreated. This file will disappear soon.
> 
> That being said, I don't think the patch hack is still needed since flycast automatically selects the BIOS region depending on the game being run. So there's currently no way to run a game with an unsupported BIOS region.

Great to know !

What is the current use of the Region option then ?

Would it be possible to disable this patch hack and force the region according to the choice of that option ? It would be a nice way to test if the patch is needed.

Also adding an Auto option :

- Default : Current behavior
- Auto : Automatically selects the BIOS region depending on the game being run
- Japan : Force Japan region (other regions shouldn't work)
- Europe : Force Europe region (other regions shouldn't work)
- USA : Force USA region (other regions shouldn't work)

**Comment by flyinghead** [comment]
The current behavior is to use the Region option value if supported by the game. If not supported, or if Default is selected, the first supported region is selected using this order of preference: USA, Europe, Japan. I prefer to avoid games not working because the user made the wrong option choice.

**Comment by Immersion95** [comment]
> The current behavior is to use the Region option value if supported by the game. If not supported, or if Default is selected, the first supported region is selected using this order of preference: USA, Europe, Japan. I prefer to avoid games not working because the user made the wrong option choice.

I understand but it is still using that patch hack in that situation as SSFX doesn't work correctly if Japan is selected.

**Comment by flyinghead** [comment]
region patch is now disabled

**Comment by Immersion95** [comment]
Thanks a lot, will try as soon as it's built tomorrow :)

**Comment by Immersion95** [comment]
Tested it with the latest core on Android and it fixed the issue :)

**Comment by ghost** [comment]
> Tested it with the latest core on Android and it fixed the issue :)

Hello this terrible slowdown also happens on terra onion mode, gdemu and USB gdrom on real hardware, is there a way to fix it? Patching the region or using a different gdi release?
