### ISSUE TITLE
Samurai Spirits - Frame-skipping issues before reset or changing the option

### ISSUE THREAD

**Issue by pjft** [libretro/flycast#889]
Hi all,

Apologies for the "vague" report here, but this is as far as I got with troubleshooting it. I hope it helps. I was looking through the code but I got nowhere, alas. I might even be a RA bug, but raising it here.

I'm running Flycast on a Pi4, and while most games run well, Samurai Spirits VI (arcade) has an interesting behavior which I narrowed down to the following. I have Threaded Rendering enabled, and there's a game core options file that sets Frameskip at 2, as that seems to be the proper compromise for speed on the Pi4. 

I just built it from source today and the same behavior happens:

- If I start the game from scratch (with the core option file with the frameskip options set) it will stutter a lot when getting to the actual battle. If you let it run and get to the attract mode battle, you'll see it play somewhat slow, and stuttering (audio and graphics) when some animations occur. It's fairly noticeable on the Pi4, especially when the blue character punches the other one after being knocked out in the air, and there's an explosion animation.
- If I _reset_ the game from within the RA menu, it will now run fine (at least, better) with the right frame-skip. The same happens if I change the frame-skip option in runtime by opening the menu (for instance, moving it to 3, and then back to 2), but doesn't seem to do so on load.

This initially also happened if I went to the core options menu and changed _some_ of the options, but it was never scientific. I changed an option and then the game started running faster - filtering, frameskip, etc - but then after saving the core options, exiting the emulator and opening it again it would be slow again.

Could it be that either the frame-skip option is not being _set_ on loading the per-game core options file, or that Framskipping is disabled _until something happens_? Or something more awkward?

Let me know how I can help troubleshoot it, if it helps.

Thanks.

**Comment by barbudreadmon** [comment]
> game core options file that sets Frameskip at 2, as that seems to be the proper compromise for speed on the Pi4.

Are you using the MAME version of the romset ? That level of performance looks really crappy, i would need to power up my odroid n2 again to check but iirc it was running full speed with upscaling on it.

**Comment by pjft** [comment]
Hi! To the best of my knowledge, I am - it's a samsptk.zip ROM file from a MAME romset. Should I be looking for something more specific? Are there other versions that I should be aware of - or trying out as an alternative?

All the other NAOMI and Atomiswave games run pretty much at solid speed without frameskip on the Pi4 if I recall correctly from the ones I tested -- other than Metal Slug 6 at the end of level 1 when all the gigantic robots come walking through (that one doesn't work even with frameskip, but it lasts only 30 seconds).

**Comment by barbudreadmon** [comment]
I confirm my previous statement : the game is running at full speed without frameskip and internal resolution set to 1280x960 on my odroid n2.

It does sound like you are using the right romset so i guess it's just that the pi4 is far slower than the odroid n2. Some things that might be worth trying : 
- make sure your mesa drivers & flycast core are up to date (i.e from sources), a workaround for the broken pi4 gpu drivers was removed recently, it was most likely affecting performance
- maybe try overclocking your cpu/gpu, there was some talks about pi4 overclocking in https://retropie.org.uk/forum/topic/25913/good-cases-for-the-pi4 recently

**Comment by pjft** [comment]
@barbudreadmon Thanks for the pointers - I'll look into the mesa drivers specifically and the other remarks especially for Metal Slug 6, as that does seem to suffer the most. I am overclocked and I just updated Flycast prior to compiling.

To clarify, as I might have come across incorrectly: the remark I was making was about frame-skipping not seeming to be active (or loaded from the core-options file?) unless I explicitly restart the core from within the RA menu, or explicitly change the core option in runtime - even if I set it back to the value it was before.

When I open the RA menu and restart the core, or I change the frame-skipping option explicitly, it will work. That was the main thing I wanted to bring up here, as this might just be a simple initialization thing.

**Comment by barbudreadmon** [comment]
Oops, yes, sorry i was just curious about the performance issue, which seemed pretty weird. I think the metal slug 6 slowdown is known, and might even happen on original pcb tbh (wouldn't be the first time for a metal slug game).

About the frameskip issue, i think it's as you said : the setting is ignored at boot.

Edit : no, the mslug6 issue doesn't happen on pcb (https://www.youtube.com/watch?v=fZUtzV_w7RU), but the slowdown is known in flycast (https://github.com/libretro/flycast/issues/743)

**Comment by flyinghead** [comment]
The above commit should fix the frame-skipping setting issue

**Comment by pjft** [comment]
Thanks both. 

@barbudreadmon ah, hadn't caught that issue already with my initial searches - thanks for bringing it up. I'll try out those settings, though it's a known issue.

@flyinghead Thanks for the reponse - I'll test it and report back!

**Comment by pjft** [comment]
Thank you both, this seems to have been solved now! Well spotted @flyinghead - hopefully it doesn't have any unintended side-effects.
