### ISSUE TITLE
NBA 2K - Black/blue screen after FMV title screens

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#89]
Also mentioned here -

https://github.com/reicast/reicast-emulator/issues/1168

> I just tested NBA 2K (USA version). After the FMV copyright/intro screens there is no picture. With cable type set to TV (RGB) it just displays a blue screen, with cable type set to VGA (RGB) it displays a black screen. You can hear the sound and it will react to button input.

**Comment by inactive123** [comment]
This gets us ingame now -

https://github.com/flyinghead/reicast-emulator/commit/e7d1688ae54618c7711b0d28927794890b5eb88b

However, once it gets ingame it starts becoming very slow (like 4fps) before it seems to 'hang'. The FPS meter of RetroArch still iterates so the emulator itself has not hanged but video update and game progression seem to have stopped entirely.

**Comment by flyinghead** [comment]
I've tested NBA 2K, NBA 2K2 and NFL 2K2 and they all have low framerate issues due to translucent modifier volumes. 
@twinaphex you might want to add a game-specific setting to disable them.

**Comment by inactive123** [comment]
With this improvement to the OIT renderer, it seems much faster now -

https://github.com/libretro/reicast-emulator/commit/20c509c65d0d92704dbe7d25d9ac714fc056363e
