### ISSUE TITLE
Lr-flycast - Retropie 4.6 - Grandia 2 missing sound effects

### ISSUE THREAD

**Issue by zasxxx** [libretro/flycast#894]
Hi,

Playing Grandia 2 on lr-flycast some sounds effects are missing, mostly during battles (example: footsteps, hitting and special attacks).

I have: 
installed it from source (today 17th may)
DSP "ON".

Raspberry pi4 (overclocked)
Retropie 4.6

Thanks,
Best Regards.

**Comment by flyinghead** [comment]
It's was an issue with the DSP. It should be fixed in the build.

**Comment by zasxxx** [comment]
Updated from source and it's fixed.

Thanks!

**Comment by flyinghead** [comment]
Closing as fixed

**Comment by jozaaaa** [comment]
Thank you @flyinghead really appreciate the fix for this issue/game
