### ISSUE TITLE
Spawn: Into the Demon's Hand, cannot select game modes

### ISSUE THREAD

**Issue by Dinierto** [libretro/flycast#896]
I've never played this in the arcade but surely this is not expected behavior.  Running in Windows 10 64 bit.

Also, I checked the compatibility list and this game is listed as OK, I also noticed that neither DoDonPachi game loads, nor does Espgaluga and I don't see those on the compatibility list.  All ROMs are the latest MAME versions.

**Comment by flyinghead** [comment]
Game modes other than Boss Attack mode are only available when multiple cabinet are networked together.

DoDonPachi and Espgaluga run on Cave hardware, not Naomi.

**Comment by Dinierto** [comment]
Ahh thank you, kind of a bummer but it's good to know it's not a bug in the game 😃
