### ISSUE TITLE
Prevent date/time screen from appearing every launch

### ISSUE THREAD

**Issue by hooby3dfx** [libretro/flycast#9]
The way the Android app code resolved this way by setting `settings.dreamcast.RTC` during init to the system time.

A good long term solution would be to have the core do this in a portable way upstream.

A short term fix for libretro would be to set this during libretro init.

The code used to calculate the time is here: https://github.com/reicast/reicast-emulator/blob/master/shell/android/src/com/android/util/DreamTime.java

Note that it still needs to be correctly set once by the user, but after that it will stop asking. 
This is also contingent on the host device having the correct date/time.

**Comment by wingedonezero** [comment]
Same issue very annoying. Would be nice if it set it self to the time and date of your desktop like mentioned above. Ive seen some mention on forums changing your bios to another but i have tryed multiple dumps and non fix the problem.

**Comment by raelgc** [comment]
Same here. Tried all workarounds mentioned, but no lucky.

**Comment by inactive123** [comment]
This is now finally fixed -

https://github.com/libretro/reicast-emulator/issues/40
