### ISSUE TITLE
(Naomi) No analog stick support + shoulder buttons

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#90]
Shoulder buttons and analog stick support should still be implemented for Naomi.

This currently prevents games from being controllable like Monkey Ball and Virtua Tennis 2/Power Smash 2.

**Comment by inactive123** [comment]
Analog stick support should now be implemented thanks to @barbudreadmon.

What about shoulder buttons/any additional buttons? Are we still missing anything here?

**Comment by barbudreadmon** [comment]
@twinaphex The Sega Jamma I/O board only supports 4 axis, and i hooked them all. 
The only issue is that they were used differently on a per-game basis on the original hardware, some example : 
- Virtua Tennis will use 2 axis for each player
- Crazy Taxi will use 3 axis for the player (steer + 2 pedals)

At the moment, the implementation assigns 2 axis to the left stick of each controller.
One way to fix this would be to define different layout on a per-game basis, basically the same way i handle things in fba. I would need some kind of unique game identifier to do that, do you know if there is anything like that in reicast ?

**Comment by barbudreadmon** [comment]
By the way, both Virtual Tennis are using dpads actually (not sure why there was previously an issue with controls, the second jamma I/O board maybe ?). 
Besides racing game, shooting game, and monkey ball, there are not that many games using analogs it seems.
