### ISSUE TITLE
Core Option for downscaling 2d elements

### ISSUE THREAD

**Issue by sjftech** [libretro/flycast#900]
Hi,

So I previously asked for the 15khz Naomi option to be added thinking it would help with forcing 240p for some Capcom fighting games as the sprites do not scale very well to outputting at 480p and look terrible at 240p however this didn't have the desired effect.

Would it be possible to add minus values to the xBRZ scaling you have for 2d elements? So that we downscale them by half to effectively have them dispaying at 320x240 while everything else is at 640x480 as would be the case on a real Dreamcast? I know there is smoothing going on with the xBRZ filter but it might work out well with a nice shader on top? Unless there is way of doing linear/nearest scaling only for 2d elements?

**Comment by flyinghead** [comment]
There's no easy way to identify 2d elements in a game. Each game is different.

However I don't understand why you'd want to downscale them (and xBRZ is for upscaling only). All Naomi games are supposed to run at 480p even when they use low-resolution textures. Are you seeing graphical errors?

**Comment by sjftech** [comment]
It's basically due to sprite scaling in a lot of the Capcom fighting games where the sprites are scaled pretty badly because as far as I'm aware on original hardware they were displayed at 240p where as the 3d elements and UI were at 480i.

I think this goes hand in hand with flycast not switching resolution dependent on the game as the original Marvel Vs Capcom is a 240p game and is displayed at 480i.

I'm just trying to play some of these older fighting games with the nice chunky sprites I remember and flycast is my only option right now :)

**Comment by flyinghead** [comment]
Again, all Naomi games are designed to run at 480p and most can also run at 480i. wldkickspw is the only Naomi game I know of that runs at 240p when the 15k switch is on.

Also there's no such thing as displaying 3D elements at 480i and 2D sprites at 240p. The naomi gpu output framebuffer resolution is 640x480 and is displayed as is.

If you're seeing something that doesn't look right, a screenshot or two would help.

**Comment by cobhc2019** [comment]
Not required.
