### ISSUE TITLE
not able to run flycast with pgo/gdb

### ISSUE THREAD

**Issue by ghost** [libretro/flycast#905]
I get a segfault when trying either. I compile without lto. Have you noticed this issue?

**Comment by flyinghead** [comment]
Not sure about pgo but flycast uses SIGSEGV a lot for various uses. If you use gdb, make sure to set it to ignore SIGSEGV signals:
```
handle SIGSEGV nostop noprint
```

**Comment by ghost** [comment]
Thanks, I'll give that a go later today. I'm interested in profiling to find hotspots on aarch64 to see why we tend to get audio stuttering when things get busy, otherwise the gameplay is quite smooth. Thanks again for your great work on this core!

**Comment by ghost** [comment]
that worked, thanks
