### ISSUE TITLE
Virtua cop 2 lightgun mouse not working

### ISSUE THREAD

**Issue by meeuuh92** [libretro/flycast#913]
Hi,

My dolphin bar works fine with gun games on dreamcast/naomi games, but for virtua cop 2, the mouse mode is not working (the target crosshair of mouse is moving, but the one of the game is fixed..). I'm doing something wrong ? 

Regards,

**Comment by flyinghead** [comment]
There seems to be an issue when using lightguns with this game.

**Comment by flyinghead** [comment]
This should be fixed by https://github.com/libretro/flycast/commit/0f29d7e14a716b88c7a8037f22799e71da5b8607

**Comment by meeuuh92** [comment]
Cool. I will test it tomorrow.

Regards,

After test, the lightgun works fine.. But, the game is a little bit laggy... It's because a wince game and i need a configuration more powerfull  ?
