### ISSUE TITLE
Segmentation fault due to glsm.c modifications (buildroot,libreelec linked ?)

### ISSUE THREAD

**Issue by magicseb** [libretro/flycast#918]
Since commit 4cf6c1f92c4ba9e53dc59deaaf3b5e7b3818c7d1 [Switch] Initial Port ]
my build on rpi4 can't run anymore due to a segmentation fault

I found out why.
I have made this patch to fix it

I hope this help.

`--- a/core/libretro-common/glsm/glsm.c	2020-03-26 18:11:40.000000000 +0100
+++ b/core/libretro-common/glsm/glsm.c	2020-03-26 18:11:40.000000000 +0100
@@ -233,22 +233,6 @@
 /*
  *
  * Core in:
- * OpenGL    : 2.0
- * OpenGLES  : 2.0
- */
-void rglGetIntegerv(GLenum pname, GLint * data)
-{
-#ifdef GLSM_DEBUG
-   log_cb(RETRO_LOG_INFO, "glGetIntegerv.\n");
-#endif
-#if defined(HAVE_OPENGL) || defined(HAVE_OPENGLES)
-   glGetIntegerv(pname, data);
-#endif
-}
-
-/*
- *
- * Core in:
  * OpenGL    : 3.2
  * OpenGLES  : 3.0
  */
@@ -262,22 +246,6 @@
 /*
  *
  * Core in:
- * OpenGL    : 2.0
- * OpenGLES  : 2.0
- */
-const GLubyte* rglGetString(GLenum name)
-{
-#ifdef GLSM_DEBUG
-   log_cb(RETRO_LOG_INFO, "glGetString.\n");
-#endif
-#if defined(HAVE_OPENGL) || defined(HAVE_OPENGLES)
-   glGetString(name);
-#endif
-}
-
-/*
- *
- * Core in:
  * OpenGL    : 3.2
  * OpenGLES  : 3.0
  */
@@ -2106,69 +2074,6 @@
 /*
  *
  * Core in:
- * OpenGL    : 2.0
- * OpenGLES  : 2.0
- */
-void rglTexParameteri(GLenum target, GLenum pname, GLint param)
-{
-#ifdef GLSM_DEBUG
-   log_cb(RETRO_LOG_INFO, "glTexParameteri.\n");
-#endif
-#if defined(HAVE_OPENGL) || defined(HAVE_OPENGLES)
-   glTexParameteri(target, pname, param);
-#endif
-}
-
-void rglTexParameterf(GLenum target, GLenum pname, GLfloat param)
-{
-#ifdef GLSM_DEBUG
-   log_cb(RETRO_LOG_INFO, "glTexParameterf.\n");
-#endif
-#if defined(HAVE_OPENGL) || defined(HAVE_OPENGLES)
-   glTexParameterf(target, pname, param);
-#endif
-}
-
-void rglGetFloatv(GLenum pname, GLfloat* params)
-{
-#ifdef GLSM_DEBUG
-   log_cb(RETRO_LOG_INFO, "glGetFloatv.\n");
-#endif
-#if defined(HAVE_OPENGL) || defined(HAVE_OPENGLES)
-   glGetFloatv(pname, params);
-#endif
-}
-
-void rglClearStencil(GLint s)
-{
-#ifdef GLSM_DEBUG
-   log_cb(RETRO_LOG_INFO, "glClearStencil.\n");
-#endif
-#if defined(HAVE_OPENGL) || defined(HAVE_OPENGLES)
-   glClearStencil(s);
-#endif
-}
-
-/*
- *
- * Core in:
- * OpenGL    : 2.0
- * OpenGLES  : 2.0
- */
-void rglTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width,
-	GLsizei height,GLint border, GLenum format,	GLenum type, const GLvoid * data)
-{
-#ifdef GLSM_DEBUG
-   log_cb(RETRO_LOG_INFO, "glTexImage2D.\n");
-#endif
-#if defined(HAVE_OPENGL) || defined(HAVE_OPENGLES)
-   glTexImage2D(target, level, internalformat, width, height, border, format, type, data);
-#endif
-}
-
-/*
- *
- * Core in:
  * OpenGL    : 4.3
  * OpenGLES  : 3.1
  */
@@ -2671,23 +2576,6 @@
 #endif
 }
 
-/*
- *
- * Core in:
- * OpenGL    : 2.0
- * OpenGLES  : 2.0
- */
-void rglReadPixels(GLint x, GLint y, GLsizei width, GLsizei height,
-   GLenum format, GLenum type, GLvoid * data)
-{
-#ifdef GLSM_DEBUG
-   log_cb(RETRO_LOG_INFO, "glFinish.\n");
-#endif
-#if defined(HAVE_OPENGL) || defined(HAVE_OPENGLES)
-   glReadPixels(x, y, width, height, format, type, data);
-#endif
-}
-
 /* GLSM-side */
 
 static void glsm_state_setup(void)
 
 --- a/core/libretro-common/include/glsm/glsmsym.h	2020-03-26 18:11:40.000000000 +0100
+++ b/core/libretro-common/include/glsm/glsmsym.h	2020-03-26 18:11:40.000000000 +0100
@@ -188,14 +188,6 @@
 #define glFlushMappedBufferRange    rglFlushMappedBufferRange
 #define glClientWaitSync            rglClientWaitSync
 #define glDrawElementsBaseVertex    rglDrawElementsBaseVertex
-#define glTexParameteri             rglTexParameteri
-#define glTexParameterf             rglTexParameterf
-#define glGetFloatv                 rglGetFloatv
-#define glClearStencil              rglClearStencil
-#define glTexImage2D                rglTexImage2D
-#define glReadPixels                rglReadPixels
-#define glGetIntegerv               rglGetIntegerv
-#define glGetString                 rglGetString
 
 const GLubyte* rglGetStringi(GLenum name, GLuint index);
 void rglTexBuffer(GLenum target, GLenum internalFormat, GLuint buffer);
@@ -492,14 +484,6 @@
  	const GLint *value);
 void rglProvokingVertex(	GLenum provokeMode);
 void rglDrawRangeElementsBaseVertex(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, GLvoid *indices, GLint basevertex);
-void rglTexParameteri(GLenum target, GLenum pname, GLint param);
-void rglTexParameterf(GLenum target, GLenum pname, GLfloat param);
-void rglGetFloatv(GLenum pname, GLfloat* params);
-void rglClearStencil(GLint s);
-void rglTexImage2D(GLenum target,GLint level, GLint internalformat, GLsizei width, GLsizei height,GLint border, GLenum format,	GLenum type, const GLvoid * data);
-void rglReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * data);
-void rglGetIntegerv(GLenum pname, GLint * data);
-const GLubyte* rglGetString(GLenum name);
 
 RETRO_END_DECLS
 

`

**Comment by magicseb** [comment]
[0009-glsmfix.patch.txt](https://github.com/libretro/flycast/files/4808794/0009-glsmfix.patch.txt)

**Comment by barbudreadmon** [comment]
Well, looking at retropie forum, people are able to use lr-flycast on pi4, so i don't understand what this patch is about

**Comment by magicseb** [comment]
On buildroot build i got this segmentation fault.
It should be a buildroot/kernel/gcc problem
Nevermind, i close this issue.
