### ISSUE TITLE
mame fotns rom not compatible with Flycast Retroarch

### ISSUE THREAD

**Issue by legluondunet** [libretro/flycast#919]
Hello, I have latest Mame merged romset and Fist of the North Star (fotns.zip) does not launch, it says it misses ax1901f01.bin file. 
@barbudreadmon  from Flycast project answered me:
"there is no reference anymore to that file in flycast (it was removed last year), so you aren't using flycast (or you are using a really old version : don't)"

I'm using Flycast libreto core downloaded from Retroarch gui.

Thank you for your help.

**Comment by barbudreadmon** [comment]
Reference to that file was removed in september 2019 : https://github.com/libretro/flycast/commit/993590622fa1fc0e2207eff9548527b10912e3e9#diff-200d866ea4dd6791be045abfb1308e5dL5676

Meaning your core date from around 1 year ago. As to why, well, i don't know anything about your setup.

**Comment by legluondunet** [comment]
I'm using last Retroarch git version on Linux Ubuntu 20.04.
I updated libreto cores directly from Retroarch gui.
Do you need others infos?

**Comment by barbudreadmon** [comment]
> I updated libreto cores from Retroarch gui.

Obviously that didn't work for some reason. As to why, i've no idea. Out of curiosity what's the version of flycast showing at the bottom left of ra's menu ? (hash)

Another way to fix your setup issue would be to use old mame romsets for your old flycast core. That's more like a workaround though since you would keep using an old core.

**Comment by legluondunet** [comment]
![Capture d’écran de 2020-06-23 19-31-01](https://user-images.githubusercontent.com/325405/85436060-b7ad7780-b588-11ea-8275-1f3236797a31.png)
![Capture d’écran de 2020-06-23 19-30-51](https://user-images.githubusercontent.com/325405/85436067-ba0fd180-b588-11ea-8355-a57faff59dbb.png)
![Capture d’écran de 2020-06-23 19-30-39](https://user-images.githubusercontent.com/325405/85436070-baa86800-b588-11ea-9e09-c355f3e2458c.png)

**Comment by legluondunet** [comment]
false issue, my fault, Retroarch Flycast core can emulate the fotns.zip Mame rom,  thank you for your help.
