### ISSUE TITLE
Evolution - The World of Sacred Device (UK/PAL) - Graphics bugs

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#92]
Unlike the US version, the UK version actually boots up.

@flyinghead These are some long standing graphics bugs with this game that have not been fixed before in Reicast. This is directly after starting a new game.

![image](https://user-images.githubusercontent.com/1075274/42136002-13c8767e-7d54-11e8-8089-2f15026dc4b0.png)

You see certain tiles here color cycling. This should not be happening. What it should look like instead can be seen in this video (captured from a real Dreamcast) -

https://www.youtube.com/watch?v=z5cNCMVcc30

**Comment by inactive123** [comment]
This issue might shed some more light on the issue -

https://github.com/reicast/reicast-emulator/issues/56

@flyinghead Could this be fixed with your flat shading branch?

> Mr.Psyman says -
> 
> It's a funky color scheme.
> 
> Flat polys use 1 vertex for color. That's what dknute once told me. For some reason I never looked at it.
> Apparently, we treat them the same as gouraud polys.

**Comment by flyinghead** [comment]
Looks like a good candidate. Let me check.

**Comment by inactive123** [comment]
Yup, the flat shading branch fixes this -

![image](https://user-images.githubusercontent.com/1075274/42136984-d5dc8d3a-7d64-11e8-92ff-4964d3052096.png)

**Comment by flyinghead** [comment]
And it works
![evolution - flat shading](https://user-images.githubusercontent.com/16261910/42136997-edfaff6e-7d64-11e8-9734-07d1f508eca6.png)

**Comment by inactive123** [comment]
Hah, both posted at the same time heh.

OK, I will backport this commit for OIT. Try to make an implementation for non-OIT as well.

**Comment by flyinghead** [comment]
Apparently the support for flat shading requires OpenGL/GLES 3.0.

**Comment by inactive123** [comment]
Ah, can we put it around ifndef GLES conditionals for now then in the non OIT renderer? That way at least desktop users can still enjoy it. glProvokeVertex is GL 3.2 though. How about adding a setting for correct handling of flat shading that will require GL 3.2, and if the setting is not enabled, we dont default to this superset?

**Comment by flyinghead** [comment]
I just pushed a commit on my master branch with flat shading between #ifdef GLES
I didn't backport glProvokeVertex since GL_LAST_VERTEX_CONVENTION is the default so it shouldn't be needed.

**Comment by flyinghead** [comment]
In the non-OIT branch there are still some weird colored polygons at the back of the scene. Not sure what they are but I assume it's a transparent sorting issue.

**Comment by inactive123** [comment]
Yeah, at a certain point, the current buggy sorting modes in non-OIT might need a rewrite. Space Channel 5 Part 2 for instance is one of the games that exhibits the most serious graphical errors of most games when it comes to alpha sorting - see this comparison video here between OIT and non-OIT -

https://www.youtube.com/watch?v=vmZ5sTYD2q8

**Comment by flyinghead** [comment]
I know but there's no easy solution. The sorting is not buggy. It's just that it's only sorting triangles, not pixels. The only real fix I know of is per-pixel sorting, aka OIT ;)
