### ISSUE TITLE
M3U not working on Windows (drive letter)

### ISSUE THREAD

**Issue by grahamtriggs** [libretro/flycast#922]
I've been puzzling with an issue in loading M3Us (primarily auto-generated by Launchbox front-end), where it would constantly boot directly to bios, and where the disc control would fail to close the virtual tray.

Looking at the generated  .ldci files, I finally found the cause.

The last disc used was listed as "E:\\E:\\<path to file>"

LaunchBox is generating M3U files with the Drive Letter included in the path to the .chd files.

If I remove the drive letter from the M3Us - e.g.

"\<path to disc 1>"
"\<path to disc 2>"

(my Retroarch and chds are on the same drive)

Then everything loads correctly.

The Flycast core does not like having drive letters at the start of the paths for the files listed in the M3U.

**Comment by flyinghead** [comment]
Actually Flycast didn't support absolute path M3Us until now. This should be fixed with the above commit.

**Comment by grahamtriggs** [comment]
Tested this morning, and it is working.
