### ISSUE TITLE
Trackball mapping + several game don't work

### ISSUE THREAD

**Issue by Massouille78** [libretro/flycast#924]
Hello,

What a great job! I lie this emulator, beautiful !

I have questions please : 

1) In several games : 
Atomiswave : claychal / basschal / waidrive
and Naomi : dygolf / otrigger / smarine / shootopl 

the trackball is emulated by the use of the mouse. But I use a 8bitdo SNES30Pro or PS4 type gamepad. I don't use keyboard+
mouse to play.

Can we use the right analog stick to emulate this trackball please?

2) Other games don't work

Atomiswave : xtrmhnt2 "occur error board"
Naomi : f355twn2 / f355 : "error master board"
smarine : no key to go up the line during a catch
toukon4 : "not acceptable by this board" 
vtennis / vtennisg : crash after several seconde of game
wldkicks : no touch to kick the ball

Have you the same problem, a solutions please?

If I can help, I'am here !

Thanks in advance,

**Comment by barbudreadmon** [comment]
If you mix different issues together, it's not gonna help tracking them, in the first place it was the main reason i told you to not report issues in the compatibility list...
Furthermore, i believe most of the issues you are mentioning here are already tracked in their own separate issues...
