### ISSUE TITLE
Carrier Audio Problems

### ISSUE THREAD

**Issue by Zombeaver** [libretro/flycast#927]
The game Carrier has a strange audio issue where the voice clips sortof repeat sporadically, almost like an echo. This can be observed in the intro text crawl during the narration and throughout the rest of the game while dialogue is taking place. I'm using a .gdi on Windows x64 Retroarch.

PC: i7 4770k / GTX 780 / 32GB RAM / W7 64-bit

**Comment by flyinghead** [comment]
Hopefully this is fixed by the above commit. Let me know the result. Thanks

**Comment by blisstik** [comment]
I'm wondering if this fixes audio bugs in Looney Tunes - Space Race

**Comment by flyinghead** [comment]
It doesn't

**Comment by Zombeaver** [comment]
Yes, that fixed it! Thank you very much!
