### ISSUE TITLE
Latest version of flycast crashes retroarch.

### ISSUE THREAD

**Issue by mochardi** [libretro/flycast#937]
Hello, i´ve been using flycast with no issues for almost a year, but suddenly with the latest updates, when i try to load any game, retroarch crashes. (Only happens with the flycast core)

I'm seeing this in the log:

[libretro ERROR] 00:01:930 libretro/common.cpp:83 E[COMMON]: [GPF]Unhandled access to : 000000004e7a5000

Thank you!

[retroarch-log.txt](https://github.com/libretro/flycast/files/4929799/retroarch-log.txt)

**Comment by andrewjennings** [comment]
Error in the same place here. I get a notice from the UI: "Failed to load state. Run-Ahead is disabled."  Then I see the Naomi logo, then "Loading Game Now...", then Retroarch crashes. I've attached a debug log for more info.

[retroarch-debug.log](https://github.com/libretro/flycast/files/5008093/retroarch-debug.log)

**Comment by Clarkstill317** [comment]
Same problem mam😕
I have been asking for a fix for quite a while but it hasn't been done yet, since flyinghead is unable to recreate the problem on his end
Here is a potential tip tho
Pay attention to the percentage when it's saving
If the saving speed is constant,it will work, however if it seems to slow down a little towards the end,it will crash at that percentage when you load state

**Comment by Maelstrom-rl** [comment]
Same problem. Updated core, then it crashes right from the start on any game load with "Unhandled access" error.

**Comment by andrewjennings** [comment]
A new install of Retroarch with the same version of the core works OK for me, using the same ROM and same state.

**Comment by Maelstrom-rl** [comment]
Turning rewind off fixed the crash on start, but saving state still crashes retroarch with same error.

[INFO] File already exists. Saving to backup buffer ...
[INFO] 
[INFO] Loading state: "F:\Emul\Retroarch\states\Cannon Spike (USA).state".
[INFO] State size: 48319645 bytes.
[INFO] State size: 28511207 bytes.
[libretro ERROR] 05:11:009 libretro/common.cpp:83 E[COMMON]: [GPF]Unhandled access to : 00000000555a8a9e

**Comment by mochardi** [comment]
A fresh install of Retroarch fixed the problem!

**Comment by daninthemix** [comment]
> A fresh install of Retroarch fixed the problem!

Lucky you. A fresh install of Retroarch does **not** fix the problem for me.
