### ISSUE TITLE
Project Justice (NAOMI) graphical errors

### ISSUE THREAD

**Issue by Silverfoenix** [libretro/flycast#948]
Using the 64 ci-build a9f1a89 dated 2020-09-07T20:33:17.000Z
Windows 7 System
ATI Radeon Graphics
Intel i5
Program Utilizes 23~25 of the processor power

It is most noticeable when choosing **Akira**!
![image](https://user-images.githubusercontent.com/48087298/92974678-092e1a00-f487-11ea-9c83-231a729d7128.png)

Settings
![image](https://user-images.githubusercontent.com/48087298/92974534-bf453400-f486-11ea-8599-b98d5dfb1391.png)
Using Dynarec with safe mode **enabled**

**Comment by kage2051** [comment]
This issue section is for the RetroArch variant of flycast. For issues related to the standalone app, make a new issue ticket at https://github.com/flyinghead/flycast/issues

**Comment by Silverfoenix** [comment]
I confused the two!!! thanks for noticing... 
![tenor (8)](https://user-images.githubusercontent.com/48087298/92999376-ae490100-f520-11ea-9473-4b982fa05103.gif)

If anyone is interested here is the issue (Someone reported it long ago)
https://github.com/flyinghead/flycast/issues/38
