### ISSUE TITLE
(Naomi) Marvel Vs Capcom 2 - crashes at Capcom screen

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#96]
This game crashes at the Capcom logo.

**Comment by kalawangman** [comment]
Mine crashes at the "LOADING GAME NOW..." screen, about last week it was working perfectly.

[retroarch-log.txt](https://github.com/libretro/reicast-emulator/files/2153025/retroarch-log.txt)

**Comment by kalawangman** [comment]
I was able to make it work by bypassing the verification of RomSize.

core/hw/naomi/naomi_cart.cpp

        //verify(offset < RomSize);
	//verify((offset + size) < RomSize);

**Comment by inactive123** [comment]
Wait, you're getting Marvel Vs. Capcom 2 Naomi to work on Reicast libretro?

Can you share with us your md5sums/ sha1sum of your marvel 2 dat ? And possibly lst file too?

**Comment by inactive123** [comment]
Are you able to actually getingame and play though?

**Comment by inactive123** [comment]
It still crashes for me at the Capcom screen/logo even when having commented those lines out in naomi_GetPtr.

**Comment by kalawangman** [comment]
Yup. Its flawless, except settings wont save.

I suspect you have a wrong hex value in your LST file.

f6647c04d7dfad18c69cda0a05f8a4df (md5 of decrypted mvc2 rom)

The LST file in the repository is different.

**Comment by kalawangman** [comment]
LST: 
[mvc2.txt](https://github.com/libretro/reicast-emulator/files/2153210/mvc2.txt)

**Comment by inactive123** [comment]
Can you give me the right .lst file in plain text then?

**Comment by inactive123** [comment]
Ah. I will test.

**Comment by inactive123** [comment]
OMG, you are right. It works now. Awesome for sharing this with us.

**Comment by kalawangman** [comment]
No, thank you. I just want this shit to work.

**Comment by inactive123** [comment]
Let me know if you can figure out more issues with Naomi games this way. We have some more Naomi issues here where we are reporting either graphical bugs or crashes; might have to do with invalid sizes too.

**Comment by inactive123** [comment]
@bparker06 says it doesn't work for him yet on Linux though. It definitely works for me on Windows 10.

@bparker06 can you elaborate?

**Comment by ghost** [comment]
Here is my log from running the game on Linux with the latest commit: http://p.0bl.net/12628

**Comment by inactive123** [comment]
I think @bparker06 got it working now.
