### ISSUE TITLE
Mazan: Flash of the Blade crashing at different occasions

### ISSUE THREAD

**Issue by pjft** [libretro/flycast#961]
Hi,

Just raising this here for tracking. Mazan: Flash of the Blade works (after calibrating inputs), but it seems to crash in different occasions with messages similar to these (what changes is the memory address):

```
[libretro ERROR] Fatal error : Invalid size
 in _vmem_read_const -> core/hw/mem/_vmem.cpp : 89 

[libretro ERROR] 01:37:052 libretro/libretro.cpp:3250 E[COMMON]: DEBUGBREAK!
[libretro ERROR] 01:37:052 libretro/common.cpp:376 E[COMMON]: SIGSEGV @ ad8c12a4 ... 0xad8c12a4 -> was not in vram (dyna code 0)
[libretro ERROR] Fatal error : segfault
 in signal_handler -> core/libretro/common.cpp : 383 

[libretro ERROR] 01:37:052 libretro/libretro.cpp:3250 E[COMMON]: DEBUGBREAK!
Illegal instruction
```

This one was during the cutscene at the end of the first level.
It also crashes consistently during the intro, and in an alternate path in Level 1, Area 3.

Similar to the crash in Ninja Assault (https://github.com/libretro/flycast/issues/950) which also crashes during the intro, and you have to skip it by inserting a coin if you want to play the game.

Maybe they're related. Let me know if I can help with any troubleshooting. Ninja Assault is marked as KO in the compatibility list, and Mazan as OK, but I imagine both are in similar situations these days - you can get them to work but they'll invariably crash at some point.

I'm on Flycast commit 033fbf48, from September 23rd, on a Pi4.

Thanks for all the great work here.

**Comment by barbudreadmon** [comment]
Did you try looking at the value of sz when it dies at https://github.com/libretro/flycast/blob/a3878de9a7838a61b6c17e684a1abdb185c27382/core/hw/mem/_vmem.cpp#L89 and/or if commenting the die allows the game to keep running ?

**Comment by pjft** [comment]
I didn't, but I will and report back.

**Comment by pjft** [comment]
Good catch - and it's the obvious one.

sz is 8. I tried commenting the die statement(s) (and kept the log message) and ended up crashing elsewhere at the same moment:

```
[libretro ERROR] 01:35:524 hw/mem/_vmem.cpp:90 E[MEMORY]: Invalid Size: 8 - returning 32 
[libretro ERROR] Fatal error : SZ_64F not supported
 in ngen_readm_immediate -> core/rec-ARM/rec_arm.cpp : 1129 
```

Same in Ninja Assault.

When I tried to quickly add stubs for `_vmem_ReadMem64FP` and `_vmem_WriteMem64FP` and have it return the proper size, it died in the same place:

```
Warning, CALL(00000000) is out of range for literal(5367FE10)
[libretro ERROR] Fatal error : SZ_64F not supported
 in ngen_readm_immediate -> core/rec-ARM/rec_arm.cpp : 1129 
```

So it's likely that it's the ARM32 Dynarec that doesn't support it, as it's the only place in the code that explicitly states ""SZ_64F not supported". I imagine this works on x86 or 64-bit builds.

Thanks for the pointer!

**Comment by barbudreadmon** [comment]
Maybe try changing https://github.com/libretro/flycast/blob/a3878de9a7838a61b6c17e684a1abdb185c27382/core/rec-ARM/rec_arm.cpp#L1079

by 
```
u32 size = memop_bytes(optp);
void* ptr = _vmem_read_const(op->rs1._imm, isram, size > 4 ? 4 : size);
```
?
Other dynarecs are doing something like this.

**Comment by pjft** [comment]
I'll try it out later - thanks.

**Comment by pjft** [comment]
Ok, so thanks to your pointers I did a bit more than that, but now I'm stuck and would appreciate some guidance if anyone in the know can help.

I submitted a PR #962 which has two commit:
- The first one just works around the crash, somewhat successfully. The game works, but some textures aren't rendered.
- A second commit where I attempted to backport the same code from rec-arm64, but I'm surely messing up the memory addresses there, so if anyone has any suggestions for me to try out I'm all ears. 

It's crashing with that second commit in:

```
[libretro ERROR] 00:40:578 rec-ARM/rec_arm.cpp:916 E[DYNAREC]: fail raddr E3470E00 {@0000118C}:(
[libretro ERROR] Fatal error : Invalid opcode: vmem fixup

 in ngen_readm_fail_v2 -> core/rec-ARM/rec_arm.cpp : 917 
```

Thanks, and sorry for the trouble. If possible I'd like to contribute with a complete fix rather than just a workaround for the crashing, though I can certainly imagine it won't be easy.

Have a great weekend, and thanks for the pointers here.

**Comment by flyinghead** [comment]
I fixed this issue on standalone: https://github.com/flyinghead/flycast/commit/063c7f7d1874b8bdaede88887f5a44cb71fd57cd

**Comment by pjft** [comment]
Thank you @flyinghead, @twinaphex and @barbudreadmon - and also for having already picked it up for libretro when I was starting to do it as well. :) I see now where I had stumped in trying to fix it. 
Have a great weekend, and thank you once again.
