### ISSUE TITLE
Missing (2D/Sprite?) elements when running Flycast with Vulkan

### ISSUE THREAD

**Issue by r2rX** [libretro/flycast#968]
Hey all,

As of a a few flycast updates back (within the last 3-4 releases), i've noticed that some visual (2D/sprite?) elements are not being rendered when using Vulkan. This is observable from the Dreamcast BIOS and in-game (using Soul Reaver as example).

The tests were done on Retroarch 1.9.0, with the latest flycast build, running on Windows 10 1809 LTSC with an NVIDIA 1070 Mobile GPU running on the latest 456.71 driver.

This issue does not occur when running in OpenGL.

My flycast config:
```
reicast_allow_service_buttons = "disabled"
reicast_alpha_sorting = "per-pixel (accurate)"
reicast_analog_stick_deadzone = "15%"
reicast_anisotropic_filtering = "16"
reicast_boot_to_bios = "disabled"
reicast_broadcast = "Default"
reicast_cable_type = "VGA (RGB)"
reicast_custom_textures = "disabled"
reicast_delay_frame_swapping = "disabled"
reicast_digital_triggers = "disabled"
reicast_div_matching = "disabled"
reicast_dump_textures = "disabled"
reicast_enable_dsp = "enabled"
reicast_enable_naomi_15khz_dipswitch = "disabled"
reicast_enable_purupuru = "enabled"
reicast_enable_rtt = "enabled"
reicast_enable_rttb = "disabled"
reicast_force_wince = "enabled"
reicast_frame_skipping = "disabled"
reicast_framerate = "fullspeed"
reicast_gdrom_fast_loading = "disabled"
reicast_hle_bios = "disabled"
reicast_internal_resolution = "640x480"
reicast_language = "Default"
reicast_lightgun1_crosshair = "disabled"
reicast_lightgun2_crosshair = "disabled"
reicast_lightgun3_crosshair = "disabled"
reicast_lightgun4_crosshair = "disabled"
reicast_mipmapping = "enabled"
reicast_oit_abuffer_size = "4GB"
reicast_per_content_vmus = "disabled"
reicast_pvr2_filtering = "enabled"
reicast_region = "Default"
reicast_render_to_texture_upscaling = "1x"
reicast_screen_rotation = "horizontal"
reicast_show_lightgun_settings = "disabled"
reicast_show_vmu_screen_settings = "disabled"
reicast_synchronous_rendering = "enabled"
reicast_system = "auto"
reicast_texupscale = "off"
reicast_texupscale_max_filtered_texture_size = "256"
reicast_threaded_rendering = "enabled"
reicast_trigger_deadzone = "0%"
reicast_vmu1_pixel_off_color = "DEFAULT_OFF 01"
reicast_vmu1_pixel_on_color = "DEFAULT_ON 00"
reicast_vmu1_screen_display = "disabled"
reicast_vmu1_screen_opacity = "100%"
reicast_vmu1_screen_position = "Upper Left"
reicast_vmu1_screen_size_mult = "1x"
reicast_vmu2_pixel_off_color = "DEFAULT_OFF 01"
reicast_vmu2_pixel_on_color = "DEFAULT_ON 00"
reicast_vmu2_screen_display = "disabled"
reicast_vmu2_screen_opacity = "100%"
reicast_vmu2_screen_position = "Upper Left"
reicast_vmu2_screen_size_mult = "1x"
reicast_vmu3_pixel_off_color = "DEFAULT_OFF 01"
reicast_vmu3_pixel_on_color = "DEFAULT_ON 00"
reicast_vmu3_screen_display = "disabled"
reicast_vmu3_screen_opacity = "100%"
reicast_vmu3_screen_position = "Upper Left"
reicast_vmu3_screen_size_mult = "1x"
reicast_vmu4_pixel_off_color = "DEFAULT_OFF 01"
reicast_vmu4_pixel_on_color = "DEFAULT_ON 00"
reicast_vmu4_screen_display = "disabled"
reicast_vmu4_screen_opacity = "100%"
reicast_vmu4_screen_position = "Upper Left"
reicast_vmu4_screen_size_mult = "1x"
reicast_volume_modifier_enable = "enabled"
reicast_widescreen_cheats = "disabled"
reicast_widescreen_hack = "disabled"
```

Here are some screenshots to showcase the issue (Note: the Vulkan screenshots were taken using the CRT Royale shader. I tested with it disabled and the results were the same; thus I kept the screenshots with it enabled):

BIOS - Vulkan:
![BIOS_VLK](https://user-images.githubusercontent.com/18622885/96044085-8f6bc080-0e78-11eb-93ea-2c26d6e98c64.png)

BIOS - OpenGL:
![BIOS_OGL](https://user-images.githubusercontent.com/18622885/96043961-57fd1400-0e78-11eb-8472-a0139707f08b.png)

Soul Reaver 2 Menu - Vulkan:
![SR2_Menu_VLK](https://user-images.githubusercontent.com/18622885/96044122-a01c3680-0e78-11eb-9644-1d8cc1a3087e.png)

Soul Reaver 2 Menu - OpenGL:
![SR2_Menu_OGL](https://user-images.githubusercontent.com/18622885/96044000-677c5d00-0e78-11eb-9805-5cfb9c9dfc5a.png)

Soul Reaver 2 In-game - Vulkan:
![SR2_Wings_VLK](https://user-images.githubusercontent.com/18622885/96044192-b9bd7e00-0e78-11eb-98ef-fa119b3bc053.png)

Soul Reaver 2 In-game - OpenGL:
![SR2_Wings_OGL](https://user-images.githubusercontent.com/18622885/96044051-7f53e100-0e78-11eb-9408-8e8e194ee0bf.png)

Could it be related to https://github.com/libretro/flycast/issues/953?

If there's any further info required, I am more than happy to provide it.

Thanks!

**Comment by inactive123** [comment]
Hi,

unfortunately, it seems a recent Nvidia driver update caused this.

Starting with driver 456.38, 2GB and 4GB seem to no longer work properly. We managed to 'fix' the 2GB pixel buffer size by changing the value to '0x7ff00000u', which should be 1.99GB. However, we didn't find a workaround for 4GB yet.

We might have to report this to Nvidia if we see no way around it. For now, you can use the '2GB' pixel buffer size.

**Comment by r2rX** [comment]
That did the trick @twinaphex. 👍 Thanks for the help and the update!

**Comment by daFourch** [comment]
Same problem with The House of the Dead 2: Lightgun Cursor just doesn't show up. Switching to glcore works. Using 2GB pixel buffer size on Vulkan didn't work though

**Comment by barbudreadmon** [comment]
> Switching to glcore works

That's normal, OpenGL can't handle 4GB so it always forces 2GB internally when 4GB is set

> Using 2GB pixel buffer size on Vulkan didn't work though

Did you update your core ? 2GB should be ok with vulkan **if you are using the latest version of flycast**

**Comment by daFourch** [comment]
Yes I did. The version I'm using is 0.1 c4e5f45

Here's my .opt

> reicast_allow_service_buttons = "disabled"
reicast_alpha_sorting = "per-pixel (accurate)"
reicast_analog_stick_deadzone = "15%"
reicast_anisotropic_filtering = "8"
reicast_boot_to_bios = "disabled"
reicast_broadcast = "Default"
reicast_cable_type = "VGA (RGB)"
reicast_custom_textures = "disabled"
reicast_delay_frame_swapping = "disabled"
reicast_digital_triggers = "disabled"
reicast_div_matching = "auto"
reicast_dump_textures = "disabled"
reicast_enable_dsp = "enabled"
reicast_enable_naomi_15khz_dipswitch = "disabled"
reicast_enable_purupuru = "enabled"
reicast_enable_rttb = "enabled"
reicast_force_wince = "disabled"
reicast_frame_skipping = "disabled"
reicast_framerate = "fullspeed"
reicast_gdrom_fast_loading = "disabled"
reicast_hle_bios = "disabled"
reicast_internal_resolution = "640x480"
reicast_language = "French"
reicast_lightgun1_crosshair = "Red"
reicast_lightgun2_crosshair = "disabled"
reicast_lightgun3_crosshair = "disabled"
reicast_lightgun4_crosshair = "disabled"
reicast_mipmapping = "enabled"
reicast_oit_abuffer_size = "2GB"
reicast_per_content_vmus = "disabled"
reicast_pvr2_filtering = "enabled"
reicast_region = "Default"
reicast_render_to_texture_upscaling = "1x"
reicast_screen_rotation = "horizontal"
reicast_show_lightgun_settings = "enabled"
reicast_show_vmu_screen_settings = "disabled"
reicast_synchronous_rendering = "enabled"
reicast_system = "auto"
reicast_texupscale = "off"
reicast_texupscale_max_filtered_texture_size = "256"
reicast_threaded_rendering = "enabled"
reicast_trigger_deadzone = "0%"
reicast_vmu1_pixel_off_color = "DEFAULT_OFF 01"
reicast_vmu1_pixel_on_color = "DEFAULT_ON 00"
reicast_vmu1_screen_display = "disabled"
reicast_vmu1_screen_opacity = "100%"
reicast_vmu1_screen_position = "Upper Left"
reicast_vmu1_screen_size_mult = "1x"
reicast_vmu2_pixel_off_color = "DEFAULT_OFF 01"
reicast_vmu2_pixel_on_color = "DEFAULT_ON 00"
reicast_vmu2_screen_display = "disabled"
reicast_vmu2_screen_opacity = "100%"
reicast_vmu2_screen_position = "Upper Left"
reicast_vmu2_screen_size_mult = "1x"
reicast_vmu3_pixel_off_color = "DEFAULT_OFF 01"
reicast_vmu3_pixel_on_color = "DEFAULT_ON 00"
reicast_vmu3_screen_display = "disabled"
reicast_vmu3_screen_opacity = "100%"
reicast_vmu3_screen_position = "Upper Left"
reicast_vmu3_screen_size_mult = "1x"
reicast_vmu4_pixel_off_color = "DEFAULT_OFF 01"
reicast_vmu4_pixel_on_color = "DEFAULT_ON 00"
reicast_vmu4_screen_display = "disabled"
reicast_vmu4_screen_opacity = "100%"
reicast_vmu4_screen_position = "Upper Left"
reicast_vmu4_screen_size_mult = "1x"
reicast_volume_modifier_enable = "enabled"
reicast_widescreen_cheats = "disabled"
reicast_widescreen_hack = "disabled"

**Comment by dclaz** [comment]
I have the same problem with my Iris Xe (Intel i5-1135G7) and 27.20.100.9415 drivers.  Changing the `reicast_oit_abuffer_size` value in flycast.opt does not make a difference.

**Comment by sharkytowers** [comment]
@dclaz Same problem here.  I have a 1165G7/Iris Xe.  Tried DX11, GLcore, Vulkan...  no go.  I'm having the issue in NBA2k2

Hope someone finds a fix.
