### ISSUE TITLE
Street Fighter III random sprite garble mid game

### ISSUE THREAD

**Issue by riggles1** [libretro/flycast#969]
Randomly when playing one of the character sprites will garble up, sometimes after 5 min, other times sooner. No issues with any other cores, MAME, Saturn, Wii/GC etc.

Laterst retroarch 64 bit, windows 10, both gl and vulkan. Tested various game options with no luck, from accurate to fastest and additional options. Still happens. 

Mainly use CRT Switchres, but the issue happens just using the main GPU in windowed mode like this as well (main desktop being outputted by a GTX1070), so its not related to that. No shaders active either.
> 
![issue](https://user-images.githubusercontent.com/28061895/96176951-648f7400-0f2d-11eb-8a64-51494e83829a.png)

**Comment by barbudreadmon** [comment]
Can you please confirm it happens with default settings, possibly only with "alpha sorting" changed to "per pixel" ?

On a sidenote, wondering what could drive someone to play the worst port of sfiii.

**Comment by riggles1** [comment]
> Can you please confirm it happens with default settings, possibly only with "alpha sorting" changed to "per pixel" ?
> 
> On a sidenote, wondering what could drive someone to play the worst port of sfiii.

Thanks for the reply, fixed it I think, it happens when you load the game in 240p mode. Not doing that and putting the internal res at 1600x1200, forcing it down to 2560x240p works great, was playing for an hour and didn't get the corruption again.

The thing with this version is that it has a training mode, I stick to the arcade version for regular playing, however I wanted a quick access training mode to mess with on my Astro City cab that didn't consist of using cheats with MAME (which works well, just that I wanted to give this a try). 
Really have no interest in playing this game on anything but the Astro City with a CRT monitor, so have no interest in newer ports of the game.

**Comment by barbudreadmon** [comment]
> it happens when you load the game in 240p mode

Ok, yes i heard of downscaling issues when setting res to 240p, wondering if @flyinghead is interested in looking into this one ? That's something i won't be able to solve by myself.
