### ISSUE TITLE
(non-OIT) Cosmic Smash - geometry issues

### ISSUE THREAD

**Issue by mlnlbrt** [libretro/flycast#97]
There are some geometry issues in Cosmic Smash with non-OIT core. They can be seen for example when starting or finishing a level:

![cosmic smash japan -180701-183407](https://user-images.githubusercontent.com/11428910/42136693-c93b6d16-7d60-11e8-8687-da05f22268f2.png)
![cosmic smash japan -180624-101854](https://user-images.githubusercontent.com/11428910/42136694-d160bf64-7d60-11e8-98c3-0d92b059469c.png)

Please note that these issues were gone after disabling Multipass support (at the time when the switch was available), but it caused some random hangups.

**Comment by inactive123** [comment]
There is something from the non-OIT renderer from @flyinghead that I still have to backport that is specific to Cosmic Smash.

**Comment by inactive123** [comment]
Backported this - I think this should be sufficient now -

https://github.com/libretro/reicast-emulator/commit/7f2208e3883e9bc0a67ed1402c93bd4d8f0980c9

![image](https://user-images.githubusercontent.com/1075274/42143053-62814c46-7db3-11e8-99da-d59b8f34718d.png)

**Comment by mlnlbrt** [comment]
@twinaphex I have checked with the latest nightly and https://github.com/libretro/reicast-emulator/commit/5c4135905a600e05c3d5b4722c5accd89b01ed18 and the issue is still there.

I have also noticed that it sutters pretty bad with https://github.com/libretro/reicast-emulator/commit/5c4135905a600e05c3d5b4722c5accd89b01ed18 while the latest nightly is fine.

**Comment by legluondunet** [comment]
I can confirm the issue is still present in the last Retroarch/Libretro Reicast core version.

![capture d ecran de 2018-10-13 05-44-05](https://user-images.githubusercontent.com/325405/46900982-6a1fd280-ceab-11e8-8cd8-0d5ddea70b86.png)
![capture d ecran de 2018-10-13 05-43-53](https://user-images.githubusercontent.com/325405/46900983-6ab86900-ceab-11e8-8667-5085c486c3b4.png)

**Comment by flyinghead** [comment]
confirmed. non-OIT only

**Comment by flyinghead** [comment]
This should be fixed. Please retest.
