### ISSUE TITLE
Super Runabout crashes Retroarch on launch

### ISSUE THREAD

**Issue by daninthemix** [libretro/flycast#976]
Is there anything special you need to do to make WinCE games boot in Flycast (this is the only one I have).

The log just shows lots of these:

`[libretro ERROR] 00:08:683 libretro/common.cpp:83 E[COMMON]: [GPF]Unhandled access to : 000000011893a0c0`

Okay it's not WinCE - it's every game, and this is a duplicate of https://github.com/libretro/flycast/issues/937

**Comment by barbudreadmon** [comment]
You are being unclear there, the other issue appears to be about flycast crashing when a savestate is loaded, is that your issue ?

**Comment by daninthemix** [comment]
> You are being unclear there, the other issue appears to be about flycast crashing when a savestate is loaded, is that your issue ?

Sorry. No for me it crashes on launch - but only the libretro core. Standalone is fine.

**Comment by barbudreadmon** [comment]
Ok, and you have disabled runahead, rewind and the settings to save/load savestates automatically ?

**Comment by daninthemix** [comment]
The only one of those I had enabled was rewind, and I have tried without it. I have also tried a fresh Retroarch install.

**Comment by barbudreadmon** [comment]
Ok, so that's a totally different issue from the one you linked, in the first place `[libretro ERROR] 00:08:683 libretro/common.cpp:83 E[COMMON]: [GPF]Unhandled access to : 000000011893a0c0` is a general msg for almost anything going wrong with flycast, so it's not helpful. Maybe we could figure out something with full logs ?

**Comment by daninthemix** [comment]
[retroarch-log.txt](https://github.com/libretro/flycast/files/5432678/retroarch-log.txt)

Sure, see attached.

**Comment by barbudreadmon** [comment]
What version of the nvidia driver are you running ? There have been several reports of bugs and crashes on specific models with newer nvidia drivers, could you try reinstalling older nvidia driver (version 450 should be fine) to see it's another of those nvidia driver regressions ? Also, does it happen when using gl/glcore video drivers ?

**Comment by daninthemix** [comment]
I have the latest driver because I updated to the latest Windows yesterday (Windows 10 2009 I believe). Sorry but I don't want to roll back drivers. I'm happy to use standalone.

**Comment by barbudreadmon** [comment]
I'm only asking this for debug's sake, and you aren't answering if gl/glcore are fine.

**Comment by daninthemix** [comment]
Yes, I did try the GL driver and it didn't help.

**Comment by barbudreadmon** [comment]
will you try reverting drivers once to see if it's related ?

**Comment by barbudreadmon** [comment]
I guess that's a no.
Since i can't reproduce and you don't want to provide additional information for debugging, i'll have to close...
