### ISSUE TITLE
Found some glitchs in atomiswave

### ISSUE THREAD

**Issue by pyjmj05** [libretro/flycast#979]
It seems that all devices are coming out.

**Samurai Shodown VI**

- vs intro background

https://youtu.be/jcbwfWrmTCk?t=92 - Arcade 
https://youtu.be/e1g_WgWVHb4?t=1483 - flycast

- win quote scene

![3](https://user-images.githubusercontent.com/73285776/98014713-569f8580-1e3f-11eb-84f9-8a1b19689023.PNG)
Arcade
![4](https://user-images.githubusercontent.com/73285776/98014740-5b643980-1e3f-11eb-8585-aae795109100.PNG)
flycast

**Neogeo Battle Coliseum**

- cyber woo's character sprite

https://youtu.be/-t97zAwcDAI?t=728

**Comment by barbudreadmon** [comment]
Those games, as many other games on dreamcast hardware, require per-pixel alpha sorting (also know as OIT - order independent transparency, you can read more about it at https://www.libretro.com/index.php/flycast-is-getting-a-vulkan-renderer-available-later-today-on-retroarch-with-nightly-core/) to be rendered properly. It's unavailable with OpenGL ES and requires a fairly good gpu anyway (something those SoCs don't have).
