### ISSUE TITLE
Purple sky in Dragon's Blood (US) or Draconus (PAL)

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#98]
As soon as you can control your character in the game and look ahead, the sky appears purple:

![dbbad](https://user-images.githubusercontent.com/12475371/42136935-f13bb2e6-7d31-11e8-89cb-2164fa6b2101.png)

However, on a real Dreamcast the game looks like this:

![image](https://user-images.githubusercontent.com/12475371/42136996-9f4ba3a0-7d32-11e8-8a51-199052ab3d6b.png)

**Comment by flyinghead** [comment]
@twinaphex Here is a fix for this: https://github.com/flyinghead/reicast-emulator/commit/99af84d7fb119f33c4f0e8f8d8db4baefaf52760

**Comment by inactive123** [comment]
Awesome, going to backport this. From what I hear, Redream is not even emulating this correctly right now.

**Comment by inactive123** [comment]
Fixed as of this commit - https://github.com/libretro/reicast-emulator/commit/058919316ea2111786bc29287b9b026495168cfe
