### ISSUE TITLE
Monitor in portrait mode

### ISSUE THREAD

**Issue by mgroves** [libretro/flycast#982]
I am running Flycast (latest build) on Windows. I've turned my monitor sideways and put Windows in portrait mode.

I've run Flycast with 'fullscreen = yes' in emu.cfg - it goes full screen, but it seems to be cutting off both sides of the game video. It's resizing bigger than the monitor. When I run in windowed mode, it works fine, except that all the windows chrome and the desktop appears. I'm trying to run this in my homemade cabinet, so I'd prefer the fullscreen mode, with black bars on top and bottom, like letterbox movies.

Is there a way to do this?

And if so, is there a way to put in an overlay to put marquee graphics and such in place of the black bars?

**Comment by barbudreadmon** [comment]
You should ask at https://github.com/flyinghead/flycast/issues
Our repo is for the libretro port and doesn't handle things specific to the standalone builds.
