### ISSUE TITLE
Request for Pi4 Vulkan Support 

### ISSUE THREAD

**Issue by bluestang2006** [libretro/flycast#983]
The Pi4’s Vulkan driver now has the direct display extension supported which allows for Vulkan apps to render direct to a display without X11, Wayland, etc. 

I built this repo with Vulkan support but running into a segfault that is beyond my level to diagnose. DuckStation works so this is not a driver issue per se, or at least I do not believe so.

Here is the backtrack on the segfault:

Starting program: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-flycast/flycast_libretro.so --config /opt/retropie/configs/dreamcast/retroarch.cfg /home/pi/RetroPie/roms/dreamcast/dolphin.zip --verbose
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ff0a8cab0 (LWP 5385)]
WARNING: v3dv is neither a complete nor a conformant Vulkan implementation. Testing use only.

```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt full
#0  0x0000000000000000 in  ()
#1  0x0000007febf3abdc in VulkanContext::Init(retro_hw_render_interface_vulkan*) () at /opt/retropie/libretrocores/lr-flycast/flycast_libretro.so
#2  0x0000007fed13bed0 in retro_vk_context_reset() () at /opt/retropie/libretrocores/lr-flycast/flycast_libretro.so
#3  0x00000055555c35b0 in drivers_init.constprop ()
#4  0x00000055555c450c in retroarch_main_init ()
#5  0x00000055555dd474 in content_load.isra ()
#6  0x00000055555de48c in task_load_content_internal.isra ()
#7  0x00000055555cb518 in rarch_main ()
#8  0x0000007ff5dc6d24 in __libc_start_main (main=0x55555924f0 <main>, argc=7, argv=0x7ffffff448, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=<optimized out>) at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf =
              {cancel_jmp_buf = {{jmp_buf = {366509196000, 0, 366504126376, 0, 0, 0, 0, 0, 0, 0, 549755810560, 14428098856111475865, 0, 14428098855941510001, 0, 0, 0, 0, 0, 0, 0, 0}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x5555e77448 <__libc_start_main@got.plt>, 0x55555927dc <_start+52>}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1441231944}}}
        not_first_call = <optimized out>
#9  0x00000055555927dc in _start ()
```

**Comment by barbudreadmon** [comment]
> DuckStation works so this is not a driver issue per se

> WARNING: v3dv is neither a complete nor a conformant Vulkan implementation. Testing use only.

It is a driver issue, as a matter of fact vulkan works with proper drivers, i'll close.

**Comment by bluestang2006** [comment]
Although the driver is developmental, the Pi4's Vulkan drivers work on a number of apps - i.e. - vkQ1/2/3. Let's be honest though, their are not many Vulkan apps out there yet for the Pi4 so there is limited real world testing.

Any idea what the problem is? It would be good to log the issue with MESA so it can be worked into the development...

Or I guess we can wait until the driver becomes 1.0 conformant and then open the issue then if it's a driver issue.

**Comment by barbudreadmon** [comment]
No idea, i'm not a vulkan dev. Let's wait for driver to be conformant before opening an issue, however considering pi4's opengl support is still glitched (see glitched colors in yabasanshiro) i think it's unlikely the rpi fundation will make a proper job with the vulkan one.

**Comment by asavah** [comment]
> i think it's unlikely the rpi fundation will make a proper job with the vulkan one

They (the fundation) certainly will not. Igalia is developing both gl and vulkan drivers for them. )

**Comment by bluestang2006** [comment]
> No idea, i'm not a vulkan dev. Let's wait for driver to be conformant before opening an issue, however considering pi4's opengl support is still glitched (see glitched colors in yabasanshiro) i think it's unlikely the rpi fundation will make a proper job with the vulkan one.

Can we revisit the issue now?

https://www.raspberrypi.org/blog/vulkan-update-were-conformant/

**Comment by barbudreadmon** [comment]
As far as i'm concerned, there is nothing to revisit, flycast works on vulkan, so if pi4 is vulkan-conformant it will work.

**Comment by bluestang2006** [comment]
> As far as i'm concerned, there is nothing to revisit, flycast works on vulkan, so if pi4 is vulkan-conformant it will work.

Strange that RetroArch will work fine with the Pi4 Vulkan driver as well as a few other libretro cores... 

The GL drivers have been updated too, and have been undergoing regular updates as far as I know. The only way to get the issues you speak of fixed (assuming they still exist) is to raise an issue with MESA's repo.

There is also the fact that the Pi Raspbian package maintainers are slooooooow with updates, and the MESA package binaries have not been updated in a long time. That is no fault of MESA...

**Comment by barbudreadmon** [comment]
So, can you confirm flycast works with the latest version of their supposedly vulkan-conformant driver ?

**Comment by bluestang2006** [comment]
> So, can you confirm flycast works with the latest version of their supposedly vulkan-conformant driver ?

I believe Khronos is the arbiter of Vulkan conformance - https://www.khronos.org/conformance/adopters/conformant-products#submission_530

And yes, I still can't get lr-flycast to work on the Pi4 under Vulkan. GLES works just fine.
