### ISSUE TITLE
DC flash checksum should be updated in the .info

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#99]
According to [MAME](https://github.com/mamedev/mame/blob/master/src/mame/drivers/dccons.cpp), the DC flash should have the following hash:
```
ROM_START(dc)
	DREAMCAST_COMMON_BIOS

	ROM_REGION(0x020000, "dcflash", 0)
	ROM_LOAD( "dcus_ntsc.bin", 0x000000, 0x020000, CRC(4136c25b) SHA1(1efa00ab9d8357a9f91e5be931a3efd6236f2b79) )  // dumped from VA2.4 mobo with 1.022 BIOS
ROM_END
```
Note that this is the second time the flash hash value has been updated in MAME, and should now be a "good dump" [This](https://git.redump.net/mame/commit/?id=a3f2c5abcd892fec0aeffbb0d661490bcf295108) old update shows the old/bad value as reflected in the current retroarch .info file.

**Comment by flyinghead** [comment]
The flash file is no longer necessary. The content of the flash memory is now created from scratch by the core if not present.

**Comment by Shoegzer** [comment]
Thanks.  I haven't tested this yet but wonder if a dynically created fresh flash file matches the "good" mame dump in hash?  And if so, to avoid confusion I wonder if the flash file should even be listed in the info or anywhere given that it can just be dynically created.    If it gets removed I'll just close this issue.

**Comment by flyinghead** [comment]
It won't match the "good" mame dump hash since it contains the current date and time.

**Comment by Shoegzer** [comment]
Ah, got it.  I must have missed the commit that generates the file.  I'll close this issue out when the hash is removed from the info.  Thanks again for this useful feature.

**Comment by flyinghead** [comment]
Flash template file is no longer a requirement
