### ISSUE TITLE
No Jamma after latest update

### ISSUE THREAD

**Issue by ThatLordGuy** [libretro/flycast#991]
https://old.reddit.com/r/RetroArch/comments/keo2y1/jamma_io_board_not_found_error_for_naomi_games_is/

**Comment by kage2051** [comment]
The 'updated' core right now seems to be an older build, from a month ago. This is due to libretro's buildbot being moved to a much more secure server. Download the November 4th version from the buildbot in the meantime.

**Comment by barbudreadmon** [comment]
This issue was fixed 3 weeks ago, please build your own core, use an older version, or wait for the new buildbot to be ready.
