### ISSUE TITLE
Flycast 0.1 ca2fa42 - Corrupting VMUs

### ISSUE THREAD

**Issue by LukasThyWalls** [libretro/flycast#992]
* System: Windows 10 Pro x64 (20H2)
* RetroArch: 1.9.0
* Core: Flycast 0.1 ca2fa42

_Description_

I'm playing Dino Crisis (dinovga-es-darc.cdi, Spanish, md5sum: 6dd60c98601aad1a22b61a74fd7ee532) using the core version 0.1 b783996 without any issue, but i updated to 0.1 ca2fa42, and since then my VMUs go corrupted and can't save or load the game.

When i save, it try to save and it shows in game (in Spanish) "Impossible to save correctly", however, the save file shows its info updated for the actual game. If i try to load it, it says (in Spanish) "Impossible to load correctly" and doesn't load anything.

_Testing_

I tried to go back to 0.1 b783996 but those saves doesn't work anymore. If i delete the VMUs, they work again and i can save and load without issue.

Copying the save files to other VMU inside BIOS make that VMU corrupted (also with 0.1 b783996). I tried to use VMU Explorer but with the corrupted VMUs tends to crash when i try to copy or doing something to the save file. I noted, in VMU Explorer the info of two VMUs, one corrupted and other not, are very different, incluing the image, and they should be the same because they are the same save file in the same point (creating both throught a near save state).

In the logs (Verbose Core Logging:  3 (Error)) shows nothing when the "Impossible to save/load" appears.

_Data provided_

* Save state directly in the door which triggers to save game.
* VMU Corrupted with that save
* VMU OK with that save

[Dino Crisis Save Issue - 0.1 ca2fa42.zip](https://github.com/libretro/flycast/files/5718601/Dino.Crisis.Save.Issue.-.0.1.ca2fa42.zip)

Thanks. If anything more is needed, tell me.

PD.: I'm in the middle of a gameplay of this, uploading to Youtube, and this has screwed up entirely... I don't think i can "restore" the files so... i learned in the hard way to lock the core when is needed...

**Comment by kage2051** [comment]
Build ca2fa42 is from a month ago and was pretty broken. Also that it's older than the other build you mentioned.

**Comment by LukasThyWalls** [comment]
0.1 b783996 and 0.1 ca2fa42 are the two consecutive cores that RetroArch downloaded for me, being ca2fa42 newer and overwrites b783996. I'm talking about the versions showed in RetroArch itself. So if those builds correspond to those commits here, I don't understand why RetroArch (STABLE) overwrited newer builds with older ones, and with an old one with an issue like that (i didn't test yet with other game, but it seems a heavy and commont issue to me)

I don't get it how this project works and how i can contribute. I try to contribute with i can to some open source projects, but the whole RetroArch i don't get it. Everything is other projects works, you need to reproduce the issues in those projects but i never can because the builds are never correlated and they haven't the same functionality. Now this happens. I try to do my best to help to fix it, but, i don't see any responsible (At least you responded, in other cores there isn't anyone). Everything is automated.

Sorry for my rant, but i'm realizing using RetroArch is a big mistake...

**Comment by taydan04** [comment]
Hey Lukas,
I had run in to the same issue as you where saving in any Dreamcast ROM was corrupting my VMU's. I eventually figured out that RetroArch 1.9.0 is fetching a really old version of the Flycast core. I have resolved the issue for me by using [this tutorial](http://emulation.gametechwiki.com/index.php/Building_RetroArch#Building_on_Windows) to build the core from source.

1. Install MSYS2 from the link on that page and follow the steps to update it and install the 64-bit build time dependencies. Then make sure to close MSYS2 MSYS and switch to MSYS2 MinGW 64-bit for the remaining 2 steps.

2. Then use the following commands to fetch just the Flycast source:

> git clone https://github.com/libretro/libretro-super.git
> cd libretro-super
> ./libretro-fetch.sh flycast

3.  Then use the following command to build the libretro core

> ./libretro-build.sh flycast

This will generate the .dll file (see the linked page for where the file will end up) that needs to be dropped in to your cores folder within retroarch. Then you should be good to go! Happy Dreamcasting!

I would also be happy to send you the compiled core in some way if you want to save a little time. However the above method did have me up and running within an hour or so even on my macbook air in bootcamp.

**Comment by LukasThyWalls** [comment]
Thanks @taydan04

However, the b783996 (old core for Retroarch) is from 25 November, and since then until now, there are only changes in the Makefile file. The ca2fa42 (new core for Retroarch) if from 16 November, and between them are reversion, changes and backports, which, one or some of them, fix this.

I have both version (because RetroArch backups the cores, but i found with this that they have only stored the last one in their build bot! I don't know why...), but also it should be interesting to see why they used and old core commit as replacement to a new core. I don't know where to put the issue for this... (I can ask in the Libretro Forums, but maybe you know).

**Comment by taydan04** [comment]
Heya @LukasThyWalls 

No worries. Yeah I have spotted the same as you. I am a complete noob to this area and only made an account to report the VMU issue until I spotted you already had. I then found that the build number on here aeb9e59 was different to the one reporting in RetroArch which was showing ca2fa42 like yours. Now that I have used Libretro-Super to build the core manually it is showing as the current build aeb9e59 in RetroArch. And I have been playing Resident Evil 2 (A Windows CE game) without problems with an impressive amount of performance and no problem saving.

As for why RetroArch is pulling an older version than it used to this is probably a question to be raised on the [RetroArch Git](https://github.com/libretro/RetroArch) or possibly the [Libretro Forums](https://github.com/libretro/RetroArch) as I doubt the flycast devs have any direct involvement with that side of things.

**Comment by brunovieira90** [comment]
Hi! Would it be very inconvenient to request the core flycast 0.1 dll file b783996?

I tried to perform the tutorial, but the link to the msys2 program on the website https://www.msys2.org/#installation seems broken.

**Comment by Scr34mik** [comment]
> 
> 
> Hi! Would it be very inconvenient to request the core flycast 0.1 dll file [b783996](https://github.com/libretro/flycast/commit/b7839962a58577cd94992ecfc0f3c6f041b90484)?
> 
> I tried to perform the tutorial, but the link to the msys2 program on the website https://www.msys2.org/#installation seems broken.

hi, check here : 
https://github.com/libretro/flycast/issues/994#issuecomment-750640495

**Comment by brunovieira90** [comment]
Thank you my friend. I was able to use the version that solves these problems that you posted.
You helped a lot.
Thank you one more time.

**Comment by LukasThyWalls** [comment]
Yesterday in my test machine i found that RetroArch 1.9.0 updated Flycast to 0.1 20caf3f, which is the actually last commit here.

I didn't test if it have this issue, but we can assume that it hasn't.

If someone can confirm that, maybe is better to close this.

**Comment by barbudreadmon** [comment]
Yes, the new buildbot is mostly ready, so flycast is now updated. As for those vmus corruptions, i didn't manage to reproduce it a few days ago so i guess i might have fixed it while reverting and backporting again.
