### ISSUE TITLE
Unable to save to VMU since latest update

### ISSUE THREAD

**Issue by taydan04** [libretro/flycast#993]
Since the latest commit I have been unable to get any games to save to the VMU files on either Windows 10 or MacOS Big Sur 11.1 running RetroArch.

This seems to effect every ROM I have tried. Have used these ROMs and bios files on previous versions with no issue. I have per-game VMU's turned off and have tried with it turned on. Have also tried the trick I have seen elsewhere and tried an "Delete All" from the Dreamcast bios and have tried deleting and re-generating the VMU files multiple times.

On Code Veronica and Shenmue i get "Game save unsuccessful" and in Resident Evil 2 and Crazy Taxi 2 I get "No VMU Found"

I have extracted a log with verbosity 0 below. But it doesn't seem to indicate any issues were detected and shows all 4 VMU files loading in.

> [INFO] [CORE]: Loading dynamic libretro core from: "C:\Users\Daniel\AppData\Roaming\RetroArch\cores\flycast_libretro.dll"
[INFO] [Overrides]: No core-specific overrides found at C:\Users\Daniel\AppData\Roaming\RetroArch\config\Flycast\Flycast.cfg.
[INFO] [Overrides]: No content-dir-specific overrides found at C:\Users\Daniel\AppData\Roaming\RetroArch\config\Flycast\Shenmue.cfg.
[INFO] [Overrides]: No game-specific overrides found at C:\Users\Daniel\AppData\Roaming\RetroArch\config\Flycast\Shenmue (Disc 1).cfg.
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] Controller port: 1
[INFO]    Controller (ID: 1)
[INFO]    Arcade Stick (ID: 1025)
[INFO]    Keyboard (ID: 3)
[INFO]    Mouse (ID: 2)
[INFO]    Light Gun (ID: 4)
[INFO]    Twin Stick (ID: 513)
[INFO]    Saturn Twin-Stick (ID: 769)
[INFO] Controller port: 2
[INFO]    Controller (ID: 1)
[INFO]    Arcade Stick (ID: 1025)
[INFO]    Keyboard (ID: 3)
[INFO]    Mouse (ID: 2)
[INFO]    Light Gun (ID: 4)
[INFO]    Twin Stick (ID: 513)
[INFO]    Saturn Twin-Stick (ID: 769)
[INFO] Controller port: 3
[INFO]    Controller (ID: 1)
[INFO]    Arcade Stick (ID: 1025)
[INFO]    Keyboard (ID: 3)
[INFO]    Mouse (ID: 2)
[INFO]    Light Gun (ID: 4)
[INFO]    Twin Stick (ID: 513)
[INFO]    Saturn Twin-Stick (ID: 769)
[INFO] Controller port: 4
[INFO]    Controller (ID: 1)
[INFO]    Arcade Stick (ID: 1025)
[INFO]    Keyboard (ID: 3)
[INFO]    Mouse (ID: 2)
[INFO]    Light Gun (ID: 4)
[INFO]    Twin Stick (ID: 513)
[INFO]    Saturn Twin-Stick (ID: 769)
[INFO] [Remaps]: remap directory: C:\Users\Daniel\AppData\Roaming\RetroArch\config\remaps
[INFO] [Overrides]: Redirecting save file to "C:\Users\Daniel\AppData\Roaming\RetroArch\saves\Shenmue (Disc 1).srm".
[INFO] [Overrides]: Redirecting save state to "C:\Users\Daniel\AppData\Roaming\RetroArch\states\Shenmue (Disc 1).state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: GET_PERF_INTERFACE.
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: SET_KEYBOARD_CALLBACK.
[INFO] [Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [CONTENT LOAD]: Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[libretro DEBUG] Rumble interface supported!
[INFO] [Environ]: SYSTEM_DIRECTORY: "C:\Users\Daniel\AppData\Roaming\RetroArch\system".
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_VARIABLE reicast_per_content_vmus:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_widescreen_hack:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_widescreen_cheats:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_screen_rotation:
	horizontal
[INFO] [Environ]: GET_VARIABLE reicast_internal_resolution:
	640x480
[INFO] [Environ]: GET_VARIABLE reicast_cpu_mode:
	N/A
[INFO] [Environ]: GET_VARIABLE reicast_boot_to_bios:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_gdrom_fast_loading:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_alpha_sorting:
	per-pixel (accurate)
[INFO] [Environ]: GET_VARIABLE reicast_mipmapping:
	enabled
[INFO] [Environ]: GET_VARIABLE reicast_system:
	auto
[INFO] [Environ]: GET_VARIABLE reicast_hle_bios:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_oit_abuffer_size:
	512MB
[INFO] [Environ]: GET_VARIABLE reicast_volume_modifier_enable:
	enabled
[INFO] [Environ]: GET_VARIABLE reicast_cable_type:
	VGA (RGB)
[INFO] [Environ]: GET_VARIABLE reicast_broadcast:
	Default
[INFO] [Environ]: GET_VARIABLE reicast_framerate:
	fullspeed
[INFO] [Environ]: GET_VARIABLE reicast_region:
	Default
[INFO] [Environ]: GET_VARIABLE reicast_language:
	Default
[INFO] [Environ]: GET_VARIABLE reicast_div_matching:
	auto
[INFO] [Environ]: GET_VARIABLE reicast_force_wince:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_anisotropic_filtering:
	4
[INFO] [Environ]: GET_VARIABLE reicast_pvr2_filtering:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_texupscale:
	off
[INFO] [Environ]: GET_VARIABLE reicast_texupscale_max_filtered_texture_size:
	256
[INFO] [Environ]: GET_VARIABLE reicast_enable_rttb:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_render_to_texture_upscaling:
	1x
[INFO] [Environ]: GET_VARIABLE reicast_threaded_rendering:
	enabled
[INFO] [Environ]: SET_SAVE_STATE_IN_BACKGROUND: yes.
[INFO] [Environ]: GET_VARIABLE reicast_synchronous_rendering:
	enabled
[INFO] [Environ]: GET_VARIABLE reicast_delay_frame_swapping:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_frame_skipping:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_enable_purupuru:
	enabled
[INFO] [Environ]: GET_VARIABLE reicast_analog_stick_deadzone:
	15
[INFO] [Environ]: GET_VARIABLE reicast_trigger_deadzone:
	0
[INFO] [Environ]: GET_VARIABLE reicast_enable_dsp:
	enabled
[INFO] [Environ]: GET_VARIABLE reicast_digital_triggers:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_allow_service_buttons:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_enable_naomi_15khz_dipswitch:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_custom_textures:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_dump_textures:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_lightgun1_crosshair:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_vmu1_screen_display:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_vmu1_screen_position:
	Upper Left
[INFO] [Environ]: GET_VARIABLE reicast_vmu1_screen_size_mult:
	1x
[INFO] [Environ]: GET_VARIABLE reicast_vmu1_screen_opacity:
	100
[INFO] [Environ]: GET_VARIABLE reicast_vmu1_pixel_on_color:
	DEFAULT_ON 00
[INFO] [Environ]: GET_VARIABLE reicast_vmu1_pixel_off_color:
	DEFAULT_OFF 01
[INFO] [Environ]: GET_VARIABLE reicast_lightgun2_crosshair:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_vmu2_screen_display:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_vmu2_screen_position:
	Upper Left
[INFO] [Environ]: GET_VARIABLE reicast_vmu2_screen_size_mult:
	1x
[INFO] [Environ]: GET_VARIABLE reicast_vmu2_screen_opacity:
	100
[INFO] [Environ]: GET_VARIABLE reicast_vmu2_pixel_on_color:
	DEFAULT_ON 00
[INFO] [Environ]: GET_VARIABLE reicast_vmu2_pixel_off_color:
	DEFAULT_OFF 01
[INFO] [Environ]: GET_VARIABLE reicast_lightgun3_crosshair:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_vmu3_screen_display:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_vmu3_screen_position:
	Upper Left
[INFO] [Environ]: GET_VARIABLE reicast_vmu3_screen_size_mult:
	1x
[INFO] [Environ]: GET_VARIABLE reicast_vmu3_screen_opacity:
	100
[INFO] [Environ]: GET_VARIABLE reicast_vmu3_pixel_on_color:
	DEFAULT_ON 00
[INFO] [Environ]: GET_VARIABLE reicast_vmu3_pixel_off_color:
	DEFAULT_OFF 01
[INFO] [Environ]: GET_VARIABLE reicast_lightgun4_crosshair:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_vmu4_screen_display:
	disabled
[INFO] [Environ]: GET_VARIABLE reicast_vmu4_screen_position:
	Upper Left
[INFO] [Environ]: GET_VARIABLE reicast_vmu4_screen_size_mult:
	1x
[INFO] [Environ]: GET_VARIABLE reicast_vmu4_screen_opacity:
	100
[INFO] [Environ]: GET_VARIABLE reicast_vmu4_pixel_on_color:
	DEFAULT_ON 00
[INFO] [Environ]: GET_VARIABLE reicast_vmu4_pixel_off_color:
	DEFAULT_OFF 01
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: GET_VARIABLE reicast_show_vmu_screen_settings:
	disabled
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: GET_VARIABLE reicast_show_lightgun_settings:
	disabled
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[libretro INFO] File extension is: .chd
[INFO] [Environ]: GET_PREFERRED_HW_RENDER.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting Vulkan context.
[INFO] [Environ]: SET_HW_RENDER_CONTEXT_NEGOTIATION_INTERFACE.
[libretro INFO] 00:00:000 hw/mem/_vmem.cpp:556 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
[libretro INFO] 00:00:015 nullDC.cpp:152 N[BOOT]: [LUT]: Product number: MK-5105950.
[libretro INFO] 00:00:015 hw/maple/maple_devs.cpp:603 N[MAPLE]: Loaded VMU from file "C:\Users\Daniel\AppData\Roaming\RetroArch\system\dc\vmu_save_A1.bin"
[libretro INFO] 00:00:015 hw/maple/maple_devs.cpp:603 N[MAPLE]: Loaded VMU from file "C:\Users\Daniel\AppData\Roaming\RetroArch\system\dc\vmu_save_B1.bin"
[libretro INFO] 00:00:015 hw/maple/maple_devs.cpp:603 N[MAPLE]: Loaded VMU from file "C:\Users\Daniel\AppData\Roaming\RetroArch\system\dc\vmu_save_C1.bin"
[libretro INFO] 00:00:015 hw/maple/maple_devs.cpp:603 N[MAPLE]: Loaded VMU from file "C:\Users\Daniel\AppData\Roaming\RetroArch\system\dc\vmu_save_D1.bin"
[INFO] [Environ]: SET_ROTATION: 0
[INFO] [SRAM]: Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Cheats]: Load game-specific cheatfile: C:\Users\Daniel\AppData\Roaming\RetroArch\cheats\Flycast\Shenmue (Disc 1).cht
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Using HW render, Vulkan driver forced.
[INFO] [Vulkan]: Vulkan dynamic library loaded.
[INFO] [Vulkan]: App: Flycast (version 1)
[INFO] [Vulkan]: Engine: Flycast (version 1)
[INFO] [Vulkan]: Found vulkan context: vk_w
[INFO] [Vulkan]: Detecting screen resolution 2560x1600.
[INFO] Setting fullscreen to 2560x1600 @ 60Hz on device \\.\DISPLAY1.
[INFO] [Vulkan]: Found GPU at index 0: Intel(R) Iris(R) Plus Graphics
[INFO] [Vulkan]: Found GPU at index 1: Intel(R) Iris(R) Plus Graphics
[INFO] [Vulkan]: Using GPU index 0.
[INFO] [Vulkan]: Using GPU: Intel(R) Iris(R) Plus Graphics
[INFO] [Vulkan]: Swapchain supports present mode: 0.
[INFO] [Vulkan]: Swapchain supports present mode: 2.
[INFO] [Vulkan]: Creating swapchain with present mode: 2
[INFO] [Vulkan]: Using swapchain size 2560 x 1600.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Vulkan]: Using resolution 2560x1600
[INFO] [Vulkan]: Using BGRA8888 format.
[INFO] [Vulkan]: Loading stock shader.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [Vulkan filter chain]: Not using frame history.
[INFO] [Vulkan filter chain]: Not using framebuffer feedback.
[WARN] [DINPUT]: Strong rumble unavailable.
[WARN] [DINPUT]: Weak rumble unavailable.
[INFO] [Joypad]: Found joypad driver: "dinput".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: win32
[libretro INFO] 00:00:441 rend/vulkan/vulkan_context.cpp:320 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
[INFO] [OpenAL]: Using 11 buffers of 1024 bytes.
[INFO] [Display]: Found display driver: "vulkan".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "winmm" driver.
[INFO] Disconnecting device from port 6.
[INFO] Disconnecting device from port 7.
[INFO] Disconnecting device from port 8.
[INFO] Disconnecting device from port 9.
[INFO] Disconnecting device from port 10.
[INFO] Disconnecting device from port 11.
[INFO] Disconnecting device from port 12.
[INFO] Disconnecting device from port 13.
[INFO] Disconnecting device from port 14.
[INFO] Disconnecting device from port 15.
[INFO] Disconnecting device from port 16.
[INFO] [Playlist]: Loading history file: [C:\Users\Daniel\AppData\Roaming\RetroArch\content_history.lpl].
[INFO] [Playlist]: Loading history file: [C:\Users\Daniel\AppData\Roaming\RetroArch\content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [C:\Users\Daniel\AppData\Roaming\RetroArch\content_video_history.lpl].
[INFO] [Playlist]: Loading history file: [C:\Users\Daniel\AppData\Roaming\RetroArch\content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [C:\Users\Daniel\AppData\Roaming\RetroArch\content_favorites.lpl].
[INFO] [Vulkan]: VSync => on
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [Vulkan filter chain]: Not using frame history.
[INFO] [Vulkan filter chain]: Not using framebuffer feedback.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, Port 1, Button "B (bottom)" => "A"
[INFO] 	RetroPad, Port 1, Button "Y (left)" => "X"
[INFO] 	RetroPad, Port 1, Button "Start" => "Start"
[INFO] 	RetroPad, Port 1, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, Port 1, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, Port 1, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, Port 1, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, Port 1, Button "A (right)" => "B"
[INFO] 	RetroPad, Port 1, Button "X (up)" => "Y"
[INFO] 	RetroPad, Port 1, Button "L2" => "L Trigger"
[INFO] 	RetroPad, Port 1, Button "R2" => "R Trigger"
[INFO] 	RetroPad, Port 2, Button "B (bottom)" => "A"
[INFO] 	RetroPad, Port 2, Button "Y (left)" => "X"
[INFO] 	RetroPad, Port 2, Button "Start" => "Start"
[INFO] 	RetroPad, Port 2, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, Port 2, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, Port 2, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, Port 2, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, Port 2, Button "A (right)" => "B"
[INFO] 	RetroPad, Port 2, Button "X (up)" => "Y"
[INFO] 	RetroPad, Port 2, Button "L2" => "L Trigger"
[INFO] 	RetroPad, Port 2, Button "R2" => "R Trigger"
[INFO] 	RetroPad, Port 3, Button "B (bottom)" => "A"
[INFO] 	RetroPad, Port 3, Button "Y (left)" => "X"
[INFO] 	RetroPad, Port 3, Button "Start" => "Start"
[INFO] 	RetroPad, Port 3, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, Port 3, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, Port 3, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, Port 3, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, Port 3, Button "A (right)" => "B"
[INFO] 	RetroPad, Port 3, Button "X (up)" => "Y"
[INFO] 	RetroPad, Port 3, Button "L2" => "L Trigger"
[INFO] 	RetroPad, Port 3, Button "R2" => "R Trigger"
[INFO] 	RetroPad, Port 4, Button "B (bottom)" => "A"
[INFO] 	RetroPad, Port 4, Button "Y (left)" => "X"
[INFO] 	RetroPad, Port 4, Button "Start" => "Start"
[INFO] 	RetroPad, Port 4, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, Port 4, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, Port 4, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, Port 4, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, Port 4, Button "A (right)" => "B"
[INFO] 	RetroPad, Port 4, Button "X (up)" => "Y"
[INFO] 	RetroPad, Port 4, Button "L2" => "L Trigger"
[INFO] 	RetroPad, Port 4, Button "R2" => "R Trigger"
[INFO] [Vulkan]: Do not need to re-create swapchain.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [Vulkan filter chain]: Not using frame history.
[INFO] [Vulkan filter chain]: Not using framebuffer feedback.
[libretro INFO] 00:01:067 hw/maple/maple_devs.cpp:603 N[MAPLE]: Loaded VMU from file "C:\Users\Daniel\AppData\Roaming\RetroArch\system\dc\vmu_save_A1.bin"
[libretro INFO] 00:01:067 hw/maple/maple_devs.cpp:603 N[MAPLE]: Loaded VMU from file "C:\Users\Daniel\AppData\Roaming\RetroArch\system\dc\vmu_save_B1.bin"
[libretro INFO] 00:01:067 hw/maple/maple_devs.cpp:603 N[MAPLE]: Loaded VMU from file "C:\Users\Daniel\AppData\Roaming\RetroArch\system\dc\vmu_save_C1.bin"
[libretro INFO] 00:01:068 hw/maple/maple_devs.cpp:603 N[MAPLE]: Loaded VMU from file "C:\Users\Daniel\AppData\Roaming\RetroArch\system\dc\vmu_save_D1.bin"
[libretro INFO] 00:01:963 hw/pvr/Renderer_if.cpp:119 N[PVR]: Creating Vulkan per-pixel renderer
[INFO] [Vulkan]: VSync => on
[INFO] Content ran for a total of: 00 hours, 00 minutes, 29 seconds.
[INFO] Saving runtime log file: C:\Users\Daniel\AppData\Roaming\RetroArch\playlists\logs\Flycast\Shenmue (Disc 1).lrtl
[INFO] [CORE]: No content, starting dummy core.
[INFO] [Cheats]: Save game-specific cheatfile: C:\Users\Daniel\AppData\Roaming\RetroArch\cheats\Flycast\Shenmue (Disc 1).cht
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [CORE]: Unloading game..
[INFO] [CORE]: Unloading core..
[INFO] [CORE]: Unloading core symbols..
[INFO] [Core Options]: Saved core options file to "C:\Users\Daniel\AppData\Roaming\RetroArch\config\Flycast\Flycast.opt"
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] RetroArch 1.9.0 (Git 6388872a54)

**Comment by taydan04** [comment]
Closing this issue ticket. I have found that RetroArch is fetching a really old build of the Flycast core. Using MSYS2 to build the core from source has resolved the issue for me.

**Comment by mikecorrea** [comment]
Any chance you can share that core with me? I’m not computer literate enough to build it myself and I’m having the same exact issue as you once did.
